### ISSUE TITLE
java.lang.NoSuchMethodError while running on JRE1.6

### ISSUE THREAD

**Issue by contactashish13** [bcgit/bc-java#1024]
I have followed all the steps mentioned here: https://stackoverflow.com/questions/33364100/how-to-use-tls-1-2-in-java-6/61115302#61115302

It works beautifully when I access my application through the browser but it fails and throws this exception
```javax.servlet.ServletException: java.lang.NoSuchMethodError: org.bouncycastle.jsse.provider.ProvAlgorithmChecker.check(Ljava/security/cert/Certificate;)V``` when my Java client tries to connect to an SQLServer2012 instance using `sqljdbc4.jar`. The relevant stack trace is here:

```
threw exception [javax.servlet.ServletException: java.lang.NoSuchMethodError: org.bouncycastle.jsse.provider.ProvAlgorithmChecker.check(Ljava/security/cert/Certificate;)V] with root cause
java.lang.NoSuchMethodError: org.bouncycastle.jsse.provider.ProvAlgorithmChecker.check(Ljava/security/cert/Certificate;)V
        at org.bouncycastle.jsse.provider.ProvAlgorithmChecker.checkChain(Unknown Source)
        at org.bouncycastle.jsse.provider.ImportX509TrustManager_5.checkAlgorithmConstraints(Unknown Source)
        at org.bouncycastle.jsse.provider.ImportX509TrustManager_5.checkAdditionalTrust(Unknown Source)
        at org.bouncycastle.jsse.provider.ImportX509TrustManager_5.checkServerTrusted(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.checkServerTrusted(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvTlsClient$1.notifyServerCertificate(Unknown Source)
        at org.bouncycastle.tls.TlsUtils.processServerCertificate(Unknown Source)
        at org.bouncycastle.tls.TlsClientProtocol.handleServerCertificate(Unknown Source)
        at org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source)
        at org.bouncycastle.tls.RecordStream.readRecord(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.blockForHandshake(Unknown Source)
        at org.bouncycastle.tls.TlsClientProtocol.connect(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(Unknown Source)
        at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1379)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:1058)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:833)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:716)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:841)
        at java.sql.DriverManager.getConnection(DriverManager.java:615)
        at java.sql.DriverManager.getConnection(DriverManager.java:195)
```

The java client works without a problem if I revert my changes and go back to using TLS1.1. What JAR could be missing here?

**Comment by tonywasher** [comment]
Looking at the git history of ProvAlgorithmChecker.java there is a commit [8a1b558](https://github.com/bcgit/bc-java/commit/8a1b558141cb659df7d7e439c1a0be0db0fa75eb#diff-2454ddce125e7609a24a451ae9de8c2a36252a5d570357046e6eb559d9d33f5a)    entitled "Avoid calling JDK 1.8 method" which is dated April 7 2020. This would appear to be a fix to the problem that you are seeing.

If you followed all the steps in the article that you linked, you will be using BouncyCastle version 1.65, which would have contained the bug that this commit fixed. The fix was include in version 1.66.

Please ensure that you upgrade to at least version 1.66, and preferably1.69. Hopefully this will fix the problem.

**Comment by contactashish13** [comment]
@tonywasher thank you! 1.69 threw another NoClassDefFoundError on 1.69 but 1.66 worked like a charm! Will do a bit more testing but it looks good :crossed_fingers:

**Comment by tonywasher** [comment]
That's great. Would you be able to supply a stack trace for the 1.69 error that you saw. It sounds as if there is another bug hiding there!!

**Comment by contactashish13** [comment]
Here you go @tonywasher 

```
org.apache.catalina.LifecycleException: Failed to initialize component [Connector[HTTP/1.1-444]]
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:106)
        at org.apache.catalina.core.StandardService.initInternal(StandardService.java:559)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
        at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:814)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
        at org.apache.catalina.startup.Catalina.load(Catalina.java:624)
        at org.apache.catalina.startup.Catalina.load(Catalina.java:649)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:622)
        at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:281)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:449)
Caused by: java.lang.NoClassDefFoundError: org/bouncycastle/asn1/eac/EACObjectIdentifiers
        at org.bouncycastle.tls.TlsUtils.createCertSigAlgOIDs(Unknown Source)
        at org.bouncycastle.tls.TlsUtils.<clinit>(Unknown Source)
        at org.bouncycastle.jsse.provider.CipherSuiteInfo.forCipherSuite(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvSSLContextSpi.addCipherSuite(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvSSLContextSpi.createSupportedCipherSuiteMap(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvSSLContextSpi.<clinit>(Unknown Source)
        at org.bouncycastle.jsse.provider.BouncyCastleJsseProvider$3.createInstance(Unknown Source)
        at org.bouncycastle.jsse.provider.BouncyCastleJsseProvider$BcJsseService.newInstance(Unknown Source)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at javax.net.ssl.SSLContext.getInstance(SSLContext.java:142)
        at org.apache.tomcat.util.net.jsse.JSSESocketFactory.<clinit>(JSSESocketFactory.java:104)
        at org.apache.tomcat.util.net.jsse.JSSEImplementation.getServerSocketFactory(JSSEImplementation.java:47)
        at org.apache.tomcat.util.net.JIoEndpoint.bind(JIoEndpoint.java:370)
        at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:566)
        at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:417)
        at org.apache.coyote.http11.AbstractHttp11JsseProtocol.init(AbstractHttp11JsseProtocol.java:119)
        at org.apache.catalina.connector.Connector.initInternal(Connector.java:956)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
        ... 12 more
```

**Comment by tonywasher** [comment]
Ah - that's an easy one.

version 1.69 introduced some re-packaging, and some code was moved out from bcprov to and new bcutil jar. Specifically ASN1 identifiers such as EACObjectIdentifiers.

You will need to download the bcutil-jdk15to18-169.jar as well and store it with the bcprov-jdk15to18-169.jar

**Comment by dghgit** [comment]
And thank you @tonywasher!
