### ISSUE TITLE
Caused by: java.io.IOException: malformed PEM data: no header found

### ISSUE THREAD

**Issue by gopikrishna1998** [bcgit/bc-java#1051]
Facing the following error in unit test case using certificate in incorrect format after upgrading from BouncyCastleCrypto-1.54 to BouncyCastleCrypto-1.67.
```
Caused by: java.io.IOException: malformed PEM data: no header found
    at org.bouncycastle.jcajce.provider.asymmetric.x509.PEMUtil.readPEMObject(Unknown Source)
    at org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory.readPEMCertificate(Unknown Source)
```
Could someone please help to understand what exactly changed in the versions and how to resolve the same?

**Comment by mwcw** [comment]
Hi

Do you have an example input?

MW

**Comment by dghgit** [comment]
Closed as inactive.
