### ISSUE TITLE
Unable to invoke creator for DEFAULT: Default key/trust managers unavailable AND DER length more than 4 bytes: 109

### ISSUE THREAD

**Issue by minQueue** [bcgit/bc-java#1052]
Hi,

I got an error when building a project with gradle, jdk1.7 with BC-FIPS jars(bc-fips 1.0.2.1 and bcfls-fips 1.0.12.2). 
I updated java.security configuration for BC-FIPS by following documents. 

I got a below build error.
**`org.bouncycastle.jsse.provider.DefaultSSLContextSpi$LazyManagers <clinit>
WARNING: Failed to load default trust managers
java.io.IOException: DER length more than 4 bytes: 109**
        at org.bouncycastle.asn1.ASN1InputStream.readLength(Unknown Source)
        at org.bouncycastle.asn1.ASN1InputStream.readLength(Unknown Source)
        at org.bouncycastle.asn1.ASN1InputStream.readObject(Unknown Source)
        at org.bouncycastle.jcajce.provider.ProvBCFKS$BCFIPSKeyStoreSpi.engineLoad(Unknown Source)
        at java.security.KeyStore.load(KeyStore.java:1226)
        at org.bouncycastle.jsse.provider.ProvTrustManagerFactorySpi.getDefaultTrustStore(ProvTrustManagerFactorySpi.java:112)
        at org.bouncycastle.jsse.provider.ProvSSLContextSpi.getDefaultTrustManagers(ProvSSLContextSpi.java:515)
        at org.bouncycastle.jsse.provider.DefaultSSLContextSpi$LazyManagers.<clinit>(DefaultSSLContextSpi.java:65)
        at org.bouncycastle.jsse.provider.DefaultSSLContextSpi.<init>(DefaultSSLContextSpi.java:113)
        at org.bouncycastle.jsse.provider.BouncyCastleJsseProvider$8.createInstance(BouncyCastleJsseProvider.java:222)
        at org.bouncycastle.jsse.provider.BouncyCastleJsseProvider$BcJsseService.newInstance(BouncyCastleJsseProvider.java:384)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
        at javax.net.ssl.SSLContext.getDefault(SSLContext.java:97)
        at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:121)
        at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:333)
        at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:291)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:85)
        at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
        at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
        at java.net.URL.openConnection(URL.java:975)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:53)
        at org.gradle.wrapper.Download.download(Download.java:42)
        at org.gradle.wrapper.Install$1.call(Install.java:57)
        at org.gradle.wrapper.Install$1.call(Install.java:44)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:44)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)

**Exception in thread "main" java.net.SocketException: java.security.NoSuchAlgorithmException: Unable to invoke creator for DEFAULT: Default key/trust managers unavailable**
        at javax.net.ssl.DefaultSSLSocketFactory.throwException(SSLSocketFactory.java:198)
        at javax.net.ssl.DefaultSSLSocketFactory.createSocket(SSLSocketFactory.java:205)
        at sun.net.www.protocol.https.HttpsClient.createSocket(HttpsClient.java:405)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:162)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:56)
        at org.gradle.wrapper.Download.download(Download.java:42)
        at org.gradle.wrapper.Install$1.call(Install.java:57)
        at org.gradle.wrapper.Install$1.call(Install.java:44)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:44)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
**Caused by: java.security.NoSuchAlgorithmException: Unable to invoke creator for DEFAULT: Default key/trust managers unavailable**
        at org.bouncycastle.jsse.provider.BouncyCastleJsseProvider$BcJsseService.newInstance(BouncyCastleJsseProvider.java:399)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
        at javax.net.ssl.SSLContext.getDefault(SSLContext.java:97)
        at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:121)
        at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:333)
        at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:291)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:85)
        at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
        at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
        at java.net.URL.openConnection(URL.java:975)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:53)
        ... 7 more
**Caused by: java.security.KeyManagementException: Default key/trust managers unavailable**
        at org.bouncycastle.jsse.provider.DefaultSSLContextSpi.<init>(DefaultSSLContextSpi.java:115)
        at org.bouncycastle.jsse.provider.BouncyCastleJsseProvider$8.createInstance(BouncyCastleJsseProvider.java:222)
        at org.bouncycastle.jsse.provider.BouncyCastleJsseProvider$BcJsseService.newInstance(BouncyCastleJsseProvider.java:384)
        ... 19 more
**Caused by: java.security.KeyManagementException: DER length more than 4 bytes: 109**
        at org.bouncycastle.jsse.provider.DefaultSSLContextSpi.avoidCapturingException(DefaultSSLContextSpi.java:20)
        at org.bouncycastle.jsse.provider.DefaultSSLContextSpi.access$200(DefaultSSLContextSpi.java:13)
        at org.bouncycastle.jsse.provider.DefaultSSLContextSpi$LazyManagers.<clinit>(DefaultSSLContextSpi.java:88)
        at org.bouncycastle.jsse.provider.DefaultSSLContextSpi.<init>(DefaultSSLContextSpi.java:113)`
        
To me, it looks like I missed some configurations from jdk with BC-FIPS. 
I appreciate if anyone knows this issue and solution.

Thanks!

**Comment by minQueue** [comment]
This is how I updated java.security.

#
# List of providers and their preference orders (see above):
#
security.provider.1=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider
security.provider.2=org.bouncycastle.jsse.provider.BouncyCastleJsseProvider fips:BCFIPS
security.provider.3=sun.security.provider.Sun

#
# Default keystore type.
#
keystore.type=bcfks

#
# Determines the default key and trust manager factory algorithms for
# the javax.net.ssl package.
#
ssl.KeyManagerFactory.algorithm=PKIX
ssl.TrustManagerFactory.algorithm=PKIX

**If I change from PKIX to X509, I got the jar unsigned error as below** 
`INFO: Found string system property [java.home]: C:\Program Files\Java\jdk1.7.0_80\jre

Exception in thread "main" java.lang.SecurityException: JCE cannot authenticate the provider BCFIPS
        at javax.crypto.Cipher.getInstance(Cipher.java:647)
        at org.bouncycastle.jcajce.util.ProviderJcaJceHelper.createCipher(Unknown Source)
        at org.bouncycastle.tls.crypto.impl.jcajce.JcaTlsCrypto.isSupportedEncryptionAlgorithm(JcaTlsCrypto.java:944)
        at org.bouncycastle.tls.crypto.impl.jcajce.JcaTlsCrypto.hasEncryptionAlgorithm(JcaTlsCrypto.java:463)
        at org.bouncycastle.tls.TlsUtils.isSupportedCipherSuite(TlsUtils.java:4344)
        at org.bouncycastle.tls.TlsUtils.getSupportedCipherSuites(TlsUtils.java:4327)
        at org.bouncycastle.jsse.provider.ProvSSLContextSpi.getActiveCipherSuites(ProvSSLContextSpi.java:628)
        at org.bouncycastle.jsse.provider.ProvTlsClient.getSupportedCipherSuites(ProvTlsClient.java:191)
        at org.bouncycastle.tls.AbstractTlsClient.init(AbstractTlsClient.java:187)
        at org.bouncycastle.tls.TlsClientProtocol.connect(TlsClientProtocol.java:81)
        at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(ProvSSLSocketDirect.java:445)
        at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(ProvSSLSocketDirect.java:426)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:56)
        at org.gradle.wrapper.Download.download(Download.java:42)
        at org.gradle.wrapper.Install$1.call(Install.java:57)
        at org.gradle.wrapper.Install$1.call(Install.java:44)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:44)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
Caused by: java.util.jar.JarException: file:/C:/Program%20Files/Java/jdk1.7.0_80/jre/lib/ext/bc-fips-1.0.2.1.jar has unsigned entries - org/bouncycastle/LICENSE.class
        at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:462)
        at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:322)
        at javax.crypto.JarVerifier.verify(JarVerifier.java:250)
        at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:161)
        at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:187)
        at javax.crypto.Cipher.getInstance(Cipher.java:643)
        ... 23 more`

**Comment by peterdettman** [comment]
Presumably you have not converted the cacerts file in your JDK to BCFKS keystore type. So when you try to use the default SSLContext, it loads the default TrustManager, and this tries to load cacerts _as BCFKS_ (per keystore.type setting), and because that file is not actually a BCFKS keystore, you get the format errors.

If this is just a test case and you will really not be using the default SSLContext, then you can just move past this I would think. However if you are intending to use the cacerts then you would need to convert it to BCFKS type. If you want to leave the original cacerts as is (e.g. to avoid interfering with other users of the JDK) it's possible to provide a jssecacerts file in the same location that will be preferred. Or even cleaner you can set the javax.net.ssl.trustStore system property for your program to point at an alternative location and place your modified cacerts there.

**Comment by minQueue** [comment]
After I changed the keystore type of cacerts from JKS to BCFKS, java.io.IOException: DER length more than 4 bytes: 109 error is gone. 
But  "**java.lang.SecurityException: JCE cannot authenticate the provider BCFIPS**" error and "**Caused by: java.util.jar.JarException: file:/C:/Program%20Files/Java/jdk1.7.0_80/jre/lib/ext/bc-fips-1.0.2.1.jar has unsigned entries - org/bouncycastle/LICENSE.class**" error still came up. 

I think I cannot sign these jars which I downloaded from maven repository. 
How can I fix these errors?

I attached full stack trace below. 
Thanks!


`INFO: Found string system property [java.home]: C:\Program Files\Java\jdk1.7.0_80\jre
Nov 01, 2021 2:29:59 PM org.bouncycastle.jsse.provider.DefaultSSLContextSpi$LazyManagers <clinit>
WARNING: Failed to load default trust managers
java.lang.SecurityException: JCE cannot authenticate the provider BCFIPS
        at javax.crypto.JceSecurity.getInstance(JceSecurity.java:114)
        at javax.crypto.Mac.getInstance(Mac.java:256)
        at org.bouncycastle.jcajce.provider.ProvBCFKS$BCFIPSKeyStoreSpi.calculateMac(Unknown Source)
        at org.bouncycastle.jcajce.provider.ProvBCFKS$BCFIPSKeyStoreSpi.verifyMac(Unknown Source)
        at org.bouncycastle.jcajce.provider.ProvBCFKS$BCFIPSKeyStoreSpi.engineLoad(Unknown Source)
        at java.security.KeyStore.load(KeyStore.java:1226)
        at org.bouncycastle.jsse.provider.ProvTrustManagerFactorySpi.getDefaultTrustStore(ProvTrustManagerFactorySpi.java:112)
        at org.bouncycastle.jsse.provider.ProvSSLContextSpi.getDefaultTrustManagers(ProvSSLContextSpi.java:515)
        at org.bouncycastle.jsse.provider.DefaultSSLContextSpi$LazyManagers.<clinit>(DefaultSSLContextSpi.java:65)
        at org.bouncycastle.jsse.provider.DefaultSSLContextSpi.<init>(DefaultSSLContextSpi.java:113)
        at org.bouncycastle.jsse.provider.BouncyCastleJsseProvider$8.createInstance(BouncyCastleJsseProvider.java:222)
        at org.bouncycastle.jsse.provider.BouncyCastleJsseProvider$BcJsseService.newInstance(BouncyCastleJsseProvider.java:384)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
        at javax.net.ssl.SSLContext.getDefault(SSLContext.java:97)
        at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:121)
        at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:333)
        at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:291)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:85)
        at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
        at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
        at java.net.URL.openConnection(URL.java:975)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:53)
        at org.gradle.wrapper.Download.download(Download.java:42)
        at org.gradle.wrapper.Install$1.call(Install.java:57)
        at org.gradle.wrapper.Install$1.call(Install.java:44)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:44)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
Caused by: java.util.jar.JarException: file:/C:/Program%20Files/Java/jdk1.7.0_80/jre/lib/ext/bc-fips-1.0.2.1.jar has unsigned entries - org/bouncycastle/LICENSE.class
        at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:462)
        at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:322)
        at javax.crypto.JarVerifier.verify(JarVerifier.java:250)
        at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:161)
        at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:187)
        at javax.crypto.JceSecurity.getInstance(JceSecurity.java:110)
        ... 30 more


Exception in thread "main" java.net.SocketException: java.security.NoSuchAlgorithmException: Unable to invoke creator for DEFAULT: Default key/trust managers unavailable
        at javax.net.ssl.DefaultSSLSocketFactory.throwException(SSLSocketFactory.java:198)
        at javax.net.ssl.DefaultSSLSocketFactory.createSocket(SSLSocketFactory.java:205)
        at sun.net.www.protocol.https.HttpsClient.createSocket(HttpsClient.java:405)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:162)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:56)
        at org.gradle.wrapper.Download.download(Download.java:42)
        at org.gradle.wrapper.Install$1.call(Install.java:57)
        at org.gradle.wrapper.Install$1.call(Install.java:44)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:44)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
Caused by: java.security.NoSuchAlgorithmException: Unable to invoke creator for DEFAULT: Default key/trust managers unavailable
        at org.bouncycastle.jsse.provider.BouncyCastleJsseProvider$BcJsseService.newInstance(BouncyCastleJsseProvider.java:399)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
        at javax.net.ssl.SSLContext.getDefault(SSLContext.java:97)
        at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:121)
        at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:333)
        at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:291)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:85)
        at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
        at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
        at java.net.URL.openConnection(URL.java:975)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:53)
        ... 7 more
Caused by: java.security.KeyManagementException: Default key/trust managers unavailable
        at org.bouncycastle.jsse.provider.DefaultSSLContextSpi.<init>(DefaultSSLContextSpi.java:115)
        at org.bouncycastle.jsse.provider.BouncyCastleJsseProvider$8.createInstance(BouncyCastleJsseProvider.java:222)
        at org.bouncycastle.jsse.provider.BouncyCastleJsseProvider$BcJsseService.newInstance(BouncyCastleJsseProvider.java:384)
        ... 19 more
Caused by: java.security.KeyManagementException: JCE cannot authenticate the provider BCFIPS
        at org.bouncycastle.jsse.provider.DefaultSSLContextSpi.avoidCapturingException(DefaultSSLContextSpi.java:20)
        at org.bouncycastle.jsse.provider.DefaultSSLContextSpi.access$200(DefaultSSLContextSpi.java:13)
        at org.bouncycastle.jsse.provider.DefaultSSLContextSpi$LazyManagers.<clinit>(DefaultSSLContextSpi.java:88)
        at org.bouncycastle.jsse.provider.DefaultSSLContextSpi.<init>(DefaultSSLContextSpi.java:113)
        ... 21 more`

**Comment by minQueue** [comment]
> Presumably you have not converted the cacerts file in your JDK to BCFKS keystore type. So when you try to use the default SSLContext, it loads the default TrustManager, and this tries to load cacerts _as BCFKS_ (per keystore.type setting), and because that file is not actually a BCFKS keystore, you get the format errors.
> 
> If this is just a test case and you will really not be using the default SSLContext, then you can just move past this I would think. However if you are intending to use the cacerts then you would need to convert it to BCFKS type. If you want to leave the original cacerts as is (e.g. to avoid interfering with other users of the JDK) it's possible to provide a jssecacerts file in the same location that will be preferred. Or even cleaner you can set the javax.net.ssl.trustStore system property for your program to point at an alternative location and place your modified cacerts there.

**Comment by dghgit** [comment]
It looks like there are two copies of the BC provider classes on the classpath. Other than that please note while it is safe to resign the jar it is not safe to remove the original BC signatures unless you are using a JCE signing key.

**Comment by dghgit** [comment]
Closing as appears dealt with.
