### ISSUE TITLE
Default cipher suites when running with java 7 (restricted)

### ISSUE THREAD

**Issue by boaks** [bcgit/bc-java#1054]
If I use 

```
<properties>
	<bc.version>1.69</bc.version>
</properties>
<dependencies>
	<dependency>
		<groupId>org.bouncycastle</groupId>
		<artifactId>bcpkix-jdk15on</artifactId>
		<version>${bc.version}</version>
		<scope>test</scope>
	</dependency>
	<dependency>
		<groupId>org.bouncycastle</groupId>
		<artifactId>bcprov-jdk15on</artifactId>
		<version>${bc.version}</version>
		<scope>test</scope>
	</dependency>
	<dependency>
		<groupId>org.bouncycastle</groupId>
		<artifactId>bctls-jdk15on</artifactId>
		<version>${bc.version}</version>
		<scope>test</scope>
	</dependency>
</dependencies>
```

with the proper setup from issue #1053 it runs well on java 8 and java 11.
If java 7 is used (with the restricted export), only weak cipher suites could be used.
But the default cipher suites of the SSLContext seems not to reflect that. 
Also "strong" ones are included and so during the handshake the

> WARNUNG: Server raised fatal(2) internal_error(80) alert: Failed to process record
> java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size
> 	at org.bouncycastle.tls.crypto.impl.jcajce.JceChaCha20Poly1305.init(Unknown Source)
> 	at org.bouncycastle.tls.crypto.impl.TlsAEADCipher.<init>(Unknown Source)
> 	at org.bouncycastle.tls.crypto.impl.jcajce.JcaTlsCrypto.createChaCha20Poly1305(Unknown Source)
> 	at org.bouncycastle.tls.crypto.impl.jcajce.JcaTlsCrypto.createCipher(Unknown Source)
> 	at org.bouncycastle.tls.TlsUtils.initCipher(Unknown Source)

error is raised.

Sure, java 7 is not longer that wide spread. I also added a work-around and just select the AES-128 cipher suites.

Anyway, wouldn't it be smoother, if key size restrictions are considered for the list of default cipher suites?

**Comment by peterdettman** [comment]
Could you explain what you mean in your expectation that "only weak cipher suites could be used" please? We don't make any distinctions based on JDK version; we provide all cipher suites where the underlying cryptographic providers support it.

**Comment by boaks** [comment]
> Could you explain what you mean in your expectation that "only weak cipher suites could be used" please? 

e.g. if a AES_256 cipher suite is in the defaults and get negotiated, the above error will be raised.
If only AES_128 cipher suites are in the defaults, no "strong cipher suite" is negotiated (which would cause the error), because no-one is proposed nor agreed on.

The current implementation seems to propose such strong cipher suites, even if a later selection will then fail.

Is that more or less clearer?

**Comment by boaks** [comment]
> Edit: our "detection" of what is supported is not perfect, so perhaps there is an issue of that sort happening here.

Guess so. And java 7 is also running out.
So, not that hard, if it is kept "as it is". That would mainly require such a work-around in using stuff, which wants to support java 7.

**Comment by peterdettman** [comment]
Are you intending to be using the BC cryptographic provider here? Or are there other cryptographic providers at higher priority? i.e. where is it that AES_256 becomes unacceptable?

Generally we attempt to create ciphers by algorithm to see whether they will "work", but possibly we don't try this with different key sizes, so can't pick up these distinctions. I will need to review.

**Comment by boaks** [comment]
AFAIK, bc jc is 1 and bc jsse is 2.

I don't think, that "other providers of java 7" will propose AES-256.

Without BC, the tests are working, with BC and java 8 (or higher), the tests are working.
But with java 7 (and the old restriction there), the tests are failing, if the strong ciphers are not removed from the defaults list.

**Comment by peterdettman** [comment]
Could you give the full stack trace please, including the lower "cause" ones.

**Comment by boaks** [comment]
Okt 31, 2021 12:09:56 PM org.bouncycastle.jsse.provider.PropertyUtils getStringSecurityProperty
INFORMATION: Found string security property [jdk.tls.disabledAlgorithms]: SSLv3
Okt 31, 2021 12:09:56 PM org.bouncycastle.jsse.provider.PropertyUtils getStringSecurityProperty
INFORMATION: Found string security property [jdk.certpath.disabledAlgorithms]: MD2, RSA keySize < 1024
Okt 31, 2021 12:09:57 PM org.bouncycastle.jsse.provider.ProvTlsClient notifyAlertRaised
WARNUNG: Client raised fatal(2) internal_error(80) alert: Failed to process record
java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size
	at org.bouncycastle.tls.crypto.impl.jcajce.JceChaCha20Poly1305.init(Unknown Source)
	at org.bouncycastle.tls.crypto.impl.TlsAEADCipher.<init>(Unknown Source)
	at org.bouncycastle.tls.crypto.impl.jcajce.JcaTlsCrypto.createChaCha20Poly1305(Unknown Source)
	at org.bouncycastle.tls.crypto.impl.jcajce.JcaTlsCrypto.createCipher(Unknown Source)
	at org.bouncycastle.tls.TlsUtils.initCipher(Unknown Source)
	at org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source)
	at org.bouncycastle.tls.RecordStream.readFullRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.safeReadFullRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.offerInput(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.offerInput(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLEngine.unwrap(Unknown Source)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:296)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1342)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1029)
	at javax.crypto.Cipher.implInit(Cipher.java:795)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:854)
	at javax.crypto.Cipher.init(Cipher.java:1374)
	... 36 more

12:09:57.921 WARN [CloseOnErrorHandler]: java.security.InvalidKeyException: Illegal key size in channel handler chain for endpoint localhost:36737. Closing connection. (o.e.c.e.t.n.CloseOnErrorHandler.exceptionCaught:73)
Okt 31, 2021 12:09:57 PM org.bouncycastle.jsse.provider.ProvTlsServer notifyAlertRaised
WARNUNG: Server raised fatal(2) internal_error(80) alert: Failed to process record
java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size
	at org.bouncycastle.tls.crypto.impl.jcajce.JceChaCha20Poly1305.init(Unknown Source)
	at org.bouncycastle.tls.crypto.impl.TlsAEADCipher.<init>(Unknown Source)
	at org.bouncycastle.tls.crypto.impl.jcajce.JcaTlsCrypto.createChaCha20Poly1305(Unknown Source)
	at org.bouncycastle.tls.crypto.impl.jcajce.JcaTlsCrypto.createCipher(Unknown Source)
	at org.bouncycastle.tls.TlsUtils.initCipher(Unknown Source)
	at org.bouncycastle.tls.TlsServerProtocol.receiveClientKeyExchangeMessage(Unknown Source)
	at org.bouncycastle.tls.TlsServerProtocol.handleHandshakeMessage(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source)
	at org.bouncycastle.tls.RecordStream.readFullRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.safeReadFullRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.offerInput(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.offerInput(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLEngine.unwrap(Unknown Source)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:296)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1342)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1284)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1029)
	at javax.crypto.Cipher.implInit(Cipher.java:795)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:854)
	at javax.crypto.Cipher.init(Cipher.java:1374)
	... 37 more

**Comment by boaks** [comment]
[bc_tls.pcapng.gz](https://github.com/bcgit/bc-java/files/7448619/bc_tls.pcapng.gz)

**Comment by boaks** [comment]
Does that help?

I guess, if you run a simple test with java 7 using the "restricted export policy", you will also get that error.

**Comment by peterdettman** [comment]
Thanks, we'll investigate further. I've found that our support-checking code doesn't attempt to distinguish based on key size, so we'll probably need to improve that (although apparently none of our users have previously been interested in restricted export policy!). Though JDK 7 is old, BCJSSE is still supporting even JDK 5 to the extent possible.

**Comment by peterdettman** [comment]
@boaks I've updated the cipher-support checks to also consult Cipher.getMaxAllowedKeyLength, which should trim the list of cipher suites accordingly under a restricted policy. If you have a mind to test it, the changes are in our latest beta version (170b10) here: https://downloads.bouncycastle.org/betas/ .

**Comment by boaks** [comment]
I will try to test it.

**Comment by boaks** [comment]
Using:

```
1156268 Nov  4 09:54 bcpkix-jdk15on-170b10.jar
6903871 Nov  4 09:53 bcprov-jdk15on-170b10.jar
1606302 Nov  4 09:54 bctls-jdk15on-170b10.jar
```

I get

```
java.lang.NoClassDefFoundError: org/bouncycastle/asn1/eac/EACObjectIdentifiers
	at org.bouncycastle.tls.TlsUtils.createCertSigAlgOIDs(TlsUtils.java:98)
	at org.bouncycastle.tls.TlsUtils.<clinit>(TlsUtils.java:60)
	at org.bouncycastle.tls.NamedGroup.canBeNegotiated(NamedGroup.java:120)
	at org.bouncycastle.jsse.provider.ProvX509KeyManagerSimple.addECFilter13(ProvX509KeyManagerSimple.java:59)
	at org.bouncycastle.jsse.provider.ProvX509KeyManagerSimple.createFiltersClient(ProvX509KeyManagerSimple.java:142)
	at org.bouncycastle.jsse.provider.ProvX509KeyManagerSimple.<clinit>(ProvX509KeyManagerSimple.java:54)
	at org.bouncycastle.jsse.provider.ProvKeyManagerFactorySpi.engineInit(ProvKeyManagerFactorySpi.java:120)
	at javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:259)
	at org.eclipse.californium.elements.util.SslContextUtil.createKeyManager(SslContextUtil.java:1222)
	at org.eclipse.californium.elements.util.SslContextUtil.createKeyManager(SslContextUtil.java:1147)
	at org.eclipse.californium.elements.util.SslContextUtil.createSSLContext(SslContextUtil.java:1080)
	at org.eclipse.californium.elements.util.SslContextUtil.createSSLContext(SslContextUtil.java:1052)
	at org.eclipse.californium.elements.tcp.netty.TlsConnectorTestUtil.initializeSsl(TlsConnectorTestUtil.java:81)
	at org.eclipse.californium.elements.tcp.netty.TlsConnectorTest.initializeSsl(TlsConnectorTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:768)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

Do I need an additional jar?

**Comment by peterdettman** [comment]
Yes, as of 1.70 some classes have been moved into the bcutil jar, so you will need that one too I guess.

**Comment by boaks** [comment]
Works! (On my machine with java 7)

```
Cipher Suites (11 suites)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (0xc023)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (0x0067)
    Cipher Suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 (0x0040)
    Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (0xc009)
    Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)
    Cipher Suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA (0x0033)
    Cipher Suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA (0x0032)
    Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA256 (0x003c)
    Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
    Cipher Suite: TLS_EMPTY_RENEGOTIATION_INFO_SCSV (0x00ff)
```

**Comment by boaks** [comment]
should I close the issue?

**Comment by peterdettman** [comment]
Thanks for the confirmation and the original report.

**Comment by timriker** [comment]
How did you dump the Cipher Suites above?

**Comment by boaks** [comment]
Setting up the TLS socket, I use the provided [SSLContext](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLContext.html) to create the [SSLEngine](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLEngine.html) and call there [SSLEngine.getEnabledCipherSuites()](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLEngine.html#getEnabledCipherSuites()).

In the meantime I removed that list, the code now only sets the cipher suites, if used with bc before 1.70.
See [SSLEngine.setEnabledCipherSuites()](https://github.com/eclipse-californium/californium/blob/main/element-connector-tcp-netty/src/main/java/org/eclipse/californium/elements/tcp/netty/TlsClientConnector.java#L154-L186)
