### ISSUE TITLE
How to parse PKCS1 encrypted privatekey by EC and sm4-cbc

### ISSUE THREAD

**Issue by flymoondust** [bcgit/bc-java#1066]
Private key like this:
-----BEGIN EC PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: SM4-CBC,xxxxxxx

I find out that the PEMUtilities.crypt don't support algorithm like sm4-cbc

my code like this:
`PEMParser pemParser = new PEMParser(new StringReader(keyStr));
            Object object = pemParser.readObject();
            JcaPEMKeyConverter converter = new JcaPEMKeyConverter().setProvider("BC");

            KeyPair kp;
            if (object instanceof PEMEncryptedKeyPair) {
                // Encrypted key - we will use provided password
                PEMEncryptedKeyPair ckp = (PEMEncryptedKeyPair) object;
                // uses the password to decrypt the key
                PEMDecryptorProvider decProv = new JcePEMDecryptorProviderBuilder().setProvider("BC").build(keyPass);
                kp = converter.getKeyPair(ckp.decryptKeyPair(decProv));

                privateKey = kp.getPrivate();`

i encounter error like this:
org.bouncycastle.openssl.EncryptionException: **unknown encryption with private key**
	at org.bouncycastle.openssl.jcajce.PEMUtilities.crypt(Unknown Source) ~[bcpkix-jdk15on-1.68.jar:1.68.00.0]
	at org.bouncycastle.openssl.jcajce.JcePEMDecryptorProviderBuilder$1$1.decrypt(Unknown Source) ~[bcpkix-jdk15on-1.68.jar:1.68.00.0]
	at org.bouncycastle.openssl.PEMEncryptedKeyPair.decryptKeyPair(Unknown Source) ~[bcpkix-jdk15on-1.68.jar:1.68.00.0]

**Comment by mmdet** [comment]
bc库已经实现了sm4算法，估计需要你自己重写某些方法来扩展了

**Comment by winfriedgerlach** [comment]
@flymoondust @mmdet is the question resolved, can the issue be closed?

**Comment by dghgit** [comment]
Now done and up on https://www.bouncycastle.org/betas
