### ISSUE TITLE
Java 16+ Using Bouncycastle Provider with SpringBoot "java.lang.SecurityException: JCE cannot authenticate the provider BC"

### ISSUE THREAD

**Issue by mikegike** [bcgit/bc-java#1067]
Hi,
I am not sure if it is really a bouncycastle issue, but I wanted to try my luck here.

Running bouncy castle functionality in a spring boot jar container ends up in the exception "java.lang.SecurityException: JCE cannot authenticate the provider BC" when using Oracle JDK from version 16+.

Running same jar container with OpenJDK 16+ or Oracle JDK 15- works fine.
Running code from IDE like Eclipse works also fine.

I found nothing special in Java 16 release notes what I could link to this problem. 
Only cause, I would suppose that it is either an issue with bouncycastelprovider signature or a springboot classloader.

You can find a simple springboot project I used to create the jar for my tests at:
[bcprovidertest](https://github.com/mikegike/bcprovidertest/blob/main/src/main/java/mis/bcprovidertest/BcprovidertestApplication.java)

Regards
Mike

Additionally the full stacktrace:
java.lang.SecurityException: JCE cannot authenticate the provider BC
        at java.base/javax.crypto.Cipher.getInstance(Cipher.java:722)
        at mis.bcprovidertest.BcprovidertestApplication.aesencryption(BcprovidertestApplication.java:76)
        at mis.bcprovidertest.BcprovidertestApplication.main(BcprovidertestApplication.java:33)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.IllegalStateException: zip file closed
        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:829)
        at java.base/java.util.zip.ZipFile.getManifestName(ZipFile.java:1055)
        at java.base/java.util.zip.ZipFile$1.getManifestName(ZipFile.java:1098)
        at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:460)
        at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:316)
        at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:259)
        at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:129)
        at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:189)
        at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:217)
        at java.base/javax.crypto.Cipher.getInstance(Cipher.java:718)
        ... 10 more

**Comment by thelateperseus** [comment]
I had the same problem. I believe the issue is related to the way that Spring Boot loads jars from the fat jar, so I've raised [#28837 ](https://github.com/spring-projects/spring-boot/issues/28837) against the Spring Boot project.

**Comment by mikegike** [comment]
Thanks a lot @thelateperseus hopefully will be solved by the mentioned ticket.

**Comment by UVHarshan** [comment]
I am having the same issue with my Spring Boot application running on JVM 16. How to solve this issue?

**Comment by jarekczek** [comment]
This bug is also filed under Spring Boot:
https://github.com/spring-projects/spring-boot/issues/28837
There are other workarounds given there.
