### ISSUE TITLE
Unable to build graalvm based native image using bcfips library

### ISSUE THREAD

**Issue by shashanka981** [bcgit/bc-java#1077]
Hi,

We are building a graalvm based native image for our application that is using bcfips library. Native image generation goes through fine, however application is failing to start as we try to register the bcfips provider programatically from the code:. Also, we have ensured bcfips library is present in the  classpath of native image command  - "RUN native-image -cp /home/app/libs/app.jar:/home/app/libs/bc-fips-1.0.2.1.jar
"

        **Security.insertProviderAt(new BouncyCastleFipsProvider(), 9999);**

version of graalvm: **FROM ghcr.io/graalvm/graalvm-ce:java11-21.3.0** 
version of bcfips : **org.bouncycastle:bc-fips:1.0.2.1**

**Args= -H:IncludeResources=logback.xml|application.yml \
  -H:Name=service \
  -H:Class=com.pega.fnx.servicecommons.Application \
  -H:+ReportExceptionStackTraces \
  -H:+ReportUnsupportedElementsAtRuntime \
  -H:+TraceSecurityServices \
  -H:-EnableSecurityServicesFeature \
  -H:AdditionalSecurityProviders=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider \
  --no-fallback \
  --report-unsupported-elements-at-runtime \
  --initialize-at-build-time=net.logstash.logback.Logback11Support,org.apache.xerces.util,org.apache.xerces.impl,org.apache.xerces.xni,org.apache.xerces.parsers \
  --initialize-at-run-time=io.micronaut.tracing.brave.instrument.http.BraveTracingServerFilter,io.micronaut.tracing.brave.instrument.http.HttpClientTracingPublisher**

Actual exception that i get when running the native image executable is :

ror instantiating bean of type [com.pega.fnx.servicecommons.lifecycle.ServiceLifecycle]: Module startup failed: Unable to initialize module: org.bouncycastle.crypto.fips.FipsAES
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [com.pega.fnx.servicecommons.lifecycle.ServiceLifecycle] could not be loaded: Error instantiating bean of type [com.pega.fnx.servicecommons.lifecycle.ServiceLifecycle]: Module startup failed: Unable to initialize module: org.bouncycastle.crypto.fips.FipsAES
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1549)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:220)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2812)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:233)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:166)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
	at com.pega.fnx.servicecommons.Application.main(Application.java:41)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [com.pega.fnx.servicecommons.lifecycle.ServiceLifecycle]: Module startup failed: Unable to initialize module: org.bouncycastle.crypto.fips.FipsAES
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1927)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2679)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2215)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1543)
	... 8 common frames omitted
Caused by: org.bouncycastle.crypto.fips.FipsOperationError: Module startup failed: Unable to initialize module: org.bouncycastle.crypto.fips.FipsAES
	at org.bouncycastle.crypto.fips.FipsStatus.isReady(Unknown Source)
	at org.bouncycastle.crypto.CryptoServicesRegistrar.getDefaultMode(Unknown Source)
	at org.bouncycastle.crypto.CryptoServicesRegistrar.<clinit>(Unknown Source)
	at org.bouncycastle.jcajce.provider.ProvSecureHash$MD5.configure(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
	at com.pega.fnx.encryptionengine.lifecycle.startup.CipherConfigInitializationTask.perform(CipherConfigInitializationTask.java:37)
	at com.pega.fnx.servicecommons.lifecycle.ServiceLifecycle.onStartUp(ServiceLifecycle.java:55)
	at com.pega.fnx.servicecommons.lifecycle.$ServiceLifecycleDefinition.initialize(Unknown Source)
	at com.pega.fnx.servicecommons.lifecycle.$ServiceLifecycleDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1898)
	... 11 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to initialize module: org.bouncycastle.crypto.fips.FipsAES
	at org.bouncycastle.crypto.fips.FipsStatus.loadClass(Unknown Source)
	at org.bouncycastle.crypto.fips.FipsStatus.access$200(Unknown Source)
	at org.bouncycastle.crypto.fips.FipsStatus$Loader.<init>(Unknown Source)
	... 23 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.crypto.fips.FipsAES
	at java.lang.Class.forName(DynamicHub.java:1433)
	at java.lang.Class.forName(DynamicHub.java:1408)
	... 26 common frames omitted

**Comment by tonywasher** [comment]
GraalVM does not support the dynamic registration of security modules. See [here](https://www.graalvm.org/reference-manual/native-image/JCASecurityServices/).

You will need to configure FIPS explicitly in the **java.security** file

**Comment by tonywasher** [comment]
To clarify, the previous link refers to the fact that GraalVM does not support dynamic registration within a native image.

**Comment by shashanka981** [comment]
@tonywasher can you point some references/sample examples on how to configure the provider in java.security file. Graalvm doc doesnt seem to cover how to configure the provider

**Comment by tonywasher** [comment]
I have no access to the BCFIPS documentation, which should be the first place to look for information. Presumably you have a BCFIPS contract and therefore access to this documentation. 

Several issues have been raised in the past regarding BCFIPS, several of which include the java.security configuration. For example [issue1000](https://github.com/bcgit/bc-java/issues/1000). I have no idea what the parameters mean and whether they are relevant to you, but it's a starting point. The BCFIPS documentation should provide the details.

**Comment by shashanka981** [comment]
@tonywasher  where do i log a ticket to get the community support for BCFIPS library

**Comment by shashanka981** [comment]
@tonywasher any idea how do i reach out to get the community support for BCFIPS library

**Comment by tonywasher** [comment]
I would start with the information on the [BouncyCastle FIPS page](https://www.bouncycastle.org/fips-java/)

**Comment by dghgit** [comment]
I'm guessing, but the module is probably failing the checksum test - if you look at the source of FipsStatus.java you'll see the FipsAES class is the first thing to get loaded, but it's not going to load if the checksum fails. You should be able to confirm this your self by commenting out the call to:

   checksumValidate();

in FipsStatus.java and recompiling.

Note that this will mean the jar is no longer FIPS compliant, although I'm not sure how much of a problem that would be as the GraalVM isn't a platform we currently certify on anyway.

As @tonywasher has pointed out, details about getting support for FIPS are available on the FIPS pages.
