### ISSUE TITLE
XECPublicKey is in module java.base of loader 'bootstrap') with 11.0.11 or 11.0.14 Corretto + Windows Server

### ISSUE THREAD

**Issue by regiseduardogregol** [bcgit/bc-java#1096]
Guys, I update my Apache Karaf from version 4.2.9 to version 4.2.14 because of log4j vulnerabilities.
After that, to raise the karaf I have the ClassCastException.
> Caused by: java.lang.ClassCastException: class org.bouncycastle.jcajce.provider.asymmetric.edec.BCXDHPublicKey cannot be cast to class java.security.interfaces.XECPublicKey (org.bouncycastle.jcajce.provider.asymmetric.edec.BCXDHPublicKey is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @49dd5aa2; java.security.interfaces.XECPublicKey is in module java.base of loader 'bootstrap')

I noticed that on Windows karaf uses older libs and on Linux it uses newer ones.
Does anyone have an idea of what to do to resolve this situation?

thanks in advance!

**Comment by dghgit** [comment]
You need to be using a system that can handle the multi-release jars.

**Comment by mouse07410** [comment]
A naive question: what is multi-release jar?

**Comment by dghgit** [comment]
With the advent of Oracle 9 a jar can contain a versions directory in META-INF which contains alternate classes for a particular JVM, we use this for Java 11 (XDH) and Java 15 (EdDSA) to provider alternate implementations for the relevant classes so that the provider is able to conform to what the JVM expects (implementation of XECPublicKey for example). Not everything recognises these though - container environments in particular. The problem is basically going away, but the reality is there are still environments out there where a jar might be loaded and the versions directory ignored.

**Comment by mouse07410** [comment]
I see. May I repeat request to move support from JDK-15 to JDK-17 (LTS)? Or at the very least, add JDK-17? And post your `bnd.sh` file? 

I recompile BC from sources, and on a machine that has only JDK-17 EdDSA tests fail.

**Comment by dghgit** [comment]
It might be more useful if you can tell me what's failing? Currently we're trying to lift the main distribution to Java 8, believe it or not even Oracle are still supporting Java 6 - it's a very broad church we're catering to.

**Comment by mouse07410** [comment]
> It might be more useful if you can tell me what's failing?

How about this:

<img width="898" alt="Screen Shot 2022-02-11 at 07 50 31" src="https://user-images.githubusercontent.com/5923577/153594421-f7b9ddc0-aaf2-4cdd-9ef3-b3c7493b2900.png">

I observe it consistently on a machine that only has JDK-17 (Amazon Corretto, if it matters - but I doubt that). Machine that builds and tests with `corretto-11` and has `corretto-17` installed, does not produce any errors.

```
CertTest: 9 failed - exception java.security.InvalidKeyException: cannot identify EdDSA public key 
at org.bouncycastle.cert.test.AllTests.testSimpleTests(AllTests.java:30) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:23) 
at junit.extensions.TestSetup$1.protect(TestSetup.java:23) 
at junit.extensions.TestSetup.run(TestSetup.java:27) 
.  .  . 
index 9 BlockCipher: IDEA/PGPCFB/NoPadding failed encryption - java.io.IOException: javax.crypto.ShortBufferException: output buffer too short for input. 

junit.framework.AssertionFailedError: index 9 BlockCipher: IDEA/PGPCFB/NoPadding failed encryption - java.io.IOException: javax.crypto.ShortBufferException: output buffer too short for input. 
at org.bouncycastle.jce.provider.test.SimpleTestTest.testJCE(SimpleTestTest.java:26) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:23) 
at junit.extensions.TestSetup$1.protect(TestSetup.java:23) 
at junit.extensions.TestSetup.run(TestSetup.java:27)
.  .  .
Expected: <null> but was: junit.framework.AssertionFailedError 

junit.framework.AssertionFailedError: Expected: <null> but was: junit.framework.AssertionFailedError 
at org.bouncycastle.jsse.provider.test.TestProtocolUtil.runClientAndServer(TestProtocolUtil.java:68) 
at org.bouncycastle.jsse.provider.test.EdDSACredentialsTest.implTestEdDSACredentials(EdDSACredentialsTest.java:211)
at org.bouncycastle.jsse.provider.test.EdDSACredentialsTest.test12_Ed25519(EdDSACredentialsTest.java:181) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:23) 
at junit.extensions.TestSetup$1.protect(TestSetup.java:23) 
at junit.extensions.TestSetup.run(TestSetup.java:27) 
.  .  .
Expected: <null> but was: junit.framework.AssertionFailedError 

junit.framework.AssertionFailedError: Expected: <null> but was: junit.framework.AssertionFailedError 
at org.bouncycastle.jsse.provider.test.TestProtocolUtil.runClientAndServer(TestProtocolUtil.java:68) 
at org.bouncycastle.jsse.provider.test.EdDSACredentialsTest.implTestEdDSACredentials(EdDSACredentialsTest.java:211)
at org.bouncycastle.jsse.provider.test.EdDSACredentialsTest.test12_Ed448(EdDSACredentialsTest.java:186) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:23) 
at junit.extensions.TestSetup$1.protect(TestSetup.java:23) 
at junit.extensions.TestSetup.run(TestSetup.java:27) 
.  .  .
Expected: <null> but was: junit.framework.AssertionFailedError 

junit.framework.AssertionFailedError: Expected: <null> but was: junit.framework.AssertionFailedError 
at org.bouncycastle.jsse.provider.test.TestProtocolUtil.runClientAndServer(TestProtocolUtil.java:68) 
at org.bouncycastle.jsse.provider.test.EdDSACredentialsTest.implTestEdDSACredentials(EdDSACredentialsTest.java:211)
at org.bouncycastle.jsse.provider.test.EdDSACredentialsTest.test13_Ed25519(EdDSACredentialsTest.java:191) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:23) 
at junit.extensions.TestSetup$1.protect(TestSetup.java:23) 
at junit.extensions.TestSetup.run(TestSetup.java:27)
.  .  .
Expected: <null> but was: junit.framework.AssertionFailedError 

junit.framework.AssertionFailedError: Expected: <null> but was: junit.framework.AssertionFailedError 
at org.bouncycastle.jsse.provider.test.TestProtocolUtil.runClientAndServer(TestProtocolUtil.java:68) 
at org.bouncycastle.jsse.provider.test.EdDSACredentialsTest.implTestEdDSACredentials(EdDSACredentialsTest.java:211)
at org.bouncycastle.jsse.provider.test.EdDSACredentialsTest.test13_Ed448(EdDSACredentialsTest.java:196) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:23) 
at junit.extensions.TestSetup$1.protect(TestSetup.java:23) 
at junit.extensions.TestSetup.run(TestSetup.java:27) 
```

**Comment by regiseduardogregol** [comment]
Guys, I'm here again. 

This alternitive fix worked for me
```java
System.setProperty("jdk.tls.namedGroups", "secp256r1, secp384r1, ffdhe2048, ffdhe3072");
```
I saw in this topic
https://github.com/qzind/tray/issues/894#issuecomment-995555488

Can I close this issue?

**Comment by mouse07410** [comment]
> Can I close this issue?

Since my comments are a side-track, not directly related to this issue - it's up to @dghgit whether to move "my" stuff to a separate issue and close this one (for that eventuality, I created a new one here https://github.com/bcgit/bc-java/issues/1107), or continue here.
