### ISSUE TITLE
WildFly fails to start with the latest FIPS jars

### ISSUE THREAD

**Issue by lenv** [bcgit/bc-java#1098]
We had working WildFly standalone server configured for FIPS environment
java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment Corretto-8.312.07.1 (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM Corretto-8.312.07.1 (build 25.312-b07, mixed mode)

After switch from ( bc-fips-1.0.1.jar bctls-fips-1.0.8.jar ) to ( bc-fips-1.0.2.jar   bctls-fips-1.0.12.2.jar ) 
we are getting the following exception on server sart up.

2022-01-27 16:48:11,414 TRACE [org.wildfly.security] (MSC service thread 1-1) Provider BCJSSE version 1.001202 was added for algorithm TLSV1
2022-01-27 16:48:11,414 TRACE [org.wildfly.security] (MSC service thread 1-1) Provider BCJSSE version 1.001202 was added for algorithm TLSV1.3
2022-01-27 16:48:11,414 TRACE [org.wildfly.security] (MSC service thread 1-1) Provider BCJSSE version 1.001202 was added for algorithm TLSV1.1
2022-01-27 16:48:11,414 TRACE [org.wildfly.security] (MSC service thread 1-1) Provider BCJSSE version 1.001202 was added for algorithm DEFAULT
2022-01-27 16:48:11,414 TRACE [org.wildfly.security] (MSC service thread 1-1) Provider BCJSSE version 1.001202 was added for algorithm TLSV1.2
2022-01-27 16:48:11,414 TRACE [org.wildfly.security] (MSC service thread 1-1) Provider BCJSSE version 1.001202 was added for algorithm TLS
2022-01-27 16:48:11,416 TRACE [org.wildfly.security] (MSC service thread 1-1) Supported protocols are: [TLSV1.2]
2022-01-27 16:48:11,416 TRACE [org.wildfly.security] (MSC service thread 1-1) Attempting to get an SSLContext instance using protocol TLSV1.2 and provider BCJSSE version 1.001202
2022-01-27 16:48:11,420 TRACE [org.jboss.modules] (MSC service thread 1-1) Finding class java.lang.StackTraceElement from Module "org.jboss.logmanager" version 2.1.14.Final from local module loader @27c20538 (finder: local module finder @72d818d1 (roots: /opt/infor/wildfly.Final/modules,/opt/infor/wildfly.Final/modules/system/layers/base))
2022-01-27 16:48:11,420 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service org.wildfly.security.ssl-context.httpsSSLContext: org.jboss.msc.service.StartException in service org.wildfly.security.ssl-context.httpsSSLContext: Failed to start service
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1731)
        at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: SSLContext has not been initialized.
        at org.bouncycastle.jsse.provider.ProvSSLContextSpi.getContextData(ProvSSLContextSpi.java:877)
        at org.bouncycastle.jsse.provider.ProvSSLContextSpi.engineGetServerSessionContext(ProvSSLContextSpi.java:821)
        at javax.net.ssl.SSLContext.getServerSessionContext(SSLContext.java:386)
        at org.wildfly.security.ssl.SSLContextBuilder.lambda$build$0(SSLContextBuilder.java:340)
        at org.wildfly.security.OneTimeSecurityFactory.create(OneTimeSecurityFactory.java:53)
        at org.wildfly.extension.elytron.SSLDefinitions$6.lambda$getValueSupplier$1(SSLDefinitions.java:1173)
        at org.wildfly.extension.elytron.TrivialService.start(TrivialService.java:53)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
        ... 6 more

java.security:

security.provider.1 = org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider
security.provider.2=org.bouncycastle.jsse.provider.BouncyCastleJsseProvider fips:org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider
security.provider.3 = sun.security.provider.Sun
security.provider.4 = sun.security.rsa.SunRsaSign
security.provider.5 = sun.security.ec.SunEC
security.provider.6 = com.sun.crypto.provider.SunJCE
security.provider.7 = sun.security.jgss.SunProvider
security.provider.8 = com.sun.security.sasl.Provider
security.provider.9 = org.jcp.xml.dsig.internal.dom.XMLDSigRI
security.provider.10 = sun.security.smartcardio.SunPCSC

ssl.KeyManagerFactory.algorithm = PKIX
ssl.TrustManagerFactory.algorithm = PKIX

What could be the reson(s) for protected synchronized void engineInit(KeyManager[] kms, TrustManager[] tms, SecureRandom sr) throws KeyManagementException
to fail to initialize contextData ?
Is it possible to capture BC messages in the WildFly log?

Regards,
Leonard

**Comment by peterdettman** [comment]
BCJSSE is strict about requiring initialization of the SSLContext before accessing anything (in this case of accessing session contexts SunJSSE has them available prior to initialization, but there are some nuanced potential bugs lurking there IMO).

In any case, [this commit](https://github.com/wildfly-security/wildfly-elytron/commit/3d7375f5f61526a7b8c4046878adc68e6777b308) appears to have fixed this issue in wildfly-elytron by moving the fetching of the session context to after the init call.

However it is not immediately clear to me which versions of wildfly will have this fix incorporated (I'm not familiar with the project organization). Please ask the wildfly crew what version(s) might have it (and posting back here would be appreciated).

**Comment by lenv** [comment]
Thank you
