### ISSUE TITLE
Code not compatible with java 1.5 in bctls-jdk15to18 org.bouncycastle.jsse.provider.ProvX509KeyManagerSimple$Match

### ISSUE THREAD

**Issue by wodzu-dudis** [bcgit/bc-java#1130]
Class org.bouncycastle.jsse.provider.ProvX509KeyManagerSimple$Match uses two methods that are not implemented in jre 1.5. It causes  java.lang.NoSuchMethodError during TLS server connection handshake :

Exception in thread "Thread-1" java.lang.NoSuchMethodError: java.lang.Boolean.compare(ZZ)I
	at org.bouncycastle.jsse.provider.ProvX509KeyManagerSimple$Match.compareTo(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvX509KeyManagerSimple.getBestMatch(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvX509KeyManagerSimple.chooseKeyBC(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvX509KeyManagerSimple.chooseServerKeyBC(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.chooseServerKey(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvTlsServer.selectServerCredentialsLegacy(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvTlsServer.selectCredentials(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvTlsServer.selectCipherSuite(Unknown Source)
	at org.bouncycastle.tls.AbstractTlsServer.getSelectedCipherSuite(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvTlsServer.getSelectedCipherSuite(Unknown Source)
	at org.bouncycastle.tls.TlsServerProtocol.generateServerHello(Unknown Source)
	at org.bouncycastle.tls.TlsServerProtocol.handleHandshakeMessage(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source)
	at org.bouncycastle.tls.RecordStream.readRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.blockForHandshake(Unknown Source)
	at org.bouncycastle.tls.TlsServerProtocol.accept(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.handshakeIfNecessary(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect$AppDataOutput.write(Unknown Source)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1685)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1594)
	at java.io.ObjectOutputStream.<init>(ObjectOutputStream.java:208)

Problematic code resides in Match.compareTo method:

```
  public int compareTo(Match that)
        {
            int cmp = Boolean.compare(that.isValid(), this.isValid());
            if (cmp == 0)
            {
                cmp = Integer.compare(this.keyTypeIndex, that.keyTypeIndex);
                if (cmp == 0)
                {
                    cmp = this.quality.compareTo(that.quality);
                }
            }
            return cmp;
        }
```

According to javadoc **Boolean.compare** and **Integer.compare** where introduced in java 1.7
[https://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html#compare(boolean,%20boolean)](https://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html#compare(boolean,%20boolean))

[https://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html#compare(int,%20int)](https://docs.oracle.com/javase/7/docs/api/java/lang/Integer.html#compare(int,%20int))

Proposed solution is to replace those compare methods with code copied from 1.7 sources:

```
      public int compareTo(Match that)
        {
            int cmp = (that.isValid() == this.isValid()) ? 0 : (that.isValid() ? 1 : -1);
            if (cmp == 0)
            {
                cmp = this.keyTypeIndex < that.keyTypeIndex?-1:(this.keyTypeIndex == that.keyTypeIndex?0:1);
                if (cmp == 0)
                {
                    cmp = this.quality.compareTo(that.quality);
                }
            }
            return cmp;
        }
```

**Comment by dghgit** [comment]
Thanks for the report. I've pushed the fix, it should appear in the next release (possibly the next beta as well..., but we're heading into release mode now).
