### ISSUE TITLE
Error: module java.base does not export sun.security.provider (JDK 17)

### ISSUE THREAD

**Issue by dvd95** [bcgit/bc-java#1149]
It seems that sun.security.provider have been marked internal post JDK 16. Because of this initialization of BC fips fails.
Is there any work around for this problem in bc-fips- 1.0.2.3.

When will the support for Java 17 for bc-fips be available?

StackTrace: 

> `Caused by: org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.IllegalAccessError: class org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$CoreSecureRandom (in unnamed module @0x1c59e897) cannot access class sun.security.provider.SecureRandom (in module java.base) because module java.base does not export sun.security.provider to unnamed module @0x1c59e897 
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1082) ... 47 more	
Caused by: java.lang.IllegalAccessError: class org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$CoreSecureRandom (in unnamed module @0x1c59e897) cannot access class sun.security.provider.SecureRandom (in module java.base) because module java.base does not export sun.security.provider to unnamed module @0x1c59e897 
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$CoreSecureRandom.&lt;init&gt;(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$2.run(Unknown Source) 
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$2.run(Unknown Source) 
	at java.base/java.security.AccessController.doPrivileged(Unknown Source) 
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.getDefaultSecureRandom(Unknown Source) 
	at org.bouncycastle.jcajce.provider.BaseSignature.engineInitSign(Unknown Source) 
	at java.base/java.security.Signature$Delegate.engineInitSign(Unknown Source) 
	at java.base/java.security.Signature.initSign(Unknown Source) 
	at com.nimbusds.jose.crypto.RSASSASigner.getInitiatedSignature(RSASSASigner.java:261) 
	at com.nimbusds.jose.crypto.RSASSASigner.sign(RSASSASigner.java:236) 
	at com.nimbusds.jose.JWSObject.sign(JWSObject.java:304) `

**Comment by dghgit** [comment]
What is the java.secrity property securerandom.strongAlgorithms set to, The stack trace should only occur if it's invalid.

**Comment by dvd95** [comment]
Hi 
This is working fine with Java 11.
I am only facing issues with Java 17.

Can you please let me know when will the Java 17 certified version release?

**Comment by dghgit** [comment]
What is the java.security property securerandom.strongAlgorithms set to? The stack trace should only occur if it's invalid.

**Comment by dvd95** [comment]
it is set to
securerandom.strongAlgorithms=Windows-PRNG:SunMSCAPI,DRBG:SUN

This is same in both the versions of Java

**Comment by dghgit** [comment]
Ah. Is the SunMSCAPI provider present in the Java17 case?

**Comment by dvd95** [comment]
Hi,
SunMSCAPI is present in Java17 and it is included in the java.security security.providers

**Comment by dghgit** [comment]
Try running a small program with the following lines in it on Java 17 and tell me what it produces:

 AccessController.doPrivileged(new PrivilegedAction<SecureRandom>()
            {
                public SecureRandom run()
                {
                    try
                    {
                        return (SecureRandom)SecureRandom.class.getMethod("getInstanceStrong").invoke(null);
                    }
                    catch (Exception e)
                    {
                        e.printStackTrace(); // return new CoreSecureRandom();  // fallback
                    }
                }
            });

I think that should tell us what is going on.

**Comment by dvd95** [comment]
It provides a java.security.SecureRandom obj with algo as "Windows-PRNG" and "SunMSCAPI" provider

**Comment by dghgit** [comment]
Okay that was unexpected. Something is lying to us... If that work then:
org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$CoreSecureRandom
should never be created. I suspect the fact it's running under spring has changed things.
Is it possible to try this with the debug version of the jar, possibly seeing what exception is being thrown?

**Comment by dghgit** [comment]
Second thought. Is there a Java security manager involved here? The FIPS module may need permission to do the getInstanceStrong() call via reflection.

**Comment by dvd95** [comment]
Hi I tried with the debug version of the jar too. 
the output is same. 

Just for information, this is running within a web application hosted on tomcat. Also, there is no Java Security manager involved.

**_Also, can you please let me know when will the Java 17 certified jar release?_**

**Comment by dghgit** [comment]
What was the stack trace?

With Java 17, that is still too be determined.

**Comment by dvd95** [comment]
It's the same as mentioned in the main question.

**Comment by dghgit** [comment]
Line numbers?

**Comment by dghgit** [comment]
closing as inactive.

**Comment by galaxis7** [comment]
Has this been resolved?  This is my stack trace trying to run "keytool" w/ BPFIPS provider to create a BCFKS keystore on Red Had OpenJDK 17, RHEL 8.4, BC FIPS 1.0.2.1; also using 1.0.2.4 - which was suppose to be **certified on JDK 17** as of last month:
```
Exception in thread "main" java.lang.IllegalAccessError: class org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$CoreSecureRandom (in unnamed module @0x2fdf22f7) cannot access class sun.security.provider.SecureRandom (in module java.base) because module java.base does not export sun.security.provider to unnamed module @0x2fdf22f7
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$CoreSecureRandom.<init>(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$4.run(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.getCoreSecureRandom(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.access$200(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$2.run(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$2.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.getDefaultEntropySource(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.getDefaultSecureRandom(Unknown Source)
	at org.bouncycastle.jcajce.provider.ProvBCFKS$BCFIPSKeyStoreSpi.getDefaultSecureRandom(Unknown Source)
	at org.bouncycastle.jcajce.provider.ProvBCFKS$BCFIPSKeyStoreSpi.generatePkbdAlgorithmIdentifier(Unknown Source)
	at org.bouncycastle.jcajce.provider.ProvBCFKS$BCFIPSKeyStoreSpi.engineLoad(Unknown Source)
	at java.base/java.security.KeyStore.load(Unknown Source)
	at java.base/sun.security.tools.keytool.Main.doCommands(Unknown Source)
	at java.base/sun.security.tools.keytool.Main.run(Unknown Source)
	at java.base/sun.security.tools.keytool.Main.main(Unknown Source)
```
This is with override from custom appended "java.security" file because [keycloak site](https://www.keycloak.org/server/fips#_bouncycastle_library) seems to be saying to do this because BCFKS needs it(?):
` securerandom.strongAlgorithms=PKCS11:SunPKCS11-NSS-FIPS`
Works fine with the default:
 `securerandom.strongAlgorithms=NativePRNGBlocking:SUN,DRBG:SUN`

BC apparently is still not accounting for the module encapsulation introduced with the Java Platform Module System (JPMS) in Java 9. In this module system, certain internal Java classes (like those under sun.* or com.sun.*) are not accessible to unnamed modules (like many traditional JARs); they're considered internal APIs of the JDK and were restricted to ensure encapsulation and improve security and maintainability. This system allows the definition of modules with explicit exports and requires statements to establish dependencies and control visibility.  In my case, I guess it's possible that the custom security property is causing BC to look for a SecureRandom provider it cannot access or is not compatible with, leading to the error(?).  Is it still calling sun.security.jca.Providers.getSunProvider()?

**Comment by dghgit** [comment]
No, the JVM doesn't flag an error if it can't set up securerandom.strongAlgorithms it just fails silently. This has nothing to do with changes in Java 17 and the BCFIPS provider. Try using java.security.debug

**Comment by tspearconquest** [comment]
Hello, I'm having the same issue as @galaxis7 with Keycloak 20.0.5 and JDK17. The issue cannot be reproduced with JDK11.

I've enabled java.security.debug as follows:

```
keytool \
  -J-Djava.security.properties="/opt/java.security" \
  -J-Djava.security.debug="all" \
  -genkeypair \
  -alias dummy \
  -dname "CN=Keycloak,OU=OrgUnit,O=Org,L=City,ST=ST,C=US" \
  -keyalg RSA \
  -keypass "${KC_HTTPS_KEY_STORE_PASSWORD}" \
  -keysize 4096 \
  -keystore "${KC_HTTPS_KEY_STORE_FILE}" \
  -provider org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider \
  -providerclass org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider \
  -providername BCFIPS \
  -providerpath "/opt/keycloak/providers/bc-fips-${BC_FIPS_PROVIDER_VERSION}.jar" \
  -sigalg SHA512withRSA \
  -storepass "${KC_HTTPS_KEY_STORE_PASSWORD}" \
  -storetype BCFKS \
  -validity 398 \
  -v
```

Note, I have tried both adding only the `securerandom.strongAlgorithms` line to a custom `java.security` as mentioned on the Keycloak website, as well as the below which I was using with Keycloak 19.0.3 and JDK11 without any issues. Neither seems to work for me, and both produce the same error. I did not try leaving `securerandom.strongAlgorithms` unchanged from the defaults in the system-wide `java.security` file as @galaxis7 did.

My custom java.security file
```
security.provider.1=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider
security.provider.2=org.bouncycastle.jsse.provider.BouncyCastleJsseProvider fips:BCFIPS
security.provider.3=SUN
security.provider.4=SunRsaSign
security.provider.5=SunEC
security.provider.6=SunJSSE
security.provider.7=SunJCE
security.provider.8=SunJGSS
security.provider.9=SunSASL
security.provider.10=XMLDSig
security.provider.11=SunPCSC
security.provider.12=JdkLDAP
security.provider.13=JdkSASL
security.provider.14=SunPKCS11
securerandom.strongAlgorithms=PKCS11:SunPKCS11-NSS-FIPS
```

[kcbuildfail.log](https://github.com/bcgit/bc-java/files/14213324/kcbuildfail.log)

**Comment by dghgit** [comment]
The error will only occur if the setting of securerandom.strongAlgorithms does not map to a real RNG. I don't think the "SunPKCS11-NSS-FIPS" provider is installed in this case. It is clear from the log file that it isn't.

**Comment by tspearconquest** [comment]
Thank you for the update. I checked with a colleague who is much more familiar with Java and we were able to get it working by adding these 2 flags to the keytool command above:

```
            -J--add-exports=java.base/sun.security.provider=ALL-UNNAMED \
            -J--add-opens=java.base/sun.security.util=ALL-UNNAMED \
```

So now the full keytool command:

```
keytool -J-Djava.security.properties="/opt/java.security" \
   -J--add-exports=java.base/sun.security.provider=ALL-UNNAMED \
   -J--add-opens=java.base/sun.security.util=ALL-UNNAMED \
   -genkeypair \
   -alias dummy \
   -dname "CN=Keycloak,OU=OrgUnit,O=Org,L=City,ST=ST,C=US" \
   -keyalg RSA \
   -keypass "${KC_HTTPS_KEY_STORE_PASSWORD}" \
   -keysize 4096 \
   -keystore "${KC_HTTPS_KEY_STORE_FILE}" \
   -provider org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider \
   -providerclass org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider \
   -providername BCFIPS \
   -providerpath "/opt/keycloak/providers/bc-fips-${BC_FIPS_PROVIDER_VERSION}.jar" \
   -sigalg SHA512withRSA \
   -storepass "${KC_HTTPS_KEY_STORE_PASSWORD}" \
   -storetype BCFKS \
   -validity 398 \
   -v
```

**Comment by jtnord** [comment]
Can here for a "me too".   When running on RedHat's OpenJDK.

```
Exception in thread "main" java.lang.IllegalAccessError: class org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$CoreSecureRandom (in unnamed module @0x63429932) cannot access class sun.security.provider.SecureRandom (in module java.base) because module java.base does not export sun.security.provider to unnamed module @0x63429932
        at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$CoreSecureRandom.<init>(Unknown Source)
        at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$4.run(Unknown Source)
        at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.getCoreSecureRandom(Unknown Source)
        at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.access$600(Unknown Source)
        at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$HybridEntropySource.<init>(Unknown Source)
        at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$2$1.get(Unknown Source)
        at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$PooledSecureRandomProvider.get(Unknown Source)
        at org.bouncycastle.crypto.CryptoServicesRegistrar.getSecureRandomIfSet(Unknown Source)
        at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.getDefaultSecureRandom(Unknown Source)
        at org.bouncycastle.jcajce.provider.ProvRandom$1.createInstance(Unknown Source)
        at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider$BcService.newInstance(Unknown Source)
        at java.base/java.security.SecureRandom.getDefaultPRNG(SecureRandom.java:296)
        at java.base/java.security.SecureRandom.<init>(SecureRandom.java:225)
        at java.base/java.io.File$TempDirectory.<clinit>(File.java:1994)
        at java.base/java.io.File.createTempFile(File.java:2151)
        at executable.Main.extractFromJar(Main.java:474)
        at executable.Main.main(Main.java:265)

```

**Comment by jtnord** [comment]
I can work around this by adding `--add-exports=java.base/sun.security.provider=ALL-UNNAMED -J--add-opens=java.base/sun.security.util=ALL-UNNAMED` to the jvm command line but this is just a temporary workaround.
I;m not sure how this maps to `securerandom.strongAlgorithms` not pointing to a real RNG?  If that where the case why does granting access to the module work?

**Comment by tspearconquest** [comment]
I ended up getting past this only to have to add the same flags to `JAVA_OPTS_APPEND` for keycloak to get past the same issue. Then it ran into:

```
ERROR: Failed to start server in (production) mode
Error details:
java.lang.RuntimeException: java.lang.NoSuchMethodError: 'void org.bouncycastle.asn1.ASN1EncodableVector.<init>(int)'
	at io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:80)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:95)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits1868654632.deploy_1(Unknown Source)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits1868654632.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:103)
	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:93)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.lang.NoSuchMethodError: 'void org.bouncycastle.asn1.ASN1EncodableVector.<init>(int)'
	at org.bouncycastle.asn1.cms.GCMParameters.toASN1Primitive(Unknown Source)
	at org.bouncycastle.jcajce.provider.ASN1AlgorithmParameters.engineInit(Unknown Source)
	at java.base/java.security.AlgorithmParameters.init(AlgorithmParameters.java:293)
	at org.bouncycastle.tls.crypto.impl.jcajce.JceAEADCipherImpl.init(JceAEADCipherImpl.java:111)
	at org.bouncycastle.tls.crypto.impl.TlsAEADCipher.decodeCiphertext(TlsAEADCipher.java:291)
	at org.bouncycastle.tls.RecordStream.decodeAndVerify(RecordStream.java:255)
	at org.bouncycastle.tls.RecordStream.readRecord(RecordStream.java:240)
	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:879)
	at org.bouncycastle.tls.TlsProtocol.blockForHandshake(TlsProtocol.java:427)
	at org.bouncycastle.tls.TlsClientProtocol.connect(TlsClientProtocol.java:88)
	at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(ProvSSLSocketWrap.java:608)
	at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(ProvSSLSocketWrap.java:584)
	at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:41)
	at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:584)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:168)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:247)
	at org.postgresql.Driver.makeConnection(Driver.java:434)
	at org.postgresql.Driver.connect(Driver.java:291)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
	at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:49)
	at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:35)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:232)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:535)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:516)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

So I think there might be something I'm still doing wrong for JDK17 that worked fine in JDK11, but its not clear what I need to do differently so for now I'm going to roll back to JDK11.

**Comment by dghgit** [comment]
Yes, securerandom.strongAlgorithms in java.security must point to a real implementation which is accessible to the JVM to avoid this issue - the exception is being raised by the provider attempting to recover from this. The implementation will be used for seed generation so it cannot rely on BCFIPS.

**Comment by tspearconquest** [comment]
What would be a real implementation that I can use with BCFIPS instead of the one I'm using from the Keycloak docs? I'm **not** going for Strict, in case it makes any difference.

**Comment by dghgit** [comment]
It just needs to be something the JVM can add - the securerandom.strongAlgorithms takes a list of algorithm_name:provider arguments. For a successful load the provider must be in the provider list and the algorithm_name must exist.

**Comment by jtnord** [comment]
for reference -> https://issues.redhat.com/browse/RHEL-3478

**Comment by tspearconquest** [comment]
Nice find @jtnord 

Any chance someone here has a contact at RHEL? The linked issue was migrated to a JIRA issue that isn't publicly accessible, so there appears to be no further updates coming on that linked issue.

**Comment by jtnord** [comment]
I think I have a support contract - but I just threw the RedHat JDK on the bonfire.
There is an amount of whack-a-mole going on...
I would suggest you add `-Dcom.redhat.fips=false` to your startup options (possibly also edit to change `/usr/lib/jvm/jre-17/conf/security/java.security` `security.useSystemPropertiesFile=true` to `security.useSystemPropertiesFile=false` so the crypto policy does not mess with the JDK config).  
If you are using bc-fips and suitable configure the JVM then you should not need the RedHat FIPS patches to be active as well.

**Comment by tspearconquest** [comment]
Thanks, I'll give this a try.

One question, if I'm not mistaken, I can avoid the edit of the system-wide java.security file by replacing `-Djava.security.properties=` with `-Djava.security.properties==` to just have my java.security file override the whole system-wide file?

I might need to still add the `security.useSystemPropertiesFile=false` to my custom security file, which is fine, but I rather avoid editing the system one in a production host or a container image if possible.

**Comment by jtnord** [comment]
yeah - but no, but maybe...   the [RedHat patches](https://access.redhat.com/jbossnetwork/restricted/softwareDetail.html?softwareId=106250&product=core.service.openjdk&version=17.0.10&downloadType=distributions) (inside the source bundle IIRC) change what properties are being looked for at runtime and some other funky stuff..
so whilst you can override all the properties - you need to override some properties you would normally not think need to be overridden list `fips.*`  and if you had a stock file those properties would be missing and I have no idea what would happen...
