### ISSUE TITLE
Bouncy Castle and TLS_RSA_WITH_AES_256_CCM

### ISSUE THREAD

**Issue by amaljesudas** [bcgit/bc-java#1160]
I am trying to run a test tool server with  TLS_RSA_WITH_AES_128_CCM.
Since BouncyCastle was providing support for CCM ciphers, I have configured the same in the java.security file.
Other CCM ciphers work with BouncyCastle but am not able to make the below 4 cipher suites work:
- TLS_RSA_WITH_AES_128_CCM
- TLS_RSA_WITH_AES_128_CCM_8
- TLS_RSA_WITH_AES_256_CCM
- TLS_RSA_WITH_AES_256_CCM_8
I only have the test tool binary and I did check and confirm that the Client Hello has Cipher Suite: TLS_RSA_WITH_AES_128_CCM (0xc09c) using WireShark.

The error stack at my server side is as below:

May 02, 2022 7:19:53 PM org.bouncycastle.jsse.provider.ProvTlsServer notifyAlertRaised
INFO: Server raised fatal(2) handshake_failure(40) alert: Failed to read record
org.bouncycastle.tls.TlsFatalAlert: handshake_failure(40); No selectable cipher suite
        at org.bouncycastle.tls.AbstractTlsServer.getSelectedCipherSuite(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvTlsServer.getSelectedCipherSuite(Unknown Source)
        at org.bouncycastle.tls.TlsServerProtocol.generateServerHello(Unknown Source)
        at org.bouncycastle.tls.TlsServerProtocol.handleHandshakeMessage(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source)
        at org.bouncycastle.tls.RecordStream.readRecord(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.blockForHandshake(Unknown Source)
        at org.bouncycastle.tls.TlsServerProtocol.accept(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.handshakeIfNecessary(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvSSLSocketDirect$AppDataInput.read(Unknown Source)
        at org.dcm4che3.util.StreamUtils.readAvailable(StreamUtils.java:57)
        at org.dcm4che3.util.StreamUtils.readFully(StreamUtils.java:68)
        at org.dcm4che3.net.PDUDecoder.readFully(PDUDecoder.java:225)
        at org.dcm4che3.net.PDUDecoder.nextPDU(PDUDecoder.java:159)
        at org.dcm4che3.net.Association$2.run(Association.java:571)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

19:19:53.581 INFO  - /[127.0.0.1:10075](http://127.0.0.1:10075/)<-/127.0.0.1:64263(1): i/o exception: org.bouncycastle.tls.TlsFatalAlert: handshake_failure(40); No selectable cipher suite in State: Sta2 - Transport connection open
19:19:53.596 INFO  - /[127.0.0.1:10075](http://127.0.0.1:10075/)<-/[127.0.0.1](http://127.0.0.1/):64263(1): close Socket[addr=/127.0.0.1,port=64263,localport=10075]
19:19:53.596 DEBUG - /[127.0.0.1:10075](http://127.0.0.1:10075/)<-/127.0.0.1:64263(1): enter state: Sta1 - Idle

Can someone provide any pointers to what could be wrong?
Do I need to make some changes to some configuration file?

Thanks in advance.

**Comment by peterdettman** [comment]
First the simple things to check. 

- Those cipher suites only work with TLS 1.2 (exactly). Check that you only have TLS 1.2 support enabled on the server.
- Those cipher suites are all in our supported cipher suites list, but none are enabled by default, so make sure you enable them.

Also, please confirm that you are using the BCJSSE "PKIX" KeyManagerFactory (no interop with other providers' implementations), either explicitly, or by setting in java.security:
    ssl.KeyManagerFactory.algorithm=PKIX

(with BCJSSE provider at high priority).

If there is any kind of custom KeyManager involved, it might be an issue; please give details.

Since other CCM cipher suites work, but not those, then I would guess the issue is the key exchange part. TLS_RSA_* suites use RSA encryption instead of signing (as e.g. for TLS_DHE_RSA_WITH_AES_256_CCM). Do you have suitable RSA credentials in your server-side KeyStore? BCJSSE is a little more strict than SunJSSE: for RSA encryption, the certificate's KeyUsage should be absent, or contain at least 'keyEncipherment'.

Perhaps just check whether TLS_RSA_WITH_AES_128_CBC_SHA256 works, as a test that there are RSA encryption credentials available.

You can get more details about the server's search for a valid cipher suite (particularly the credentials) if you set the logging level down to FINEST. We use Java Logging API; configure in your JDK's logging.properties file:

```
#java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.level = FINEST
org.bouncycastle.jsse.level = FINEST
```

**Comment by amaljesudas** [comment]
Thanks @petedettman.
TLS_RSA_WITH_AES_128_CBC_SHA256  didn't work for me either.
So as mentioned in your reply, I did the below two steps:

1. Copied bcpkix-$version.jar to %JAVA_HOME%\lib\ext path
2. Updated java.security to ssl.KeyManagerFactory.algorithm=PKIX

After the above two changes, TLS_RSA_WITH_AES_256_CCM and other ciphers work as expected.

Thanks a ton.

**Comment by Auties00** [comment]
> BCJSSE

I was having this exact issue, thanks for writing this :)
