### ISSUE TITLE
An error occurred when connecting to SMTP "java.security.cert.CertificateException: Unable to find certificate chain."

### ISSUE THREAD

**Issue by AVG3000** [bcgit/bc-java#1184]
The application is currently running in java version build 1.7.0_79-b15 and the third party application upgraded its TLS to 1.3 version. We can't easily upgrade java version that will support TLS 1.3 and so we decided to use Bouncy Castle in order for us comply with the third party. We were able to connect to the third party system after using Bouncy Castle but, the existing mail service that is working on previous default java security is no longer working due to the error below.
```
Caused by: org.bouncycastle.tls.TlsFatalAlert: certificate_unknown(46)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.checkServerTrusted(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvTlsClient$1.notifyServerCertificate(Unknown Source)
	at org.bouncycastle.tls.TlsUtils.processServerCertificate(Unknown Source)
	at org.bouncycastle.tls.TlsClientProtocol.handleServerCertificate(Unknown Source)
	at org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source)
	at org.bouncycastle.tls.RecordStream.readRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.blockForHandshake(Unknown Source)
	at org.bouncycastle.tls.TlsClientProtocol.connect(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1037)
	at javax.activation.URLDataSource.getInputStream(URLDataSource.java:107)
	at javax.activation.DataHandler.writeTo(DataHandler.java:304)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1350)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:845)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:361)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:85)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:883)
	at javax.activation.DataHandler.writeTo(DataHandler.java:316)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1350)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:845)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:361)
	at com.sun.mail.handlers.multipart_mixed.writeTo(multipart_mixed.java:85)
	at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:883)
	at javax.activation.DataHandler.writeTo(DataHandler.java:316)
	at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1350)
	at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1683)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:585)
	... 75 more
Caused by: java.security.cert.CertificateException: Unable to find certificate chain.
	at org.bouncycastle.jsse.provider.ProvX509TrustManager.validateChain(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvX509TrustManager.checkTrusted(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvX509TrustManager.checkServerTrusted(Unknown Source)
	... 110 more
```

Are there any way to disable Bouncy Castle or processing certificate when sending message through SMTP? Or any way to fix it? Do I need to generate a certificate even if the mail server does not have a certificate? Any suggestions or help are highly appreciated. thanks!

**Comment by AVG3000** [comment]
Able to resolve this issue.
