### ISSUE TITLE
NTRULPRime private and public key rebuilding from encoded form fails (PQC)

### ISSUE THREAD

**Issue by java-crypto** [bcgit/bc-java#1208]
Hi team,
I'm working with the Post Quantum Crypto algorithm "NTRULPrime" to securely generate a shared secret ("KEM").

The complete process is working (generation of the keypair, generate the encapsulatedKey with the public key and
extract the secret key with the private key).

However, when trying to rebuild the keys from its encoded using the KeyFactory form I'm getting errors:

```
java.security.spec.InvalidKeySpecException: java.io.IOException: long form definite-length more than 31 bits
	at org.bouncycastle.pqc.jcajce.provider.ntruprime.NTRULPRimeKeyFactorySpi.engineGeneratePrivate(NTRULPRimeKeyFactorySpi.java:37)
	at java.base/java.security.KeyFactory.generatePrivate(KeyFactory.java:384)
	at de.androidcrypto.postquantumcryptographybc.PqcNtruPrimeLKemSo.main(PqcNtruPrimeLKemSo.java:54)
java.security.spec.InvalidKeySpecException: java.lang.IllegalArgumentException: failed to construct sequence from byte[]: Extra data detected in stream
	at org.bouncycastle.pqc.jcajce.provider.ntruprime.NTRULPRimeKeyFactorySpi.engineGeneratePublic(NTRULPRimeKeyFactorySpi.java:60)
	at java.base/java.security.KeyFactory.generatePublic(KeyFactory.java:346)
	at de.androidcrypto.postquantumcryptographybc.PqcNtruPrimeLKemSo.main(PqcNtruPrimeLKemSo.java:65)
```

This happens as well when using the SNTRUPrime algorithm.

Here is the complete code, I'm using BouncyCastle Version 1.72 Beta 13:

```
import org.bouncycastle.crypto.AsymmetricCipherKeyPair;
import org.bouncycastle.crypto.params.AsymmetricKeyParameter;
import org.bouncycastle.pqc.crypto.ntruprime.NTRULPRimeKeyGenerationParameters;
import org.bouncycastle.pqc.crypto.ntruprime.NTRULPRimeKeyPairGenerator;
import org.bouncycastle.pqc.crypto.ntruprime.NTRULPRimeParameters;
import org.bouncycastle.pqc.crypto.ntruprime.NTRULPRimePrivateKeyParameters;
import org.bouncycastle.pqc.crypto.ntruprime.NTRULPRimePublicKeyParameters;
import org.bouncycastle.pqc.jcajce.provider.BouncyCastlePQCProvider;

import java.security.KeyFactory;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.SecureRandom;
import java.security.Security;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;

public class PqcNtruPrimeLKemSo {


    public static void main(String[] args) {
        //Security.addProvider(new BouncyCastleProvider());
        // we do need the newest Bouncy Castle beta file that includes the PQC provider
        // get Bouncy Castle here: https://downloads.bouncycastle.org/betas/
        // tested with BC version 1.72 Beta 13
        if (Security.getProvider("BCPQC") == null) {
            Security.addProvider(new BouncyCastlePQCProvider());
        }
        System.out.println("PQC NTRU LPRime kem");

        NTRULPRimeParameters ntrulpRimeParameter = NTRULPRimeParameters.ntrulpr653;

        System.out.println("generate the NTRULPRime keypair");
        AsymmetricCipherKeyPair keyPair;
        NTRULPRimeKeyPairGenerator keyPairGenerator = new NTRULPRimeKeyPairGenerator();
        keyPairGenerator.init(new NTRULPRimeKeyGenerationParameters(new SecureRandom(), ntrulpRimeParameter));
        keyPair = keyPairGenerator.generateKeyPair();

        // storing the key as byte array
        System.out.println("storing the keys as byte array");
        byte[] privateKeyByte = ((NTRULPRimePrivateKeyParameters) keyPair.getPrivate()).getEncoded();
        byte[] publicKeyByte = ((NTRULPRimePublicKeyParameters) keyPair.getPublic()).getEncoded();

        System.out.println("get the private key from encoded");
        AsymmetricKeyParameter privateKeyLoad = null;
        try {
            KeyFactory keyFactory = KeyFactory.getInstance("NTRULPRIME", "BCPQC");
            PKCS8EncodedKeySpec pkcs8EncodedKeySpec = new PKCS8EncodedKeySpec(privateKeyByte);
            PrivateKey privateKey = keyFactory.generatePrivate(pkcs8EncodedKeySpec);
            privateKeyLoad = (AsymmetricKeyParameter) privateKey;
        } catch (NoSuchAlgorithmException | NoSuchProviderException | InvalidKeySpecException e) {
            e.printStackTrace();
        }

        System.out.println("get the public key from encoded");
        AsymmetricKeyParameter publicKeyLoad = null;
        try {
            KeyFactory keyFactory = KeyFactory.getInstance("NTRULPRIME", "BCPQC");
            X509EncodedKeySpec x509EncodedKeySpec = new X509EncodedKeySpec(publicKeyByte);
            PublicKey publicKey = keyFactory.generatePublic(x509EncodedKeySpec);
            publicKeyLoad = (AsymmetricKeyParameter) publicKey;
        } catch (NoSuchAlgorithmException | NoSuchProviderException | InvalidKeySpecException e) {
            e.printStackTrace();
        }

        if (privateKeyLoad != null) {
            System.out.println("privateKeyLoad: " + privateKeyLoad.toString());
        }
        if (publicKeyLoad != null) {
            System.out.println("publicKeyLoad: " + publicKeyLoad.toString());
        }
    }
}

```

Btw: The key rebuilding using 

`NTRULPRimePrivateKeyParameters(ntruPrimeParameter, f, ginv, pk, rho, hash)
`

is working but this is not using the encoded form but a bunch of data.

Michael

**Comment by dghgit** [comment]
Use PrivateKeyFactory and PublicKeyFactory in the org/bouncycastle.pqc.util package - the JCA expects keys to be wrapped in either a SubjectPublicKeyInfo or PKCS8 PrivateKeyInfo.

**Comment by java-crypto** [comment]
Thanks for your answer, and I'm sorry for asking again, but are we talking about this path?: 

[bc-java/core/src/main/java/org/bouncycastle/pqc/crypto/util/PrivateKeyFactory.java](url)

There seems to be no algOID for NTRULPRime available:

```
import org.bouncycastle.pqc.asn1.SPHINCS256KeyParams;
import org.bouncycastle.pqc.asn1.XMSSKeyParams;
import org.bouncycastle.pqc.asn1.XMSSMTKeyParams;
import org.bouncycastle.pqc.asn1.XMSSMTPrivateKey;
import org.bouncycastle.pqc.asn1.XMSSPrivateKey;
import org.bouncycastle.pqc.crypto.lms.HSSPrivateKeyParameters;
import org.bouncycastle.pqc.crypto.lms.LMSPrivateKeyParameters;
import org.bouncycastle.pqc.crypto.newhope.NHPrivateKeyParameters;
import org.bouncycastle.pqc.crypto.qtesla.QTESLAPrivateKeyParameters;
import org.bouncycastle.pqc.crypto.sphincs.SPHINCSPrivateKeyParameters;
import org.bouncycastle.pqc.crypto.xmss.BDS;
import org.bouncycastle.pqc.crypto.xmss.BDSStateMap;
import org.bouncycastle.pqc.crypto.xmss.XMSSMTParameters;
import org.bouncycastle.pqc.crypto.xmss.XMSSMTPrivateKeyParameters;
import org.bouncycastle.pqc.crypto.xmss.XMSSParameters;
import org.bouncycastle.pqc.crypto.xmss.XMSSPrivateKeyParameters;
```

Can you please provide a short example how to get the AsymmetricKeyParameter for the encoded private and public key ?

Thanks,
Michael

**Comment by dghgit** [comment]
Yes,

It depends on how you want to play it though, but if you are trying to read or write the ASN.1 structures for keys you want to be using the ones in the util package. You can find examples of both parsing and creation in the JCA key classes, for example in BCNTRULPRimePrivateKey.getEncoded() or in the constructor.

If you have any further questions, please let us know - this is hot topic right now, so I'd guess it will of benefit to many.

**Comment by MichaelsPlayground** [comment]
Hi Team,
I get the encoded forms using NTRULPRimeParameters.ntrulpr653 with these two lines:

```
byte[] privateKeyByte = ((NTRULPRimePrivateKeyParameters) keyPair.getPrivate()).getEncoded();
byte[] publicKeyByte = ((NTRULPRimePublicKeyParameters) keyPair.getPublic()).getEncoded();
```

The lengths are as long as expected and seem to be the pure private and public keys without any structure:

```
privateKeyByte.length: 1125
publicKeyByte.length:  897
```

So the question is: how to get the (AsymmetricKeyParameter) privateKeyRebuild and publicKeyRebuild from the byte arrays ?

The "PrivateKeyFactory.createKey" needs 
```
byte[] privateKeyInfoData -or-
InputStream inStr -or-
PrivateKeyInfo keyInfo
```

The "PublicKeyFactory.createKey" needs 
```
byte[] keyInfoData -or-
InputStream inStr -or-
SubjectPublicKeyInfo keyInfo
```

What is the easiest way to retrieve the necessary data from the encoded forms (and kindly provide code for it, thanks) ?

Thanks and have a nice weekend, Michael

**Comment by dghgit** [comment]
See SubjectPublicKeyInfoFactory and PrivateKeyInfoFactory.
