### ISSUE TITLE
master fails testDilithiumRandomSig

### ISSUE THREAD

**Issue by mouse07410** [bcgit/bc-java#1210]
Java-17, current BC master. One test reports Failure (not an Error):

```
testDilithiumRandomSig  Failure (Type: N/A)

junit.framework.AssertionFailedError 
at org.bouncycastle.pqc.jcajce.provider.test.DilithiumTest.testDilithiumRandomSig(Unknown Source) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:23) 
at junit.extensions.TestSetup$1.protect(TestSetup.java:23) 
at junit.extensions.TestSetup.run(TestSetup.java:27) 
```

**Comment by dghgit** [comment]
Thanks. I've been able to reproduce this in 1.8 as well. I'm pretty sure this is a bug. It looks like there's an occasional bit flip in the signature generation - I suspect it'll be an uncaught sign extension, it's definitely not some weirdness due to Java 17.

**Comment by dghgit** [comment]
Yes, it was a bug. Thanks. A couple of swapped ifs... in the signature unpacking validation code. I've published a new beta on https://www.bouncycastle.org/betas  and github has just synced up. You should find the test passes now.
