### ISSUE TITLE
ArrayIndexOutOfBoundsException in GeneralDigest.update

### ISSUE THREAD

**Issue by jochenhager** [bcgit/bc-java#1217]
I am running code to sign URLs with my own SecKey parameter using BC libraries. The code runs in a Tomcat server. After a while processing stops and the Tomcat exception log shows this error and ends the request with a return code 500 internal error:

BC Library /usr/local/crypto-171/bcprov-debug-jdk18on-171.jar, Java 11, Tomcat 9.0.45 on a Debian Unix 10 VM.

30-Aug-2022 15:25:42.025 SEVERE [http-nio-8080-exec-7] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [ServerInfoServlet] in context with path [/solXchgServer] threw exception
	java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
		at org.bouncycastle.crypto.digests.GeneralDigest.update(GeneralDigest.java:107)
		at org.bouncycastle.jcajce.provider.asymmetric.dsa.DSASigner.engineUpdate(DSASigner.java:90)
		at java.base/java.security.Signature$Delegate.engineUpdate(Signature.java:1394)
		at java.base/java.security.Signature.update(Signature.java:903)
		at java.base/java.security.Signature.update(Signature.java:872)
		at org.bouncycastle.jcajce.io.SignatureUpdatingOutputStream.write(SignatureUpdatingOutputStream.java:36)
		at org.bouncycastle.cms.SignerInfoGenerator.generate(Unknown Source)
		at org.bouncycastle.cms.CMSSignedDataGenerator.generate(Unknown Source)
		at acSharedClasses.SecKey.signMessage(Unknown Source)
               [...]

When the next request hits the server, this happens: (Index value 5) 

30-Aug-2022 15:25:42.026 SEVERE [http-nio-8080-exec-9] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [ServerInfoServlet] in context with path [/solXchgServer] threw exception
	java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 4
		at org.bouncycastle.crypto.digests.GeneralDigest.update(GeneralDigest.java:57)
		at org.bouncycastle.crypto.digests.GeneralDigest.finish(GeneralDigest.java:120)
		at org.bouncycastle.crypto.digests.SHA1Digest.doFinal(SHA1Digest.java:120)
		at org.bouncycastle.jcajce.provider.asymmetric.dsa.DSASigner.engineSign(DSASigner.java:98)
		at java.base/java.security.Signature$Delegate.engineSign(Signature.java:1404)
		at java.base/java.security.Signature.sign(Signature.java:713)
		at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder$1.getSignature(Unknown Source)
		at org.bouncycastle.cms.SignerInfoGenerator.generate(Unknown Source)
		at org.bouncycastle.cms.CMSSignedDataGenerator.generate(Unknown Source)
		at acSharedClasses.SecKey.signMessage(Unknown Source)
               [...]

and then this:  (Index value 6) (and then the index increases, but always errors in line 83 of the code)

30-Aug-2022 15:25:42.042 SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [ServerInfoServlet] in context with path [/solXchgServer] threw exception
	java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 4
		at org.bouncycastle.crypto.digests.GeneralDigest.update(GeneralDigest.java:83)
		at org.bouncycastle.jcajce.provider.asymmetric.dsa.DSASigner.engineUpdate(DSASigner.java:90)
		at java.base/java.security.Signature$Delegate.engineUpdate(Signature.java:1394)
		at java.base/java.security.Signature.update(Signature.java:903)
		at java.base/java.security.Signature.update(Signature.java:872)
		at org.bouncycastle.jcajce.io.SignatureUpdatingOutputStream.write(SignatureUpdatingOutputStream.java:36)
		at org.bouncycastle.cms.SignerInfoGenerator.generate(Unknown Source)
		at org.bouncycastle.cms.CMSSignedDataGenerator.generate(Unknown Source)
		at acSharedClasses.SecKey.signMessage(Unknown Source)

[localhost.2022-08-30.log](https://github.com/bcgit/bc-java/files/9457420/localhost.2022-08-30.log)

Thank you for your review!

**Comment by dghgit** [comment]
It'll be because the digest is being shared across threads. Digest classes are stateful, they are not thread safe - you need to use a new digest for each thread, or stick one in a thread local if a particular thread needs to use it multiple times, or synchronize on it if all the threads need to input to it.

**Comment by jochenhager** [comment]
Thank you for your response! Surrounding the CMSSignedDataGenerator.generate library call with a JAVA synchronized (this) { [...] } in my SecKey.signMessage method resolved the issues without any changes to the Tomcat setup.
