### ISSUE TITLE
java.io.EOFException: Unexpected end of ZIP input stream

### ISSUE THREAD

**Issue by abialias** [bcgit/bc-java#1262]
Hi, 
I was trying  decryption using the following sample files.

github.com/bcgit/bc-java/blob/master/pg/src/main/java/org/bouncycastle/openpgp/examples/KeyBasedFileProcessor.java
github.com/bcgit/bc-java/blob/master/pg/src/main/java/org/bouncycastle/openpgp/examples/KeyBasedLargeFileProcessor.java

Both files, I am getting  "java.io.EOFException: Unexpected end of ZIP input stream"

Stacktrace: 
java.io.EOFException: Unexpected end of ZIP input stream
	at org.bouncycastle.openpgp.PGPCompressedData$1.fill(Unknown Source)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at org.bouncycastle.bcpg.BCPGInputStream.read(Unknown Source)
	at org.bouncycastle.bcpg.BCPGInputStream$PartialInputStream.read(Unknown Source)
	at org.bouncycastle.bcpg.BCPGInputStream.read(Unknown Source)
	at org.bouncycastle.util.io.Streams.pipeAll(Unknown Source)
	at com.pgp.test.KeyBasedLargeFileProcessor.decryptFile(KeyBasedLargeFileProcessor.java:150)
	at com.pgp.test.KeyBasedLargeFileProcessor.decryptFile(KeyBasedLargeFileProcessor.java:70)
	at com.pgp.test.KeyBasedLargeFileProcessor.main(KeyBasedLargeFileProcessor.java:261)

Kindy please suggest what is causing the issue?

**Comment by dghgit** [comment]
I think it might be a bug (sigh) try https://www.bouncycastle.org/betas 173b04 or later. You just need to get the PGP jar.

**Comment by dghgit** [comment]
Okay 172,1 for the BC PG API is now on https://www.bouncycastle.org/latest_releases.html

**Comment by abialias** [comment]
Thank you so much or all of your suggestions. This was due my mistake from my side.

While encrypting, I didn't close the compression stream which cause the issue. so the same file decrypted, caused the issue.
PGPCompressedDataGenerator compressionData = new PGPCompressedDataGenerator(CompressionAlgorithmTags.ZIP);
**compressionData.close();**

So this is not an issue now.
 Closing this ticket.
