### ISSUE TITLE
org.bouncycastle.pg module-info.java is out of date

### ISSUE THREAD

**Issue by denofevil** [bcgit/bc-java#1263]
When loading PGPPublicKeyRingCollection I'm getting following exception:
```
java.lang.IllegalAccessError: class org.bouncycastle.openpgp.PGPKeyRing (in module org.bouncycastle.pg) cannot access class java.util.logging.Logger (in module java.logging) because module org.bouncycastle.pg does not read module java.logging
	at org.bouncycastle.pg/org.bouncycastle.openpgp.PGPKeyRing.<clinit>(Unknown Source)
	at org.bouncycastle.pg/org.bouncycastle.openpgp.PGPObjectFactory.nextObject(Unknown Source)
	at org.bouncycastle.pg/org.bouncycastle.openpgp.PGPPublicKeyRingCollection.<init>(Unknown Source)
```

Looks like module-info.java is missing `require java.logging`

**Comment by dghgit** [comment]
Further to this, there is now a new version of the PGP API 172.1 on the https://www.bouncycastle.org/latest_releases.html it should avoid the cryptlib issue.
