### ISSUE TITLE
PGPEncryptData: NullPointerException

### ISSUE THREAD

**Issue by mouse07410** [bcgit/bc-java#1270]
macOS Monterey 12.6.1, Java-17 (Amazon Corretto JDK-17.0.5), BC - current master.

```
PGPEncryptedData: Exception: java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[], int, int)" because "inStr" is null

junit.framework.AssertionFailedError: PGPEncryptedData: Exception: java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[], int, int)" because "inStr" is null
at org.bouncycastle.openpgp.test.AllTests.testPGP(AllTests.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:23)
at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
at junit.extensions.TestSetup.run(TestSetup.java:27)
```

**Comment by dghgit** [comment]
Sorry, out of date ant file. It hadn't synced up. Should be fixed now.

**Comment by mouse07410** [comment]
I concur - it's fixed now, thanks.
