### ISSUE TITLE
bc-fips and bcprov conflicting when used in the same project

### ISSUE THREAD

**Issue by thought-tobi** [bcgit/bc-java#1287]
# Problem Description

I'm working on a project that explicitly imports _org.bouncycastle:bc-fips:1.0.2.3_ and _org.mock-server:mockserver-spring-test-listener:5.14.0_, which transitively imports _org.bouncycastle:bcprov-jdk18on:1.69_.

Using _bcprov_ and _bc-fips_ alongside each other causes an issue at _BouncyCastleProvider.loadAlgorithms()_. Specifically, upon loading the Digests, it attempts to load _blake3_256_. _org.bouncycastle.jcajce.provider.digest.Blake3_ makes the following call:

`provider.addAlgorithm("Alg.Alias.MessageDigest." + MiscObjectIdentifiers.blake3_256, "BLAKE3-256");`

There now is some ambiguity with regards to which MiscObjectIdentifiers is referenced, as org.bouncycastle.asn1.misc.MiscObjectIdentifiers exists in both the bc-fips and the bcprov jars. When the class loader chooses to use the MiscObjectIdentifiers class from the bc-fips jar, it fails, because the blake3_256 field doesn't exist in it. It does exist in the MiscObjectIdentifiers from the bcprov jar though. This results in the following stacktrace:

```
java.lang.NoSuchFieldError: blake3_256
	at org.bouncycastle.jcajce.provider.digest.Blake3$Mappings.configure(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.loadAlgorithms(BouncyCastleProvider.java:247)
        at org.bouncycastle.jce.provider.BouncyCastleProvider.setup(BouncyCastleProvider.java:163)
        at org.bouncycastle.jce.provider.BouncyCastleProvider.access$000(BouncyCastleProvider.java:60)
        at org.bouncycastle.jce.provider.BouncyCastleProvider$1.run(BouncyCastleProvider.java:155)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at org.bouncycastle.jce.provider.BouncyCastleProvider.<init>(BouncyCastleProvider.java:151)
        at org.mockserver.socket.tls.bouncycastle.BCKeyAndCertificateFactory.<clinit>(BCKeyAndCertificateFactory.java:55)
	at org.mockserver.socket.tls.KeyAndCertificateFactoryFactory.createKeyAndCertificateFactory(KeyAndCertificateFactoryFactory.java:28)
	at org.mockserver.socket.tls.KeyAndCertificateFactoryFactory.createKeyAndCertificateFactory(KeyAndCertificateFactoryFactory.java:21)
...
```

# Steps to Reproduce

I have created a basic example in Gradle to reproduce the error. When you run the test, you are going to get more or less exactly the same stacktrace I've shown above. Find the example project here: https://github.com/thought-tobi/bouncycastle-issue-demo

# Remediation suggestion

The easiest fix here seems to be to update the MiscObjectIdentifiers.java in the bc-fips jar to contain roughly the same contents as the MiscObjectIdentifiers.java in the bcprov jar. I would have created a PR myself, but was unable to find the source code from which bc-fips is built.

Thanks a lot for your hard work, it is highly appreciated!

**Comment by dghgit** [comment]
You have to use one or the other (it's one of the rules) The FIPS source code is available at https://www.bouncycastle.org.fips-java and on Maven central. 

Note it takes about 14 months at the moment to certify a FIPS release.
