### ISSUE TITLE
false "No CRLs found for issuer "cn=QuoVadis Root CA 2 G3,o=QuoVadis Limited,c=BM""

### ISSUE THREAD

**Issue by ralfhauser** [bcgit/bc-java#1309]
For the attached certificate, there is a CRL in http://crl.quovadisglobal.com/qvrca2g3.crl

why does the validator fail with ?

Caused by: org.bouncycastle.jce.provider.RecoverableCertPathValidatorException: No CRLs found for issuer "cn=QuoVadis Root CA 2 G3,o=QuoVadis Limited,c=BM"
	at org.bouncycastle.jce.provider.CertPathValidatorUtilities.checkCRLsNotEmpty(CertPathValidatorUtilities.java:1413)
	at org.bouncycastle.jce.provider.CertPathValidatorUtilities.getCompleteCRLs(CertPathValidatorUtilities.java:1204)
	at org.bouncycastle.jce.provider.RFC3280CertPathUtilities.checkCRL(RFC3280CertPathUtilities.java:1692)
	at org.bouncycastle.jce.provider.RFC3280CertPathUtilities.checkCRLs(RFC3280CertPathUtilities.java:1907)
	at org.bouncycastle.jce.provider.ProvCrlRevocationChecker.check(ProvCrlRevocationChecker.java:53)
	at org.bouncycastle.jce.provider.ProvRevocationChecker.check(ProvRevocationChecker.java:165)
	at java.base/java.security.cert.PKIXCertPathChecker.check(PKIXCertPathChecker.java:176)
	at org.bouncycastle.jce.provider.RFC3280CertPathUtilities.processCertA(RFC3280CertPathUtilities.java:1445)
	at org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi_8.engineValidate(PKIXCertPathValidatorSpi_8.java:353)
	at org.bouncycastle.jce.provider.PKIXCertPathBuilderSpi_8.build(PKIXCertPathBuilderSpi_8.java:210)
	at org.bouncycastle.jce.provider.PKIXCertPathBuilderSpi_8.build(PKIXCertPathBuilderSpi_8.java:266)
	at org.bouncycastle.jce.provider.PKIXCertPathBuilderSpi_8.engineBuild(PKIXCertPathBuilderSpi_8.java:119)
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)

see also https://github.com/bcgit/bc-java/issues/800

**Comment by peterdettman** [comment]
Hi Ralf,
Not sure exactly the question here. The failure is because no CRL was found and the code seems clear that it needs to find one (is your question more why that restriction exists?).

Are you sure all the relevant CRLs are available in the PKIX parameters? RFC3280CertPathUtilities.checkCRL has this comment:

```
        /*
         * We always get timely valid CRLs, so there is no step (a) (1).
         * "locally cached" CRLs are assumed to be in getStore(), additional
         * CRLs must be enabled in the ExtendedPKIXParameters and are in
         * getAdditionalStore()
         */
```

To look in more detail I think we would need the exact code you're using (including certs/keystore/TAs).

**Comment by ralfhauser** [comment]
The certificate is 

-----BEGIN CERTIFICATE-----
MIIGnTCCBIWgAwIBAgIUZTJHgU9fpmu4VNrwU/MpJl1yZTgwDQYJKoZIhvcNAQEL
BQAwSDELMAkGA1UEBhMCQk0xGTAXBgNVBAoTEFF1b1ZhZGlzIExpbWl0ZWQxHjAc
BgNVBAMTFVF1b1ZhZGlzIFJvb3QgQ0EgMiBHMzAeFw0yMTExMDMxNzQxMDFaFw0y
NjExMDIxNzQxMDBaME0xCzAJBgNVBAYTAkJNMRkwFwYDVQQKExBRdW9WYWRpcyBM
aW1pdGVkMSMwIQYDVQQDExpRdW9WYWRpcyBHbG9iYWwgU1NMIElDQSBHMzCCAiIw
DQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANf8Od17be6c6lTGJDhEXpmkTs4y
Q39Rr5VJyBeWCg06nSS71s6xF3sZvKcV0MbXlXCYM2ZX7cNTbJ81gs7uDsKFp+vK
EymiKyEiI2SImOtECNnSg+RVR4np/xz/UlC0yFUisH75cZsJ8T1pkGMfiEouR0EM
7O0uFgoboRfUP582TTWy0F7ynSA6YfGKnKj0OFwZJmGHVkLs1VevWjhj3R1fsPan
H05P5moePFnpQdj1FofoSxUHZ0c7VB+sUimboHm/uHNY1LOsk77qiSuVC5/yrdg3
2EEfP/mxJYT4r/5UiD7VahySzeZHzZ2OibQm2AfgfMN3l57lCM3/WPQBhMAPS1jz
kE+7MjajM2f0aZctimW4Hasrj8AQnfAdHqZehbhtXaAlffNEzCdpNK584oCTVR7N
UR9iZFx83ruTqpo+GcLP/iSYqhM4g7fy45sNhU+IS+ca03zbxTl3TTlkofXunI5B
xxE30eGSQpDZ5+iUJcEOAuVKrlYocFbB3KF45hwcbzPWQ1DcO2jFAapOtQzeS+MZ
yZzT2YseJ8hQHKu8YrXZWwKaNfyl8kFkHUBDICowNEoZvBwRCQp8sgqL6YRZy0uD
JGxmnC2e0BVKSjcIvmq/CRWH7yiTk9eWm73xrsg9iIyD/kwJEnLyIk8tR5V8p/hc
1H2AjDrZH12PsZ45AgMBAAGjggF4MIIBdDASBgNVHRMBAf8ECDAGAQH/AgEAMB8G
A1UdIwQYMBaAFO3nb3Zav2DsSVvGpXe7chZxm8Q9MHQGCCsGAQUFBwEBBGgwZjA4
BggrBgEFBQcwAoYsaHR0cDovL3RydXN0LnF1b3ZhZGlzZ2xvYmFsLmNvbS9xdnJj
YTJnMy5jcnQwKgYIKwYBBQUHMAGGHmh0dHA6Ly9vY3NwLnF1b3ZhZGlzZ2xvYmFs
LmNvbTA8BgNVHSAENTAzMA4GDCsGAQQBvlgAAmQBAjAHBgVngQwBATAIBgZngQwB
AgIwDgYMKwYBBAG+WAACZAEBMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
ATA7BgNVHR8ENDAyMDCgLqAshipodHRwOi8vY3JsLnF1b3ZhZGlzZ2xvYmFsLmNv
bS9xdnJjYTJnMy5jcmwwHQYDVR0OBBYEFLMSibWpSzW8FQDwgOnYeIfxE3x2MA4G
A1UdDwEB/wQEAwIBBjANBgkqhkiG9w0BAQsFAAOCAgEAdVT3VnI1hVwhdF3Xu2h5
cmpy30QZP3Lv10cqMME8bay6saBeZbNxj/K/OcgjcmKA8pdOA5pzsE6EaGoJWkBe
QcN6FtDMpXmHwzCW6FbJWKPaF0pLiIpznTqWRikBZ7VLjh2pnE3qmQvihzBLKq0l
sBaU3uCm8V5p6DmsYPk3FURLQwLTtKtYrNKVwJhY0I1ziX12+QzhIzwJ7QzY/CQN
TDaRpyxaOn9b6oiECf2DHHsXfpXcn1/uKfJSJJxZQmwG1MaiwMu/m5uuZvvVO/Xb
hzcBHszELjra+vfZ+v6UH21UUCNzIusJvVt/6+5HTZE7yoxHBC6plxB3cBWTVMo2
7hRxnr700GTC44izrj6XIzf8YYH1XI9xqhKwvm1XCW3DQjVzyiFTP8ta7lM+SYpR
fo2nuhFjIlo9vq5vZkcQg0gNX8ktEnp9I4/jlmaRelUPOwo04kAU56LfXKXXVRQp
2Ch7PzvzY+93x9r5cdB2V6Qz6LxkYP9WGtEHU4mYa4mB8gUa/aeVj6RbxjbQyXb2
76M0x7KfYW8FCQ2EvAvcb0WI+5JpBdMUKVpEXMUeMH92Kn8MYh1/fe+F5S9YszwE
rkiFeA5FaTi2r0NS2Bt+NuThfEYDgafpFewQPxO1I/7yjR3/jCWd8T+4mklWtaFU
DawUneoshWUTsQW27vi9LnM=
-----END CERTIFICATE-----

**Comment by ralfhauser** [comment]
Hi Peter, 
Apologies,  it may really be a programming error from my side.

However, the javaDoc of the calling method in CertPathValidatorUtilities.getCompleteCRLs() says
 /**
     * Fetches complete CRLs according to RFC 3280.
...

Seems that in reality it does not "fetch" them from the DistributionPoint (dp) but only "retrieves" them from the various stores provided (assuming that they have been fetched before already).

1) so I suggest to put this javaDoc in line with the one you cite above

Also, it would be helpful to

2) say in the error message from which DistributionPoint(s) the CRL could be obtained from in theory

Many thanks

**Comment by gsaviane** [comment]
hi @ralfhauser, 
  I am experiencing the same issue. I am using bc-fips and bcpkix-fips and enabled CRL checks via system properties:
- com.sun.security.enableCRLDP=true 
- com.sun.net.ssl.checkRevocation=true 
- org.bouncycastle.x509.enableCRLDP=true

With the standard JDK security provider works as expected. A TLS connection established to a party bringing a revoked certificate gets blocked. I can see the TLS stack accessing the CRL through the provided CDP in the certificate.

If I switch to the BC FIPS provider I keep receiving the same error "No CRLs found for issuer...". Contrary to the standard provider, the TLS stack never accesses the CRL. From what you said I cannot understand which stores BC expects to find the CRL. I tried to debug the code, and apparently it fails to get the CRL from a map (namedCRLStoreMap) that is always empty
`Caused by: java.security.cert.CertPathValidatorException: No CRLs found for issuer "CN=XXX OU=XXX, O=XXX, L=XXX, ST=XX, C=XX"
	at org.bouncycastle.jcajce.provider.RFC3280CertPathUtilities.processCertA(RFC3280CertPathUtilities.java:1563) ~[bc-fips-debug-1.0.2.4.jar:1.0.2.4]
	at org.bouncycastle.jcajce.provider.PKIXCertPathValidatorSpi.engineValidate(PKIXCertPathValidatorSpi.java:291) ~[bc-fips-debug-1.0.2.4.jar:1.0.2.4]
	at org.bouncycastle.jcajce.provider.PKIXCertPathBuilderSpi.build(PKIXCertPathBuilderSpi.java:184) ~[bc-fips-debug-1.0.2.4.jar:1.0.2.4]
	at org.bouncycastle.jcajce.provider.PKIXCertPathBuilderSpi.build(PKIXCertPathBuilderSpi.java:241) ~[bc-fips-debug-1.0.2.4.jar:1.0.2.4]
	at org.bouncycastle.jcajce.provider.PKIXCertPathBuilderSpi.engineBuild(PKIXCertPathBuilderSpi.java:100) ~[bc-fips-debug-1.0.2.4.jar:1.0.2.4]
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[?:1.8.0_392]
	at org.bouncycastle.jsse.provider.ProvX509TrustManager.buildCertPath(ProvX509TrustManager.java:245) ~[bctls-fips-1.0.18.jar:1.0.18]
	at org.bouncycastle.jsse.provider.ProvX509TrustManager.validateChain(ProvX509TrustManager.java:300) ~[bctls-fips-1.0.18.jar:1.0.18]
	at org.bouncycastle.jsse.provider.ProvX509TrustManager.checkTrusted(ProvX509TrustManager.java:272) ~[bctls-fips-1.0.18.jar:1.0.18]
	at org.bouncycastle.jsse.provider.ProvX509TrustManager.checkServerTrusted(ProvX509TrustManager.java:181) ~[bctls-fips-1.0.18.jar:1.0.18]
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.checkServerTrusted(ProvSSLSocketDirect.java:131) ~[bctls-fips-1.0.18.jar:1.0.18]
	at org.bouncycastle.jsse.provider.ProvTlsClient$1.notifyServerCertificate(ProvTlsClient.java:382) ~[bctls-fips-1.0.18.jar:1.0.18]
	at org.bouncycastle.tls.TlsUtils.processServerCertificate(TlsUtils.java:4849) ~[bctls-fips-1.0.18.jar:1.0.18]
	at org.bouncycastle.tls.TlsClientProtocol.handleServerCertificate(TlsClientProtocol.java:797) ~[bctls-fips-1.0.18.jar:1.0.18]
	at org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(TlsClientProtocol.java:687) ~[bctls-fips-1.0.18.jar:1.0.18]
	at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(TlsProtocol.java:715) ~[bctls-fips-1.0.18.jar:1.0.18]
	at org.bouncycastle.tls.TlsProtocol.processRecord(TlsProtocol.java:591) ~[bctls-fips-1.0.18.jar:1.0.18]
	at org.bouncycastle.tls.RecordStream.readRecord(RecordStream.java:247) ~[bctls-fips-1.0.18.jar:1.0.18]
	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:879) ~[bctls-fips-1.0.18.jar:1.0.18]
	at org.bouncycastle.tls.TlsProtocol.blockForHandshake(TlsProtocol.java:427) ~[bctls-fips-1.0.18.jar:1.0.18]
	at org.bouncycastle.tls.TlsClientProtocol.connect(TlsClientProtocol.java:88) ~[bctls-fips-1.0.18.jar:1.0.18]
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(ProvSSLSocketDirect.java:426) ~[bctls-fips-1.0.18.jar:1.0.18]
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(ProvSSLSocketDirect.java:407) ~[bctls-fips-1.0.18.jar:1.0.18]`

Do I miss some configuration in BC to let it know where to pick the CRLs?
Sorry for bothering you, but you might have understood how it works and the BC documentation does not help.

Regards

**Comment by winfriedgerlach** [comment]
@ralfhauser @gsaviane has your question/issue also be resolved with bc-fips-2.0.0 as explained in #1772? Can this issue be closed?

**Comment by gsaviane** [comment]
@winfriedgerlach I figured out myself hot to initialize the TrustManagerFactory with a specific X509RevocationChecker when BC is in use. For me, the bug can be closed

**Comment by winfriedgerlach** [comment]
@peterdettman [Ralf's last comment](https://github.com/bcgit/bc-java/issues/1309#issuecomment-1371897793) contains enhancement suggestions. Do you consider these suggestions still (partly) relevant or shall we close the ticket?

**Comment by peterdettman** [comment]
@winfriedgerlach They seem like useful enhancements; please leave open.

**Comment by dghgit** [comment]
Enhancements now done. Up on https://www.bouncycastle.org/betas
