### ISSUE TITLE
bctls-fips:1.0.14 is fails socket write error with windows server and windows wsl

### ISSUE THREAD

**Issue by srinirag2016** [bcgit/bc-java#1314]
```
package com.veracode.fips;

import nl.altindag.ssl.SSLFactory;
import nl.altindag.ssl.util.Apache5SslUtils;
import org.apache.hc.client5.http.classic.methods.HttpGet;
import org.apache.hc.client5.http.impl.classic.CloseableHttpClient;
import org.apache.hc.client5.http.impl.classic.CloseableHttpResponse;
import org.apache.hc.client5.http.impl.classic.HttpClients;
import org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManagerBuilder;
import org.apache.hc.client5.http.io.HttpClientConnectionManager;
import org.apache.hc.client5.http.socket.LayeredConnectionSocketFactory;
import org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider;
import org.bouncycastle.jsse.provider.BouncyCastleJsseProvider;
import org.bouncycastle.jsse.util.CustomSSLSocketFactory;
import org.bouncycastle.tls.TlsFatalAlertReceived;

import javax.net.ssl.*;
import java.net.Socket;
import java.net.URL;
import java.util.Collections;
import java.util.List;

import static java.util.Objects.nonNull;
import static org.apache.hc.core5.http.HttpHeaders.USER_AGENT;

/**
 * Hello world!
 */
public class App {
    public static void main(String[] args) {
        final var urls = List
                .of("https://marketplace.vmware.com", "https://aws.amazon.com");

        for (final var url : urls) {
            try {
                testWithSNIHostName(url);
                testWithoutSNIHostNameApache(url);
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }


    public static void testWithSNIHostName(String urlString) throws Exception {
        URL url = new URL(urlString);
        final SSLFactory sslFactory = sslFactory(true);

        SSLContext context = sslFactory.getSslContext();
        System.out.println("Created  sslFactory");
        HttpsURLConnection connection = (HttpsURLConnection) url.openConnection();
        connection.setSSLSocketFactory(context.getSocketFactory());
        connection.setSSLSocketFactory(new CustomSSLSocketFactory(context.getSocketFactory()) {
            @Override
            protected Socket configureSocket(Socket s) {
                SSLParameters sslParams = new SSLParameters();
                sslParams.setServerNames(
                        Collections.<SNIServerName>singletonList(new SNIHostName(url.getHost())));
                ((SSLSocket) s).setSSLParameters(sslParams);
                return s;
            }
        });
        connection.setInstanceFollowRedirects(false);
        connection.setHostnameVerifier((ss, sslSession) -> true);
        System.out.println("Connection started" + urlString);
        connection.connect();
        System.out.println("Connected " + urlString);
    }
    


    public static void testWithoutSNIHostNameApache(String urlString) throws Exception {
        URL url = new URL(urlString); // Handshake fails
        //  URL url = new URL("https://aws.amazon.com"); // Succeeds here
        final SSLFactory sslFactory = sslFactory(true);

        System.out.println("Created  sslFactory");

        final CloseableHttpClient httpClient = apacheHttpClient(sslFactory);
        HttpGet httpGet = new HttpGet(url.toURI());
        httpGet.addHeader("User-Agent", USER_AGENT);
        System.out.println("Connection started " + urlString);
        CloseableHttpResponse httpResponse = httpClient.execute(httpGet);
        System.out.println("Connected " + urlString);
    }

    private static CloseableHttpClient apacheHttpClient(final SSLFactory sslFactory) {
        if (nonNull(sslFactory)) {
            final LayeredConnectionSocketFactory socketFactory = Apache5SslUtils.toSocketFactory(sslFactory);
            final HttpClientConnectionManager cm = PoolingHttpClientConnectionManagerBuilder.create()
                    .setSSLSocketFactory(socketFactory)
                    .build();
            return HttpClients.custom()
                    .setConnectionManager(cm)
                    .build();
        } else {
            return HttpClients.createDefault();
        }
    }

    private static SSLFactory sslFactory(boolean validateCert) {
        final SSLFactory.Builder builder = SSLFactory.builder();
        if (validateCert) {
            builder.withDefaultTrustMaterial();
        } else {
            builder.withTrustingAllCertificatesWithoutValidation();
        }
        builder.withSecurityProvider(new BouncyCastleJsseProvider(true, new BouncyCastleFipsProvider()))
                .withProtocols("TLSv1.2", "TLSv1.3")
                .build();
        System.out.println("Building sslFactory");
        return builder.build();
    }
}
```

The above is the simulation code for reproducing the issue 

This is tested with openjdk 11 

```
java --version
openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
```

The test passes in all OS except in Windows server (2012-2022) and WSL based linux
and fails intermittently with the below exception and it very slow and passes sometimes ruling out SSL protocol issues 

```
Jan 05, 2023 9:33:08 PM org.bouncycastle.jsse.provider.ProvTlsClient notifyAlertRaised
WARNING: Client raised fatal(2) internal_error(80) alert: Failed to write record
java.net.SocketException: Software caused connection abort: socket write error
        at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
        at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
        at org.bouncycastle.tls.RecordStream.writeRecord(RecordStream.java:307)
        at org.bouncycastle.tls.TlsProtocol.safeWriteRecord(TlsProtocol.java:946)
        at org.bouncycastle.tls.TlsProtocol.sendChangeCipherSpecMessage(TlsProtocol.java:1811)
        at org.bouncycastle.tls.TlsProtocol.sendChangeCipherSpec(TlsProtocol.java:1803)
        at org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(TlsClientProtocol.java:658)
        at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(TlsProtocol.java:711)
        at org.bouncycastle.tls.TlsProtocol.processRecord(TlsProtocol.java:587)
        at org.bouncycastle.tls.RecordStream.readRecord(RecordStream.java:245)
        at org.bouncycastle.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:875)
        at org.bouncycastle.tls.TlsProtocol.blockForHandshake(TlsProtocol.java:422)

```

Not able proceed further debugging with Wireshark the TLS is not sending the client hello

This issues only happens with Windows server and WSL and passes in all other os including windows 11 home

**Comment by dghgit** [comment]
Looking at this I'd now suspect the SunMSCAPI provider might have been removed and the JVM is failing to keep up due to the overheads of key generation.
