### ISSUE TITLE
IllegalAccessError in Java 17 while using SSLContext

### ISSUE THREAD

**Issue by amrynsky** [bcgit/bc-java#1315]
Environment:

- bc-fips 1.0.2.3
- java 17.0.5 2022-10-18 LTS

Getting the following error while connecting to MongoDB using X509 certificate. 

```
Caused by: java.lang.IllegalAccessError: class org.bouncycastle.jcajce.provider.ProvSunTLSKDF$TLSMasterSecretGenerator$1 (in unnamed module @0x4dd90166) cannot access class sun.security.internal.spec.TlsMasterSecretParameterSpec (in module java.base) because module java.base does not export sun.security.internal.spec to unnamed module @0x4dd90166
    at org.bouncycastle.jcajce.provider.ProvSunTLSKDF$TLSMasterSecretGenerator$1.run(Unknown Source)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
    at org.bouncycastle.jcajce.provider.ProvSunTLSKDF$TLSMasterSecretGenerator.engineInit(Unknown Source)
    at java.base/javax.crypto.KeyGenerator.init(KeyGenerator.java:476)
...
```

Not sure how to create small reproducible example but here is a code that we use to create `SSLContext`
```
@SneakyThrows
private SSLContext loadSslContext() {
	X509Certificate cert = loadCertificate(certificate);
	RSAPrivateKey key = loadPrivateKey(privateKey);

	log.info("Using X509 certificate to connect to Mongo: {}", cert.getSubjectX500Principal().getName());

	KeyStore keyStore = KeyStore.getInstance(KeyStore.getDefaultType());
	keyStore.load(null, null);
	keyStore.setKeyEntry("1", key, null, new X509Certificate[] { cert });

	return SSLContextBuilder.create()
			.setProtocol("TLS")
			.loadKeyMaterial(keyStore, null)
			.setSecureRandom(new SecureRandom())
			.build();
}
```

Java
```
> java --version
java 17.0.5 2022-10-18 LTS
Java(TM) SE Runtime Environment (build 17.0.5+9-LTS-191)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)
```

java.security
```
security.provider.1=SunEC
security.provider.2=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider
security.provider.3=SUN
security.provider.4=SunRsaSign
# moved up as a workaround based on https://github.com/bcgit/bc-java/issues/589#issuecomment-530780788
# to fix SSLException: Could not generate XDH keypair
#security.provider.4=SunEC
security.provider.5=SunJSSE
security.provider.6=SunJCE
security.provider.7=SunJGSS
security.provider.8=SunSASL
security.provider.9=XMLDSig
security.provider.10=SunPCSC
security.provider.11=JdkLDAP
security.provider.12=JdkSASL
security.provider.13=Apple
security.provider.14=SunPKCS11
```

Full call stack
```
Exception thrown from Netty Stream","error.stack_trace":"com.mongodb.MongoInternalException: Exception thrown from Netty Stream
    at com.mongodb.connection.netty.NettyStream$FutureAsyncCompletionHandler.get(NettyStream.java:478)
    at com.mongodb.connection.netty.NettyStream.write(NettyStream.java:224)
    at com.mongodb.internal.connection.InternalStreamConnection.sendMessage(InternalStreamConnection.java:552)
    at com.mongodb.internal.connection.InternalStreamConnection.sendCommandMessage(InternalStreamConnection.java:381)
    at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:329)
    at com.mongodb.internal.connection.CommandHelper.sendAndReceive(CommandHelper.java:101)
    at com.mongodb.internal.connection.CommandHelper.executeCommand(CommandHelper.java:45)
    at com.mongodb.internal.connection.InternalStreamConnectionInitializer.initializeConnectionDescription(InternalStreamConnectionInitializer.java:131)
    at com.mongodb.internal.connection.InternalStreamConnectionInitializer.startHandshake(InternalStreamConnectionInitializer.java:73)
    at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:182)
    at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:193)
    at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:157)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalAccessError: class org.bouncycastle.jcajce.provider.ProvSunTLSKDF$TLSMasterSecretGenerator$1 (in unnamed module @0x4dd90166) cannot access class sun.security.internal.spec.TlsMasterSecretParameterSpec (in module java.base) because module java.base does not export sun.security.internal.spec to unnamed module @0x4dd90166
    at org.bouncycastle.jcajce.provider.ProvSunTLSKDF$TLSMasterSecretGenerator$1.run(Unknown Source)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
    at org.bouncycastle.jcajce.provider.ProvSunTLSKDF$TLSMasterSecretGenerator.engineInit(Unknown Source)
    at java.base/javax.crypto.KeyGenerator.init(KeyGenerator.java:476)
    at java.base/javax.crypto.KeyGenerator.init(KeyGenerator.java:452)
    at java.base/sun.security.ssl.SSLMasterKeyDerivation$LegacyMasterKeyDerivation.deriveKey(SSLMasterKeyDerivation.java:149)
    at java.base/sun.security.ssl.KAKeyDerivation.t12DeriveKey(KAKeyDerivation.java:89)
    at java.base/sun.security.ssl.KAKeyDerivation.deriveKey(KAKeyDerivation.java:61)
    at java.base/sun.security.ssl.ECDHClientKeyExchange$ECDHEClientKeyExchangeProducer.produce(ECDHClientKeyExchange.java:426)
    at java.base/sun.security.ssl.ClientKeyExchange$ClientKeyExchangeProducer.produce(ClientKeyExchange.java:65)
    at java.base/sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:440)
    at java.base/sun.security.ssl.ServerHelloDone$ServerHelloDoneConsumer.consume(ServerHelloDone.java:182)
    at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
    at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
    at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1277)
    at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1264)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
    at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1209)
    at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1549)
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1395)
    at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)
    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    ... 1 more

```

**Comment by amrynsky** [comment]
Some additional information regarding the issue. Adding `BouncyCastleJsseProvider` fixed the issue but I'm still trying to understand the root cause. Is using `BouncyCastleFipsProvider` without `BouncyCastleJsseProvider` a valid use case?

```
security.provider.1=SunEC
security.provider.2=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider
security.provider.3=org.bouncycastle.jsse.provider.BouncyCastleJsseProvider fips:BCFIPS
security.provider.4=SUN
security.provider.5=SunRsaSign
# moved up as a workaround based on https://github.com/bcgit/bc-java/issues/589#issuecomment-530780788
# to fix SSLException: Could not generate XDH keypair
#security.provider.4=SunEC
security.provider.6=SunJSSE
security.provider.7=SunJCE
security.provider.8=SunJGSS
security.provider.9=SunSASL
security.provider.10=XMLDSig
security.provider.11=SunPCSC
security.provider.12=JdkLDAP
security.provider.13=JdkSASL
security.provider.14=Apple
security.provider.15=SunPKCS11
```

**Comment by dghgit** [comment]
So the issue shows up because the SunJSSE uses internal classes for the TLS KDFs. From the file above it appears you care about FIPS mode so I would recommend removing the SunJSSE altogether as it has not had FIPS support since Java 9. SunEC can be deleted as well, amongst others.

**Comment by amrynsky** [comment]
@dghgit  Thank you for the answer. What providers whould you recommend to keep for FIPS compliance?

As for removing SunJSSE & SunEC. It means that `ssl.KeyManagerFactory.algorithm` should be changed  from `SunX509` to `X509` as SunJSSE is used as a default provider for `KeyManagerFactory`. Right?

**Comment by dghgit** [comment]
Ideally you'd remove any provider you don't need, although it's really only the ones that provide cryptographic services which aren't shadowed by the BCFIPS provider that can cause issues. The BCFIPS provider will shadow the Sun one. The SSL settings should all be PKIX as described in: https://downloads.bouncycastle.org/fips-java/BC-FJA-(D)TLSUserGuide-1.0.13.pdf

**Comment by dghgit** [comment]
Appears dealt with.

**Comment by anekar3416** [comment]
@amrynsky I am also facing exactly similar issue. Can you please let me know what did you do to resolve this?

**Comment by damonreynolds** [comment]
@anekar3416 I ran into the same issue today and this post was very helpful. 

As @dghgit mentioned, you'll want to refer to section 2.1 of [this](Legion of the Bouncy Castle Inc. Java (D)TLS API and JSSE Provider User ... https://downloads.bouncycastle.org/fips-java/BC-FJA-(D)TLSUserGuide-1.0.13.pdf) user guide.
