### ISSUE TITLE
FipsUnapprovedOperationError: Attempt to create key pair with unapproved RNG: DH

### ISSUE THREAD

**Issue by Bonn93** [bcgit/bc-java#1369]
Hello, 

I have a java application running on Java 11/Adopt OpenJDK which throws an interesting exception when deployed on AWS. We cannot yet reproduce it locally. The application uses SpringBoot, DynamoDB and the AWS SDK/Http Client to connect to Dynamo. The entire application lives inside Docker image where all this is configured. 

The error is

```
com.amazonaws.SdkClientException: Unable to execute HTTP request: unable to create key pair
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1219)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1165)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.doInvoke(AmazonCloudWatchClient.java:3341)
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.invoke(AmazonCloudWatchClient.java:3308)
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.invoke(AmazonCloudWatchClient.java:3297)
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.executePutMetricData(AmazonCloudWatchClient.java:2808)
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.putMetricData(AmazonCloudWatchClient.java:2777)
	at com.amazonaws.metrics.internal.cloudwatch.MetricUploaderThread.run(MetricUploaderThread.java:102)
Caused by: org.bouncycastle.tls.crypto.TlsCryptoException: unable to create key pair
	at org.bouncycastle.fips.tls/org.bouncycastle.tls.crypto.impl.jcajce.JceTlsDHDomain.generateKeyPair(JceTlsDHDomain.java:161)
	at org.bouncycastle.fips.tls/org.bouncycastle.tls.crypto.impl.jcajce.JceTlsDH.generateEphemeral(JceTlsDH.java:30)
	at org.bouncycastle.fips.tls/org.bouncycastle.tls.TlsUtils.collectKeyShares(TlsUtils.java:5347)
	at org.bouncycastle.fips.tls/org.bouncycastle.tls.TlsUtils.addKeyShareToClientHello(TlsUtils.java:5276)
	at org.bouncycastle.fips.tls/org.bouncycastle.tls.TlsClientProtocol.sendClientHello(TlsClientProtocol.java:1841)
	at org.bouncycastle.fips.tls/org.bouncycastle.tls.TlsClientProtocol.beginHandshake(TlsClientProtocol.java:106)
	at org.bouncycastle.fips.tls/org.bouncycastle.tls.TlsClientProtocol.connect(TlsClientProtocol.java:84)
	at org.bouncycastle.fips.tls/org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(ProvSSLSocketWrap.java:620)
	at org.bouncycastle.fips.tls/org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(ProvSSLSocketWrap.java:596)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:142)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at jdk.internal.reflect.GeneratedMethodAccessor92.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy115.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1346)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	... 13 common frames omitted
Caused by: java.security.InvalidAlgorithmParameterException: Attempt to create key pair with unapproved RNG: DH
	at org.bouncycastle.fips.core/org.bouncycastle.jcajce.provider.ProvDH$KeyPairGeneratorSpi.initialize(Unknown Source)
	at org.bouncycastle.fips.tls/org.bouncycastle.tls.crypto.impl.jcajce.JceTlsDHDomain.generateKeyPair(JceTlsDHDomain.java:156)
	... 40 common frames omitted
Caused by: org.bouncycastle.crypto.fips.FipsUnapprovedOperationError: Attempt to create key pair with unapproved RNG: DH
	at org.bouncycastle.fips.core/org.bouncycastle.crypto.fips.Utils.validateRandom(Unknown Source)
	at org.bouncycastle.fips.core/org.bouncycastle.crypto.fips.Utils.validateKeyPairGenRandom(Unknown Source)
	at org.bouncycastle.fips.core/org.bouncycastle.crypto.fips.FipsDH$KeyPairGenerator.<init>(Unknown Source)
	... 42 common frames omitted
```

Now, bear with me here - this is an experimental/dev piece of work since we are using 4 security providers. I know this is not fully compliant. The images `java.security` file looks like this, the first provider is ACCP which is compiled into FIPS mode from https://github.com/corretto/amazon-corretto-crypto-provider#fips-builds

The goal of this setup is to leverage the BCTLS modules to make TLS FIPS Compliant and use ACCP to gain AES-NI and hardware acceleration. 

```
security.provider.1=com.amazon.corretto.crypto.provider.AmazonCorrettoCryptoProvider
security.provider.2=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider
security.provider.3=org.bouncycastle.jsse.provider.BouncyCastleJsseProvider fips:BCFIPS
security.provider.4=SUN
```

I recently added the 4th as I could produce some failures with `SecureRandom.getInstanceStrong()` and looking at the JSSE installation, it does specify the SUN provider be present for a minimal install. The `java.security` file also includes the below, which is why I believe the JSSE states the SUN provider be present to provide the `NativePRNGBlocking` interface.

```
securerandom.strongAlgorithms=DEFAULT:AmazonCorrettoCryptoProvider,NativePRNGBlocking:SUN,DRBG:SUN
```

For some extra debugging steps, I have tried to write vanilla test cases to connect to Dynamo, use SecureRandom and several other things in a basic Kotlin application. Aspects like Key Generation does work, when it's complaint against the policy set in our `jdk.tls.disabledAlgorithms` section of the file. Ie DH Key size > 1024 and generating a DH key:pair does work when the strength is correct. 

There's also some other code that uses the OkHTTP client which seems to be running fine. This error is thrown when we call an endpoint which writes to DynamoDB.

To also add, I have the following `JAVA_OPTS` set
```
ENV JAVA_OPTS="--add-modules com.amazon.corretto.crypto.provider,org.bouncycastle.fips.tls,org.bouncycastle.fips.core \
--module-path /opt/service/dependencies \
--add-exports java.base/sun.security.provider=com.amazon.corretto.crypto.provider \
--add-exports java.base/sun.security.provider=org.bouncycastle.fips.tls \
--add-exports java.base/sun.security.provider=org.bouncycastle.fips.core \
-Djava.security.properties=/opt/java/openjdk/conf/security/java.security \
-Dorg.bouncycastle.jsse.client.assumeOriginalHostName=true \
-Dorg.bouncycastle.fips.approved_only=true \
-Dorg.bouncycastle.jca.enable_jks=true \
"
```

**Comment by dghgit** [comment]
Hmmm... okay, I don't this is going to work out - I'd guess the problem is that there's a corretto DRBG in there somewhere, also the AmazonCorrettoCryptoProvider provider is not FIPS compliant its presence actually rules out any possibility of the application being  FIPS compliant so you don't really need to set the approved_only flag.

The 2.1.0 version of BCFIPS is hardware accelerated. It's only available under early access at the moment though.

**Comment by Bonn93** [comment]
Hi, thanks for the response, great to hear the news for 2.1.0 - I am actually trying to sort out a support contract and access to that :) 

Another thing we found was changing the provider order seems to have a difference here. Two questions in this case:

* Would changing the `securerandom.strongAlgorithms=DEFAULT:AmazonCorrettoCryptoProvider` to use BCFIPS work instead? Would that just tell it to use a different secure random provider?  (thus getting hardware acceleration if using ACCP, but with a different securerandom ( that is also compliant? ) 

* Are you saying that the `approved_only` flag is not correct in this instance? Wouldn't that allow the use of non-FIPS algos/ciphers ie chacha20 because its not in approved mode? 

Thanks

**Comment by dghgit** [comment]
So with 1 - usually just the Sun one, Blocking. The FIPS provider uses the securerandom.strongAlgorithms property to locate the JVMs entropy source, so there's no point in putting a BCFIPS rng there (it will either cause a regress or be ignored).

With 2 - the presence of the non-fips provider for doing AES in position 1 means that what ever the application is up to it's not FIPS compliant, so approved_only's only effect is to block non-FIPS algorithms in the BCFIPS provider. It's not clear that that is the look you are really going for.

**Comment by galaxis7** [comment]
I thought the entropy source is gotten from property "securerandom.source".

**Comment by galaxis7** [comment]
My ? is, does BC use a FIPS-compliant RNG algo w/out having to override default `securerandom.strongAlgorithms=NativePRNGBlocking:SUN,DRBG:SUN` in Java 17?

**Comment by dghgit** [comment]
The FIPS API does use SP 800-90A DRBG algorithms internally, but I think you might be thinking of SP 800-90B. BC FIPS will use the generateSeed() method on the SecureRandom specified by secureRandom.strongAlgorithms - it's what is used there that determines the level of entropy provided to the module.

**Comment by galaxis7** [comment]
Thx [dghgit](https://github.com/dghgit), I was actually referring to both in my 2 stmts sry for confusion.  1st stmt was question the entropy source as different than above, but 2nd stmt, was ultimately looking to understand if those default JDK 17 RNG algos (particularly `DRBG:SUN`) are NIST SP 800-90Ar1 listed/FIPS compliant (which I guess infers by association/the 90A std means that entropy source is also 90B compliant); I realize 800-90A is inherently about DRBG algos, but  is that Sun impl part of that std (it appears to support Hash_DRBG and HMAC_DRBG mechanisms with DRBG algorithm SHA-224, SHA-512/224, SHA-256, SHA-512/256, SHA-384 and SHA-512, and CTR_DRBG).

Current problem is w/ Keycloak; when creating a BC keystore, [keycloak site](https://www.keycloak.org/server/fips#_bouncycastle_library) is saying BCFKS override the default:
 `securerandom.strongAlgorithms=NativePRNGBlocking:SUN,DRBG:SUN`
 with:
`securerandom.strongAlgorithms=PKCS11:SunPKCS11-NSS-FIPS`
on the "keytool" cmd line.  Using that NSS override tho, is causing BC FIPS to blow up basically because of [this 1149 issue](https://github.com/bcgit/bc-java/issues/1149) getting rand num.  I'v never had to use any specific RNG overrides in the past w/ BC; c oulda been missing something tho - and don't know why keycloak thinks it needs that override - just trying determine if we get a FIPS compliant keystore w/out it.
