### ISSUE TITLE
PGPSignature verification is not thread-safe

### ISSUE THREAD

**Issue by vanitasvitae** [bcgit/bc-java#1379]
A user recently noticed, that some PGP operations (decryption of a message in this case) would sometimes fail randomly.
It turns out, their code was multi-threaded, and PGPainless would prior to message decryption check binding signatures on the encryption subkey.

This caused the following error in BCs PGPSignature class:
```
java.lang.ArrayIndexOutOfBoundsException: length=8; index=8
at org.bouncycastle.crypto.digests.LongDigest.update(Unknown Source:8)
at org.bouncycastle.crypto.digests.LongDigest.update(Unknown Source:8)
at org.bouncycastle.openpgp.operator.bc.BcImplProvider$EdDsaSigner.update(Unknown Source:2)
at org.bouncycastle.openpgp.operator.bc.SignerOutputStream.write(Unknown Source:2)
at org.bouncycastle.openpgp.PGPSignature.blockUpdate(Unknown Source:2)
at org.bouncycastle.openpgp.PGPSignature.update(Unknown Source:16)
at org.bouncycastle.openpgp.PGPSignature.update(Unknown Source:2)
at org.bouncycastle.openpgp.PGPSignature.updateWithPublicKey(Unknown Source:21)
at org.bouncycastle.openpgp.PGPSignature.verifyCertification(Unknown Source:4)
```

After some digging, we figured out, that this is probably caused by multiple threads working on the same PGPPublicKeyRing instance (and therefore on the same PGPSignature instance, hence the same SignerOutputStream using the same EdDsaSigner, using the same LongDigest).

Upon further inspection, it turns out that PGPSignature is not designed to be used in a multi-threaded environment. The SignerOutputStream is a member of the class, so parallel verification would probably write garbage to that stream, resulting in verification fails.

Would you consider a patch that refactors the PGPSignature class in such a way that the stateful verification code is moved into a separate class, even though such a patch would break the API backwards compatibility?

I could imagine something along these lines:
```java
PGPSignature signature = ...;
SignatureVerifier verifier = signature.init(verifierBuilderProvider, pubKey); // stateful stuff is moved here
boolean valid = verifier.verifyCertification(masterKey, pubKey);
```

I think this would allow multiple threads to work on the same PGPSignature instance without interfering (since each thread would have its own copy of the SignatureVerifier class).

Now that I think about it, if instead of refactoring the `init` method, we add a separate method (`betterInit`?), we can even change the behavior without breaking backwards compat.

What do you think?

Related resources:
[original bug report](https://github.com/pgpainless/pgpainless/issues/365)
[reproducer for PGPainless](https://github.com/pgpainless/pgpainless/pull/370)
[ported reproducer for BC](https://github.com/pgpainless/bc-java/commit/5c73f0fa3083faea01eba032fb9fcf1677e84795)

**Comment by vanitasvitae** [comment]
I prototyped an implementation of the discussed patch [here](https://github.com/bcgit/bc-java/commit/cb024359b083679ba678ec44c6d32d0864321ddc).

As you can see, the patch would be backwards compatible, but would enable thread-safe verification of signatures.

**Comment by vanitasvitae** [comment]
Have you tried with PGPainless 1.7.3, which depends on BC 1.80 instead of 1.78.1?
