### ISSUE TITLE
RSA/ECB/OAEPPadding decryption with HSM private key breaking changes for 1.7

### ISSUE THREAD

**Issue by fialo4ka** [bcgit/bc-java#1381]
BC 1.46
Java 17

In BC 1.46 to decrypt data from RSA/ECB/OAEPPadding using private key from hsm was going with
```
KeyPairGenerator generator = KeyPairGenerator.getInstance("RSA", "BC");
generator.initialize(new RSAKeyGenParameterSpec("2048", BigInteger.valueOf(1)))
rsaKey2048 = generator.generateKeyPair();
//decrypt with private key from hsm
Cipher cipher = Cipher.getInstance("RSA/ECB/NoPadding", "SunPKCS11-cknfast0");
cipher.init(Cipher.DECRYPT_MODE, privatePK11Key);  
decryptedWithPadding = cipher.doFinal(data);
// resolve paddingresolve padding
cipher.init(Cipher.DECRYPT_MODE, rsaKey2048.getPrivate());
decrypted = cipher.doFinal(decryptedWithPadding );
```

BC 1.70 
Java 17

in BC 1.70 this already not working

I need to change 2d line to:
  generator.initialize("2048");

in resolve padding part it give an exception
```
Caused by: org.bouncycastle.jcajce.provider.util.BadBlockException: unable to decrypt block
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.getOutput(Unknown Source) ~[bcprov-jdk15on-1.70.jar:1.70.0]
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineDoFinal(Unknown Source) ~[bcprov-jdk15on-1.70.jar:1.70.0]
	at javax.crypto.Cipher.doFinal(Cipher.java:2207) ~[?:?]
	at com.globalblue.cryptoservice.busines.service.decryption.rsa.RsaDecryption.decryptRsaByteDataOaepOld(RsaDecryption.java:96) ~[classes/:?]
	... 73 more
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: data wrong
	at org.bouncycastle.crypto.encodings.OAEPEncoding.decodeBlock(Unknown Source) ~[bcprov-jdk15on-1.70.jar:1.70.0]
	at org.bouncycastle.crypto.encodings.OAEPEncoding.processBlock(Unknown Source) ~[bcprov-jdk15on-1.70.jar:1.70.0]
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.getOutput(Unknown Source) ~[bcprov-jdk15on-1.70.jar:1.70.0]
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.CipherSpi.engineDoFinal(Unknown Source) ~[bcprov-jdk15on-1.70.jar:1.70.0]
	at javax.crypto.Cipher.doFinal(Cipher.java:2207) ~[?:?]
```
How now code need to be changed to support oaep?

**Comment by dghgit** [comment]
Two things. First, the PKCS#11 side is not using OAEPPadding. It's PKCS1.5. The code appears to be using 2 independent keys to decrypt some cipher text, it would never have worked with 1.46.

**Comment by fialo4ka** [comment]
Thanks :) but it was working for us years :)
But I found the solution, I just copy and adjust org.bouncycastle.crypto.encodings.OAEPEncoding class for my case.
