### ISSUE TITLE
bc-java v1.73: test tls:test fails on UBI 8.7

### ISSUE THREAD

**Issue by pooja0805** [bcgit/bc-java#1382]
Hello,

I encountered an issue while running the `gradle test` command on UBI 8.7 to test bc-java v1.73. Specifically, we encountered an error with the test tls:test, which is detailed in the error log provided below:

```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :core:compileJava UP-TO-DATE
> Task :core:processResources UP-TO-DATE
> Task :core:classes UP-TO-DATE
> Task :core:jar UP-TO-DATE
> Task :core:compileTestJava UP-TO-DATE
> Task :core:processTestResources UP-TO-DATE
> Task :core:testClasses UP-TO-DATE
> Task :core:test UP-TO-DATE
> Task :prov:compileJava UP-TO-DATE
> Task :prov:processResources UP-TO-DATE
> Task :prov:classes UP-TO-DATE
> Task :prov:jar UP-TO-DATE
> Task :util:compileJava UP-TO-DATE
> Task :util:processResources NO-SOURCE
> Task :util:classes UP-TO-DATE
> Task :util:jar UP-TO-DATE
> Task :pkix:compileJava UP-TO-DATE
> Task :pkix:processResources NO-SOURCE
> Task :pkix:classes UP-TO-DATE
> Task :pkix:jar UP-TO-DATE
> Task :mail:compileJava UP-TO-DATE
> Task :mail:processResources UP-TO-DATE
> Task :mail:classes UP-TO-DATE
> Task :mail:jar UP-TO-DATE
> Task :mail:compileTestJava UP-TO-DATE
> Task :mail:processTestResources UP-TO-DATE
> Task :mail:testClasses UP-TO-DATE
> Task :mail:test UP-TO-DATE
> Task :pg:compileJava UP-TO-DATE
> Task :pg:processResources NO-SOURCE
> Task :pg:classes UP-TO-DATE
> Task :pg:jar UP-TO-DATE
> Task :pg:compileTestJava UP-TO-DATE
> Task :pg:processTestResources UP-TO-DATE
> Task :pg:testClasses UP-TO-DATE
> Task :pg:test UP-TO-DATE
> Task :pkix:compileTestJava UP-TO-DATE
> Task :pkix:processTestResources UP-TO-DATE
> Task :pkix:testClasses UP-TO-DATE
> Task :pkix:test UP-TO-DATE
> Task :prov:compileTestJava UP-TO-DATE
> Task :prov:processTestResources UP-TO-DATE
> Task :prov:testClasses UP-TO-DATE
> Task :prov:test UP-TO-DATE
> Task :tls:compileJava UP-TO-DATE
> Task :tls:processResources NO-SOURCE
> Task :tls:classes UP-TO-DATE
> Task :tls:jar UP-TO-DATE
> Task :tls:compileTestJava UP-TO-DATE
> Task :tls:processTestResources UP-TO-DATE
> Task :tls:testClasses UP-TO-DATE

> Task :tls:test
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

org.bouncycastle.jsse.provider.test.AllTests STANDARD_ERROR
    Apr 25, 2023 8:44:40 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSecurityProperty
    INFO: Found string security property [jdk.tls.disabledAlgorithms]: DH keySize < 2048, TLSv1.1, TLSv1, SSLv3, SSLv2, DHE_DSS, RSA_EXPORT, DHE_DSS_EXPORT, DHE_RSA_EXPORT, DH_DSS_EXPORT, DH_RSA_EXPORT, DH_anon, ECDH_anon, DH_RSA, DH_DSS, ECDH, 3DES_EDE_CBC, DES_CBC, RC4_40, RC4_128, DES40_CBC, RC2, HmacMD5
    Apr 25, 2023 8:44:40 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSecurityProperty
    INFO: Found string security property [jdk.certpath.disabledAlgorithms]: MD2, MD5, DSA, RSA keySize < 2048
    Apr 25, 2023 8:44:40 AM org.bouncycastle.jsse.provider.PropertyUtils getBooleanSecurityProperty
    INFO: Found boolean security property [keystore.type.compat]: true
    Apr 25, 2023 8:44:40 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [java.home]: /usr/lib/jvm/java-11-openjdk-11.0.19.0.7-1.el8_7.x86_64

org.bouncycastle.jsse.provider.test.AllTests > org.bouncycastle.jsse.provider.test.ECDSACredentialsTest.test13_secp256r1 STANDARD_ERROR
    Apr 25, 2023 8:44:41 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1
    Apr 25, 2023 8:44:41 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1

org.bouncycastle.jsse.provider.test.AllTests > org.bouncycastle.jsse.provider.test.ECDSACredentialsTest.test13_secp384r1 STANDARD_ERROR
    Apr 25, 2023 8:44:41 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1
    Apr 25, 2023 8:44:41 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1

org.bouncycastle.jsse.provider.test.AllTests > org.bouncycastle.jsse.provider.test.ECDSACredentialsTest.test13_secp521r1 STANDARD_ERROR
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1

org.bouncycastle.jsse.provider.test.AllTests > org.bouncycastle.jsse.provider.test.ECDSACredentialsTest.test12_brainpoolP256r1 STANDARD_ERROR
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1

org.bouncycastle.jsse.provider.test.AllTests > org.bouncycastle.jsse.provider.test.ECDSACredentialsTest.test12_brainpoolP384r1 STANDARD_ERROR
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1

org.bouncycastle.jsse.provider.test.AllTests > org.bouncycastle.jsse.provider.test.ECDSACredentialsTest.test12_brainpoolP512r1 STANDARD_ERROR
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1

org.bouncycastle.jsse.provider.test.AllTests > org.bouncycastle.jsse.provider.test.ECDSACredentialsTest.test12_secp256r1 STANDARD_ERROR
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1

org.bouncycastle.jsse.provider.test.AllTests > org.bouncycastle.jsse.provider.test.ECDSACredentialsTest.test12_secp384r1 STANDARD_ERROR
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1

org.bouncycastle.jsse.provider.test.AllTests > org.bouncycastle.jsse.provider.test.ECDSACredentialsTest.test12_secp521r1 STANDARD_ERROR
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1

org.bouncycastle.jsse.provider.test.AllTests > org.bouncycastle.jsse.provider.test.ECDSACredentialsTest.test13_brainpoolP384r1tls13 STANDARD_ERROR
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1

org.bouncycastle.jsse.provider.test.AllTests > org.bouncycastle.jsse.provider.test.ECDSACredentialsTest.test13_brainpoolP512r1tls13 STANDARD_ERROR
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1

org.bouncycastle.jsse.provider.test.AllTests > org.bouncycastle.jsse.provider.test.ECDSACredentialsTest.test13_brainpoolP256r1tls13 STANDARD_ERROR
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1
    Apr 25, 2023 8:44:42 AM org.bouncycastle.jsse.provider.PropertyUtils getStringSystemProperty
    INFO: Found string system property [jdk.tls.namedGroups]: secp256r1,secp384r1,secp521r1,brainpoolP256r1tls13,brainpoolP384r1tls13,brainpoolP512r1tls13,brainpoolP256r1,brainpoolP384r1,brainpoolP512r1

org.bouncycastle.jsse.provider.test.AllTests > org.bouncycastle.jsse.provider.test.KeyManagerFactoryTest.testBasicRSA FAILED
    junit.framework.AssertionFailedError at KeyManagerFactoryTest.java:244

org.bouncycastle.jsse.provider.test.AllTests > org.bouncycastle.jsse.provider.test.KeyManagerFactoryTest.testRSAServerTrustEE STANDARD_ERROR
    Apr 25, 2023 8:44:43 AM org.bouncycastle.jsse.provider.ProvTlsClient notifyAlertReceived
    INFO: Client received fatal(2) handshake_failure(40) alert

org.bouncycastle.jsse.provider.test.AllTests > org.bouncycastle.jsse.provider.test.KeyManagerFactoryTest.testRSAServerTrustEE FAILED
    org.bouncycastle.tls.TlsFatalAlertReceived at KeyManagerFactoryTest.java:133

org.bouncycastle.jsse.provider.test.AllTests > org.bouncycastle.jsse.provider.test.KeyManagerFactoryTest.testRSAServer STANDARD_ERROR
    javax.net.ssl.SSLHandshakeException: no cipher suites in common
    	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
    	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
    	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:347)
    	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:303)
    	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:294)
    	at java.base/sun.security.ssl.ServerHello$T12ServerHelloProducer.chooseCipherSuite(ServerHello.java:460)
    	at java.base/sun.security.ssl.ServerHello$T12ServerHelloProducer.produce(ServerHello.java:295)
    	at java.base/sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:436)
    	at java.base/sun.security.ssl.ClientHello$T12ClientHelloConsumer.consume(ClientHello.java:1091)
    	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:843)
    	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:802)
    	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
    	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
    	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
    	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
    	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
    	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1507)
    	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1417)
    	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:456)
    	at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:922)
    	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1013)
    	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:973)
    	at org.bouncycastle.jsse.provider.test.SSLUtils$1.run(SSLUtils.java:87)
    	at java.base/java.lang.Thread.run(Thread.java:829)
    java.net.BindException: Address already in use (Bind failed)
    	at java.base/java.net.PlainSocketImpl.socketBind(Native Method)
    	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:452)
    	at java.base/java.net.ServerSocket.bind(ServerSocket.java:395)
    	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:257)
    	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:201)
    	at java.base/javax.net.ssl.SSLServerSocket.<init>(SSLServerSocket.java:136)
    	at java.base/sun.security.ssl.SSLServerSocketImpl.<init>(SSLServerSocketImpl.java:70)
    	at java.base/sun.security.ssl.SSLServerSocketFactoryImpl.createServerSocket(SSLServerSocketFactoryImpl.java:73)
    	at org.bouncycastle.jsse.provider.test.SSLUtils$1.run(SSLUtils.java:76)
    	at java.base/java.lang.Thread.run(Thread.java:829)
```
However, the same test suite runs successfully on Ubuntu without any issues. Could you please investigate this issue and provide any guidance on how to resolve it.?

To reproduce the error, please follow these steps:
1. export HOME_DIR=$PWD
2. sudo yum install -y git wget tar java-11-openjdk-devel unzip openssl-devel
3. export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
4. export PATH=$JAVA_HOME/bin:$PATH
5. java -version
6. cd $HOME_DIR
7. wget https://services.gradle.org/distributions/gradle-7.6.1-bin.zip
8. unzip gradle-7.6.1-bin.zip
9. sudo mkdir /opt/gradle
10. sudo cp -pr gradle-7.6.1/* /opt/gradle
11. export PATH=/opt/gradle/bin:${PATH}
12. cd $HOME_DIR
13. git clone https://github.com/bcgit/bc-java.git
14. cd bc-java
15. git checkout r1rv73
16. cd $HOME_DIR
17. git clone https://github.com/bcgit/bc-test-data.git
18. cd $HOME_DIR/bc-java
19. export JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"
20. gradle clean build -x test
21. gradle test

**Comment by pooja0805** [comment]
@dghgit Could you please have a look at this issue?

**Comment by dghgit** [comment]
I cannot reproduce this here. All I can suggest is check the actual test reports, particularly the first failures, there may be extra detail in them which will help isolate the problem. It's likely the final error "address already in use" is due to an earlier test that has gotten hung up.

**Comment by pooja0805** [comment]
Thank you for your suggestion. I will review the test reports, particularly the first failures, to see if there is any additional information that can help identify the issue.

Regarding the "address already in use" error, your theory that it may be due to an earlier test getting hung up makes sense. I will investigate the earlier tests to see if there are any that could potentially cause this issue.

Thanks again for your help. I'll let you know if I have any further questions or if I discover anything significant in the test reports.

**Comment by dghgit** [comment]
Appears resolved.
