### ISSUE TITLE
JcaJce: Cannot find any provider supporting AES/OCB/NoPadding or AES/EAX/NoPadding

### ISSUE THREAD

**Issue by vanitasvitae** [bcgit/bc-java#1390]
Hey!
I'm currently testing SEIPDv2 support with Bouncycastles beta release 174b01.

I noticed, that decryption of AEAD encrypted messages using EAX and OCB fails when using the JcaJce API.

```
org.bouncycastle.openpgp.PGPException: cannot create cipher: Cannot find any provider supporting AES/EAX/NoPadding
	at org.bouncycastle.openpgp.operator.jcajce.OperatorHelper.createCipher(Unknown Source)
	at org.bouncycastle.openpgp.operator.jcajce.JceAEADUtil.createAEADCipher(Unknown Source)
	at org.bouncycastle.openpgp.operator.jcajce.JcePBEDataDecryptorFactoryBuilder$1.recoverAEADEncryptedSessionData(Unknown Source)
	at org.bouncycastle.openpgp.PGPPBEEncryptedData.getSessionKey(Unknown Source)
	at org.bouncycastle.openpgp.PGPPBEEncryptedData.getDataStream(Unknown Source)
```

The stacktrace for OCB looks similar, just the algorithm is swapped out.

The exceptions do not happen if I use a `BcPBEDataDecryptorFactory` instead.

Is this to be expected?

**Comment by vanitasvitae** [comment]
Nevermind, this issue appears to be my faulty setup.

**Comment by vanitasvitae** [comment]
Reopening, since this is actually a bug.

**Comment by dghgit** [comment]
I assume #1391 is the fix for this one?

**Comment by vanitasvitae** [comment]
Correct :)
