### ISSUE TITLE
org.bouncycastle.crypto.fips.FipsOperationError: Module checksum failed: expected 

### ISSUE THREAD

**Issue by nssssandeep** [bcgit/bc-java#1415]
Getting below error when I try to include bc fips jar into my jar. How do I solve this?

[735510be1bb5157434c14d1e1ca9844b6971634fc03481d93eec75ff27b27034] got [4fc88822bd6ca528e6963f3951c4056aa33976ae3e8b82f7c8cc3f433a1e1f3f]
	at org.bouncycastle.crypto.fips.FipsStatus.moveToErrorStatus(Unknown Source)
	at org.bouncycastle.crypto.fips.FipsStatus.checksumValidate(Unknown Source)
	at org.bouncycastle.crypto.fips.FipsStatus.isReady(Unknown Source)
	at org.bouncycastle.crypto.CryptoServicesRegistrar.getDefaultMode(Unknown Source)
	at org.bouncycastle.crypto.CryptoServicesRegistrar.<clinit>(Unknown Source)
	at org.bouncycastle.jcajce.provider.ProvSecureHash$MD5.configure(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
	at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)

**Comment by mwcw** [comment]
Hi,

The checksum is a FIPS requirement.

Merging it with another jar is the equivalent of adding other classes to it which causes the checksum to  be different and this causes the module startup failure you are seeing.

A solution for you is to include it on the same classpath that loads "myjar".

MW

**Comment by peterdettman** [comment]
Any modification or repackaging of the jar will cause the checksum failure, which is by design. The only way to "resolve the issue" is to not do those things.

**Comment by prabusenthil** [comment]
> Any modification or repackaging of the jar will cause the checksum failure, which is by design. The only way to "resolve the issue" is to not do those things.

I downloaded the checksum from the Bouncy Castle official website. Here is the reference

 <html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/PRABHU~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/PRABHU~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


bc-fips-1.0.2.4.jar | 9008d04fc13da6455e6a792935b93b629757335d | 703ecd8a3a619800269bc8cd442f2ebf469bd2fe70478364f58ddc6460c35f9f
-- | -- | --




</body>

</html>


but when I opened bc-fips-1.0.2.4 jar and checked, the checksum value was different. Please see this reference

[repo1.maven.org/maven2/org/bouncycastle/bc-fips/1.0.2.4/bc-fips-1.0.2.4.jar.sha256](https://repo1.maven.org/maven2/org/bouncycastle/bc-fips/1.0.2.4/bc-fips-1.0.2.4.jar.sha256)

why this difference? in my code, i am getting this 

Exception in thread "main" org.bouncycastle.crypto.fips.FipsOperationError: org.bouncycastle.crypto.fips.FipsOperationError: Module checksum failed: expected [9f6751f059ab42f7d83e4e107881438036787e1e1821cd23a53c4b8181cc300f] got [44a0ea1cfdbcd90db49358391eeefdc443fb61bb50d69975128d94cb43a91fce]

Note : we are not modify or repackage the bc-fips jar

On Tue, Jun 25, 2024 at 3:47 PM Peter Dettman <[notifications@github.com](mailto:notifications@github.com)> wrote:
Any modification or repackaging of the jar will cause the checksum failure, which is by design. The only way to "resolve the issue" is to not do those things.—

**Comment by peterdettman** [comment]
@prabusenthil You are confusing two different checksums. There is the SHA-256 checksum that is an externally-calculated SHA-256 digest over the jar file so that you can confirm correct download (e.g. with something like "openssl dgst -sha256 bc-fips-1.0.2.4.jar").

However the jar also maintains an internally-stored checksum so that it can self-validate at startup (per FIPS requirement). The exception message relates to this internal checksum.

> Note : we are not modify or repackage the bc-fips jar

Great, then you aren't getting the exception.
