### ISSUE TITLE
Getting error "Could not generate XDH keypair" with jdk 11 while making the http call to S3 to find the region of bucket 

### ISSUE THREAD

**Issue by pjonnlagadda** [bcgit/bc-java#1419]
Where i am migrating from jdk 8 to jdk 11, i am facing the below error, if some else is facing the same, please suggest or start the discussion
Getting error "Could not generate XDH keypair" with jdk 11 while making the http call to S3 to find the region of bucket
**Note:-** The same is working as expected in the Jdk8

> Caused by: javax.net.ssl.SSLException: Could not generate XDH keypair
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:353)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:296)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:291)
	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1690)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:471)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	... 18 more
Caused by: java.lang.RuntimeException: Could not generate XDH keypair
	at java.base/sun.security.ssl.XDHKeyExchange$XDHEPossession.<init>(XDHKeyExchange.java:109)
	at java.base/sun.security.ssl.NamedGroup$XDHScheme.createPossession(NamedGroup.java:602)
	at java.base/sun.security.ssl.NamedGroup$NamedGroupSpec.createPossession(NamedGroup.java:511)
	at java.base/sun.security.ssl.NamedGroup.createPossession(NamedGroup.java:419)
	at java.base/sun.security.ssl.SSLKeyExchange$T13KeyAgreement.createPossession(SSLKeyExchange.java:568)
	at java.base/sun.security.ssl.SSLKeyExchange.createPossessions(SSLKeyExchange.java:84)
	at java.base/sun.security.ssl.KeyShareExtension$CHKeyShareProducer.produce(KeyShareExtension.java:259)
	at java.base/sun.security.ssl.SSLExtension.produce(SSLExtension.java:582)
	at java.base/sun.security.ssl.SSLExtensions.produce(SSLExtensions.java:253)
	at java.base/sun.security.ssl.ClientHello$ClientHelloKickstartProducer.produce(ClientHello.java:639)
	at java.base/sun.security.ssl.SSLHandshake.kickstart(SSLHandshake.java:525)
	at java.base/sun.security.ssl.ClientHandshakeContext.kickstart(ClientHandshakeContext.java:112)
	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:233)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:449)
	... 33 more
Caused by: java.security.InvalidAlgorithmParameterException: AlgorithmParameterSpec not recognized: java.security.spec.NamedParameterSpec
	at org.bouncycastle.jcajce.provider.ProvEdEC$KeyPairGeneratorSpi.initialize(Unknown Source)
	at java.base/sun.security.ssl.XDHKeyExchange$XDHEPossession.<init>(XDHKeyExchange.java:104)
	... 46 more

**Comment by dghgit** [comment]
You don't say which version of BC you are using.

**Comment by pjonnlagadda** [comment]
Hi @dghgit
Thanks for addressing. the **org.bouncycastle.jcajce.provider.ProvEdEC$KeyPairGeneratorSpi** is from bc-fips-1.0.2.3.jar in my class path belongs to latest

**Comment by dghgit** [comment]
Use the FIPS version of the BCJSSE - if you're running with the FIPS API there's no point in using the regular JSSE in any case (the actually issue is the JSSE is using a class that the BCFIPS API doesn't support)
