### ISSUE TITLE
Current main fails testPGP

### ISSUE THREAD

**Issue by mouse07410** [bcgit/bc-java#1446]
MacOS, Amazon Corretto JDK-17, current main. One test (`testPGP`) fails:

```text
ArmoredOutputStream: no message

junit.framework.AssertionFailedError: ArmoredOutputStream: no message
at org.bouncycastle.openpgp.test.AllTests.testPGP(AllTests.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)
at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
at junit.extensions.TestSetup.run(TestSetup.java:27)
```

I made sure `bc-java` and `bc-test-data` are up to date.

**Comment by dghgit** [comment]
Odd. We'll look into it. Thanks for letting us know.

**Comment by dghgit** [comment]
Okay, I think this is now fixed, turned out to be the version string. Let us know. Thanks again.

**Comment by mouse07410** [comment]
Concur - fixed. Thanks
