### ISSUE TITLE
hwo to parse sm2 certificate and create class PrivateKey

### ISSUE THREAD

**Issue by flymoondust** [bcgit/bc-java#1454]
I use this：`PrivateKeyInfo privateKeyInfo = PrivateKeyInfo.getInstance(bytesContents);`

exception：

```
java.lang.IllegalArgumentException: failed to construct sequence from byte[]: Extra data detected in stream

	at org.bouncycastle.asn1.ASN1Sequence.getInstance(Unknown Source)
	at org.bouncycastle.asn1.pkcs.PrivateKeyInfo.getInstance(Unknown Source)
```

**Comment by flymoondust** [comment]
My real request is to use sm4 encrypt the sm2 Privatekey to create encrypted Privatekey

**Comment by dghgit** [comment]
Support for SM4 has been added to the PEM classes in the OpenSSL package. Now on https://www.bouncycastle.org/betas
