### ISSUE TITLE
The issue arises when using bc-java 1.75 version with TLS 1.2 on Android 4.2 devices. It results in an error that needs to be addressed. Further details about the error and its potential causes would be helpful in resolving the problem.

### ISSUE THREAD

**Issue by yb1994917** [bcgit/bc-java#1461]
val sslContext = SSLContext.getInstance("TLS",BouncyCastleJsseProvider.PROVIDER_NAME) 

FATAL EXCEPTION: OkHttp Dispatcher
 java.lang.NoSuchMethodError: javax.crypto.Cipher.updateAAD
        at org.bouncycastle.tls.crypto.impl.jcajce.JceAEADCipherImpl.doFinal(Unknown Source)
        at org.bouncycastle.tls.crypto.impl.TlsAEADCipher.encodePlaintext(Unknown Source)
        at org.bouncycastle.tls.RecordStream.writeRecord(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.safeWriteRecord(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.raiseAlertWarning(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.handleClose(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.close(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.close(Unknown Source)
        at okhttp3.internal.Util.closeQuietly(Util.java:121)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:317)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
        at java.lang.Thread.run(Thread.java:856)

**Comment by dghgit** [comment]
Try https://www.bouncycastle.org/betas

**Comment by dghgit** [comment]
Okay, try bctls-jdk15to18-176.jar it's only available on [the latest_releases](https://www.bouncycastle.org/latest_releases.html) at the moment.

**Comment by dghgit** [comment]
Fixed in 1.76.
