### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/asn1/cms/CMSObjectIdentifiers

### ISSUE THREAD

**Issue by sumanbanerjee1981** [bcgit/bc-java#1502]
I am using standard signing methods of bouncy castle from my code. When I am using bouncy castle jar versions - bcpkix-jdk15on-1.60.jar, bcprov-ext-jdk15on-1.60.jar,bcprov-jdk15on-1.60.jar I am getting the below error : Please suggest what is the issue with this version? The code is running with other versions of Bouncy Castle Jars. The reason of using this version is Oracle Latest Web Logic patch for 12.1.2.4 uses the same version of jars. 

Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/asn1/cms/CMSObjectIdentifiers
	at org.bouncycastle.operator.DefaultSignatureNameFinder.<clinit>(Unknown Source)
	at org.bouncycastle.operator.jcajce.OperatorHelper.<clinit>(Unknown Source)
	at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.<init>(Unknown Source)
	at com.ncb.sign.Encrypt_Dcrypt.sign(Encrypt_Dcrypt.java:99)
	at com.ncb.sign.Encrypt_Dcrypt.main(Encrypt_Dcrypt.java:80)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.asn1.cms.CMSObjectIdentifiers
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

**Comment by dghgit** [comment]
You need the bcutil jar as well.

**Comment by sumanbanerjee1981** [comment]
I tried with other sets of jars bcpkix-jdk15on-1.60.jar, bcprov-ext-jdk15on-1.60.jar,bcprov-jdk15on-1.60.jar having different sizes then it is working without bcutil. I am adding two zip files with same jars but different sizes among which one set is working and another set is not working.  Are there two different packaging in same version ? Which one is correct one and we should use ?

**Comment by AlBundy33** [comment]
it seems that this change was introduced in 1.69 but I'm not sure why.
In this version `org.bouncycastle.asn1.cms.CMSObjectIdentifiers` was moved to `org.bouncycastle.internal.asn1.cms.CMSObjectIdentifiers` in bc-prov and therefore we get the NoClassDefFoundException.
As @dghgit mentioned bc-util seems to include the class on it's old location.

So including bc-util may fix this issue (not tested yet)
