### ISSUE TITLE
External PSK support with TLS 1.3

### ISSUE THREAD

**Issue by sunnysingh85** [bcgit/bc-java#1524]
I'm trying to perform a TLS handshake between client and the server with TLS 1.3 using an externally supplied PSK. I'm on version 1.70. The server is currently rejecting usage of cipher suite TLS_PSK_WITH_AES_256_GCM_SHA384 as it looks like it's only [supported with TLS 1.2](https://github.com/bcgit/bc-java/blob/main/tls/src/main/java/org/bouncycastle/tls/TlsUtils.java#L2225-L2238). Are there any plans to support external PSK with TLS 1.3 on the server in the near future?

Exception seen on the server side:

```
Caused by: org.bouncycastle.tls.TlsFatalAlert: handshake_failure(40); No selectable cipher suite
	at org.bouncycastle.tls.AbstractTlsServer.getSelectedCipherSuite(AbstractTlsServer.java:443) ~[bctls-jdk15on-1.70.jar:1.70.00.0]
	at org.bouncycastle.tls.TlsServerProtocol.generate13ServerHello(TlsServerProtocol.java:284) ~[bctls-jdk15on-1.70.jar:1.70.00.0]
	at org.bouncycastle.tls.TlsServerProtocol.generateServerHello(TlsServerProtocol.java:518) ~[bctls-jdk15on-1.70.jar:1.70.00.0]
	at org.bouncycastle.tls.TlsServerProtocol.handleHandshakeMessage(TlsServerProtocol.java:1021) ~[bctls-jdk15on-1.70.jar:1.70.00.0]
	at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(TlsProtocol.java:708) ~[bctls-jdk15on-1.70.jar:1.70.00.0]
	at org.bouncycastle.tls.TlsProtocol.processRecord(TlsProtocol.java:584) ~[bctls-jdk15on-1.70.jar:1.70.00.0]
```

**Comment by peterdettman** [comment]
TLS 1.3 uses a different set of cipher suites from earlier versions (e.g. TLS_AES_128_GCM_SHA256) and at least one of those cipher suites must be offered by client (and server) in order to negotiate TLS 1.3. In particular there are no longer any PSK-specific cipher suites.

I suggest referring to the example in our tests:
https://github.com/bcgit/bc-java/blob/main/tls/src/test/java/org/bouncycastle/tls/test/Tls13PSKProtocolTest.java .
Pay particular attention to the PSK-related setup in `MockPSKTls13Client` and/or `MockPSKTls13Server`.

Of course I also recommend using the latest version of the library.

**Comment by winfriedgerlach** [comment]
Closing this as question seems to be answered to satisfaction.
