### ISSUE TITLE
BouncyCastle FIPS 1.0.2.4 giving error FipsUnapprovedOperationError: RSA PKCS1.5 encryption disallowed

### ISSUE THREAD

**Issue by Theres1998** [bcgit/bc-java#1529]
When we upgraded from bouncy castle fips version 1.0.2.3 to 1.0.2.4 and attempted to establish a connection to a PostgreSQL db in RDS over SSL, we started seeing a "Bouncy Castle FipsUnapprovedOperationError." This error is specifically related to the disallowance of RSA PKCS1.5 encryption and it's evident that the transition to version 1.0.2.4 has led to the disallowance of RSA PKCS1.5 encryption.
The error message  is as follows:

org.bouncycastle.crypto.fips.FipsUnapprovedOperationError: RSA PKCS1.5 encryption disallowed
	at org.bouncycastle.crypto.fips.FipsRSA$KeyWrapOperatorFactory$KeyWrapper.<init>(Unknown Source)
	at org.bouncycastle.crypto.fips.FipsRSA$KeyWrapOperatorFactory$KeyWrapper.withSecureRandom(Unknown Source)
	at org.bouncycastle.crypto.fips.FipsRSA$KeyWrapOperatorFactory$KeyWrapper.withSecureRandom(Unknown Source)
	at org.bouncycastle.jcajce.provider.Utils.addRandomIfNeeded(Unknown Source)
	at org.bouncycastle.jcajce.provider.BaseSingleBlockCipher.engineInit(Unknown Source)
	at org.bouncycastle.jcajce.provider.BaseSingleBlockCipher.engineInit(Unknown Source)
	at javax.crypto.Cipher.init(Cipher.java:1249)
	at org.bouncycastle.tls.crypto.impl.jcajce.JcaTlsRSAEncryptor.encrypt(JcaTlsRSAEncryptor.java:35)
	at org.bouncycastle.tls.crypto.impl.AbstractTlsSecret.encrypt(AbstractTlsSecret.java:67)
	at org.bouncycastle.tls.TlsUtils.generateEncryptedPreMasterSecret(TlsUtils.java:5871)
	at org.bouncycastle.tls.TlsRSAKeyExchange.generateClientKeyExchange(TlsRSAKeyExchange.java:72)
	at org.bouncycastle.tls.TlsClientProtocol.sendClientKeyExchange(TlsClientProtocol.java:1937)
	at org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(TlsClientProtocol.java:628)
	at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(TlsProtocol.java:711)
	at org.bouncycastle.tls.TlsProtocol.processRecord(TlsProtocol.java:587)
	at org.bouncycastle.tls.RecordStream.readRecord(RecordStream.java:245)
	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:875)
	at org.bouncycastle.tls.TlsProtocol.blockForHandshake(TlsProtocol.java:422)
	at org.bouncycastle.tls.TlsClientProtocol.connect(TlsClientProtocol.java:88)
	at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(ProvSSLSocketWrap.java:620)
	at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(ProvSSLSocketWrap.java:596)
	at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:41)
	at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:446)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:140)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:197)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:459)
	at org.postgresql.Driver.connect(Driver.java:261)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1176)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1163)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1908)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)

But we haven't explicitly specified the use of this algorithm in our code. The code relies on the ComboPooledDataSource with the following configuration: 
 ComboPooledDataSource comboPooledDataSource = new ComboPooledDataSource();
 comboPooledDataSource.setDriverClass("org.postgresql.Driver");
…

We are using com.mchange.c3p0:0.9.5.5 , org.postgresql:postgresql:42.5.1 

This issue cannot be replicated locally , only on aws .Any idea on this error?

**Comment by peterdettman** [comment]
You will need to configure the JDBC connection's SSL to not offer any cipher suites that use RSA key exchange (names like TLS_RSA_*), or better yet choose a specific set of cipher suites to offer.

[This page](https://jdbc.postgresql.org/documentation/ssl/) explains how to specify a custom SSLSocketFactory which should give the ability to intercept socket creation and control the enabled cipher suites.

It's also possible to use a system property "jdk.tls.client.cipherSuites", though this will affect your whole program.

**Comment by dghgit** [comment]
The release notes at https://www.bouncycastle.org/fips-java/RELEASE_NOTES.md also provide some additional information on this. Note that PKCS1.5 RSA encryption is disallowed after the end of this year though, originally this was a hard transition, hence the module disables it by default now, however even with the security property override available it would be best to move as far away from this one as you can. It wont be in anything released for FIPS 140-3.
