### ISSUE TITLE
junit.framework.ComparisonFailure: expected:<It's 1:12:00[ ]PM GMT at Aug 17, 20...> but was:<It's 1:12:00[ ]PM GMT at Aug 17, 20...>

### ISSUE THREAD

**Issue by vaukai** [bcgit/bc-java#1530]
With `Java 21` Gentoo gets a test failure:
```
There was 1 failure:
1) testGetEntry(org.bouncycastle.i18n.test.LocalizedMessageTest)
junit.framework.ComparisonFailure: expected:<It's 1:12:00[ ]PM GMT at Aug 17, 20...> but was:<It's 1:12:00[ ]PM GMT at Aug 17, 20...>
        at junit.framework.Assert.assertEquals(Assert.java:100)
        at junit.framework.Assert.assertEquals(Assert.java:107)
        at junit.framework.TestCase.assertEquals(TestCase.java:260)
        at org.bouncycastle.i18n.test.LocalizedMessageTest.testGetEntry(LocalizedMessageTest.java:61)

FAILURES!!!
Tests run: 276,  Failures: 1
```

The full build log, too long for posting here, is located at https://917070.bugs.gentoo.org/attachment.cgi?id=874350

**Comment by dghgit** [comment]
I've pushed an update for this one as well, should now be fixed.

**Comment by vaukai** [comment]
Thanks for fixing it.  Now using a `811c490` snapshot with old [test-data](https://github.com/bcgit/bc-test-data/archive/r1rv76.tar.gz) I get the following:
```
There were 2 failures:
1) testVectors(org.bouncycastle.pqc.crypto.test.CrystalsKyberTest)
junit.framework.AssertionFailedError: kyber512.rsp 0: secret key
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.Assert.assertTrue(Assert.java:22)
        at junit.framework.TestCase.assertTrue(TestCase.java:192)
        at org.bouncycastle.pqc.crypto.test.CrystalsKyberTest.testVectors(CrystalsKyberTest.java:202)
2) testVectors(org.bouncycastle.pqc.crypto.test.CrystalsDilithiumTest)
junit.framework.AssertionFailedError: PQCsignKAT_Dilithium2.rsp 0 secret key
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.Assert.assertTrue(Assert.java:22)
        at junit.framework.TestCase.assertTrue(TestCase.java:192)
        at org.bouncycastle.pqc.crypto.test.CrystalsDilithiumTest.testVectors(CrystalsDilithiumTest.java:141)

FAILURES!!!
Tests run: 277,  Failures: 2
```

**Comment by dghgit** [comment]
Yes, you'll need the latest test data now - both those algorithm changed on the publication of the drafts for FIPS PUB 203 and FIPS PUB 204. You'll find even the Interop certificates on the IETF website have updated as well now.

**Comment by vaukai** [comment]
Tested and works.
