### ISSUE TITLE
Different behavior of bc-fips 1.0.2.3 and 1.0.2.4 under Java 17

### ISSUE THREAD

**Issue by pavelnemirovsky** [bcgit/bc-java#1537]
Currently, we rely on bc-fips 1.0.2.3, and keystore conversion works great, but somehow, after upgrading to 1.0.2.4, it is no longer working. Any help is very much appreciated.
Thx

Notes: Bouncy Castle modules incorporated into Java Distribution using jlink" 

```
RUN /opt/jdk-${JAVA_VERSION_EXTENDED}.orig/bin/jlink --no-header-files --no-man-pages  --compress=2 --strip-debug  --module-path "/opt/jdk-${JAVA_VERSION_EXTENDED}.orig/lib/bc-fips-${BC_FIPS_VERSION}.jar:/opt/jdk-${JAVA_VERSION_EXTENDED}.orig/lib/bcpkix-fips-${BC_PKIX_VERSION}.jar:/opt/jdk-${JAVA_VERSION_EXTENDED}.orig/lib/bctls-fips-${BC_TLS_VERSION}.jar"  --add-modules java.base,java.compiler,java.datatransfer,java.desktop,java.instrument,java.logging,java.management,java.management.rmi,java.naming,java.net.http,java.prefs,java.rmi,java.scripting,java.se,java.security.jgss,java.security.sasl,java.smartcardio,java.sql,java.sql.rowset,java.transaction.xa,java.xml,java.xml.crypto,jdk.accessibility,jdk.attach,jdk.charsets,jdk.compiler,jdk.crypto.cryptoki,jdk.crypto.ec,jdk.dynalink,jdk.editpad,jdk.hotspot.agent,jdk.httpserver,jdk.incubator.foreign,jdk.incubator.vector,jdk.internal.ed,jdk.internal.jvmstat,jdk.internal.le,jdk.internal.opt,jdk.internal.vm.ci,jdk.internal.vm.compiler,jdk.internal.vm.compiler.management,jdk.jartool,jdk.javadoc,jdk.jcmd,jdk.jconsole,jdk.jdeps,jdk.jdi,jdk.jdwp.agent,jdk.jfr,jdk.jlink,jdk.jpackage,jdk.jshell,jdk.jsobject,jdk.jstatd,jdk.localedata,jdk.management,jdk.management.agent,jdk.management.jfr,jdk.naming.dns,jdk.naming.rmi,jdk.net,jdk.nio.mapmode,jdk.random,jdk.sctp,jdk.security.auth,jdk.security.jgss,jdk.unsupported,jdk.unsupported.desktop,jdk.xml.dom,jdk.zipfs,org.bouncycastle.fips.core,org.bouncycastle.fips.tls --output /opt/jdk-${JAVA_VERSION_EXTENDED}/ --ignore-signing-information
```

```#15 [11/18] RUN rm /opt/jdk-17.0.9/lib/security/cacerts
#15 DONE 0.7s

#16 [12/18] RUN keytool -importkeystore -srckeystore /opt/jdk-17.0.9/lib/security/cacerts.orig -srcstoretype JKS -destkeystore /opt/jdk-17.0.9/lib/security/cacerts -deststoretype BCFKS -deststorepass changeit -srcstorepass changeit
#16 0.781 Importing keystore /opt/jdk-17.0.9/lib/security/cacerts.orig to /opt/jdk-17.0.9/lib/security/cacerts...
#16 1.486 Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.bouncycastle.crypto.CryptoServicesRegistrar
#16 1.487 	at org.bouncycastle.fips.core/org.bouncycastle.jcajce.provider.ProvSecureHash$MD5.configure(Unknown Source)
#16 1.488 	at org.bouncycastle.fips.core/org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
#16 1.488 	at org.bouncycastle.fips.core/org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
#16 1.488 	at org.bouncycastle.fips.core/org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
#16 1.488 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
#16 1.488 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
#16 1.488 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
#16 1.488 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
#16 1.488 	at java.base/java.lang.reflect.ReflectAccess.newInstance(Unknown Source)
#16 1.488 	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(Unknown Source)
#16 1.488 	at java.base/java.lang.Class.newInstance(Unknown Source)
#16 1.488 	at org.bouncycastle.fips.tls/org.bouncycastle.jsse.provider.BouncyCastleJsseProvider.createCryptoProvider(Unknown Source)
#16 1.488 	at org.bouncycastle.fips.tls/org.bouncycastle.jsse.provider.BouncyCastleJsseProvider.<init>(Unknown Source)
#16 1.488 	at org.bouncycastle.fips.tls/org.bouncycastle.jsse.provider.BouncyCastleJsseProvider.configure(Unknown Source)
#16 1.488 	at java.base/sun.security.jca.ProviderConfig$3.run(Unknown Source)
#16 1.488 	at java.base/sun.security.jca.ProviderConfig$3.run(Unknown Source)
#16 1.488 	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
#16 1.488 	at java.base/sun.security.jca.ProviderConfig.doLoadProvider(Unknown Source)
#16 1.488 	at java.base/sun.security.jca.ProviderConfig.getProvider(Unknown Source)
#16 1.488 	at java.base/sun.security.jca.ProviderList.getProvider(Unknown Source)
#16 1.488 	at java.base/sun.security.jca.ProviderList.getService(Unknown Source)
#16 1.488 	at java.base/sun.security.jca.GetInstance.getInstance(Unknown Source)
#16 1.488 	at java.base/java.security.Security.getImpl(Unknown Source)
#16 1.488 	at java.base/java.security.KeyStore.getInstance(Unknown Source)
#16 1.488 	at java.base/sun.security.tools.keytool.Main.doCommands(Unknown Source)
#16 1.489 	at java.base/sun.security.tools.keytool.Main.run(Unknown Source)
#16 1.489 	at java.base/sun.security.tools.keytool.Main.main(Unknown Source)
#16 1.489 Caused by: java.lang.ExceptionInInitializerError: Exception org.bouncycastle.crypto.fips.FipsOperationError: Module checksum failed: unable to calculate [in thread "main"]
#16 1.489 	at org.bouncycastle.fips.core/org.bouncycastle.crypto.fips.FipsStatus.checksumValidate(Unknown Source)
#16 1.489 	at org.bouncycastle.fips.core/org.bouncycastle.crypto.fips.FipsStatus.isReady(Unknown Source)
#16 1.489 	at org.bouncycastle.fips.core/org.bouncycastle.crypto.CryptoServicesRegistrar.getDefaultMode(Unknown Source)
#16 1.489 	at org.bouncycastle.fips.core/org.bouncycastle.crypto.CryptoServicesRegistrar.<clinit>(Unknown Source)
#16 1.489 	at org.bouncycastle.fips.core/org.bouncycastle.jcajce.provider.ProvSecureHash$MD5.configure(Unknown Source)
#16 1.489 	at org.bouncycastle.fips.core/org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
#16 1.489 	at org.bouncycastle.fips.core/org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
#16 1.489 	at org.bouncycastle.fips.core/org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
#16 1.489 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
#16 1.489 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
#16 1.489 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
#16 1.489 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
#16 1.489 	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
#16 1.489 	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(Unknown Source)
#16 1.489 	at java.base/java.util.ServiceLoader$ProviderImpl.get(Unknown Source)
#16 1.489 	at java.base/java.util.ServiceLoader$3.next(Unknown Source)
#16 1.489 	at java.base/sun.security.jca.ProviderConfig$ProviderLoader.load(Unknown Source)
#16 1.489 	... 13 more
#16 ERROR: process "/bin/sh -c keytool -importkeystore -srckeystore /opt/jdk-${JAVA_VERSION_EXTENDED}/lib/security/cacerts.orig -srcstoret
```

**java security:**

```
security.provider.1=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider C:HYBRID;ENABLE{All};
security.provider.2=org.bouncycastle.jsse.provider.BouncyCastleJsseProvider fips:org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider
security.provider.3=SUN
security.provider.4=SunRsaSign
security.provider.5=SunEC
security.provider.6=SunJSSE
security.provider.7=SunJCE
security.provider.8=SunJGSS
security.provider.9=SunSASL
security.provider.10=XMLDSig
security.provider.11=SunPCSC
security.provider.12=JdkLDAP
security.provider.13=JdkSASL
security.provider.14=SunPKCS11
securerandom.source=file:/dev/random
securerandom.strongAlgorithms=NativePRNGBlocking:SUN,DRBG:SUN
securerandom.drbg.config=
login.configuration.provider=sun.security.provider.ConfigFile
policy.provider=sun.security.provider.PolicyFile
policy.url.1=file:${java.home}/conf/security/java.policy
policy.url.2=file:${user.home}/.java.policy
policy.expandProperties=true
policy.allowSystemProperty=true
policy.ignoreIdentityScope=false
keystore.type=BCFKS
keystore.type.compat=true
package.access=sun.misc.,\
               sun.reflect.,\
               org.GNOME.Accessibility.,\
               org.GNOME.Bonobo.
package.definition=sun.misc.,\
                   sun.reflect.,\
                   org.GNOME.Accessibility.,\
                   org.GNOME.Bonobo.
security.overridePropertiesFile=true
security.useSystemPropertiesFile=true
ssl.KeyManagerFactory.algorithm=SunX509
ssl.TrustManagerFactory.algorithm=PKIX
networkaddress.cache.negative.ttl=10
krb5.kdc.bad.policy = tryLast
sun.security.krb5.disableReferrals=false
sun.security.krb5.maxReferrals=5
jdk.disabled.namedCurves = secp256k1
jdk.certpath.disabledAlgorithms=MD2, MD5, SHA1 jdkCA & usage TLSServer, \
    RSA keySize < 1024, DSA keySize < 1024, EC keySize < 224, \
    SHA1 usage SignedJAR & denyAfter 2019-01-01, \
    include jdk.disabled.namedCurves
jdk.security.legacyAlgorithms=SHA1, \
    RSA keySize < 2048, DSA keySize < 2048
jdk.jar.disabledAlgorithms=MD2, MD5, RSA keySize < 1024, \
      DSA keySize < 1024, SHA1 denyAfter 2019-01-01, \
      include jdk.disabled.namedCurves
jdk.tls.disabledAlgorithms=SSLv3, RC4, DES, MD5withRSA, \
    DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL, \
    include jdk.disabled.namedCurves
jdk.tls.legacyAlgorithms= \
        K_NULL, C_NULL, M_NULL, \
        DH_anon, ECDH_anon, \
        RC4_128, RC4_40, DES_CBC, DES40_CBC, \
        3DES_EDE_CBC
jdk.tls.keyLimits=AES/GCM/NoPadding KeyUpdate 2^37, \
                  ChaCha20-Poly1305 KeyUpdate 2^37
crypto.policy=unlimited
jdk.xml.dsig.secureValidationPolicy=\
    disallowAlg http://www.w3.org/TR/1999/REC-xslt-19991116,\
    maxTransforms 5,\
    maxReferences 30,\
    disallowReferenceUriSchemes file http https,\
    minKeySize RSA 1024,\
    minKeySize DSA 1024,\
    minKeySize EC 224,\
    noDuplicateIds,\
    noRetrievalMethodLoops
jceks.key.serialFilter = java.base/java.lang.Enum;java.base/java.security.KeyRep;\
  java.base/java.security.KeyRep$Type;java.base/javax.crypto.spec.SecretKeySpec;!*
jdk.sasl.disabledMechanisms=
jdk.security.caDistrustPolicies=SYMANTEC_TLS
jdk.io.permissionsUseCanonicalPath=false
jdk.tls.alpnCharset=ISO_8859_1
```

**Comment by dghgit** [comment]
I'm sorry, but it's not possible to use the FIPS provider with jlink at the moment due to the way it repackages the jar. It wasn't actually possible to use 1.0.2.3 either, however due to a bug, now fixed, it used to appear to work.

**Comment by pavelnemirovsky** [comment]
@dghgit thank you. Is 1.0.2.3 properly working with jlink due to some Java bug? Could you tell me the suggested workaround to make it properly work without using jlink?

**Comment by dghgit** [comment]
1.0.2.3 is not working. Unfortunately, it just looks like its working - the module isn't correctly validating its checksum so it is not compliant. If you check the calculated checksum it will come back as a string of zeros, very not FIPS compliant. We have raised the issue with Oracle, but I gather it's very difficult to fix at the moment.

**Comment by pavelnemirovsky** [comment]
@dghgit OMG, since functionality-wise everything works great, I'm so sad to hear that. The only alternative way is to include Bouncy Castle jars in classpath and invoke specific classes while we use keystore, etc.

**Comment by dghgit** [comment]
Yep. Sorry, but until the Oracle side work out what to do, that's where we are at.

**Comment by cuzic4n** [comment]
Any new update on this issue? Ran into same exact scenario.

**Comment by dghgit** [comment]
No. Sorry, but until the Oracle side work out what to do, that's where we are at. Please note, it is most definitely not FIPS compliant to use any version of the bc-fips jars with jlink.

**Comment by chicodeme** [comment]
Is there a github issue on openjdk or some oracle system that you could point me to.. then, I could go help raise some attention to it? Ty 4 your prompt responses and your time.

**Comment by cuzic4n** [comment]
Is there a github issue on openjdk or some oracle system that you could point me to.. then, I could go help raise some attention to it? Ty 4 your prompt responses and your time.
