### ISSUE TITLE
bc-fips and SpringBoot 3.2 compatibility issue

### ISSUE THREAD

**Issue by x41dev** [bcgit/bc-java#1538]
Hello Team

After upgrading my project to SpringBoot 3.2  app is not starting with an error:
**FipsOperationError: Module checksum failed: unable to find**

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
  at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
  at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
Caused by: org.bouncycastle.crypto.fips.FipsOperationError: Module checksum failed: unable to find
  at org.bouncycastle.crypto.fips.FipsStatus.checksumValidate(Unknown Source)
  at org.bouncycastle.crypto.CryptoServicesRegistrar.getDefaultMode(Unknown Source)
  at org.bouncycastle.crypto.CryptoServicesRegistrar.<clinit>(Unknown Source)
  at org.bouncycastle.jcajce.provider.ProvSecureHash$MD5.configure(Unknown Source)
  at org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider.<init>(Unknown Source)
```
BC Provider is added during app startup
`
Security.insertProviderAt(new BouncyCastleFipsProvider(), 1);
`
  
  After some analysis I found a root cause
  - SB 3.2 introduced [Nested Jar Support](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#nested-jar-support) which changes URL format:
  ```
The previous URL format of jar:file:/dir/myjar.jar:BOOT-INF/lib/nested.jar!/com/example/MyClass.class has been replaced with jar:nested:/dir/myjar.jar/!BOOT-INF/lib/nested.jar!/com/example/MyClass.class
```
- org.bouncycastle.crypto.fips.FipsStatus#getResourceName has hardcoded `marker.startsWith("jar:file:") && marker.contains("!/")` so method returns null to the caller org.bouncycastle.crypto.fips.FipsStatus#checksumValidate and mentioned exception is raised

**workaround**:
use SB loader fallback option 
- gradle:
```
bootJar {
  loaderImplementation = org.springframework.boot.loader.tools.LoaderImplementation.CLASSIC
}
```
- maven
```
<build>
  <plugins>
    <plugin>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>repackage</goal>
            </goals>
            <configuration>
              <loaderImplementation>CLASSIC</loaderImplementation>
            </configuration>
          </execution>
        </executions>
    </plugin>
  </plugins>
</build>
```

**Comment by dghgit** [comment]
The bc-fips jars can't be tampered with or repackaged. This indicates one of those things has probably happened.

**Comment by x41dev** [comment]
In this case I repackage my app because I want to create fat jar with all dependencies inside. bc-fips jar is untouched under
my-app.jar!/BOOT-INF/lib/bc-fips-1.0.2.4.jar

org.bouncycastle.crypto.fips.FipsStatus#getMarker returns:
- `jar:file:my-app.jar!/BOOT-INF/lib/bc-fips-1.0.2.4.jar!/` - in SB3.1.x
- `jar:nested:my-app.jar/!BOOT-INF/lib/bc-fips-1.0.2.4.jar!/` - in SB3.2.0

to be more specific: 
LICENSE.class.getProtectionDomain() **.getCodeSource()** uses new Springboot's classloader and returns this 'nested' substring'

**IMO possible fix:**
adding:
```
else if (marker.startsWith("jar:nested:") && marker.contains("!/")){
  try{
    String jarFilename = URLDecoder.decode(marker.substring("jar:nested:".length(), marker.lastIndexOf("!/")), "UTF-8");
    result = jarFilename;
  }
  catch (IOException e){
    result = null;
  }
}
```
to org.bouncycastle.crypto.fips.FipsStatus#getResourceName should fix the problem without regression

**Comment by dghgit** [comment]
Ah, is that what's going on. Yes, we should be able to do that. It's likely to take a while though, I'm pretty sure a change like this would be regarded as what they call a 1SUB, but it's still going to take months to get it approved.

**Comment by nibexo** [comment]
@dghgit 
Looks like I have the same problem in my project
Any update with this issue?

**Comment by dghgit** [comment]
We're going through the process. It will take months to be done though.

**Comment by nibexo** [comment]
@x41dev  
Looks like for me works unpack BC 
```
bootJar {
  requiresUnpack('**/bc-fips-*.jar', '**/bctls-fips-*.jar')
}
```

**Comment by jaymz1439** [comment]
any updates about this issue? @dghgit

**Comment by kranthirathikanti** [comment]
@dghgit 

Hi, it also needs to handle marker.startsWith("vfs:") as all jboss / wildfly refers its classpath modules / libraries with vfs as protocol.

I hope your team will include this change as well.

**Comment by skfazil** [comment]
Hey @dghgit , Good day!

I see this conversation is still open, and we are facing similar issue while trying to upgrade to SB 3.2. Is there any solution defined yet. If not, any ETA's that is discussed at the moment?

Please do let us know.

**Comment by dghgit** [comment]
1.0.2.5 is now available on Maven Central and the BC website. Note: certification is still in progress for this module, however we believe it should fix this issue.

**Comment by arysin** [comment]
It looks like 1.0.2.5 helped same exception I saw with SpringBoot 3.2

**Comment by dghgit** [comment]
Just a further note to this - the 1.0.2.4 cert has hit it's sunset date so the 1.0.2.5 certification has been stopped. It should be still be regarded as a patch release on 1.0.2.4 though.

**Comment by xnox** [comment]
bc-fips 2.0.0 has been certified, does bc-fips 2.0 work? with any springboot versions?

**Comment by dghgit** [comment]
You need to use the workaround given at the start. It should work with that.

**Comment by oridool** [comment]
> bc-fips 2.0.0 has been certified, does bc-fips 2.0 work? with any springboot versions?

We are using 2.0.0 and issue still exists.
The solution is simple. You need to add the following to your bootJar task:
```
bootJar {
    // https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#nested-jar-support
    loaderImplementation = org.springframework.boot.loader.tools.LoaderImplementation.CLASSIC
}
```

**Comment by YanivKunda** [comment]
I found a more pinpoint workaround here:
https://motorcycleguy.blogspot.com/2024/05/running-bcfips-in-springboot-32.html

It involves using the `spring-boot-maven-plugin`'s capability to unpack specific artifact jars at runtime to a temp directory, which result in a very ordinary URL.
I added the following to the `spring-boot-maven-plugin` configuration:
```
                        <requiresUnpack>
                            <dependency>
                                <groupId>org.bouncycastle</groupId>
                                <artifactId>bc-fips</artifactId>
                            </dependency>
                            <dependency>
                                <groupId>org.bouncycastle</groupId>
                                <artifactId>bcjmail-fips</artifactId>
                            </dependency>
                            <dependency>
                                <groupId>org.bouncycastle</groupId>
                                <artifactId>bcmail-fips</artifactId>
                            </dependency>
                            <dependency>
                                <groupId>org.bouncycastle</groupId>
                                <artifactId>bcpg-fips</artifactId>
                            </dependency>
                            <dependency>
                                <groupId>org.bouncycastle</groupId>
                                <artifactId>bcpkix-fips</artifactId>
                            </dependency>
                            <dependency>
                                <groupId>org.bouncycastle</groupId>
                                <artifactId>bctls-fips</artifactId>
                            </dependency>
                            <dependency>
                                <groupId>org.bouncycastle</groupId>
                                <artifactId>bcutil-fips</artifactId>
                            </dependency>
                        </requiresUnpack>
```

**Comment by xnox** [comment]
> I found a more pinpoint workaround here: https://motorcycleguy.blogspot.com/2024/05/running-bcfips-in-springboot-32.html
> 
> It involves using the `spring-boot-maven-plugin`'s capability to unpack specific artifact jars at runtime to a temp directory, which result in a very ordinary URL. I added the following to the `spring-boot-maven-plugin` configuration:
> 
> ```
>     <requiresUnpack>
>         <dependency>
>             <groupId>org.bouncycastle</groupId>
>             <artifactId>bc-fips</artifactId>
>         </dependency>
>         <dependency>
>             <groupId>org.bouncycastle</groupId>
>             <artifactId>bcjmail-fips</artifactId>
>         </dependency>
>         <dependency>
>             <groupId>org.bouncycastle</groupId>
>             <artifactId>bcmail-fips</artifactId>
>         </dependency>
>         <dependency>
>             <groupId>org.bouncycastle</groupId>
>             <artifactId>bcpg-fips</artifactId>
>         </dependency>
>         <dependency>
>             <groupId>org.bouncycastle</groupId>
>             <artifactId>bcpkix-fips</artifactId>
>         </dependency>
>         <dependency>
>             <groupId>org.bouncycastle</groupId>
>             <artifactId>bctls-fips</artifactId>
>         </dependency>
>         <dependency>
>             <groupId>org.bouncycastle</groupId>
>             <artifactId>bcutil-fips</artifactId>
>         </dependency>
>     </requiresUnpack>
> ```
> 
> This doesn't force you to fallback to the classic loader.

how do things look like on disk / at runtime? are signatures of jars present? are you able to run with `org.bouncycastle.fips.approved_only=true` property set? and does self-test pass?

I was under impression that unpacking jars broke that, if that all works, it is great news!

**Comment by YanivKunda** [comment]
> > I found a more pinpoint workaround here: https://motorcycleguy.blogspot.com/2024/05/running-bcfips-in-springboot-32.html
> > It involves using the `spring-boot-maven-plugin`'s capability to unpack specific artifact jars at runtime to a temp directory, which result in a very ordinary URL. I added the following to the `spring-boot-maven-plugin` configuration:
> > ```
> >     <requiresUnpack>
> >         <dependency>
> >             <groupId>org.bouncycastle</groupId>
> >             <artifactId>bc-fips</artifactId>
> >         </dependency>
> >         <dependency>
> >             <groupId>org.bouncycastle</groupId>
> >             <artifactId>bcjmail-fips</artifactId>
> >         </dependency>
> >         <dependency>
> >             <groupId>org.bouncycastle</groupId>
> >             <artifactId>bcmail-fips</artifactId>
> >         </dependency>
> >         <dependency>
> >             <groupId>org.bouncycastle</groupId>
> >             <artifactId>bcpg-fips</artifactId>
> >         </dependency>
> >         <dependency>
> >             <groupId>org.bouncycastle</groupId>
> >             <artifactId>bcpkix-fips</artifactId>
> >         </dependency>
> >         <dependency>
> >             <groupId>org.bouncycastle</groupId>
> >             <artifactId>bctls-fips</artifactId>
> >         </dependency>
> >         <dependency>
> >             <groupId>org.bouncycastle</groupId>
> >             <artifactId>bcutil-fips</artifactId>
> >         </dependency>
> >     </requiresUnpack>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This doesn't force you to fallback to the classic loader.
> 
> how do things look like on disk / at runtime? are signatures of jars present? are you able to run with `org.bouncycastle.fips.approved_only=true` property set? and does self-test pass?
> 
> I was under impression that unpacking jars broke that, if that all works, it is great news!

I initially also thought it wouldn't work, but in this context "unpacking" means extracting the original dependency jars from the spring-boot uber-jar as-is - and since they are tampered neither when packed into the uber-jar nor when unpacked from it, the signatures remain valid.
They are stored in a temp folder - for example, this is from a container running a flow involving the bc lib:
```
sh-5.1# ls -l /tmp/starlord-app.jar-spring-boot-libs-1faa5c51-1faa-4d18-9836-145bfe3b3863
total 6188
-rw-r--r-- 1 root root 4095679 Dec 17 07:51 bc-fips-2.0.0.jar
-rw-r--r-- 1 root root 1527113 Dec 17 07:51 bctls-fips-2.0.19.jar
-rw-r--r-- 1 root root  710650 Dec 17 07:51 bcutil-fips-2.0.3.jar
```

**Comment by YanivKunda** [comment]
Comparing the computed sha1 signatures of the jars extracted on the container -
```
sh-5.1# sha1sum /tmp/starlord-app.jar-spring-boot-libs-1faa5c51-1faa-4d18-9836-145bfe3b3863/*
ee9ac432cf08f9a9ebee35d7cf8a45f94959a7ab  /tmp/starlord-app.jar-spring-boot-libs-1faa5c51-1faa-4d18-9836-145bfe3b3863/bc-fips-2.0.0.jar
9cc33650ede63bc1a8281ed5c8e1da314d50bc76  /tmp/starlord-app.jar-spring-boot-libs-1faa5c51-1faa-4d18-9836-145bfe3b3863/bctls-fips-2.0.19.jar
a1857cd639295b10cc90e6d31ecbc523cdafcc19  /tmp/starlord-app.jar-spring-boot-libs-1faa5c51-1faa-4d18-9836-145bfe3b3863/bcutil-fips-2.0.3.jar
```
with the ones in maven central -
```
➜  ~ curl https://repo1.maven.org/maven2/org/bouncycastle/bc-fips/2.0.0/bc-fips-2.0.0.jar.sha1
ee9ac432cf08f9a9ebee35d7cf8a45f94959a7ab%                                                                                                                                            ➜  ~ curl https://repo1.maven.org/maven2/org/bouncycastle/bctls-fips/2.0.19/bctls-fips-2.0.19.jar.sha1
9cc33650ede63bc1a8281ed5c8e1da314d50bc76%                                                                                                                                            ➜  ~ curl https://repo1.maven.org/maven2/org/bouncycastle/bcutil-fips/2.0.3/bcutil-fips-2.0.3.jar.sha1
a1857cd639295b10cc90e6d31ecbc523cdafcc19%
```
shows this process preserves the signatures.

**Comment by xnox** [comment]
> "unpacking" means extracting the original dependency jars from the spring-boot uber-jar as-is - and since they are tampered neither when packed into the uber-jar nor when unpacked from it, the signatures remain valid.

oh that's nice, I should document this somewhere.
