### ISSUE TITLE
use of cleared weak reference in provider OcspCache

### ISSUE THREAD

**Issue by dghgit** [bcgit/bc-java#1541]
<div role="document" tabindex="-1" aria-label="Message body" class="XbIp4 jmmB7 GNqVo yxtKT allowTextSelection OuGoX" id="UniqueMessageBody"><div><div>
<div>
  | You don't often get email from felix.dorner@gmail.com. Learn why this is important |  
-- | -- | --

<div>
<div style="color:black;font-size:10pt;font-family:Calibri;text-align:left;background-color:#FFEB9C;width:100%;padding:2pt;border:1pt solid #9C6500;line-height:12pt;"><span style="color:#9C6500;font-weight:bold;">CAUTION:</span>
 External Sender - Be cautious when clicking links or opening 
attachments. Please email InfoSec@keyfactor.com with any questions.</div><br aria-hidden="true">
<div>
<div dir="ltr">Hi,  
<div><br aria-hidden="true">
</div>
<div>I hit the NPE below with OCSP validation using these BC libs:</div>
<div><br aria-hidden="true">
</div>
<div> +--- org.bouncycastle:bcpkix-jdk15on:1.70<br aria-hidden="true">
|    |    +--- org.bouncycastle:bcprov-jdk15on:1.70<br aria-hidden="true">
|    |    \--- org.bouncycastle:bcutil-jdk15on:1.70<br aria-hidden="true">
|    |         \--- org.bouncycastle:bcprov-jdk15on:1.70<br aria-hidden="true">
|    +--- org.bouncycastle:bcprov-jdk15on:1.70<br aria-hidden="true">
</div>
<div><br aria-hidden="true">
</div>
<div>The exception does not happen reproducibly, it's rather intermittent:</div>
<div><br aria-hidden="true">
</div>
<div>at java.base/java.lang.Thread.run(Thread.java:833) Caused by: 
java.lang.NullPointerException: Cannot invoke "java.util.Map.put(Object,
 Object)" because "&lt;local6&gt;" is null<br aria-hidden="true">
at org.bouncycastle.jce.provider.OcspCache.getOcspResponse(Unknown Source)<br aria-hidden="true">
at org.bouncycastle.jce.provider.ProvOcspRevocationChecker.check(Unknown Source)<br aria-hidden="true">
at org.bouncycastle.jce.provider.ProvRevocationChecker.check(Unknown Source)<br aria-hidden="true">
at java.base/java.security.cert.PKIXCertPathChecker.check(PKIXCertPathChecker.java:176)<br aria-hidden="true">
at org.bouncycastle.jce.provider.RFC3280CertPathUtilities.processCertA(Unknown Source)<br aria-hidden="true">
at org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi_8.engineValidate(Unknown Source)<br aria-hidden="true">
at org.bouncycastle.jce.provider.PKIXCertPathBuilderSpi_8.build(Unknown Source) ... 86 common frames omitted<br aria-hidden="true">
<div><br aria-hidden="true">
</div>
<div>I will replace the dependency with the debug artefacts to get info 
about line numbers, but maybe someone on this list has seen this before 
and can advise.</div></div></div></div></div></div></div></div></div>You don't often get email from felix.dorner@gmail.com. [Learn why this is important](https://aka.ms/LearnAboutSenderIdentification)
	
CAUTION: External Sender - Be cautious when clicking links or opening attachments. Please email InfoSec@keyfactor.com with any questions.

Hi, 

I hit the NPE below with OCSP validation using these BC libs:

 +--- org.bouncycastle:bcpkix-jdk15on:1.70
|    |    +--- org.bouncycastle:bcprov-jdk15on:1.70
|    |    \--- org.bouncycastle:bcutil-jdk15on:1.70
|    |         \--- org.bouncycastle:bcprov-jdk15on:1.70
|    +--- org.bouncycastle:bcprov-jdk15on:1.70

The exception does not happen reproducibly, it's rather intermittent:

at java.base/java.lang.Thread.run(Thread.java:833) Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.put(Object, Object)" because "<local6>" is null
at org.bouncycastle.jce.provider.OcspCache.getOcspResponse(Unknown Source)
at org.bouncycastle.jce.provider.ProvOcspRevocationChecker.check(Unknown Source)
at org.bouncycastle.jce.provider.ProvRevocationChecker.check(Unknown Source)
at java.base/java.security.cert.PKIXCertPathChecker.check(PKIXCertPathChecker.java:176)
at org.bouncycastle.jce.provider.RFC3280CertPathUtilities.processCertA(Unknown Source)
at org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi_8.engineValidate(Unknown Source)
at org.bouncycastle.jce.provider.PKIXCertPathBuilderSpi_8.build(Unknown Source) ... 86 common frames omitted

I will replace the dependency with the debug artefacts to get info about line numbers, but maybe someone on this list has seen this before and can advise.

From:Eckenfels. Bernd <B.Eckenfels@seeburger.de>

I bet it’s the weak reference here:

[https://github.com/bcgit/bc-java/blob/5c35c9a5e79648d7fdf85d7cbaffe8169f249443/prov/src/main/java/org/bouncycastle/jce/provider/OcspCache.java#L199C32-L199C32](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbcgit%2Fbc-java%2Fblob%2F5c35c9a5e79648d7fdf85d7cbaffe8169f249443%2Fprov%2Fsrc%2Fmain%2Fjava%2Forg%2Fbouncycastle%2Fjce%2Fprovider%2FOcspCache.java%23L199C32-L199C32&data=05%7C01%7CDavid.Hook%40keyfactor.com%7C927debb2c5404b0ba95808dbf189766f%7Cc9ed4b459f70418aaa58f04c80848ca9%7C0%7C0%7C638369344955296662%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NmrMzTglUuSqY%2F8W0EwQhvSfRwFy9GZhXmcJszGzt2E%3D&reserved=0)

 responseMap = markerRef.get();

 responseMap.put(certID, response);

**Comment by dghgit** [comment]
More excitement than I've had in a while, but I'm pleased to say the site is back. Let me know how you go.

**Comment by felixdo** [comment]
https://github.com/bcgit/bc-java/issues/1548 is blocking me from upgrading.

**Comment by dghgit** [comment]
@felixdo have you confirmed the latest beta fixes the issue?

**Comment by felixdo** [comment]
@dghgit as commented above I can't even try because of #1548

**Comment by dghgit** [comment]
@felixdo #1548 has been fixed as part of this.

**Comment by felixdo** [comment]
@dghgit It's on my list to test this, but can't say when.

**Comment by dghgit** [comment]
Fixed in 1.78.
