### ISSUE TITLE
PBKDF-OpenSSL SecretKeyFactory not available since 1.53 release.

### ISSUE THREAD

**Issue by MonkeyLeeT** [bcgit/bc-java#156]
Hey all, I'm reposting an issue that appears since 1.53 releases: https://github.com/box/box-java-sdk/issues/168, and here http://bouncy-castle.1462172.n4.nabble.com/Issues-when-migrating-to-1-53-td4657955.html.

I wonder if there's any plan to resolve it so that people like me don't need to resort to 1.52 for development. Thanks a lot.

**Comment by bcgit** [comment]
Are you able to provide an example where it's happening with either 1.54 or 1.55? The secret key factory is definitely there.

**Comment by MonkeyLeeT** [comment]
Thanks for the update. Here's the snippet.

```
JcaPEMKeyConverter converter = new JcaPEMKeyConverter().setProvider("BC");  
PEMDecryptorProvider decryptionProvider = new JcePEMDecryptorProviderBuilder().build("key".toCharArray());  
PEMKeyPair decryptedKeyPair = ((PEMEncryptedKeyPair) object).decryptKeyPair(decryptionProvider);
```

**Comment by bcgit** [comment]
stacktrace?

**Comment by MonkeyLeeT** [comment]
Caused by: org.bouncycastle.openssl.PEMException: Unable to create OpenSSL PBDKF: PBKDF-OpenSSL SecretKeyFactory not available
	at org.bouncycastle.openssl.jcajce.PEMUtilities.getKey(Unknown Source)
	at org.bouncycastle.openssl.jcajce.PEMUtilities.crypt(Unknown Source)
	at org.bouncycastle.openssl.jcajce.JcePEMDecryptorProviderBuilder$1$1.decrypt(Unknown Source)
	at org.bouncycastle.openssl.PEMEncryptedKeyPair.decryptKeyPair(Unknown Source)
	at xxxxxxxxxxxxxx.<init>(xxxxxx.java:44)
	... 28 more
Caused by: java.security.NoSuchAlgorithmException: PBKDF-OpenSSL SecretKeyFactory not available
	at javax.crypto.SecretKeyFactory.<init>(SecretKeyFactory.java:122)
	at javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:160)
	at org.bouncycastle.jcajce.util.DefaultJcaJceHelper.createSecretKeyFactory(Unknown Source)
	... 33 more

**Comment by bcgit** [comment]
Yep, it's not using the BC provider - you have to configure it to use BC. The DefaultJcaJceHelper does exactly what it says, it uses the default provider mechanism. You will not see this stack trace if you have called setProvider("BC");

**Comment by MonkeyLeeT** [comment]
@bcgit Thanks for the heads up. However as you can see from my code snippet above, I did call  setProvider("BC") and I was getting those struck trace with it.

**Comment by bcgit** [comment]
The stack trace shows: org.bouncycastle.jcajce.util.DefaultJcaJceHelper.createSecretKeyFactory() You might have called setProvider("BC") but someone else hasn't.

**Comment by jitubaba10** [comment]
I have added Security.addProvider(new BouncyCastleProvider()); before above code and working fine for me.
