### ISSUE TITLE
Out of memory when using CipherInputStream

### ISSUE THREAD

**Issue by freedom1b2830** [bcgit/bc-java#1568]
I thought that CipherInputStream encrypts and returns a byte array when Inputstream::read is called.
But that the cipher accumulates data in ByteArrayOutputStream during this action
```java
import static java.nio.file.Files.newInputStream;
import static java.nio.file.Files.newOutputStream;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.security.InvalidAlgorithmParameterException;
import java.security.InvalidKeyException;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.SecureRandom;
import java.security.spec.ECGenParameterSpec;

import javax.crypto.Cipher;
import javax.crypto.CipherInputStream;
import javax.crypto.NoSuchPaddingException;

import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.bouncycastle.jce.spec.IEKeySpec;
import org.bouncycastle.jce.spec.IESParameterSpec;

/**
 *
 */
public class EncryptionsDemo {
	/**
	 *
	 */
	private static final String FILE_PREFIX = "alive-crypto-EncryptionsDemo";

	private static final BouncyCastleProvider provider = new BouncyCastleProvider();

	private static String keyName = "secp521r1";
	private static String cryptAlgo = "ECIES/None/NoPadding";
	private static int MAC_KEY_SIZE_BITS = 256;

	private static void createFilledFile(final Path pathIn) throws IOException {
		if (Files.size(pathIn) == 0) {
			var countbytes = 2 * 1024 * 1024 * 1024L;// 8G
			final SecureRandom random = new SecureRandom();
			final var bufferWrite = new byte[10_000];
			System.err.println(countbytes);
			try (var os = newOutputStream(pathIn)) {
				while (countbytes > 0) {
					random.nextBytes(bufferWrite);
					os.write(bufferWrite);
					countbytes = countbytes - bufferWrite.length;
				}
			}
			System.err.println(countbytes);
		}
	}

	private static void encryptFile(final KeyPair sender, final KeyPair reciver, final Path pathIn,
			final Path pathEncrypted) throws IOException {
		try (var is = newInputStream(pathIn)) {
			if (is == null) {
				throw new NoSuchFileException(pathIn.toString());
			}
			try (var encryptedIS = encryptStream(sender.getPrivate(), reciver.getPublic(), is);
					var out = newOutputStream(pathEncrypted);) {
				final var bufferWrite = new byte[10_000];
				while (true) {
					final var readed = encryptedIS.read(bufferWrite);
					if (readed == -1) {
						break;
					}
					out.write(bufferWrite, 0, readed);
				}
			}
		}
	}

	public static InputStream encryptStream(final PrivateKey sender, final PublicKey reciver,
			final InputStream inputStream) {

		final var encrypter = getEncoder(sender, reciver);
		return new CipherInputStream(inputStream, encrypter);
	}

	public static KeyPair genPair() {
		try {
			final var generator = KeyPairGenerator.getInstance("ECDH", provider);
			generator.initialize(new ECGenParameterSpec(keyName));
			return generator.generateKeyPair();
		} catch (InvalidAlgorithmParameterException | NoSuchAlgorithmException e) {
			throw new SecurityException(e);
		}
	}

	public static Cipher getDecoder(final PrivateKey recipientPrivateKey, final PublicKey senderPublicKey) {
		try {
			final var iesCipher2 = Cipher.getInstance(cryptAlgo, provider);
			final IESParameterSpec param = new IESParameterSpec(null, null, MAC_KEY_SIZE_BITS);
			iesCipher2.init(Cipher.DECRYPT_MODE, new IEKeySpec(recipientPrivateKey, senderPublicKey), param);
			return iesCipher2;
		} catch (InvalidAlgorithmParameterException | InvalidKeyException | NoSuchAlgorithmException
				| NoSuchPaddingException e) {
			throw new SecurityException(e);
		}
	}

	public static Cipher getEncoder(final PrivateKey senderPrivateKey, final PublicKey recipientPublicKey) {
		try {
			final var iesCipher = Cipher.getInstance(cryptAlgo, provider);
			final IESParameterSpec param = new IESParameterSpec(null, null, MAC_KEY_SIZE_BITS);
			iesCipher.init(Cipher.ENCRYPT_MODE, new IEKeySpec(senderPrivateKey, recipientPublicKey), param);
			return iesCipher;
		} catch (InvalidAlgorithmParameterException | InvalidKeyException | NoSuchAlgorithmException
				| NoSuchPaddingException e) {
			throw new SecurityException(e);
		}
	}

	public static void main(final String[] args) throws IOException {
		final var tmpFileInput = File.createTempFile(FILE_PREFIX, "input");
		final var tmpFileOut = File.createTempFile(FILE_PREFIX, "encrypted");
		final var tmpFileDecrypted = File.createTempFile(FILE_PREFIX, "decrypted");
		final var pathInput = tmpFileInput.toPath();
		final var pathEncrypted = tmpFileOut.toPath();
		final var pathDecrypted = tmpFileDecrypted.toPath();

		try {
			createFilledFile(pathInput);

			final var sender = genPair();
			final var reciver = genPair();

			encryptFile(sender, reciver, pathInput, pathEncrypted);
		} catch (final Throwable e) {
			e.printStackTrace();
		}
		Files.deleteIfExists(pathInput);
		Files.deleteIfExists(pathEncrypted);
		Files.deleteIfExists(pathDecrypted);
	}

}
```
```
2147483648
-6352
java.lang.OutOfMemoryError: Required array length 2147483639 + 9 is too large
	at java.base/jdk.internal.util.ArraysSupport.hugeLength(ArraysSupport.java:752)
	at java.base/jdk.internal.util.ArraysSupport.newLength(ArraysSupport.java:745)
	at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:100)
	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:132)
	at org.bouncycastle.provider/org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher.engineUpdate(Unknown Source)
	at java.base/javax.crypto.Cipher.update(Cipher.java:1908)
	at java.base/javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:175)
	at java.base/javax.crypto.CipherInputStream.read(CipherInputStream.java:281)
	at java.base/javax.crypto.CipherInputStream.read(CipherInputStream.java:257)
	at bouncycastle.dos/alive.crypto.demo.EncryptionsDemo.encryptFile(EncryptionsDemo.java:75)
	at bouncycastle.dos/alive.crypto.demo.EncryptionsDemo.main(EncryptionsDemo.java:140)
	Suppressed: java.lang.OutOfMemoryError: Java heap space
		at java.base/java.util.Arrays.copyOf(Arrays.java:3541)
		at java.base/java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:187)
		at org.bouncycastle.provider/org.bouncycastle.jcajce.provider.asymmetric.ec.IESCipher.engineDoFinal(Unknown Source)
		at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2125)
		at java.base/javax.crypto.CipherInputStream.close(CipherInputStream.java:368)
		at bouncycastle.dos/alive.crypto.demo.EncryptionsDemo.encryptFile(EncryptionsDemo.java:81)
		... 1 more

```

**Comment by dghgit** [comment]
Sorry, CipherInputStream is not a BC class.
