### ISSUE TITLE
PQC tests fail - missing files

### ISSUE THREAD

**Issue by mouse07410** [bcgit/bc-java#1606]
Current `main` branch, JDK-21, MacOS Sonoma 14.4 (probably irrelevant):
```text
$ uname -a
Darwin xxxxxxxx 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:45:49 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6020 arm64
$ java -version
openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Zulu21.32+17-CA (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Zulu21.32+17-CA (build 21.0.2+13-LTS, mixed mode, sharing)
```

Here are the errors.

In `textDecodingAndVerificationExternal`:
```text
/Users/ur20980/src/bc-test-data/pqc/composite/compositeSignatures.sample (No such file or directory)

java.io.FileNotFoundException: /Users/ur20980/src/bc-test-data/pqc/composite/compositeSignatures.sample (No such file or directory)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
at org.bouncycastle.test.TestResourceFinder.findTestResource(TestResourceFinder.java:37)
at org.bouncycastle.jcajce.provider.test.CompositeSignaturesTest.testDecodingAndVerificationExternal(CompositeSignaturesTest.java:177)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)
at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
at junit.extensions.TestSetup.run(TestSetup.java:27)
```

and `testPQCgenKAT_kem`:
```text
/Users/ur20980/src/bc-test-data/pqc/crypto/ntru/ntruhps40961229/PQCkemKAT_2366.rsp (No such file or directory)

java.io.FileNotFoundException: /Users/ur20980/src/bc-test-data/pqc/crypto/ntru/ntruhps40961229/PQCkemKAT_2366.rsp (No such file or directory)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
at org.bouncycastle.test.TestResourceFinder.findTestResource(TestResourceFinder.java:37)
at org.bouncycastle.pqc.crypto.test.NTRUTest.testPQCgenKAT_kem(NTRUTest.java:88)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)
at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
at junit.extensions.TestSetup.run(TestSetup.java:27)
```

**Comment by dghgit** [comment]
These should now be present.
