### ISSUE TITLE
Tests broken again

### ISSUE THREAD

**Issue by mouse07410** [bcgit/bc-java#1609]
```text
.  .  .
build-test:
     [copy] Copying 3 files to /Users/ur20980/src/bc-java/build/artifacts/jdk1.8/bctest-jdk18on-178/src
   [delete] Deleting: /Users/ur20980/src/bc-java/build/artifacts/jdk1.8/bctest-jdk18on-178/src/org/bouncycastle/pqc/crypto/lms/AllTests.java
   [delete] Deleting: /Users/ur20980/src/bc-java/build/artifacts/jdk1.8/bctest-jdk18on-178/src/org/bouncycastle/x509/CertPathReviewerMessages_de.properties
   [delete] Deleting: /Users/ur20980/src/bc-java/build/artifacts/jdk1.8/bctest-jdk18on-178/src/org/bouncycastle/x509/CertPathReviewerMessages.properties
    [javac] /Users/ur20980/src/bc-java/ant/bc+-build.xml:164: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 537 source files to /Users/ur20980/src/bc-java/build/bctest-jdk18on-178/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 8
    [javac] warning: [options] source value 8 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 8 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] /Users/ur20980/src/bc-java/build/artifacts/jdk1.8/bctest-jdk18on-178/src/org/bouncycastle/gpg/keybox/AllTests.java:20: error: cannot find symbol
    [javac]         org.bouncycastle.util.test.Test[] tests = RegressionTest.tests;
    [javac]                                                   ^
    [javac]   symbol:   variable RegressionTest
    [javac]   location: class AllTests
    [javac] /Users/ur20980/src/bc-java/build/artifacts/jdk1.8/bctest-jdk18on-178/src/org/bouncycastle/i18n/test/LocalizedMessageTest.java:87: warning: [removal] Float(float) in Float has been deprecated and marked for removal
    [javac]         args = new Object[] { new TrustedInput(new Float(0.2f))  };
    [javac]                                                ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error
    [javac] 5 warnings

BUILD FAILED
```

I don't know who's responsible for making self-consistent updates, but to me breaking published builds or tests every one or two weeks seems abnormal.

**Comment by dghgit** [comment]
The class is there, as far as I can tell.

**Comment by dghgit** [comment]
The updated ant script should be appearing shortly.

**Comment by mouse07410** [comment]
@dghgit Thank you - the updated script is there now. And it unmasked another problem:
```text
[junit] Test org.bouncycastle.gpg.keybox.AllTests FAILED
.  .  .
org.bouncycastle.gpg.keybox.KeyBoxByteBufferTest KeyBoxBuffer: Exception: java.lang.SecurityException: class "org.bouncycastle.gpg.keybox.KeyBoxByteBuffer"'s signer information does not match signer information of other classes in the same package

junit.framework.AssertionFailedError: org.bouncycastle.gpg.keybox.KeyBoxByteBufferTest KeyBoxBuffer: Exception: java.lang.SecurityException: class "org.bouncycastle.gpg.keybox.KeyBoxByteBuffer"'s signer information does not match signer information of other classes in the same package
at org.bouncycastle.gpg.keybox.AllTests.testPGP(AllTests.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)
at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
at junit.extensions.TestSetup.run(TestSetup.java:27)
```
