### ISSUE TITLE
testPGP fails - wrong signer (???)

### ISSUE THREAD

**Issue by mouse07410** [bcgit/bc-java#1610]
```text
org.bouncycastle.gpg.keybox.KeyBoxByteBufferTest KeyBoxBuffer: Exception: java.lang.SecurityException: class "org.bouncycastle.gpg.keybox.KeyBoxByteBuffer"'s signer information does not match signer information of other classes in the same package

junit.framework.AssertionFailedError: org.bouncycastle.gpg.keybox.KeyBoxByteBufferTest KeyBoxBuffer: Exception: java.lang.SecurityException: class "org.bouncycastle.gpg.keybox.KeyBoxByteBuffer"'s signer information does not match signer information of other classes in the same package
at org.bouncycastle.gpg.keybox.AllTests.testPGP(AllTests.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)
at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
at junit.extensions.TestSetup.run(TestSetup.java:27)
```

What signature is this about? Does it look like a pilot error...?

**Comment by mouse07410** [comment]
Appears to be a pilot error - Oracle-issued JCE-signing certificate expired. :-(

And it looks like for Azul and Corretto JCE provider doesn't have to be signed.
