### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space with 1.78

### ISSUE THREAD

**Issue by theangrydev** [bcgit/bc-java#1626]
I haven't been able to narrow this down yet or create a small reproducer, but I see this java.lang.OutOfMemoryError only when using 1.78 not 1.77.

Seemingly unrelated stack trace, not clear on why 1.78 might be causing this but I am able to reproduce this consistently in my CI build.

```
16:32:44   [INFO] Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
16:32:44   [INFO]   at java.base/java.util.ArrayList.iterator(ArrayList.java:977)
16:32:44   [INFO]   at java.base/java.io.InputStream.readNBytes(InputStream.java:432)
16:32:44   [INFO]   at java.base/java.io.InputStream.readAllBytes(InputStream.java:333)
16:32:44   [INFO]   at java.base/java.util.jar.JarFile.getBytes(JarFile.java:824)
16:32:44   [INFO]   at java.base/java.util.jar.JarFile.checkForSpecialAttributes(JarFile.java:1022)
16:32:44   [INFO]   at java.base/java.util.jar.JarFile.isMultiRelease(JarFile.java:390)
16:32:44   [INFO]   at java.base/java.util.jar.JarFile.getEntry(JarFile.java:515)
16:32:44   [INFO]   at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:476)
16:32:44   [INFO]   at java.base/jdk.internal.util.jar.JarIndex.getJarIndex(JarIndex.java:118)
16:32:44   [INFO]   at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:760)
16:32:44   [INFO]   at java.base/jdk.internal.loader.URLClassPath$JarLoader$1.run(URLClassPath.java:752)
16:32:44   [INFO]   at java.base/java.security.AccessController.doPrivileged(Native Method)
16:32:44   [INFO]   at java.base/jdk.internal.loader.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:751)
16:32:44   [INFO]   at java.base/jdk.internal.loader.URLClassPath$JarLoader.<init>(URLClassPath.java:726)
16:32:44   [INFO]   at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:494)
16:32:44   [INFO]   at java.base/jdk.internal.loader.URLClassPath$3.run(URLClassPath.java:477)
16:32:44   [INFO]   at java.base/java.security.AccessController.doPrivileged(Native Method)
16:32:44   [INFO]   at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:476)
16:32:44   [INFO]   at java.base/jdk.internal.loader.URLClassPath.getLoader(URLClassPath.java:445)
16:32:44   [INFO]   at java.base/jdk.internal.loader.URLClassPath.getResource(URLClassPath.java:314)
16:32:44   [INFO]   at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:695)
16:32:44   [INFO]   at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
16:32:44   [INFO]   at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
16:32:44   [INFO]   at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
16:32:44   [INFO]   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
16:32:44   [INFO]   at java.base/java.lang.Class.forName0(Native Method)
16:32:44   [INFO]   at java.base/java.lang.Class.forName(Class.java:315)
```

I am using:
```
org.bouncycastle:bcprov-jdk18on
org.bouncycastle:bcpkix-jdk18on
org.bouncycastle:bcutil-jdk18on
```

**Comment by dghgit** [comment]
Can't say we've seen that. The new bcprov does have multi-release support for the KEM APIs in it now, it's possible something MR related is actually causing an out of memory. What's the current limit? Have you tried increasing it?

**Comment by theangrydev** [comment]
I was seeing it with an app that is usually fine with -Xmx128m and I still saw it when increasing to -Xmx256m. It reproduces for me on Linux but not Mac or Windows. Using Java 8, Temurin latest builds. Happens immediately on startup. It's possible it's a red herring and the version bump is triggering another totally unrelated issue somehow.

I'll update this if/when I get the time to confirm some more details. For now I just downgraded to 1.77.

**Comment by theangrydev** [comment]
@dghgit this was a red herring, bc-java not at fault
