### ISSUE TITLE
version 1.78.1：java.lang.ClassNotFoundException: org.bouncycastle.asn1.oiw.OIWObjectIdentifiers

### ISSUE THREAD

**Issue by zukunftChan** [bcgit/bc-java#1638]
After I upgraded to version 1.78.1, my project gave me this error:

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: java.lang.NoClassDefFoundError: org/bouncycastle/asn1/oiw/OIWObjectIdentifiers
        at org.bouncycastle.openssl.MiscPEMGenerator.<clinit>(Unknown Source)
        at org.bouncycastle.openssl.jcajce.JcaPEMWriter.writeObject(Unknown Source)
        at org.bouncycastle.openssl.jcajce.JcaPEMWriter.writeObject(Unknown Source)
        at xxx
        ... 8 more
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.asn1.oiw.OIWObjectIdentifiers
        at java.net.URLClassLoader.findClass(URLClassLoader.java:407)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 14 more

**Comment by dghgit** [comment]
It sounds like the bcutil jar is missing from the class path.

**Comment by dghgit** [comment]
Assumed dealt with.

**Comment by StonyBrookReus** [comment]
Hi @dghgit , is this issue fixed? Still get this error with version 1.78 and 1.78.1

**Comment by dghgit** [comment]
Are you including the bcutil jar?

**Comment by StonyBrookReus** [comment]
No. Is there a guide?

**Comment by dghgit** [comment]
For adding a jar to the classpath?

**Comment by StonyBrookReus** [comment]
Oh I was looking for the correct place to download bcutil jar... Let me find out and try it. Thanks

**Comment by Deepak07111997** [comment]
Thanks @dghgit , After adding a jar, for me the issue has been resoled,
