### ISSUE TITLE
ASN1ObjectIdentifier.createPrimitive fails to instantiate a CMSSignedData starting from 1.78 

### ISSUE THREAD

**Issue by bsanchezb** [bcgit/bc-java#1639]
Hello,

We have a problem with validation of some signatures and timestamps after the commit https://github.com/bcgit/bc-java/commit/3790993df5d28f661a64439a8664343437ed3865, in particular after introduction of the _!ASN1RelativeOID.isValidContents_ condition in the _ASN1ObjectIdentifier.createPrimitive_ method:
```
    static ASN1ObjectIdentifier createPrimitive(byte[] contents, boolean clone)
    {
        checkContentsLength(contents.length);
        
        final OidHandle hdl = new OidHandle(contents);
        ASN1ObjectIdentifier oid = pool.get(hdl);
        if (oid != null)
        {
            return oid;
        }

        if (!ASN1RelativeOID.isValidContents(contents))
        {
            throw new IllegalArgumentException("invalid OID contents");
        }

        return new ASN1ObjectIdentifier(clone ? Arrays.clone(contents) : contents, null);
    }
```

The problem is BouncyCastle not being able to build a _CMSSignedData_ when having a signature or a timestamp with an invalid _ASN1ObjectIdentifier's_ content.

This is critical for us, as it blocks validation of some legacy signatures, as well as failure on _new CMSSignedData(InputStream)_ call makes it impossible to provide any relevant data about nature of the issue to the end-user:
```
Caused by: org.bouncycastle.cms.CMSException: IOException reading content.
	at org.bouncycastle.cms.CMSUtils.readContentInfo(Unknown Source)
	at org.bouncycastle.cms.CMSUtils.readContentInfo(Unknown Source)
	at org.bouncycastle.cms.CMSSignedData.<init>(Unknown Source)
	... 61 more
Caused by: org.bouncycastle.asn1.ASN1Exception: invalid OID contents
	at org.bouncycastle.asn1.ASN1InputStream.createPrimitiveDERObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.parseImplicitPrimitive(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.implParseObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DLSequenceParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DLSetParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DLSequenceParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.loadTaggedDL(Unknown Source)
	at org.bouncycastle.asn1.DLTaggedObjectParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DLSequenceParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DLSetParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.BERSequenceParser.parse(Unknown Source)
	at org.bouncycastle.asn1.BERSequenceParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.loadTaggedIL(Unknown Source)
	at org.bouncycastle.asn1.BERTaggedObjectParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.BERSequenceParser.parse(Unknown Source)
	at org.bouncycastle.asn1.ASN1InputStream.readObject(Unknown Source)
	... 65 more
Caused by: java.lang.IllegalArgumentException: invalid OID contents
	at org.bouncycastle.asn1.ASN1ObjectIdentifier.createPrimitive(Unknown Source)
	... 90 more
```

We would prefer to have an exception on extraction of particular data, but failure on CMSSignedData instantiation is a breaking change for us.

Thank you.

**Comment by bsanchezb** [comment]
Test file:
[bc1639test.zip](https://github.com/bcgit/bc-java/files/15093236/bc1639test.zip)

Unit test:
```
        File signatureFile = new File("bc1639test.p7m");

        try (InputStream is = Files.newInputStream(signatureFile.toPath())) {
             CMSSignedData cmsSignedData = new CMSSignedData(is);
        }
```

**Comment by dghgit** [comment]
Oh dear. I can't say I've ever heard of someone messing up the encoding of an OID, but I guess there's always a first time. So are you asking for a different exception or that the check be disabled? As far as specific exceptions go, the ASN1Exception is really pointing out the data stream is invalid - I'm not sure we can be more specific than that.

**Comment by peterdettman** [comment]
@bsanchezb For existing data, couldn't you re-encode it using old BC? I assume you are worried that would break a signature/timestamp but have you checked that assumption?

**Comment by dghgit** [comment]
I think the only way we can deal with this is to introduce a system property, which isn't great... I'll look into it.

**Comment by dghgit** [comment]
So the problem OID is here:
```
Sequence
      ObjectIdentifier(1.2.840.113549.1.9.16.2.4)
      Set
        Sequence
              UTF8String(please ignore this attribute) 
              ObjectIdentifier()
```

This has to be deliberate... the level of stupidity it would require to do it by accident beggars belief. I've extended the property I added for #1758 to cover this case as well.
