### ISSUE TITLE
AES/CBC/WITHCTS Need at least one block of input for CTS

### ISSUE THREAD

**Issue by trohsb** [bcgit/bc-java#1649]
Hi,
I'm performing encryption and dectryption with AES/CBC/WITHCTS. If the data is less than 16 bytes, a block, then I get the following error:

`javax.crypto.IllegalBlockSizeException: need at least one block of input for CTS
        at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source) ~[bcprov-jdk15on-1.69.jar!/:1.69.0]
        at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2417) ~[na:na]
`

[Wikipedia](https://en.wikipedia.org/wiki/Ciphertext_stealing) says:

_Ciphertext stealing for [CBC](https://en.wikipedia.org/wiki/Cipher_block_chaining) mode doesn't necessarily require the plaintext to be longer than one [block](https://en.wikipedia.org/wiki/Block_size_(cryptography)). In the case where the plaintext is one block long or less, the [Initialization vector](https://en.wikipedia.org/wiki/Initialization_vector) (IV) can act as the prior block of ciphertext. In this case a modified IV must be sent to the receiver. This may not be possible in situations where the IV can not be freely chosen by the sender when the ciphertext is sent (e.g., when the IV is a derived or pre-established value), and in this case ciphertext stealing for CBC mode can only occur in plaintexts longer than one block._

Are there any examples on how todo that?

**Comment by dghgit** [comment]
So, the wikipedia entry is talking about adding an additional IV which is inlined with the cipher text (in other words for short data add a block of random data to the front of it and then remove it at the other end). The usual convention is that IVs are not inlined. To support this you would need to do the in-lining for all message sizes though, not just short ones.
