### ISSUE TITLE
TlsPSKProtocolTest fails with TLS_PSK_WITH_NULL_SHA256

### ISSUE THREAD

**Issue by afarber** [bcgit/bc-java#166]
When I modify the 2 files:

core/src/test/java/org/bouncycastle/crypto/tls/test/MockPSKTlsClient.java
core/src/test/java/org/bouncycastle/crypto/tls/test/MockPSKTlsServer.java

by changing the getCipherSuites method to:

```
    protected int[] getCipherSuites()
    {
        return new int[]{  CipherSuite.TLS_PSK_WITH_NULL_SHA256 };
    }
```

And run "gradle.bat :core:test", then TlsPSKProtocolTest fails:

```
:core:compileJava UP-TO-DATE
:core:processResources UP-TO-DATE
:core:classes UP-TO-DATE
:core:instrument SKIPPED
:core:copyCoberturaDatafile SKIPPED
:core:compileTestJava
warning: [options] bootstrap class path not set in conjunction with -source 1.5
warning: [options] source value 1.5 is obsolete and will be removed in a future release
warning: [options] target value 1.5 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 warnings
:core:processTestResources UP-TO-DATE
:core:testClasses
:core:test

org.bouncycastle.crypto.tls.test.AllTests > org.bouncycastle.crypto.tls.test.TlsPSKProtocolTest.testClientServer FAILED
    java.io.IOException at TlsPSKProtocolTest.java:34
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8, 1 failed

135 tests completed, 1 failed
:core:test FAILED
:core:generateCoberturaReport SKIPPED
:core:performCoverageCheck SKIPPED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:test'.
> There were failing tests. See the report at: bc-java/core/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3 mins 32.873 secs
```

The reported exception is:

```
java.io.IOException: Internal TLS error, this could be an attack
	at org.bouncycastle.crypto.tls.TlsProtocol.processAlert(TlsProtocol.java:406)
	at org.bouncycastle.crypto.tls.TlsProtocol.processRecord(TlsProtocol.java:259)
	at org.bouncycastle.crypto.tls.RecordStream.readRecord(RecordStream.java:174)
	at org.bouncycastle.crypto.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:519)
	at org.bouncycastle.crypto.tls.TlsProtocol.blockForHandshake(TlsProtocol.java:191)
	at org.bouncycastle.crypto.tls.TlsClientProtocol.connect(TlsClientProtocol.java:107)
	at org.bouncycastle.crypto.tls.test.TlsPSKProtocolTest.testClientServer(TlsPSKProtocolTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:23)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.extensions.TestSetup.run(TestSetup.java:27)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I am using gradle 2.14.1, java 1.8 on Windows 7.

Is TLS_PSK_WITH_NULL_SHA256 cipher not supported yet, why does the test fail please?

**Comment by afarber** [comment]
I've created a JIRA issue at http://www.bouncycastle.org/jira/browse/BJB-62

**Comment by peterdettman** [comment]
There was a problem recognising the cipher type for NULL encryption, now fixed.

As a workaround until the next release, just make sure the encrypt-then-MAC extension is not offered (see MockPSKTlsClient.getClientExtensions() method), or if you are running a server you can override AbstractTlsServer.allowEncryptThenMAC() to return false.

Thanks for the report.
