### ISSUE TITLE
TLS fatal alert bad_certificate(42) - empty extension sequence found

### ISSUE THREAD

**Issue by mondain** [bcgit/bc-java#1661]
Posting here even though I don't know which library is at-fault in this case. Using version 1.78 on my server, I get this error when an application like OBS connects for WHIP publishing. It would seem that an empty extension sequence should be allowed to proceed, unless I'm misunderstanding what that actually consists of in the grand scheme of DTLS 1.2 handshaking. I'm open to a solution on my end or a workaround to allow libdatachannel clients to work once again.

```
WARN BCDtlsControlImpl - Connect exception
org.bouncycastle.tls.TlsFatalAlert: bad_certificate(42)
	at org.bouncycastle.tls.crypto.impl.bc.BcTlsCertificate.parseCertificate(Unknown Source)
	at org.bouncycastle.tls.crypto.impl.bc.BcTlsCertificate.<init>(Unknown Source)
	at org.bouncycastle.tls.crypto.impl.bc.BcTlsCrypto.createCertificate(Unknown Source)
	at org.bouncycastle.tls.Certificate.parse(Unknown Source)
	at org.bouncycastle.tls.TlsUtils.receiveServerCertificate(Unknown Source)
	at org.bouncycastle.tls.DTLSClientProtocol.processServerCertificate(Unknown Source)
	at org.bouncycastle.tls.DTLSClientProtocol.clientHandshake(Unknown Source)
	at org.bouncycastle.tls.DTLSClientProtocol.connect(Unknown Source)
	at BCDtlsControlImpl.lambda$start$0(BCDtlsControlImpl.java:254)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: empty extension sequence found
	at org.bouncycastle.asn1.x509.Extensions.<init>(Unknown Source)
	at org.bouncycastle.asn1.x509.Extensions.getInstance(Unknown Source)
	at org.bouncycastle.asn1.x509.TBSCertificate.<init>(Unknown Source)
	at org.bouncycastle.asn1.x509.TBSCertificate.getInstance(Unknown Source)
	at org.bouncycastle.asn1.x509.Certificate.<init>(Unknown Source)
	at org.bouncycastle.asn1.x509.Certificate.getInstance(Unknown Source)
	... 14 common frames omitted
```

Issue posted to libdatachannel: https://github.com/paullouisageneau/libdatachannel/issues/1182

**Comment by peterdettman** [comment]
The empty extension check was removed in 1.78.1.
