### ISSUE TITLE
When gradle `plugin` transitive dependency: Unsupported class file major version 65

### ISSUE THREAD

**Issue by gabrieljones** [bcgit/bc-java#1697]
Running gradle with JDK17.

When`bcprov-jdk18on-1.78.1` is a transitive dependency of a gradle project everything is fine.

When `bcprov-jdk18on-1.78.1` is a transitive dependency of a gradle `plugin` the build chokes during configuration with:

```
org.gradle.api.GradleException: Failed to create Jar file ~/.gradle/caches/jars-9/73e6eaeec66f5f8587038cf8343282d5/bcprov-jdk18on-1.78.1.jar.
        at org.gradle.internal.classpath.ClasspathBuilder.jar(ClasspathBuilder.java:57)
        at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.instrument(InstrumentingClasspathFileTransformer.java:190)
        at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.transform(InstrumentingClasspathFileTransformer.java:182)
        at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.transform(InstrumentingClasspathFileTransformer.java:149)
        at org.gradle.internal.classpath.DefaultCachedClasspathTransformer.transformFile(DefaultCachedClasspathTransformer.java:239)
        at org.gradle.internal.classpath.DefaultCachedClasspathTransformer.lambda$cachedFile$9(DefaultCachedClasspathTransformer.java:232)
        at org.gradle.internal.UncheckedException.unchecked(UncheckedException.java:74)
        at org.gradle.internal.classpath.DefaultCachedClasspathTransformer.lambda$transformAll$11(DefaultCachedClasspathTransformer.java:279)
        ... 2 more
Caused by: java.io.IOException: Failed to process the entry 'META-INF/versions/21/org/bouncycastle/pqc/jcajce/provider/NTRU$Mappings.class' from '~/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk18on/1.78.1/39e9e45359e20998eb79c1828751f94a818d25f8/bcprov-jdk18on-1.78.1.jar'
        at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.lambda$visitEntries$1(InstrumentingClasspathFileTransformer.java:222)
        at org.gradle.internal.classpath.ClasspathWalker.visitJarContents(ClasspathWalker.java:91)
        at org.gradle.internal.classpath.ClasspathWalker.visit(ClasspathWalker.java:55)
        at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.visitEntries(InstrumentingClasspathFileTransformer.java:201)
        at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.lambda$instrument$0(InstrumentingClasspathFileTransformer.java:192)
        at org.gradle.internal.classpath.ClasspathBuilder.buildJar(ClasspathBuilder.java:68)
        at org.gradle.internal.classpath.ClasspathBuilder.jar(ClasspathBuilder.java:55)
        ... 9 more
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 65
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.gradle.internal.classpath.InstrumentingClasspathFileTransformer.lambda$visitEntries$1(InstrumentingClasspathFileTransformer.java:207)
```

```
> ./gradlew -version

------------------------------------------------------------
Gradle 8.1
------------------------------------------------------------

Build time:   2023-04-12 12:07:45 UTC
Revision:     40ba32cde9d6daf2b92c39376d2758909dd6b813

Kotlin:       1.8.10
Groovy:       3.0.15
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.11 (Eclipse Adoptium 17.0.11+9)
OS:           Mac OS X 14.4.1 aarch64
```

**Comment by gabrieljones** [comment]
Looks like this was fixed in more recent versions of gradle. If anyone know the exact gradle PR that fixed it, please link it here.
