### ISSUE TITLE
SocketException: Socket is closed with DTLSTestServer and Client

### ISSUE THREAD

**Issue by jython234** [bcgit/bc-java#170]
Running the DTLSTestServer and Client programs with the provided keys results in the server crashing due to a SocketException.

Server output:
```
Accepting connection from 10.107.50.100:5556
DTLS server received client certificate chain of length 2
    fingerprint:SHA-256 F5:DD:37:DF:9B:E7:DA:87:7C:6C:D6:61:5A:61:18:AE:B3:6A:A3:3A:B4:5B:33:53:05:4A:7B:FC:B9:D5:A7:DA (CN=BouncyCastle Test Client)
    fingerprint:SHA-256 F2:B0:0A:FB:DC:2F:36:FF:60:52:AC:26:C8:E6:1A:89:92:77:9B:F4:1C:9D:A0:4C:25:58:3D:35:A5:C1:DC:C0 (CN=BouncyCastle TLS Test CA)
Exception in thread "main" DTLS server received alert: warning(1), close_notify(0)
DTLS server raised alert: warning(1), close_notify(0)
java.net.SocketException: Socket is closed
	at java.net.DatagramSocket.setSoTimeout(DatagramSocket.java:901)
	at org.bouncycastle.crypto.tls.UDPTransport.receive(Unknown Source)
	at org.bouncycastle.crypto.tls.DTLSRecordLayer.receiveRecord(Unknown Source)
	at org.bouncycastle.crypto.tls.DTLSRecordLayer.receive(Unknown Source)
	at org.bouncycastle.crypto.tls.DTLSTransport.receive(Unknown Source)
	at Server.main(Server.java:52)
```

Client output:
```
Negotiated DTLS 1.2
DTLS client received server certificate chain of length 2
    fingerprint:SHA-256 D4:25:89:8B:69:5E:19:B3:E3:81:F0:4E:B7:C6:1C:E5:3B:AB:B8:06:97:A2:E8:BB:35:BF:D1:CC:19:66:55:84 (CN=BouncyCastle Test Server)
    fingerprint:SHA-256 F2:B0:0A:FB:DC:2F:36:FF:60:52:AC:26:C8:E6:1A:89:92:77:9B:F4:1C:9D:A0:4C:25:58:3D:35:A5:C1:DC:C0 (CN=BouncyCastle TLS Test CA)
DTLS client raised alert: warning(1), close_notify(0)
```

While the bouncycastle client can't connect to the bouncycastle server, each work fine with their openssl server/client counterpart. That means the openssl client can connect to the DTLSServerTest fine and the DTLSClientTest can connect to the openssl server fine.

I've also tried using my own generated keys which results in the same.

Any ideas?

**Comment by Schekamatik** [comment]
Hello,

did you find the answer or any solution for this issue?

BR
Eugen

**Comment by jython234** [comment]
I did not. I just gave up on DTLS in general because it seems like no one
uses it.

**Comment by Schekamatik** [comment]
Do you know why can help me with this issue?
I am working on the Secure UDP connection and therefore i need DTLS.

Thank You
 Eugen

**Comment by H21lab** [comment]
Does anyone find some solution for this?
I have tested the latest maven repository bcprov-jdk15on 1.59 on linux and get the same issue.

**Comment by peterdettman** [comment]
The close_notify alerts indicate the client connected to the server and then disconnected. Both client and server exit for me (with expected socket-related exceptions) on latest code, although we did have problems getting clean exits from DTLS tests in years gone by.
