### ISSUE TITLE
DTLS implementation

### ISSUE THREAD

**Issue by Nishant-Pathak** [bcgit/bc-java#172]
Thanks Bouncy Castle for the awesome work and making things secure.
Currently I am working on reliable UDP (Mocket) and looking for some help in adding secure layer on top of UDP ( DTLS ), Something similar to your DTLS implementation. https://github.com/Nishant-Pathak/mocket/issues/3 . 

Please give your valuable suggestion.

**Comment by Schekamatik** [comment]
Hello,

do you know where i can find a working DTLS Client Server Example based on bouncy castle API?
Because I get this issue during the runtime.

Server output:

Accepting connection from 10.107.50.100:5556
DTLS server received client certificate chain of length 2
    fingerprint:SHA-256 F5:DD:37:DF:9B:E7:DA:87:7C:6C:D6:61:5A:61:18:AE:B3:6A:A3:3A:B4:5B:33:53:05:4A:7B:FC:B9:D5:A7:DA (CN=BouncyCastle Test Client)
    fingerprint:SHA-256 F2:B0:0A:FB:DC:2F:36:FF:60:52:AC:26:C8:E6:1A:89:92:77:9B:F4:1C:9D:A0:4C:25:58:3D:35:A5:C1:DC:C0 (CN=BouncyCastle TLS Test CA)
Exception in thread "main" DTLS server received alert: warning(1), close_notify(0)
DTLS server raised alert: warning(1), close_notify(0)
java.net.SocketException: Socket is closed
	at java.net.DatagramSocket.setSoTimeout(DatagramSocket.java:901)
	at org.bouncycastle.crypto.tls.UDPTransport.receive(Unknown Source)
	at org.bouncycastle.crypto.tls.DTLSRecordLayer.receiveRecord(Unknown Source)
	at org.bouncycastle.crypto.tls.DTLSRecordLayer.receive(Unknown Source)
	at org.bouncycastle.crypto.tls.DTLSTransport.receive(Unknown Source)
	at Server.main(Server.java:52)

Client output:

Negotiated DTLS 1.2
DTLS client received server certificate chain of length 2
    fingerprint:SHA-256 D4:25:89:8B:69:5E:19:B3:E3:81:F0:4E:B7:C6:1C:E5:3B:AB:B8:06:97:A2:E8:BB:35:BF:D1:CC:19:66:55:84 (CN=BouncyCastle Test Server)
    fingerprint:SHA-256 F2:B0:0A:FB:DC:2F:36:FF:60:52:AC:26:C8:E6:1A:89:92:77:9B:F4:1C:9D:A0:4C:25:58:3D:35:A5:C1:DC:C0 (CN=BouncyCastle TLS Test CA)
DTLS client raised alert: warning(1), close_notify(0)

BR
Eugen

**Comment by richdrich** [comment]
If anyone's interested, I worked out the problem which stops the `DTLSServerTest` and `DTLSClienttest` examples from talking to each other (although they will talk to gnutls server and client respectively). 

The issue was the call to `DTLSClientTest#createSession` which performs a `dtls.close()`, sending a close alert to the server. This isn't needed.

I think that because the `DTLSServerTest` is a fairly naive one-shot server implementation, it won't then restart the handshake and recover, which the gnu server will. (And likewise, the gnu client doesn't send the close message).

I could make a PR?
