### ISSUE TITLE
 AlgorithmParameterSpec class not recognized: java.security.spec.ECGenParameterSpec

### ISSUE THREAD

**Issue by aokolovskis** [bcgit/bc-java#176]
Hi guys, 

I am facing difficulties running the EC* JAVA tests.  DH and ElGamal are working without issues. 

FAQ topic "1. Why do I get "java.lang.SecurityException: Unsupported keysize or algorithm parameters.." fixed some issues. 

While running PGPECDSATest the following Exception accrues:  . 

`PGPECDSATest: Exception: org.bouncycastle.openpgp.PGPException: exception constructing public key
org.bouncycastle.openpgp.PGPException: exception constructing public key
	at org.bouncycastle.openpgp.operator.jcajce.JcaPGPKeyConverter.getPublicKey(Unknown Source)
	at org.bouncycastle.openpgp.operator.jcajce.JcaPGPContentVerifierBuilderProvider$JcaPGPContentVerifierBuilder.build(Unknown Source)
	at org.bouncycastle.openpgp.PGPSignature.init(Unknown Source)
	at com.company.test.PGPECDSATest.performTest(PGPECDSATest.java:264)
	at org.bouncycastle.util.test.SimpleTest.perform(Unknown Source)
	at org.bouncycastle.util.test.SimpleTest.runTest(Unknown Source)
	at org.bouncycastle.util.test.SimpleTest.runTest(Unknown Source)
	at com.company.test.PGPECDSATest.main(PGPECDSATest.java:320)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.security.spec.InvalidParameterSpecException: AlgorithmParameterSpec class not recognized: java.security.spec.ECGenParameterSpec
	at org.bouncycastle.jcajce.provider.asymmetric.ec.AlgorithmParametersSpi.engineInit(Unknown Source)
	at java.security.AlgorithmParameters.init(AlgorithmParameters.java:275)
	at org.bouncycastle.openpgp.operator.jcajce.JcaPGPKeyConverter.getECParameterSpec(Unknown Source)`

Running on a mac. 
Tried with jdk1.7 and 1.8. 
libs: 
    bcpg-jdk15on-156
    jce-jdk13-156

Any hints are appreciated. 
Thank you in advance,
Alex

**Comment by aokolovskis** [comment]
Wrong library used. 
With correct bcprov-jdk15on-156 library all tests passed.
