### ISSUE TITLE
org.bouncycastle.tls.TlsFatalAlertReceived: handshake_failure(40) with Java 17 + BCJSSE

### ISSUE THREAD

**Issue by munishphogat** [bcgit/bc-java#1762]
Hi

We upgraded our system to Java 17. I started seeing handshake failure. I also went through [this issue](https://github.com/bcgit/bc-java/issues/1156) but was still unable to find it.

I saw the server is presenting Cert but later getting reset is coming. Same is working if I disable BCJSSE. 

Would you please help me to understand where is it going wrong?

Here is stack trace:
`
2024-07-31 13:52:45.856  INFO 78775 --- [           main] c.m.polaris.common.crypto.ProviderId     : FIPSMODE: Enabled SecureRand: BouncyCastle Security Provider (FIPS edition) v1.0.2.4 : org.bouncycastle.crypto.fips.FipsDRBG$Base@6d0114c0 Restrict Suite B: NO Restrict PKCS12: NO
2024-07-31 13:52:45.919  INFO 78775 --- [           main] c.m.p.c.net.ssl.StrictX509TrustManager   : Found default trust manager: org.bouncycastle.jsse.provider.ExportX509TrustManager_7
2024-07-31 13:52:45.919  WARN 78775 --- [           main] c.m.p.c.net.ssl.X509TrustManagerFactory  : org.bouncycastle.pkix.disable_certpath not set, falling back to StrictX509TrustManager
2024-07-31 13:52:45.928 DEBUG 78775 --- [           main] o.b.jsse.provider.PropertyUtils          : Integer system property [javax.net.ssl.sessionCacheSize] defaulted to: 20480
2024-07-31 13:52:45.938 DEBUG 78775 --- [           main] o.b.jsse.provider.PropertyUtils          : Boolean system property [jdk.tls.trustNameService] defaulted to: false
2024-07-31 13:52:46.176 DEBUG 78775 --- [           main] o.b.jsse.provider.PropertyUtils          : Boolean system property [jsse.enableSNIExtension] defaulted to: true
2024-07-31 13:52:46.206 DEBUG 78775 --- [           main] o.b.jsse.provider.PropertyUtils          : Boolean system property [org.bouncycastle.jsse.ec.disableChar2] defaulted to: false
2024-07-31 13:52:46.206 DEBUG 78775 --- [           main] o.b.jsse.provider.PropertyUtils          : Boolean system property [org.bouncycastle.ec.disable_f2m] defaulted to: false
2024-07-31 13:52:46.706 DEBUG 78775 --- [           main] o.b.jsse.provider.ProvTlsClient          : Client notified of selected protocol version: TLSv1.2
2024-07-31 13:52:46.706 DEBUG 78775 --- [           main] o.b.jsse.provider.ProvTlsClient          : Server specified new session: c5a27bd6842d3c207a35e2d2b0b37cf09ed41611d8bcc02cd4fe441aab381a8d
2024-07-31 13:52:46.710 DEBUG 78775 --- [           main] o.b.jsse.provider.ProvTlsClient          : Client notified of selected cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
2024-07-31 13:52:47.576  INFO 78775 --- [           main] o.b.jsse.provider.ProvTlsClient          : Client received fatal(2) handshake_failure(40) alert
2024-07-31 13:52:47.580 DEBUG 78775 --- [           main] o.b.jsse.provider.ProvSSLSocketDirect    : Failed to establish connection

org.bouncycastle.tls.TlsFatalAlertReceived: handshake_failure(40)
	at org.bouncycastle.tls.TlsProtocol.handleAlertMessage(TlsProtocol.java:167) ~[bctls-fips-1.0.9.jar:1.0.9]
	at org.bouncycastle.tls.TlsProtocol.processAlertQueue(TlsProtocol.java:570) ~[bctls-fips-1.0.9.jar:1.0.9]
	at org.bouncycastle.tls.TlsProtocol.processRecord(TlsProtocol.java:435) ~[bctls-fips-1.0.9.jar:1.0.9]
	at org.bouncycastle.tls.RecordStream.readRecord(RecordStream.java:224) ~[bctls-fips-1.0.9.jar:1.0.9]
	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:686) ~[bctls-fips-1.0.9.jar:1.0.9]
	at org.bouncycastle.tls.TlsProtocol.blockForHandshake(TlsProtocol.java:324) ~[bctls-fips-1.0.9.jar:1.0.9]
	at org.bouncycastle.tls.TlsClientProtocol.connect(TlsClientProtocol.java:83) ~[bctls-fips-1.0.9.jar:1.0.9]
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(ProvSSLSocketDirect.java:422) ~[bctls-fips-1.0.9.jar:1.0.9]
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.handshakeIfNecessary(ProvSSLSocketDirect.java:487) ~[bctls-fips-1.0.9.jar:1.0.9]
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.getConnection(ProvSSLSocketDirect.java:229) ~[bctls-fips-1.0.9.jar:1.0.9]
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.getSession(ProvSSLSocketDirect.java:295) ~[bctls-fips-1.0.9.jar:1.0.9]
	at com.mobileiron.polaris.common.net.utils.HttpUtils.getCertificateChain(HttpUtils.java:209) ~[polaris-common-net-104.0.16.jar:104.0.16.2]`

**This is the order of providers with PKIX as Key and Trust algorithms:**
BCFIPS
BCJSSE
SunJSSE
SUN
SunRsaSign
SunEC
SunJCE
SunJGSS
SunSASL
XMLDSig
SunPCSC
JdkLDAP
JdkSASL
Apple
SunPKCS11
Also 

I am attaching TCP dump capture withBCJSSE and withoutBCJSSE here [tcp](https://drive.google.com/drive/folders/1fxW9Nglwr3l6WsXkDeqUn_NTek0F_YtJ?usp=sharing) You need to put a filter on IP. These are destination IPs. 
ip.addr == 3.221.171.32 || ip.addr == 34.194.114.224 

Let me know if you need sample jar also.

**Comment by dghgit** [comment]
bctls-fips is npw at 1.0.19. Please update and  try again.

**Comment by munishphogat** [comment]
Thanks for the response.
I updated all BC libraries to the latest version and got the error. Following are the versions:
bc-fips : 1.0.2.5
bctls-fips: 1.0.19
bcpkix-fips:  1.0.7
bcmail-fips: 1.0.4

Error stack trace:

> 2024-08-01 07:01:53.518 DEBUG 54827 --- [           main] o.b.jsse.provider.PropertyUtils          : Boolean system property [com.sun.net.ssl.checkRevocation] defaulted to: false
2024-08-01 07:01:53.518 DEBUG 54827 --- [           main] o.b.jsse.provider.PropertyUtils          : Boolean system property [org.bouncycastle.jsse.trustManager.checkEKU] defaulted to: true
2024-08-01 07:01:53.526  INFO 54827 --- [           main] c.m.p.c.net.ssl.StrictX509TrustManager   : Found default trust manager: org.bouncycastle.jsse.provider.ExportX509TrustManager_7
2024-08-01 07:01:53.526  WARN 54827 --- [           main] c.m.p.c.net.ssl.X509TrustManagerFactory  : org.bouncycastle.pkix.disable_certpath not set, falling back to StrictX509TrustManager
2024-08-01 07:01:53.533 DEBUG 54827 --- [           main] o.b.jsse.provider.X509TrustManagerUtil   : Importing X509TrustManager implementation: com.test.common.net.ssl.StrictX509TrustManager
2024-08-01 07:01:53.535 DEBUG 54827 --- [           main] o.b.jsse.provider.PropertyUtils          : Integer system property [javax.net.ssl.sessionCacheSize] defaulted to: 20480
2024-08-01 07:01:53.535 DEBUG 54827 --- [           main] o.b.jsse.provider.PropertyUtils          : Boolean system property [org.bouncycastle.jsse.ec.disableChar2] defaulted to: false
2024-08-01 07:01:53.536 DEBUG 54827 --- [           main] o.b.jsse.provider.PropertyUtils          : Boolean system property [org.bouncycastle.ec.disable_f2m] defaulted to: false
2024-08-01 07:01:53.536 DEBUG 54827 --- [           main] o.b.jsse.provider.PropertyUtils          : Boolean system property [jsse.enableFFDHE] defaulted to: true
2024-08-01 07:01:53.715 DEBUG 54827 --- [           main] o.b.jsse.provider.PropertyUtils          : Boolean system property [org.bouncycastle.jsse.client.assumeOriginalHostName] defaulted to: false
2024-08-01 07:01:53.715 DEBUG 54827 --- [           main] o.b.jsse.provider.PropertyUtils          : Boolean system property [jdk.tls.trustNameService] defaulted to: false
2024-08-01 07:01:54.005 DEBUG 54827 --- [           main] o.b.jsse.provider.PropertyUtils          : Boolean system property [org.bouncycastle.jsse.client.acceptRenegotiation] defaulted to: false
2024-08-01 07:01:54.011 DEBUG 54827 --- [           main] o.b.jsse.provider.PropertyUtils          : Boolean system property [jdk.tls.client.enableCAExtension] defaulted to: false
2024-08-01 07:01:54.011 DEBUG 54827 --- [           main] o.b.jsse.provider.PropertyUtils          : Boolean system property [org.bouncycastle.jsse.client.enableSessionResumption] defaulted to: true
2024-08-01 07:01:54.011 DEBUG 54827 --- [           main] o.b.jsse.provider.PropertyUtils          : Boolean system property [jdk.tls.client.enableStatusRequestExtension] defaulted to: true
2024-08-01 07:01:54.011 DEBUG 54827 --- [           main] o.b.jsse.provider.PropertyUtils          : Boolean system property [org.bouncycastle.jsse.client.enableTrustedCAKeysExtension] defaulted to: false
2024-08-01 07:01:54.011 DEBUG 54827 --- [           main] o.b.jsse.provider.PropertyUtils          : Boolean system property [org.bouncycastle.jsse.client.omitSigAlgsCertExtension] defaulted to: true
2024-08-01 07:01:54.011 DEBUG 54827 --- [           main] o.b.jsse.provider.PropertyUtils          : Boolean system property [jsse.enableSNIExtension] defaulted to: true
2024-08-01 07:01:54.041  INFO 54827 --- [           main] o.b.jsse.provider.ProvTlsClient          : [client #1 @71fb8301] opening connection to (unknown):443
2024-08-01 07:01:54.271 DEBUG 54827 --- [           main] o.b.jsse.provider.ProvTlsClient          : [client #1 @71fb8301] notified of selected protocol version: TLSv1.2
2024-08-01 07:01:54.271 DEBUG 54827 --- [           main] o.b.jsse.provider.ProvTlsClient          : [client #1 @71fb8301]: Server specified new session: 1dccce2b0d05cae7d27e566795bfdef9bc5db7a031cd9eb08db593c550ee5a18
2024-08-01 07:01:54.274 DEBUG 54827 --- [           main] o.b.jsse.provider.ProvTlsClient          : [client #1 @71fb8301] notified of selected cipher suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
2024-08-01 07:01:54.853 TRACE 54827 --- [           main] o.b.jsse.provider.ProvTlsClient          : [client #1 @71fb8301] peer signature_algorithms: SHA256withECDSA SHA384withECDSA SHA512withECDSA SHA256withRSAandMGF1:RSASSA-PSS SHA384withRSAandMGF1:RSASSA-PSS SHA512withRSAandMGF1:RSASSA-PSS SHA256withRSAandMGF1:RSA SHA384withRSAandMGF1:RSA SHA512withRSAandMGF1:RSA SHA256withRSA SHA384withRSA SHA512withRSA SHA224withECDSA SHA224withRSA SHA224withDSA SHA256withDSA
2024-08-01 07:01:55.076  INFO 54827 --- [           main] o.b.jsse.provider.ProvTlsClient          : [client #1 @71fb8301] received fatal(2) handshake_failure(40) alert
2024-08-01 07:01:55.078  INFO 54827 --- [           main] o.b.jsse.provider.ProvTlsClient          : [client #1 @71fb8301] disconnected from (unknown):443
2024-08-01 07:01:55.081 DEBUG 54827 --- [           main] o.b.jsse.provider.ProvSSLSocketDirect    : Failed to establish connection
org.bouncycastle.tls.TlsFatalAlertReceived: handshake_failure(40)
	at org.bouncycastle.tls.TlsProtocol.handleAlertMessage(TlsProtocol.java:245) ~[bctls-fips-1.0.19.jar:1.0.19]
	at org.bouncycastle.tls.TlsProtocol.processAlertQueue(TlsProtocol.java:740) ~[bctls-fips-1.0.19.jar:1.0.19]
	at org.bouncycastle.tls.TlsProtocol.processRecord(TlsProtocol.java:563) ~[bctls-fips-1.0.19.jar:1.0.19]
	at org.bouncycastle.tls.RecordStream.readRecord(RecordStream.java:247) ~[bctls-fips-1.0.19.jar:1.0.19]
	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:879) ~[bctls-fips-1.0.19.jar:1.0.19]
	at org.bouncycastle.tls.TlsProtocol.blockForHandshake(TlsProtocol.java:427) ~[bctls-fips-1.0.19.jar:1.0.19]
	at org.bouncycastle.tls.TlsClientProtocol.connect(TlsClientProtocol.java:88) ~[bctls-fips-1.0.19.jar:1.0.19]
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(ProvSSLSocketDirect.java:425) ~[bctls-fips-1.0.19.jar:1.0.19]
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.handshakeIfNecessary(ProvSSLSocketDirect.java:518) ~[bctls-fips-1.0.19.jar:1.0.19]
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.getConnection(ProvSSLSocketDirect.java:200) ~[bctls-fips-1.0.19.jar:1.0.19]
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.getSessionImpl(ProvSSLSocketDirect.java:509) ~[bctls-fips-1.0.19.jar:1.0.19]
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.getSession(ProvSSLSocketDirect.java:266) ~[bctls-fips-1.0.19.jar:1.0.19]

Here is the latest TCP dump, please put filter on this destination IP: **ip.addr == 34.194.114.224**
[bcJSSEWithLatestLib.pcapng.zip](https://github.com/user-attachments/files/16448755/bcJSSEWithLatestLib.pcapng.zip)

**Comment by munishphogat** [comment]
@dghgit One thing I noticed is when I am enabling BCJSSE then server comes back with a Certificate Request which I am not presenting I believe.

Can enabling BCJSSE at the client cause mutual auth?

**Comment by peterdettman** [comment]
The exception type is `TlsFatalAlertReceived`, so we "received a fatal alert", which tells us that it is the server aborting the handshake. In general you would need to consult the server to find out why it is aborting.

In this case we see in the pcap that after your client sends its Certificate message (length 66 means it's an empty cert chain i.e. the client declined to authenticate), the server sends its fatal alert, so presumably it requires client auth.

It's hard to comment further without more details of what you were expecting to happen (and what exactly happens in the non-BCJSSE case that you say works).

**Comment by munishphogat** [comment]
I got it working on presenting the cert @peterdettman. I could get server side pcap though. Thanks for help. Closing it.
