### ISSUE TITLE
Tests failing - missing bc-test-data files

### ISSUE THREAD

**Issue by mouse07410** [bcgit/bc-java#1786]
Again, somebody forgot to push the new files to https://github.com/bcgit/bc-test-data.git  :

```text
/Users/ur20980/src/bc-test-data/pqc/crypto/kyber/acvp/encapDecap_decapsulation_ML-KEM-512.txt (No such file or directory)

java.io.FileNotFoundException: /Users/ur20980/src/bc-test-data/pqc/crypto/kyber/acvp/encapDecap_decapsulation_ML-KEM-512.txt (No such file or directory)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
at org.bouncycastle.test.TestResourceFinder.findTestResource(TestResourceFinder.java:37)
at org.bouncycastle.pqc.crypto.test.CrystalsKyberTest.testEncapDecap_decapsulation(CrystalsKyberTest.java:212)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)
at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
at junit.extensions.TestSetup.run(TestSetup.java:27)

/Users/ur20980/src/bc-test-data/pqc/crypto/kyber/acvp/keyGen_ML-KEM-512.txt (No such file or directory)

java.io.FileNotFoundException: /Users/ur20980/src/bc-test-data/pqc/crypto/kyber/acvp/keyGen_ML-KEM-512.txt (No such file or directory)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
at org.bouncycastle.test.TestResourceFinder.findTestResource(TestResourceFinder.java:37)
at org.bouncycastle.pqc.crypto.test.CrystalsKyberTest.testKeyGen(CrystalsKyberTest.java:57)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)
at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
at junit.extensions.TestSetup.run(TestSetup.java:27)

/Users/ur20980/src/bc-test-data/pqc/crypto/kyber/acvp/encapDecap_encapsulation_ML-KEM-512.txt (No such file or directory)

java.io.FileNotFoundException: /Users/ur20980/src/bc-test-data/pqc/crypto/kyber/acvp/encapDecap_encapsulation_ML-KEM-512.txt (No such file or directory)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
at org.bouncycastle.test.TestResourceFinder.findTestResource(TestResourceFinder.java:37)
at org.bouncycastle.pqc.crypto.test.CrystalsKyberTest.testEncapDecap_encapsulation(CrystalsKyberTest.java:132)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)
at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
at junit.extensions.TestSetup.run(TestSetup.java:27)

/Users/ur20980/src/bc-test-data/pqc/crypto/dilithium/acvp/keyGen_ML-DSA-44.txt (No such file or directory)

java.io.FileNotFoundException: /Users/ur20980/src/bc-test-data/pqc/crypto/dilithium/acvp/keyGen_ML-DSA-44.txt (No such file or directory)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
at org.bouncycastle.test.TestResourceFinder.findTestResource(TestResourceFinder.java:37)
at org.bouncycastle.pqc.crypto.test.CrystalsDilithiumTest.testKeyGen(CrystalsDilithiumTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)
at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
at junit.extensions.TestSetup.run(TestSetup.java:27)

/Users/ur20980/src/bc-test-data/pqc/crypto/dilithium/acvp/sigGen_ML-DSA-44.txt (No such file or directory)

java.io.FileNotFoundException: /Users/ur20980/src/bc-test-data/pqc/crypto/dilithium/acvp/sigGen_ML-DSA-44.txt (No such file or directory)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
at org.bouncycastle.test.TestResourceFinder.findTestResource(TestResourceFinder.java:37)
at org.bouncycastle.pqc.crypto.test.CrystalsDilithiumTest.testSigGen(CrystalsDilithiumTest.java:123)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)
at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
at junit.extensions.TestSetup.run(TestSetup.java:27)

/Users/ur20980/src/bc-test-data/pqc/crypto/dilithium/acvp/sigVer_ML-DSA-44.txt (No such file or directory)

java.io.FileNotFoundException: /Users/ur20980/src/bc-test-data/pqc/crypto/dilithium/acvp/sigVer_ML-DSA-44.txt (No such file or directory)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
at org.bouncycastle.test.TestResourceFinder.findTestResource(TestResourceFinder.java:37)
at org.bouncycastle.pqc.crypto.test.CrystalsDilithiumTest.testSigVer(CrystalsDilithiumTest.java:202)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at junit.extensions.TestDecorator.basicRun(TestDecorator.java:24)
at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
at junit.extensions.TestSetup.run(TestSetup.java:27)
```

**Comment by dghgit** [comment]
Should all be back in sync now.
