### ISSUE TITLE
Java.lang.nosuchmethoderror: org.bouncycastle.asn1

### ISSUE THREAD

**Issue by sai12318** [bcgit/bc-java#1834]
Hi Team,

We are facing this in our project , if we are upgrading jars version it is causing issue with other ssl interface connections. Could you please suggest

Caused by: java.lang.NoSuchMethodError: org.bouncycastle.asn1.x509.SubjectPublicKeyInfo.getPublicKeyData()Lorg/bouncycastle/asn1/DE
RBitString;
        at org.bouncycastle.tls.crypto.impl.jcajce.JceX25519Domain.encodePublicKey(Unknown Source) ~[bctls-jdk15on-1.68.jar:1.68.00
.0]
        at org.bouncycastle.tls.crypto.impl.jcajce.JceX25519.generateEphemeral(Unknown Source) ~[bctls-jdk15on-1.68.jar:1.68.00.0]
        at org.bouncycastle.tls.TlsECDHEKeyExchange.generateEphemeral(Unknown Source) ~[bctls-jdk15on-1.68.jar:1.68.00.0]
        at org.bouncycastle.tls.TlsECDHEKeyExchange.generateClientKeyExchange(Unknown Source) ~[bctls-jdk15on-1.68.jar:1.68.00.0]
        at org.bouncycastle.tls.TlsClientProtocol.sendClientKeyExchange(Unknown Source) ~[bctls-jdk15on-1.68.jar:1.68.00.0]
        at org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(Unknown Source) ~[bctls-jdk15on-1.68.jar:1.68.00.0]
        at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(Unknown Source) ~[bctls-jdk15on-1.68.jar:1.68.00.0]
        at org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source) ~[bctls-jdk15on-1.68.jar:1.68.00.0]
        at org.bouncycastle.tls.RecordStream.readRecord(Unknown Source) ~[bctls-jdk15on-1.68.jar:1.68.00.0]
        at org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source) ~[bctls-jdk15on-1.68.jar:1.68.00.0]
        at org.bouncycastle.tls.TlsProtocol.blockForHandshake(Unknown Source) ~[bctls-jdk15on-1.68.jar:1.68.00.0]
        at org.bouncycastle.tls.TlsClientProtocol.connect(Unknown Source) ~[bctls-jdk15on-1.68.jar:1.68.00.0]
        at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(Unknown Source) ~[bctls-jdk15on-1.68.jar:1.68.00.0]
        at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(Unknown Source) ~[bctls-jdk15on-1.68.jar:1.68.00.0]
        at sun.net.
www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:558)
~[?:1.8.0_411]
        at sun.net.
www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:201)
~[?:1:

**Comment by dghgit** [comment]
Update the TLS jar as well - it's way out of date.
