### ISSUE TITLE
Building jar JNI error

### ISSUE THREAD

**Issue by IndianBartonka** [bcgit/bc-java#1862]
How i can fix this error?
Error:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at java.base/sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:339)
        at java.base/sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:281)
        at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:320)
        at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:232)
        at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:760)
        at java.base/java.util.jar.JarFile.ensureInitialization(JarFile.java:1070)
        at java.base/java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:42)
        at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:841)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:848)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:529)
        at java.base/java.lang.Class.forName(Class.java:508)
        at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:841)
        at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:736)
```

I using java 17 with :
```xml
<dependency>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcpkix-jdk15on</artifactId>
                    <version>1.70</version>
                    <scope>compile</scope>
                </dependency>
```
My build:
```xml
<build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>16</source>
                    <target>16</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>pl.indianbartonka.sync.DesktopClient</mainClass>
                                </transformer>
                            </transformers>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <finalName>${project.name}${jar.suffix}-${project.version}</finalName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources/</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
```

**Comment by dghgit** [comment]
Use the latest jdk18on release. 1.70 is way out of date.

**Comment by IndianBartonka** [comment]
> Use the latest jdk18on release. 1.70 is way out of date.

```xml
   <dependency>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcprov-jdk18on</artifactId>
                    <version>1.78.1</version>
                    <scope>compile</scope>
                </dependency>
```
```xml
   <dependency>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcprov-jdk18on</artifactId>
                    <version>1.78.1</version>
                    <scope>compile</scope>
                </dependency>
```

**Comment by dghgit** [comment]
Looking at this again it looks like it's using a shaded jar - the shading needs to be tweaked so the BC jar is not unpacked (apparently this can be done) as on the JVM in question the JVM is expecting a valid JCE signature for any provider it loads.
