### ISSUE TITLE
X509Certificate getPublicKey().getEncoded() return NullPointerException

### ISSUE THREAD

**Issue by keyfunc** [bcgit/bc-java#189]
code
```
Security.addProvider(new BouncyCastleProvider());
CertificateFactory certFact = CertificateFactory.getInstance("X.509", BouncyCastleProvider.PROVIDER_NAME);
X509Certificate x509 = (X509Certificate)certFact.generateCertificate(new ByteArrayInputStream(sm2X509));
System.out.println(x509.getPublicKey());
System.out.println(Base64.toBase64String(x509.getPublicKey().getEncoded()));
```

SM2 Certificate
```
MIICwzCCAmmgAwIBAgIIIBQGIgAAAAMwCgYIKoEcz1UBg3UwgdgxCzAJBgNVBAYT
AkNOMRIwEAYDVQQIDAnmsZ/oi4/nnIExEjAQBgNVBAcMCeWNl+S6rOW4gjE8MDoG
A1UECgwz5rGf6IuP55yB55S15a2Q5ZWG5Yqh5pyN5Yqh5Lit5b+D5pyJ6ZmQ6LSj
5Lu75YWs5Y+4MUswSQYDVQQLDELmsZ/oi4/nnIHnlLXlrZDllYbliqHmnI3liqHk
uK3lv4PmnInpmZDotKPku7vlhazlj7jlronlhajkuovkuJrpg6gxFjAUBgNVBAMM
DUpTQ0FfUk9PVF9TTTIwHhcNMTQwNjIyMDQ1MzAyWhcNMzQwNjIyMDQ1MzAyWjCB
1jELMAkGA1UEBhMCQ04xEjAQBgNVBAgMCeaxn+iLj+ecgTESMBAGA1UEBwwJ5Y2X
5Lqs5biCMTwwOgYDVQQKDDPmsZ/oi4/nnIHnlLXlrZDllYbliqHmnI3liqHkuK3l
v4PmnInpmZDotKPku7vlhazlj7gxSzBJBgNVBAsMQuaxn+iLj+ecgeeUteWtkOWV
huWKoeacjeWKoeS4reW/g+aciemZkOi0o+S7u+WFrOWPuOWuieWFqOS6i+S4mumD
qDEUMBIGA1UEAwwLSlNDQV9DQV9TTTIwWTATBgcqhkjOPQIBBggqgRzPVQGCLQNC
AAS/gvW90+LvyXPgpR7L0pwlVoZQdan7V5YQMEpxt47tzer31/8WJIfldx9NL/1A
swkk6ItveCVW5k0u+IIk6crLox0wGzAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwIB
BjAKBggqgRzPVQGDdQNIADBFAiEAy9NkogihHCj9Jx0ZiHdkMyCHF0wHWX58KZco
CW5mjbgCIC9cAyuVV91ygLWk14PDuIAPFWKm6rJPXbiZL6KzwHQA
```

```
EC Public Key
            X: bf82f5bdd3e2efc973e0a51ecbd29c2556865075a9fb579610304a71b78eedcd
            Y: eaf7d7ff162487e5771f4d2ffd40b30924e88b6f782556e64d2ef88224e9cacb
Exception in thread "main" java.lang.NullPointerException
	at org.bouncycastle.jcajce.provider.asymmetric.util.ECUtil.getNamedCurveOid(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.ec.ECUtils.getDomainParametersFromName(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.ec.BCECPublicKey.getEncoded(Unknown Source)
	at com.nichijou.crypto.test.SM2Test.main(SM2Test.java:29)
```

**Comment by peterdettman** [comment]
Thanks for the report. GMNamedCurves lookup wasn't added to ECUtil.getCurveName, so it fails to retrieve the name "sm2p256v1" (though the OID is retrieved correctly). Fixed in our repo now.

It's possible you can use the key just fine if you don't actually _need_ to encode it, but in any case the fix will be in the next beta build.

**Comment by keyfunc** [comment]
```
X509CertificateHolder cert = new X509CertificateHolder(sm2X509);
AsymmetricKeyParameter` keyParameter = PublicKeyFactory.createKey(cert.getSubjectPublicKeyInfo());
```
```
Exception in thread "main" java.lang.NullPointerException
	at org.bouncycastle.crypto.util.PublicKeyFactory.createKey(Unknown Source)
```

**Comment by peterdettman** [comment]
Thanks, I think that was also fixed by the original patch. Please test with a beta version from https://downloads.bouncycastle.org/betas/ .
