### ISSUE TITLE
Cannot invoke "org.bouncycastle.openpgp.PGPEncryptedData$TruncatedStream.getLookAhead()" because "this.truncStream" is null

### ISSUE THREAD

**Issue by singpolyma** [bcgit/bc-java#1914]
Using https://github.com/bcgit/bc-java/blob/main/pg/src/main/java/org/bouncycastle/openpgp/examples/PBEFileProcessor.java to decrypt an SEKv6+SEIPv2 message generated by bouncycastle, it works except that I get this exception after the file is successfully written:

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.bouncycastle.openpgp.PGPEncryptedData$TruncatedStream.getLookAhead()" because "this.truncStream" is null
	at org.bouncycastle.openpgp.PGPEncryptedData.verify(Unknown Source)
	at org.bouncycastle.openpgp.examples.PBEFileProcessor.decryptFile(Unknown Source)
	at org.bouncycastle.openpgp.examples.PBEFileProcessor.decryptFile(Unknown Source)
	at org.bouncycastle.openpgp.examples.PBEFileProcessor.main(Unknown Source)
```

As far as I can tell https://github.com/bcgit/bc-java/blob/main/pg/src/main/java/org/bouncycastle/openpgp/PGPEncryptedData.java#L227 should be true and so verify should return before getting to the `getLookAhead` call but it seems that is not happening for some reason.

This is with version 1.77

**Comment by vanitasvitae** [comment]
This was fixed with https://github.com/bcgit/bc-java/commit/c6c45d361428e30168a4813d06b409b759e3ffef#diff-83881d5485ba95e07b97362e957d08ea04fe479d7ed772db5c8db5336d1545d8R186-R197

**Comment by winfriedgerlach** [comment]
@singpolyma @vanitasvitae can this issue be closed?
