### ISSUE TITLE
bc-fips 2.0 module-path approach does not work on JDK 21

### ISSUE THREAD

**Issue by bahrigencsoy** [bcgit/bc-java#1939]
Reading the latest java-fips documentation at https://downloads.bouncycastle.org/fips-java/docs/BC-FJA-UserGuide-2.0.0.pdf, the recommended approach is to append `--module-path` to the java executable. What I understand from the documentation is that this is the only requisite, modifying the java security file is no longer needed. So I set up an environment to validate this claim.

**Target App**: apache artemis 2.38 (mostly a black box)
**OS**: Redhat Ubi 9.5 in k8s
**JDK**: Zulu 21 JDK
**Sidecar container**: A rate limiting proxy in front of Artemis JMS port
**Command used for validation**: `for i in $(seq 1 1000); do sleep 0.1 && jstack 1 | grep -A10 -B10 bouncy | tee -a /tmp/stacks.txt; done`

**Container Using Module Path**
```sh
bash-5.1$ cat /proc/1/cmdline | tr '\0' '\n'
java
-Djavax.net.ssl.keyStore=/var/lib/artemis/etc/artemis-ssl.ks
-Djavax.net.ssl.trustStore=/var/lib/artemis/etc/artemis-ssl.ts
--add-opens
java.base/jdk.internal.misc=ALL-UNNAMED
-Djava.security.auth.login.config=/var/lib/artemis/etc/login.config
-classpath
/opt/apache-artemis-2.38.0/lib/artemis-boot.jar
-Dartemis.home=/opt/apache-artemis-2.38.0
-Dartemis.instance=/var/lib/artemis
-Djava.library.path=/opt/apache-artemis-2.38.0/bin/lib/linux-aarch64
--module-path
/opt/activemq-artemis/bc-lib
org.apache.activemq.artemis.boot.Artemis
run
--properties
/assets/broker.properties
(some parameters reducted)

bash-5.1$ for i in $(seq 1 1000); do sleep 0.1 && jstack 1 | grep -A10 -B10 bouncy | tee -a /tmp/stacks.txt; done
(empty output)
```

**Container Using Security File**
```sh
bash-5.1$ cat /proc/1/cmdline | tr '\0' '\n'
java
-Djava.security.properties=file:///usr/lib/jvm/zulu-21/conf/security/java.fips.security
-Djavax.net.ssl.keyStore=/var/lib/artemis/etc/artemis-ssl.ks
-Djavax.net.ssl.trustStore=/var/lib/artemis/etc/artemis-ssl.ts
--add-opens
java.base/jdk.internal.misc=ALL-UNNAMED
-Djava.security.auth.login.config=/var/lib/artemis/etc/login.config
-classpath
/opt/apache-artemis-2.38.0/lib/artemis-boot.jar:/opt/activemq-artemis/bc-lib/bc-fips-2.0.0.jar:/opt/activemq-artemis/bc-lib/bctls-fips-2.0.19.jar:/opt/activemq-artemis/bc-lib/bcutil-fips-2.0.3.jar
-Dartemis.home=/opt/apache-artemis-2.38.0
-Dartemis.instance=/var/lib/artemis
-Djava.library.path=/opt/apache-artemis-2.38.0/bin/lib/linux-aarch64
-Dartemis.instance.etc=/var/lib/artemis/etc
org.apache.activemq.artemis.boot.Artemis
run
--properties
/assets/broker.properties

bash-5.1$ for i in $(seq 1 1000); do sleep 0.1 && jstack 1 | grep -A10 -B10 bouncy | tee -a /tmp/stacks.txt; done
"RMI TCP Connection(5)-10.1.7.9" #103 [2795] daemon prio=5 os_prio=0 cpu=10.08ms elapsed=29.91s tid=0x0000fffefc005750 nid=2795 runnable  [0x0000ffff5520b000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.Net.poll(java.base@21.0.5/Native Method)
	at sun.nio.ch.NioSocketImpl.park(java.base@21.0.5/NioSocketImpl.java:191)
	at sun.nio.ch.NioSocketImpl.timedRead(java.base@21.0.5/NioSocketImpl.java:280)
	at sun.nio.ch.NioSocketImpl.implRead(java.base@21.0.5/NioSocketImpl.java:304)
	at sun.nio.ch.NioSocketImpl.read(java.base@21.0.5/NioSocketImpl.java:346)
	at sun.nio.ch.NioSocketImpl$1.read(java.base@21.0.5/NioSocketImpl.java:796)
	at java.net.Socket$SocketInputStream.read(java.base@21.0.5/Socket.java:1109)
	at org.bouncycastle.tls.RecordStream$Record.fillTo(RecordStream.java:442)
	at org.bouncycastle.tls.RecordStream$Record.readHeader(RecordStream.java:481)
	at org.bouncycastle.tls.RecordStream.readRecord(RecordStream.java:216)
	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:879)
	at org.bouncycastle.tls.TlsProtocol.readApplicationData(TlsProtocol.java:842)
	at org.bouncycastle.jsse.provider.ProvSSLSocketWrap$AppDataInput.read(ProvSSLSocketWrap.java:801)
	at java.io.BufferedInputStream.fill(java.base@21.0.5/BufferedInputStream.java:291)
	at java.io.BufferedInputStream.implRead(java.base@21.0.5/BufferedInputStream.java:325)
	at java.io.BufferedInputStream.read(java.base@21.0.5/BufferedInputStream.java:312)
	at java.io.FilterInputStream.read(java.base@21.0.5/FilterInputStream.java:71)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(java.rmi@21.0.5/TCPTransport.java:580)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(java.rmi@21.0.5/TCPTransport.java:844)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(java.rmi@21.0.5/TCPTransport.java:721)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda/0x00000078015f7b18.run(java.rmi@21.0.5/Unknown Source)
	at java.security.AccessController.executePrivileged(java.base@21.0.5/AccessController.java:778)
	at java.security.AccessController.doPrivileged(java.base@21.0.5/AccessController.java:400)
```

I had run this experiment several times, and never seen a stack trace element referencing bouncy castle classes in the former.

**Comment by dghgit** [comment]
I'll look at rewriting it, although I'm not sure I understand why you have this impression. The mod path instructions are about the BC jars (including the two containing providers but also including the ones that don't), we make no comment saying this changes the usual rules for adding an actual provider (which needs to be either added at runtime in application code, or statically in java.security) as documented by Oracle.
