### ISSUE TITLE
When writing a certificate with multiple ExtendedKeyUsage purposes to a PKCS12 keystore, other security providers may fail to load it

### ISSUE THREAD

**Issue by andpab** [bcgit/bc-java#1945]
The issue can be reproduced as follows with BC 1.79 - I used the jdk18on jars:

1.  Configure BouncyCastle security provider as the primary security provider
2.  Generate an X.509 Certificate that contains an ExtendedKeyUsage extension with at least two purposes
3.  Write the X.509 Certificate object to a PKCS12 keystore
4.  Read the X.509 Certificate object from the PKCS12 keystore
5.  Write the X.509 Certificate object to a second PKCS12 keystore
6.  Remove BouncyCastle security provider, so that the default JRE security provider is the primary security provider again
7.  Read the certificate from the PKCS12 keystore into a new java.security.cert.Certificate object

Step 7 results in the following exception:

> java.io.IOException: keystore password was incorrect
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2159)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:221)
	at java.base/java.security.KeyStore.load(KeyStore.java:1473)
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: java.io.IOException: DerValue.getOID, not an OID 49

The same error occurs if instead of step 6 and step 7 you try to open the second keystore with the JRE keytool utility.

Note that the write-read-write sequence appears to be necessary to reproduce it. The first keystore can be opened just fine. The second keystore can also still be opened, but only if the BouncyCastle security provider is still configured.

Here's an SSCCE in the form of a test that reproduces the issue:

```java
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.math.BigInteger;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.GeneralSecurityException;
import java.security.KeyPairGenerator;
import java.security.KeyStore;
import java.security.SecureRandom;
import java.security.Security;
import java.security.cert.Certificate;
import java.security.cert.X509Certificate;
import java.time.Instant;
import java.time.Period;
import java.util.Date;

import org.bouncycastle.asn1.x500.X500Name;
import org.bouncycastle.asn1.x509.ExtendedKeyUsage;
import org.bouncycastle.asn1.x509.Extension;
import org.bouncycastle.asn1.x509.KeyPurposeId;
import org.bouncycastle.asn1.x509.SubjectPublicKeyInfo;
import org.bouncycastle.cert.X509v3CertificateBuilder;
import org.bouncycastle.cert.jcajce.JcaX509CertificateConverter;
import org.bouncycastle.crypto.util.PrivateKeyFactory;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.bouncycastle.operator.DefaultDigestAlgorithmIdentifierFinder;
import org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder;
import org.bouncycastle.operator.OperatorCreationException;
import org.bouncycastle.operator.bc.BcRSAContentSignerBuilder;
import org.junit.jupiter.api.Test;

public class ExtendedKeyUsageTest {

    @Test
    public void create_write_read_write_and_then_read_without_bc() throws GeneralSecurityException, IOException, OperatorCreationException {
        Path tempDir = Files.createTempDirectory("bctest");
        Security.insertProviderAt(new BouncyCastleProvider(), 1);

        String keystoreType = "PKCS12";
        String certificateAlias = "myAlias";
        String keystorePassword = "myPassword";

        // generate certificate
        Certificate originalCertificate = new X509CertificateFactory().create();

        // store original certificate to a truststore
        Path pathToFirstTrustStore = tempDir.resolve("first-trust-store.p12");
        {
            Files.deleteIfExists(pathToFirstTrustStore);
            KeyStore firstTrustStore = KeyStore.getInstance(keystoreType);
            firstTrustStore.load(null, new char[0]);
            firstTrustStore.setCertificateEntry(certificateAlias, originalCertificate);
            try (OutputStream outputStream = Files.newOutputStream(pathToFirstTrustStore)) {
                firstTrustStore.store(outputStream, keystorePassword.toCharArray());
            }
        }

        // read certificate from the truststore
        KeyStore firstTrustStoreReadAgain = KeyStore.getInstance(keystoreType);
        try (InputStream inputStream = Files.newInputStream(pathToFirstTrustStore)) {
            firstTrustStoreReadAgain.load(inputStream, keystorePassword.toCharArray());
        }
        Certificate certificateReadFromFirstTrustStore = firstTrustStoreReadAgain.getCertificate(certificateAlias);

        // store read certificate to a different truststore
        Path pathToSecondTrustStore = tempDir.resolve("second-trust-store.p12");
        {
            Files.deleteIfExists(pathToSecondTrustStore);
            KeyStore secondTrustStore = KeyStore.getInstance(keystoreType);
            secondTrustStore.load(null, new char[0]);
            secondTrustStore.setCertificateEntry(certificateAlias, certificateReadFromFirstTrustStore);
            try (OutputStream outputStream = Files.newOutputStream(pathToSecondTrustStore)) {
                secondTrustStore.store(outputStream, keystorePassword.toCharArray());
            }
        }

        // read certificate from different truststore without BC
        Security.removeProvider(BouncyCastleProvider.PROVIDER_NAME);
        KeyStore secondTrustStoreReadWithoutBc = KeyStore.getInstance(keystoreType);
        try (InputStream inputStream = Files.newInputStream(pathToSecondTrustStore)) {
            // The following will fail with an exception that has the following root cause: java.io.IOException: DerValue.getOID, not an OID 49
            secondTrustStoreReadWithoutBc.load(inputStream, keystorePassword.toCharArray());
        }
    }

    private static class X509CertificateFactory {

        X509Certificate create() throws GeneralSecurityException, IOException, OperatorCreationException {
            var keyPairGenerator = KeyPairGenerator.getInstance("RSA", BouncyCastleProvider.PROVIDER_NAME);
            keyPairGenerator.initialize(1024, new SecureRandom());
            var keyPair = keyPairGenerator.generateKeyPair();

            var certificateBuilder = new X509v3CertificateBuilder(new X500Name("CN=localhost"),
                                                                  BigInteger.valueOf(new SecureRandom().nextLong()).abs(),
                                                                  Date.from(Instant.now()),
                                                                  Date.from(Instant.now().plus(Period.ofDays(1000))),
                                                                  new X500Name("CN=localhost"),
                                                                  SubjectPublicKeyInfo.getInstance(keyPair.getPublic().getEncoded()));

            certificateBuilder.addExtension(Extension.extendedKeyUsage, false,
                                            new ExtendedKeyUsage(new KeyPurposeId[]{
                                                    KeyPurposeId.id_kp_serverAuth,
                                                    KeyPurposeId.id_kp_clientAuth
                                            }));

            var sigAlgId = new DefaultSignatureAlgorithmIdentifierFinder().find("SHA512WITHRSA");
            var digAlgId = new DefaultDigestAlgorithmIdentifierFinder().find(sigAlgId);
            var certificateHolder = certificateBuilder.build(
                    new BcRSAContentSignerBuilder(sigAlgId, digAlgId)
                            .build(PrivateKeyFactory.createKey(keyPair.getPrivate().getEncoded())));

            return new JcaX509CertificateConverter()
                    .setProvider(BouncyCastleProvider.PROVIDER_NAME)
                    .getCertificate(certificateHolder);
        }

    }

}
```

Curiously enough, if you serialize and deserialize the `Certificate` object before writing it to the second store, then the issue does not occur.

It also doesn't occur if you specify just one key purpose in the ExtendedKeyUsage extension rather than two.

I don't know if we're doing something wrong here or there is an issue in the code. Hopefully, someone can shed some light on this peculiarity.

**Comment by dghgit** [comment]
Thanks for the report. All I'll say is "That was not fun..." So the issue turned out to be something about the oracle trusted certificate attribute for PKCS12, it appears that if it gets duplicated and if the extended key usage the attribute contains has more than one entry in it the JVM parser falls over when it tries to reload the key store. I've fixed our implementation so that the attribute can no longer be repeated, this shouldn't cause any issues as the attribute is meant to be set to what's in the ExtendedKeyUsage extension, or to KeyPurposeId.any if there isn't one.

You should find the latest on https://downloads.bouncycastle.org/betas fixes the problem. Let me know how it goes.

**Comment by andpab** [comment]
I can confirm that the fix solves the problem and does not appear to introduce any other issues. 

Thank you for diving into it.
