### ISSUE TITLE
ECGOST 2001/2012 certificate signature varification

### ISSUE THREAD

**Issue by MikeSafonov** [bcgit/bc-java#208]
Hello. I trying to check certificate signature generated using ECGOST 3410 algorithms.
```
        KeyPairGenerator keyPairGenerator =
                KeyPairGenerator.getInstance("ECGOST3410", "BC");
        keyPairGenerator.initialize(new ECGenParameterSpec(
                "GostR3410-2001-CryptoPro-A"), new SecureRandom());
        KeyPair caKeyPair = keyPairGenerator.generateKeyPair();



        X509CertificateHolder caCertificate = ...;
        X509CertificateHolder userCertificate = ...;


        BcContentVerifierProviderBuilder builder = new BcECContentVerifierProviderBuilder(new DefaultDigestAlgorithmIdentifierFinder());
        ContentVerifierProvider contentVerifierProvider = builder.build(caCertificate);
        System.out.println("Signature check using certificate");
        try {
            System.out.println(userCertificate.isSignatureValid(contentVerifierProvider));
        }catch (Exception ex){
            ex.printStackTrace();
        }

        ECPublicKey k = (ECPublicKey) caKeyPair.getPublic();
        ECParameterSpec s = k.getParameters();
        ECDomainParameters domainParameters = new ECDomainParameters(s.getCurve(), s.getG(), s.getN());
        AsymmetricKeyParameter keyParameter =  new ECPublicKeyParameters(
                k.getQ(),
                domainParameters);

        contentVerifierProvider = builder.build(keyParameter);
        System.out.println("Signature check using public key ");
        System.out.println(userCertificate.isSignatureValid(contentVerifierProvider));
```
Output:

> Signature check using certificate
org.bouncycastle.cert.CertException: unable to process signature: algorithm identifier in key not recognised
	at org.bouncycastle.cert.X509CertificateHolder.isSignatureValid(X509CertificateHolder.java:298)
...
com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.RuntimeException: algorithm identifier in key not recognised
	at org.bouncycastle.crypto.util.PublicKeyFactory.createKey(PublicKeyFactory.java:192)
	at org.bouncycastle.operator.bc.BcECContentVerifierProviderBuilder.extractKeyParameters(BcECContentVerifierProviderBuilder.java:38)
	at org.bouncycastle.operator.bc.BcContentVerifierProviderBuilder$1.get(BcContentVerifierProviderBuilder.java:44)
	at org.bouncycastle.cert.X509CertificateHolder.isSignatureValid(X509CertificateHolder.java:287)
	... 24 more
Signature check using public key 
true

As I see the cause is in _PublicKeyFactory.createKey_

**Comment by bcgit** [comment]
The PublicKeyFactory now supports GOST keys as well. See the latest beta on https://www.bouncycastle.org/betas for details.

**Comment by MikeSafonov** [comment]
thanks!
