### ISSUE TITLE
cipher suites "TLS_RSA_WITH_AES_256_GCM_SHA384" and "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384" can't work

### ISSUE THREAD

**Issue by zhanglei-1987** [bcgit/bc-java#222]
cipher suites "TLS_RSA_WITH_AES_256_GCM_SHA384" and "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384" can't work on "https://59.151.65.97/preSvr".

Client raised fatal(2) handshake_failure(40) alert: Failed to read record
org.bouncycastle.tls.TlsFatalAlert: handshake_failure(40)

**Comment by peterdettman** [comment]
Which API are you trying to use for TLS (the old org.bouncycastle.crypto.tls, the new org.bouncycastle.tls, or the BCJSSE provider)?

BTW, both cipher suites are well-tested as working with e.g. openssl, gnutls, so the initial suspicion would be that the server is at fault. Without more information about what software the server is running, it's very difficult to guess what is wrong.

When I try to connect to that URL (TLS 1.2, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384), the server responds immediately with handshake failure, so it looks like a simple case of lacking support.

**Comment by zhanglei-1987** [comment]
bctls-jdk15on-1.58.jar and bcprov-jdk15on-1.58.jar

BouncyCastleJsseProvider provider = new BouncyCastleJsseProvider(new BouncyCastleProvider());

**Comment by zhanglei-1987** [comment]
sorry, I'm write wrong.  

cipher suites "TLS_RSA_WITH_AES_256_GCM_SHA384" and "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384" .

**Comment by zhanglei-1987** [comment]
the server connect well by jdk1.8

**Comment by peterdettman** [comment]
OK, there are 2 issues:

- The server doesn't appear to support RFC 5746 ("secure renegotiation"), so the BCJSSE client is aborting after it receives the ServerHello. We've now added support for the "sun.security.ssl.allowLegacyHelloMessages" system property (which defaults to true), which should solve the immediate problem.

- If the client offers EC cipher suites, but the server chooses a non-EC cipher suite, the server is still sending an ec_point_formats extension, which it shouldn't be doing. Currently the BCJSSE client also aborts because of this, but it's not particularly harmful, so I've added a workaround for this also.

With those fixes, I can complete a handshake with this server, but if you have any control over the server software, it would ideally be fixed - or probably it will have interop problems with other clients too.

We'll try to get a new beta version of the bctls jar out shortly with these changes.

**Comment by peterdettman** [comment]
A new beta (159b03) containing these changes is available here:
https://downloads.bouncycastle.org/betas/

**Comment by zhanglei-1987** [comment]
using "bctls-jdk15on-159b03.jar" still can't connect!

**Comment by peterdettman** [comment]
OK, well what error are you seeing now? Can you give me the stack trace of whatever exception you're getting?

**Comment by zhanglei-1987** [comment]
My Code ：
`BouncyCastleJsseProvider provider = new BouncyCastleJsseProvider(new BouncyCastleProvider());

		SSLContext context = SSLContext.getInstance("TLS", provider);

		TrustAllX509TrustManager manager = new TrustAllX509TrustManager();

		context.init(null, new X509TrustManager[] { manager }, new SecureRandom());

		URL url = new URL("https://59.151.65.97/preSvr");

		HttpsURLConnection connection = (HttpsURLConnection) url.openConnection();
		connection.setSSLSocketFactory(context.getSocketFactory());

		connection.connect();`

Stack Trace ：
`2017-9-5 19:14:38 org.bouncycastle.jsse.provider.ProvTlsClient notifyAlertRaised
INFO: Client raised fatal(2) handshake_failure(40) alert: Failed to read record
org.bouncycastle.tls.TlsFatalAlert: handshake_failure(40)
	at org.bouncycastle.tls.AbstractTlsPeer.notifySecureRenegotiation(Unknown Source)
	at org.bouncycastle.tls.TlsClientProtocol.receiveServerHelloMessage(Unknown Source)
	at org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source)
	at org.bouncycastle.tls.RecordStream.readRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.blockForHandshake(Unknown Source)
	at org.bouncycastle.tls.TlsClientProtocol.connect(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:434)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:166)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:133)`

**Comment by peterdettman** [comment]
Sorry, it looks like the beta didn't actually pick up the changes. We'll put together another one tomorrow.

**Comment by bcgit** [comment]
New beta is now up. Try 159b04 or later/

**Comment by zhanglei-1987** [comment]
can't connect on jdk1.6 , but well on jdk1.7 

`java.lang.NoClassDefFoundError: javax/net/ssl/ExtendedSSLSession
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:632)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:616)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
	at org.bouncycastle.jsse.provider.ProvSSLSessionContext.reportSession(ProvSSLSessionContext.java:95)
	at org.bouncycastle.jsse.provider.ProvTlsClient.notifyHandshakeComplete(ProvTlsClient.java:430)
	at org.bouncycastle.tls.TlsProtocol.completeHandshake(TlsProtocol.java:327)
	at org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(TlsClientProtocol.java:239)
	at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(TlsProtocol.java:456)
	at org.bouncycastle.tls.TlsProtocol.processRecord(TlsProtocol.java:374)
	at org.bouncycastle.tls.RecordStream.readRecord(RecordStream.java:222)
	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:593)
	at org.bouncycastle.tls.TlsProtocol.blockForHandshake(TlsProtocol.java:274)
	at org.bouncycastle.tls.TlsClientProtocol.connect(TlsClientProtocol.java:100)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(ProvSSLSocketDirect.java:286)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:434)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:166)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:133)
	at cn.quickly.project.utility.net.SocketFactorysTest.testGetTrustAll(SocketFactorysTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.lang.ClassNotFoundException: javax.net.ssl.ExtendedSSLSession
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
	... 50 more

`

**Comment by peterdettman** [comment]
OK, we've hopefully fixed the backward compatibility issue with JDK6. A new beta should be available soon.

**Comment by bcgit** [comment]
The new beta is now up. Try 159b05 or later.

**Comment by zhanglei-1987** [comment]
thanks very much, it's connect well on jdk1.6!
