### ISSUE TITLE
ProvExtendedSSLSession doesnt support getApplicationBufferSize()

### ISSUE THREAD

**Issue by mondain** [bcgit/bc-java#227]
I am attempting to use the BCJSSE provider for my SSL/TLS needs and I'm running into this exception with version 1.58 (paired with BC version 1.58 on JDK 8).
```
java.lang.UnsupportedOperationException: null
	at org.bouncycastle.jsse.provider.ProvExtendedSSLSession.getApplicationBufferSize(Unknown Source)
	at org.apache.mina.filter.ssl.SslHandler.unwrap(SslHandler.java:763)
	at org.apache.mina.filter.ssl.SslHandler.messageReceived(SslHandler.java:369)
	at org.apache.mina.filter.ssl.SslFilter.messageReceived(SslFilter.java:500)
```
Are there plans to implement this or is there a system property that I should be setting somewhere?

**Comment by peterdettman** [comment]
Thanks for the report - this is actually fixed already by https://github.com/bcgit/bc-java/commit/d2e12f9680f69f11bb78bd74c5d51738794e92cb . Latest beta has this fix and several other improvements in session handling: https://downloads.bouncycastle.org/betas/ .
