### ISSUE TITLE
EDE3 mode unsupported

### ISSUE THREAD

**Issue by rmonico** [bcgit/bc-java#248]
The code:

        Security.addProvider(new BouncyCastleProvider());

        try {
            Cipher.getInstance("DES/EDE3/CBC");
        } catch (Exception e) {
            e.printStackTrace();
        }

Throws:

Caused by: java.security.NoSuchAlgorithmException: can't support mode EDE3
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineSetMode(Unknown Source)
	at javax.crypto.Cipher$Transform.setModePadding(Cipher.java:374)
	at javax.crypto.Cipher.getInstance(Cipher.java:533)

Am I doing something wrong? Thanks in advance!

**Comment by bcgit** [comment]
The format of the name is wrong. I'd guess you probably mean DESede/CBC/PKCS7Padding, assuming EDE3 is an attempt to use Triple-DES
