### ISSUE TITLE
OCSP Request ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by MikeSafonov** [bcgit/bc-java#270]
Hello!
I experienced with some floating bug: sometimes i get this exception when generating OCSP request.
```
DigestCalculator digestCalculator = DigestCalculatorBuilder.build().get(CertificateID.HASH_SHA1);
 OCSPReqBuilder ocspReqBuilder = new OCSPReqBuilder();
ocspReqBuilder.addRequest(new CertificateID(digestCalculator,issuerCertificate, 
               subjectCertificate.getSerialNumber());
    OCSPReq req = ocspReqBuilder.build();
```

SubjectCertificate:
```
-----BEGIN CERTIFICATE-----
MIIB7TCCAZygAwIBAgIBETAIBgYqhQMCAgMwKzELMAkGA1UEBhMCZHAxDzANBgNV
BAoMBkRQUiBDQTELMAkGA1UEAwwCQ0EwHhcNMTcxMjE4MTMyNDQ5WhcNMTgxMjE4
MDAwMDAwWjAzMQ8wDQYDVQQDDAZraXJpbGwxDDAKBgNVBBQTAzEyMzESMBAGCSqG
SIb3DQEJARYDMUAxMIGqMCEGCCqFAwcBAQECMBUGCSqFAwcBAgECAQYIKoUDBwEB
AgMDgYQABIGAZRFc5oWEgXhT03YB9/szAIDaLctXaPgTRYvUmMypUvvVqkI4hwcS
Z+MIhANK7kh00f9qW7/abBtCJo4Nl4ZoaBI+zdtX/Ktbb9xr1w8ar2kKIZILYV/+
3CqNw3SrDJutOVoTjIkHYWjpUStVT/75JEVxPHwUllKnThgGa5EtevGjWTBXMA8G
A1UdDwEB/wQFAwMH+YAwRAYIKwYBBQUHAQEBAf8ENTAzMDEGCCsGAQUFBzABhiVo
dHRwOi8vMTAuNzYuMC4zNzo4MDgwL3B1YmxpYy9jYS9vY3NwMAgGBiqFAwICAwNB
ABxsVQKi9Mza4tfmeZSVyBENKWTtzIy6dYCcWzdmN7vYZYJd2k9qn7kvG6qa5Nsv
qrvy2u90saFaYuPNkNPKZeQ=
-----END CERTIFICATE-----
```

IssuerCertificate:
```
-----BEGIN CERTIFICATE-----
MIIBjjCCATagAwIBAgIBATAIBgYqhQMCAgMwNTELMAkGA1UEBhMCZHAxFDASBgNV
BAoMC0RQUiBST09UIENBMRAwDgYDVQQDDAdST09UIENBMB4XDTE3MDgxNjA2NTUy
NVoXDTE4MDgxNjA2NTUyNVowKzELMAkGA1UEBhMCZHAxDzANBgNVBAoMBkRQUiBD
QTELMAkGA1UEAwwCQ0EwYjAbBgYqhQMCAhMwEQYHKoUDAgIjAgYGKoUDAgIJA0MA
BEBdF197WnDphXsLLiHyTynmRTm8v/ihBoqyBtw4dnaqA8Fiq0bEOIua2e5KfkJ3
0ODhxBpKIsI7yyPV+Y9V3jRfozowODASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1Ud
DwEB/wQEAwIAtzASBgNVHSUBAf8ECDAGBgRVHSUAMAgGBiqFAwICAwNIADBFAiEA
v+uMnJabjxmO24ISOlpRn4KinsRWI/D3WWl0u2M95dICIF7rYMcOWZ87kMI2qVRg
c1YczGInIE6mDnsENpvo5EQP
-----END CERTIFICATE-----

```

Stacktrace:
```
Caused by: org.bouncycastle.cert.ocsp.OCSPException: problem creating ID: java.lang.ArrayIndexOutOfBoundsException: 4
  at org.bouncycastle.cert.ocsp.CertificateID.createCertID(CertificateID.java:153)
  at org.bouncycastle.cert.ocsp.CertificateID.<init>(CertificateID.java:51)
  ... 4 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
  at org.bouncycastle.crypto.digests.GeneralDigest.update(GeneralDigest.java:57)
  at org.bouncycastle.crypto.digests.GeneralDigest.finish(GeneralDigest.java:124)
  at org.bouncycastle.crypto.digests.SHA1Digest.doFinal(SHA1Digest.java:120)
  at org.bouncycastle.jcajce.provider.digest.BCMessageDigest.engineDigest(BCMessageDigest.java:43)
  at java.security.MessageDigest.digest(MessageDigest.java:365)
  at org.bouncycastle.operator.jcajce.JcaDigestCalculatorProviderBuilder$DigestOutputStream.getDigest(JcaDigestCalculatorProviderBuilder.java:111)
  at org.bouncycastle.operator.jcajce.JcaDigestCalculatorProviderBuilder$1$1.getDigest(JcaDigestCalculatorProviderBuilder.java:74)
  at org.bouncycastle.cert.ocsp.CertificateID.createCertID(CertificateID.java:138)
  ... 7 more
```
Java version: 1.8.0_144
BouncyCastle version: 159b08

**Comment by peterdettman** [comment]
Are you possibly sharing a single DigestCalculator between multiple requests (and presumably in separate threads)?

**Comment by MikeSafonov** [comment]
> Are you possibly sharing a single DigestCalculator between multiple requests (and presumably in separate threads)?
Yes. Thanks for reply.  I have fixed my code and all works fine
