### ISSUE TITLE
Certificate Problem with Version 1.56 and higher

### ISSUE THREAD

**Issue by Novaax** [bcgit/bc-java#278]
Hello,

we have a Problem with one of our Certificates. The Problem occurs when we want to load the Keystore over the following Code `keyStore = KeyStore.getInstance("PKCS12", new BouncyCastleProvider()); keyStore.load(inputStream, "ieffect".toCharArray());`  

The following Exception will be thrown:
`java.lang.IllegalArgumentException: invalid info structure in RSA public key
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.BCRSAPublicKey.populateFromPublicKeyInfo(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.BCRSAPublicKey.<init>(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.rsa.KeyFactorySpi.generatePublic(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.getPublicKey(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.x509.X509CertificateObject.getPublicKey(Unknown Source)
	at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
	at java.security.KeyStore.load(KeyStore.java:1445)`

Is there a Problem with the BouncyCastleProvider()?

Certificate:
[46036057_PROD.zip](https://github.com/bcgit/bc-java/files/1631194/46036057_PROD.zip)

**Comment by bcgit** [comment]
No, the modulus in the public key is:

0058593768aeb6d8f3df60b400993525afe233c80a2bd79e65ababe091fe14ec6175505e510f77caefba9d3cd9cfd147f4abbe56d83b66634728bac76f207812ecca8c27aaa0f1119be38375967e569bc9e62576c2d9f55a4f42b16ccf1f16eef0280f73b201b2a3ec4005f1ce4669efa22aa2b32cc7e5af4df292aea0db6c38cf

This is clearly invalid as it starts with a zero byte when none is required. You can still accept the certificate by setting the system property org.bouncycastle.asn1.allow_unsafe_integer to "true", but
as the property name suggest it would be better if the certificate issuer was producing a valid certificate.

**Comment by Novaax** [comment]
Thank you for the fast Answer.

Do we somehow have the possibility to get the faulty certificate or to find out the alias? Or can the error message still be modified by the alias of the certificate with errors?
