### ISSUE TITLE
BCFKS/PBES2: NPE if Pbkdf2 keyLength field is omitted

### ISSUE THREAD

**Issue by aalba6675** [bcgit/bc-java#281]
On 1.59

1. In (ASN.1) PBKDF2-params the keyLength field is OPTIONAL; in PBES2 the desired keyLength can be derived from the encryptionScheme, so it is indeed redundant.
2. This BCFKS KeyStore, constructed so that the keyLength field is omitted in PBKDF2-params, causes a NPE.
3. [Update] The NPE is caused when `generateKey` tries to access the non-existent `keyLength`
```

java.io.IOException: java.lang.NullPointerException                                                    
        at org.bouncycastle.jcajce.provider.keystore.bcfks.BcFKSKeyStoreSpi.decryptData(BcFKSKeyStoreSpi.java:1035)
        at org.bouncycastle.jcajce.provider.keystore.bcfks.BcFKSKeyStoreSpi.engineLoad(BcFKSKeyStoreSpi.java:962)
        at org.bouncycastle.jcajce.provider.keystore.bcfks.BcFKSKeyStoreSpi$Std.engineLoad(BcFKSKeyStoreSpi.java:1108)
        at java.security.KeyStore.load(KeyStore.java:1445)        
```                     
[break.zip](https://github.com/bcgit/bc-java/files/1646770/break.zip) (contains `break.fks`)
The storepass is `changeit`

**Comment by aalba6675** [comment]
Reproducer:
`java Dump break.fks`

```
import java.security.*;
import java.io.*;


public class Dump {

        public static void main(String [] args) {


                System.out.println("hello, world");

                try {
                        KeyStore ks = KeyStore.getInstance("BCFKS");

                        char [] password = "changeit".toCharArray();

                        FileInputStream fis = new FileInputStream(args[0]);
                        ks.load(fis, password);
                }
                catch (Exception e) {
                        e.printStackTrace();
                }
        }
}
```

**Comment by aalba6675** [comment]
If I restore the `keyLength` field to 32, same as the key length of AES-256-CCM, the keystore works:
```
keytool -list -storepass changeit -storetype BCFKS -keystore break-fixed.fks                                                                                                
Keystore type: BCFKS     
Keystore provider: BC    

Your keystore contains 1 entry                     

verisign, Jan 19, 2018, trustedCertEntry,          
Certificate fingerprint (SHA1): 22:D5:D8:DF:8F:02:31:D1:8D:F7:9D:B7:CF:8A:2D:64:C9:3F:6C:3A            
```

**Comment by aalba6675** [comment]
Bad KeyStore:
```
openssl asn1parse -inform DER -in break.fks 
    0:d=0  hl=4 l=1363 cons: SEQUENCE          
    4:d=1  hl=4 l=1177 cons: SEQUENCE          
    8:d=2  hl=3 l= 146 cons: SEQUENCE          
   11:d=3  hl=2 l=   9 prim: OBJECT            :PBES2
   22:d=3  hl=3 l= 132 cons: SEQUENCE          
   25:d=4  hl=2 l=  98 cons: SEQUENCE          
   27:d=5  hl=2 l=   9 prim: OBJECT            :PBKDF2
   38:d=5  hl=2 l=  85 cons: SEQUENCE          
   40:d=6  hl=2 l=  64 prim: OCTET STRING      [HEX DUMP]:55930A10574F1EB304F36023AB9A77F6AE3873AC2BC2C727B5258D79F92B9EF8EF5574E860A7CBC883AD999D22076D9D110C544E706714451A2C8C159901D65D
  106:d=6  hl=2 l=   3 prim: INTEGER           :C800
  111:d=6  hl=2 l=  12 cons: SEQUENCE          
  113:d=7  hl=2 l=   8 prim: OBJECT            :hmacWithSHA512
  123:d=7  hl=2 l=   0 prim: NULL              
```

**Comment by aalba6675** [comment]
Good KeyStore:
```
openssl asn1parse -inform DER -in break-fixed.fks 
    0:d=0  hl=4 l=1366 cons: SEQUENCE          
    4:d=1  hl=4 l=1180 cons: SEQUENCE          
    8:d=2  hl=3 l= 149 cons: SEQUENCE          
   11:d=3  hl=2 l=   9 prim: OBJECT            :PBES2
   22:d=3  hl=3 l= 135 cons: SEQUENCE          
   25:d=4  hl=2 l= 101 cons: SEQUENCE          
   27:d=5  hl=2 l=   9 prim: OBJECT            :PBKDF2
   38:d=5  hl=2 l=  88 cons: SEQUENCE          
   40:d=6  hl=2 l=  64 prim: OCTET STRING      [HEX DUMP]:850284F040781B482D021F890686C4E7B3AA01E23E8642CD667EE2D26E6A1CC8EDEC94B5815C661244F7B55E6CF33CC368B6D8284D13374315B2F7910339AEE8
  106:d=6  hl=2 l=   3 prim: INTEGER           :C800
  111:d=6  hl=2 l=   1 prim: INTEGER           :20
  114:d=6  hl=2 l=  12 cons: SEQUENCE          
  116:d=7  hl=2 l=   8 prim: OBJECT            :hmacWithSHA512
  126:d=7  hl=2 l=   0 prim: NULL              
  128:d=4  hl=2 l=  30 cons: SEQUENCE          
  130:d=5  hl=2 l=   9 prim: OBJECT            :aes-256-ccm
  141:d=5  hl=2 l=  17 cons: SEQUENCE          
  143:d=6  hl=2 l=  12 prim: OCTET STRING      [HEX DUMP]:31707151D4AFC127873B7154
  157:d=6  hl=2 l=   1 prim: INTEGER           :08
```

**Comment by aalba6675** [comment]
The NPE is caused by the `generateKey()` method at line 682. This method assumes that the key length is always available as part of the PBKDF2-param object.

In PBES2 the key length can be obtained from the sister encryptionScheme object so may be omitted form the keyDerivationFunc parameters.

**Comment by bcgit** [comment]
I'll look into it, but for the moment please treat the key length as required for the purposes of defining a BCFKS file.

**Comment by bcgit** [comment]
Okay, this is now done - in the case of BC the keysize can be optional if it can be determined for the OID. The latest version on https://www.bouncycastle.org/betas now supports this.

We will try to also add this to BC-FJA 1.0.2
