### ISSUE TITLE
NullPointerException in X509TrustedCertificateBlock when using PEMParser to read a trusted cert

### ISSUE THREAD

**Issue by RyanBard** [bcgit/bc-java#310]
I've been having problems with PEMParser when trying to read in a trusted certificate (locally created root CA).  I'm not sure I've created it correctly, but OpenSSL seems happy and nothing I saw in the error message (or while trying to trace the code in a debugger) indicated to me that I've done something wrong (which is probably just lack of knowledge on my part).

Commands I used to create the cert:
```
openssl genrsa -out ca.key 4096
openssl req -new -key ca.key -out ca.csr
openssl x509 -req -days 3650 -in ca.csr -trustout -signkey ca.key -out ca.crt
```
(It's possible I've messed something up with the cert; I haven't played around with root CA certs often enough to feel confident that I didn't make a mistake.  OpenSSL seemed happy with the certs I was creating -- I verified some certs signed by this CA and an intermediate with: `openssl verify -verbose -purpose sslserver -CAfile <(cat intermediate.crt ca.crt) child.crt` and they verified ok.)

OpenSSL Version:
```
LibreSSL 2.2.7
```

uname -a:
```
Darwin *obfuscated* 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```

java -version:
```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

bc version:
```
bcprov-debug-jdk15on-1.59.jar
bcpkix-jdk15on-1.59.jar
```

Example code to reproduce the issue:
```java
import org.bouncycastle.cert.X509CertificateHolder;
import org.bouncycastle.cert.jcajce.JcaX509CertificateConverter;
import org.bouncycastle.openssl.PEMParser;

import java.io.FileInputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.security.cert.X509Certificate;

public class Main {

    private static X509Certificate getCert(String pemFilePath) throws Exception {
        InputStream cert = new FileInputStream(pemFilePath);
        PEMParser parser = new PEMParser(new InputStreamReader(cert));
        Object o;
        do {
            o = parser.readObject();
            if (o instanceof X509CertificateHolder) {
                X509CertificateHolder certificateHolder = (X509CertificateHolder) o;
                return new JcaX509CertificateConverter().getCertificate(certificateHolder);
            }
        } while (o != null);
        throw new RuntimeException("No certificate found in PEM file!");
    }

    public static void main(String[] args) throws Exception {
        System.out.println(getCert("./ca.crt"));
    }

}
```

The stacktrace (with debug build's jar to avoid the "Unknown Source"):
```
Exception in thread "main" org.bouncycastle.openssl.PEMException: problem parsing cert: java.lang.NullPointerException
	at org.bouncycastle.openssl.PEMParser$X509TrustedCertificateParser.parseObject(PEMParser.java:366)
	at org.bouncycastle.openssl.PEMParser.readObject(PEMParser.java:92)
	at Main.getCert(Main.java:17)
	at Main.main(Main.java:27)
Caused by: java.lang.NullPointerException
	at org.bouncycastle.openssl.X509TrustedCertificateBlock.<init>(X509TrustedCertificateBlock.java:29)
	at org.bouncycastle.openssl.PEMParser$X509TrustedCertificateParser.parseObject(PEMParser.java:362)
	... 3 more
```

The offending trusted cert:
```
-----BEGIN TRUSTED CERTIFICATE-----
MIIFVjCCAz4CCQDKCppIGaPSADANBgkqhkiG9w0BAQUFADBtMQswCQYDVQQGEwJV
UzELMAkGA1UECAwCR0ExEDAOBgNVBAcMB0F0bGFudGExDTALBgNVBAoMBEFjbWUx
ETAPBgNVBAMMCGFjbWUuY29tMR0wGwYJKoZIhvcNAQkBFg5hZG1pbkBhY21lLmNv
bTAeFw0xODAzMDgyMjQ3NDBaFw0yODAzMDUyMjQ3NDBaMG0xCzAJBgNVBAYTAlVT
MQswCQYDVQQIDAJHQTEQMA4GA1UEBwwHQXRsYW50YTENMAsGA1UECgwEQWNtZTER
MA8GA1UEAwwIYWNtZS5jb20xHTAbBgkqhkiG9w0BCQEWDmFkbWluQGFjbWUuY29t
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAy6Y3k+YvorOy/QSUViIa
aP8emMHtcsvZ5eKth3klolBwyZHqqGHsomepd1Rf4V5Xs+AqMosOiq52vPFQNf76
54wLYLIw/T6AqNhkGgy+wOwZ4DY2wgtZ61T94RneQVvhnLngfRP9WqdJhcHjFwWa
YUaBQnreRguSae8uG6JXIOvva24/xHCtHZA9RrN8Q6ajlEJsaX8Nmt8w55I1m2xM
bGXcrpIjv2z2/vxjK4pXiwXc1biu5ybSiwLcljqih0vBs2jKA9n9aJW79YItGxli
Dpowm/hUpayUPUefO7HUZNR8oD3pNcUIPGg7/mkGABjp4Z7iSRbglh8Yc5iOdrhp
G/lQMwB4uHjZs4zVgxhx/dmJRXi2mlBojnL+epanNlOM14y1rYLFZEltIuHgk8gs
M76yUIzLlLbm8xfh+9Q5n8S/wxxrJPvBLZgDzaQw6BA/UnbsGv4B7FcsxYUajGhQ
jhJ8kZfQ+zwYachv/SbnxtBQ/p/76zeVkgdX3Jpbhe5y+ZLG6dYvjtKcq/iwAvsS
8RDdYeP1e7BzOVdiOu1aDri3GcvvKcvO7+iCY1IyGvVnnL/c1ofojJ4yVtHgKlak
PGAKgROtE27QGmZOW31zTXPrORYqDczFMXjVHwF63x9EM87mZmk3y54Di/VjY9Ah
4HtB7nnuvThREXMbQ1a5AxkCAwEAATANBgkqhkiG9w0BAQUFAAOCAgEAmBe9TUp6
Oyz6w92f0Q+Oy9JvJWfDc43zj0KGHylXfaGCaUmG8+QMdZJ3aDDqDc9lqGfKzTbx
fYpZMDN/qiTl83eJlD3jQCgXYlov3STM2YRr6BwlwrnmGR/8vE4fspAhpkkLBxhQ
n9RrUTiT8l0TjZirjrWiNiwE7XaPxt5zcC+VllJg5gIAzOwvwr4iaLBY86dkCmQZ
ZckjVH12gJ7Gn6S+IkWK0Mn5dJOaRrOUjfULHwc2CsDa+ERLOBTRoiu2jRyP2Z4h
8tMgkbKZJjlZUToHzhpj3LoWZ6ztkZoEV9jm3BhA4KfP2SO5mJumuBpI/BpspQkY
c4oqMjbZQhGnLH4CJ2nwhD8QM4zI6Bo/XDzOYObjDYK3bS+WvB6DsEJZE5QRBFkU
SkMhoYGttNIEvErA97xub6nJ1Xwn6pB18CVdoADpHzHpEApDjJMDyFbbJoXC1uvD
xk6xxKMtytGv9DtqPd9aFhgDzfOQHT2Hz0ysGdrSNs6VphDKR/2mWt66Q/3HsGoA
McAhVxrKUKM4QCHBhJcH6F8zw4PKkhwvueVqaIq76vhVAmd46RLVM1lvToKyH/Ed
gaYyNmGTx79IvTAmMExEOuTnL7JpV/V8iE9jKE3N/lrNGuF7B6rSc4PE9GZAEYRS
CZWVyzvUAsbkZFD6rokDNtqZLpxKwteOMxE=
-----END TRUSTED CERTIFICATE-----
```

**Comment by RyanBard** [comment]
I'm pretty sure my trusted cert created was not correct.  When I follow along with https://jamielinux.com/docs/openssl-certificate-authority/introduction.html I see many options for the CA that I never gave, so I'm probably missing something required and tripped up the bc code by not having something that should be required.

I ended up testing my (probably incorrect) cert chain w/ a pkix path validator in java (I ended up converting these certs from pem to der) and it wasn't happy about the path, so I'm not sure why openssl was so forgiving.

I'm now using (probably correct) certs that I created from jamielinux's tutorial and both java's pkix and bc's pem parser are happy with them (however, I ended up with CERTIFICATE for the CA instead of a TRUSTED CERTIFICATE, so it's not going through the same code path).

If you decide not to close this ticket as invalid (if you want to try to determine an error message to send back instead of a NullPointerException), here are more details of what I did when creating the invalid cert chain:

```
openssl genrsa -out ca.key 4096
openssl req -new -key ca.key -out ca.csr -config <(cat ca.txt)
openssl x509 -req -days 3650 -in ca.csr -trustout -signkey ca.key -out ca.crt
```

ca.txt:
```
[req]
default_bits = 4096
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn

[ dn ]
C = US
ST = GA
L = Atlanta
O = VMware
OU = AirWatch
emailAddress = admin@alice.com
CN = alice.com

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = alice.com
```

(I'm leaving out the info for generating my intermediate and child keys/certs/etc. because they don't seem relevant for the pem parser failing to load the ca.crt)

**Comment by bcgit** [comment]
Okay, so the issue is the "trusted certificate" doesn't have a trust block and the parser is expecting to find one. Can't say I've seen one of these before, still it looks like you managed to generate one. I've fixed the parser so that it will handle a null trust block by simply setting the trustBlock in the object to null if it is absent.
