### ISSUE TITLE
Blake2bDigest.compress(Unknown Source)

### ISSUE THREAD

**Issue by catena2w** [bcgit/bc-java#324]
I have such a piece of Scala code 
```scala
override def hash(inputs: Message*): Array[Byte] = {
    val digestFn = new Blake2bDigest(DigestSize * 8)
    inputs.foreach(i => digestFn.update(i, 0, i.length))
    val res = new Array[Byte](DigestSize)
    digestFn.doFinal(res, 0)
    res
  }
```
that sometimes throws NPE expection:
```
java.lang.NullPointerException was thrown.
java.lang.NullPointerException
	at org.bouncycastle.crypto.digests.Blake2bDigest.compress(Unknown Source)
	at org.bouncycastle.crypto.digests.Blake2bDigest.doFinal(Unknown Source)
```

Can you please comment, what may be wrong? 
Relates to https://github.com/ScorexFoundation/AVLIODB/issues/19

**Comment by catena2w** [comment]
Looks like it's because of concurrent access to this function, better error massage may be useful
