### ISSUE TITLE
ArrayIndexOutOfBounds in CFBBlockCipher

### ISSUE THREAD

**Issue by geNAZt** [bcgit/bc-java#332]
Exception in thread "ProxProx Thread #4154" java.lang.ArrayIndexOutOfBoundsException: 16
        at org.bouncycastle.crypto.modes.CFBBlockCipher.encryptByte(Unknown Source)
        at org.bouncycastle.crypto.modes.CFBBlockCipher.calculateByte(Unknown Source)
        at org.bouncycastle.crypto.StreamBlockCipher.processBytes(Unknown Source)
        at org.bouncycastle.crypto.modes.CFBBlockCipher.processBlock(Unknown Source)
        at org.bouncycastle.crypto.BufferedBlockCipher.processBytes(Unknown Source)
        at io.gomint.proxprox.network.EncryptionHandler.processCipher(EncryptionHandler.java:321)

We use this 

```java
    private BufferedBlockCipher createCipher( boolean encryptor, byte[] key, byte[] iv ) {
        BufferedBlockCipher cipher = new BufferedBlockCipher( new CFBBlockCipher( new AESEngine(), 8 ) );
        cipher.init( encryptor, new ParametersWithIV( new KeyParameter( key ), iv ) );
        return cipher;
    }
```

to generate the cipher. We use SHA256 hashes as keys, and use the first 16 bytes as IV. This does not happen all the time but users reported it to us and we think its a issue in bouncycastle since we saw this in 1.54 and in latest release 1.59

**Comment by bcgit** [comment]
Are you absolutely sure the cipher object is not being used by more than one thread? Ciphers have to carry internal state as they are operating, they cannot be shared between threads.

**Comment by bcgit** [comment]
Closed as likely to be a usage error.
