### ISSUE TITLE
ECElGamal encryption with ECGOST keys

### ISSUE THREAD

**Issue by MikeSafonov** [bcgit/bc-java#335]
Hello,
Im trying to use EC ElGamal encryption with ECGOST keys (bcprov-jdk15on:1.59)

```
        BCECGOST3410PublicKey pubKey = (BCECGOST3410PublicKey) publicKey;
        BCECGOST3410PrivateKey privKey = (BCECGOST3410PrivateKey) privateKey;

        ECParameterSpec parameters = pubKey.getParameters();
        ECDomainParameters domainParameters = new ECDomainParameters(parameters.getCurve(), parameters.getG(), parameters.getN());
        ECPublicKeyParameters publicKeyParameters = new ECPublicKeyParameters(pubKey.getQ(), domainParameters);
        ECPrivateKeyParameters privateKeyParameters = new ECPrivateKeyParameters(privKey.getD(), domainParameters);
        BigInteger value = BigInteger.valueOf(20);


        ParametersWithRandom pRandom = new ParametersWithRandom(publicKeyParameters, new SecureRandom());
        ECEncryptor encryptor = new ECElGamalEncryptor();
        encryptor.init(pRandom);

        ECPoint data = privateKeyParameters.getParameters().getG().multiply(value);

        ECPair pair = encryptor.encrypt(data);

        ECDecryptor decryptor = new ECElGamalDecryptor();
        decryptor.init(privateKeyParameters);

        ECPoint result = decryptor.decrypt(pair);
```

```
java.lang.IllegalArgumentException: 'points' entries must be null or on this curve

	at org.bouncycastle.math.ec.ECCurve.checkPoints(ECCurve.java:529)
	at org.bouncycastle.math.ec.ECCurve.normalizeAll(ECCurve.java:262)
	at org.bouncycastle.math.ec.ECCurve.normalizeAll(ECCurve.java:239)
	at org.bouncycastle.crypto.ec.ECElGamalEncryptor.encrypt(ECElGamalEncryptor.java:77)
```

**Comment by bcgit** [comment]
Thanks for the report. This should now be fixed in the latest beta.

You can find it on https://www.bouncycastle.org/betas 160b08 or later.
