### ISSUE TITLE
JSchException: verify: false for the version 1.59

### ISSUE THREAD

**Issue by javadev** [bcgit/bc-java#344]
Hi,

I found an error in our sftp server emulator.

When I add library 1.59 I see an exception in log:

```
2018-05-15 10:39:31,410 SimpleGeneratorHostKeyProvider [pool-2-thread-1] INFO - Generating host key...
2018-05-15 10:39:38,982 FtpUtils [main] ERROR - could not copy remote files from shopFtpUser@localhost:8026, useProxy: »
2018-05-15 10:39:38,983 FtpUtils [main] DEBUG - stacktrace:
java.io.IOException: com.jcraft.jsch.JSchException: verify: false
...
Caused by: com.jcraft.jsch.JSchException: verify: false
        at com.jcraft.jsch.Session.connect(Session.java:309)
        at com.jcraft.jsch.Session.connect(Session.java:162)
        at util.SFTPHandler.connectAndLogin(SFTPHandler.java:198)
```

but when I switch to the version 1.53 the error disappeared.

**Comment by bcgit** [comment]
I'm guessing, but the issue probably relates to the fact that after 1.53 we started enforcing correct encoding of DER attributes in SignerInfo structures in CMS signatures. If these are CMS signatures that you are talking about, they are not properly constructed and should be fixed.
