### ISSUE TITLE
Cipher.getParameters() exception for CAST6 modes CBC/OFB/CFB, modes ECB/GCM ok

### ISSUE THREAD

**Issue by justincranford** [bcgit/bc-java#420]
In BC 1.60, I am calling these APIs for different CAST6 transforms. I tried with 5 different modes. That last call to getParameters() works for 2 modes, and throws an unexpected exception for 3 modes:
- Cipher.getInstance()
- Cipher.init()
- Cipher.doFinal()
- Cipher.getParameters()

For these CAST6 modes and padding, all 4 calls worked:
- CAST6/ECB/PKCS5Padding
- CAST6/GCM/NoPadding

For these CAST6 modes and padding, the first 3 calls work, and the last call throws an unexpected exception:
- CAST6/CBC/PKCS5Padding
- CAST6/OFB/PKCS5Padding
- CAST6/CFB/PKCS5Padding

Here is the unexpected exception from BC when making that call to getParameters(). I expect it to return valid, random generate parameters instead of throwing an exception:

```
java.lang.RuntimeException: java.security.NoSuchAlgorithmException: no such algorithm: CAST6 for provider BC
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineGetParameters(Unknown Source)
	at javax.crypto.Cipher.getParameters(Cipher.java:995)

```

Here is a code snippet to demonstrate the Cipher.getParameters() results for the 2 working and 3 non-working modes of CAST6. Key size did not seem to matter:

```
final SecureRandom SECURE_RANDOM = SecureRandom.getInstanceStrong();
final byte[]       CLEAR_BYTES   = "Clear".getBytes("UTF-8");
final String[] cast6Providers        = new String[] {"BC"};
final String[] cast6CipherTransforms = new String[] {"CAST6/ECB/PKCS5Padding", "CAST6/CBC/PKCS5Padding", "CAST6/OFB/PKCS5Padding", "CAST6/CFB/PKCS5Padding", "CAST6/GCM/NoPadding"};
final int[]    cast6KeyLengths       = new int[]    {128,160,192,224,256};

for (String cast6Provider : cast6Providers) {
	for (int cast6KeyLength : cast6KeyLengths) {
		final KeyGenerator keyGenerator = KeyGenerator.getInstance("CAST6", "BC");
		keyGenerator.init(cast6KeyLength, SECURE_RANDOM);
		final SecretKey cast6SecretKey = keyGenerator.generateKey();
		for (String cast6CipherTransform : cast6CipherTransforms) {
			final Cipher cipher = Cipher.getInstance(cast6CipherTransform, cast6Provider);
			cipher.init(Cipher.ENCRYPT_MODE, cast6SecretKey, SECURE_RANDOM);
			final byte[] cipherBytes = cipher.doFinal(CLEAR_BYTES);
			try {
				final AlgorithmParameters algorithmParameters = cipher.getParameters();
				System.out.println("CAST6 size " + cast6KeyLength + ", transform " + cast6CipherTransform + ", provider " + cast6Provider + ": Cipher.getParameters() succeeded");
				} catch(Exception e) {
				System.out.println("CAST6 size " + cast6KeyLength + ", transform " + cast6CipherTransform + ", provider " + cast6Provider + ": Cipher.getParameters() failed");
//				e.printStackTrace();
			}
		}
		System.out.println(" ");
	}
}
```

Here is the output I get from the above code snippet:

```
CAST6 size 128, transform CAST6/ECB/PKCS5Padding, provider BC: Cipher.getParameters() succeeded
CAST6 size 128, transform CAST6/CBC/PKCS5Padding, provider BC: Cipher.getParameters() failed
CAST6 size 128, transform CAST6/OFB/PKCS5Padding, provider BC: Cipher.getParameters() failed
CAST6 size 128, transform CAST6/CFB/PKCS5Padding, provider BC: Cipher.getParameters() failed
CAST6 size 128, transform CAST6/GCM/NoPadding, provider BC: Cipher.getParameters() succeeded
 
CAST6 size 160, transform CAST6/ECB/PKCS5Padding, provider BC: Cipher.getParameters() succeeded
CAST6 size 160, transform CAST6/CBC/PKCS5Padding, provider BC: Cipher.getParameters() failed
CAST6 size 160, transform CAST6/OFB/PKCS5Padding, provider BC: Cipher.getParameters() failed
CAST6 size 160, transform CAST6/CFB/PKCS5Padding, provider BC: Cipher.getParameters() failed
CAST6 size 160, transform CAST6/GCM/NoPadding, provider BC: Cipher.getParameters() succeeded
 
CAST6 size 192, transform CAST6/ECB/PKCS5Padding, provider BC: Cipher.getParameters() succeeded
CAST6 size 192, transform CAST6/CBC/PKCS5Padding, provider BC: Cipher.getParameters() failed
CAST6 size 192, transform CAST6/OFB/PKCS5Padding, provider BC: Cipher.getParameters() failed
CAST6 size 192, transform CAST6/CFB/PKCS5Padding, provider BC: Cipher.getParameters() failed
CAST6 size 192, transform CAST6/GCM/NoPadding, provider BC: Cipher.getParameters() succeeded
 
CAST6 size 224, transform CAST6/ECB/PKCS5Padding, provider BC: Cipher.getParameters() succeeded
CAST6 size 224, transform CAST6/CBC/PKCS5Padding, provider BC: Cipher.getParameters() failed
CAST6 size 224, transform CAST6/OFB/PKCS5Padding, provider BC: Cipher.getParameters() failed
CAST6 size 224, transform CAST6/CFB/PKCS5Padding, provider BC: Cipher.getParameters() failed
CAST6 size 224, transform CAST6/GCM/NoPadding, provider BC: Cipher.getParameters() succeeded
 
CAST6 size 256, transform CAST6/ECB/PKCS5Padding, provider BC: Cipher.getParameters() succeeded
CAST6 size 256, transform CAST6/CBC/PKCS5Padding, provider BC: Cipher.getParameters() failed
CAST6 size 256, transform CAST6/OFB/PKCS5Padding, provider BC: Cipher.getParameters() failed
CAST6 size 256, transform CAST6/CFB/PKCS5Padding, provider BC: Cipher.getParameters() failed
CAST6 size 256, transform CAST6/GCM/NoPadding, provider BC: Cipher.getParameters() succeeded
```

**Comment by bcgit** [comment]
Thanks for the report. I've added the missing algorithm parameters class. Will show up in 161b14.
