### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kalallokesh** [bcgit/bc-java#428]
Getting muliple ArrayIndexOutOfBoundsException in our android app.
Is there any to fix it.
**Fatal Exception: java.lang.ArrayIndexOutOfBoundsExceptionsrc.length=112 srcPos=96 dst.length=16 dstPos=16 length=16at java.lang.System.arraycopy(System.java:282)
at com.android.org.bouncycastle.crypto.paddings.PaddedBufferedBlockCipher.processBytes(PaddedBufferedBlockCipher.java:221)
at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$BufferedGenericBlockCipher.processBytes(BaseBlockCipher.java:1000)
at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(BaseBlockCipher.java:844)
at javax.crypto.Cipher.doFinal(Cipher.java:1502)**

**Comment by bcgit** [comment]
Probably. It's impossible to tell from the detail provided though.
