### ISSUE TITLE
why not support algorithm SM2/3/4/9 and ZUC in provider?

### ISSUE THREAD

**Issue by zhanglei-1987** [bcgit/bc-java#440]

**Comment by bcgit** [comment]
Which version of the provider are you looking at? We already support SM2/3/4.

**Comment by zhanglei-1987** [comment]
java.security.NoSuchAlgorithmException: no such algorithm: SM2 for provider BC

1.60

**Comment by zhanglei-1987** [comment]
Cipher cipher = Cipher.getInstance("SM2", new BouncyCastleProvider());
cipher.init(Cipher.ENCRYPT_MODE, privateKey);

java.security.NoSuchAlgorithmException: No such algorithm: SM2
	at javax.crypto.Cipher.getInstance(Cipher.java:687)


1.60

**Comment by bcgit** [comment]
Ah, you are talking about SM2 in cipher mode. I've added it, have a look at https://www.bouncycastle.org/betas 161b23 or later. Just keep in mind SM2 are EC keys, so you use the EC key pair generator. Let me know how it goes. There is an example of usage in SM2CipherTest in the JCE test classes.

**Comment by BobFirstAccount** [comment]
@bcgit I am using 1.61 release version, but same error comes out.
SM2Cipher: Exception: java.security.NoSuchAlgorithmException: No such algorithm: SM2
java.security.NoSuchAlgorithmException: No such algorithm: SM2
	at javax.crypto.Cipher.getInstance(Cipher.java:687)
	at javax.crypto.Cipher.getInstance(Cipher.java:595)
	at org.bouncycastle.jce.provider.test.SM2CipherTest.performTest(SM2CipherTest.java:56)
	at org.bouncycastle.util.test.SimpleTest.perform(Unknown Source)
	at org.bouncycastle.util.test.SimpleTest.runTest(Unknown Source)
	at org.bouncycastle.util.test.SimpleTest.runTest(Unknown Source)
	at org.bouncycastle.jce.provider.test.SM2CipherTest.main(SM2CipherTest.java:116)

**Comment by bcgit** [comment]
I've checked, it's there. It might be worth checking your class path, it looks like an older version of the provider may have gotten introduced as well.

**Comment by bcgit** [comment]
Zuc is now supported in the current beta of 1.63.
