### ISSUE TITLE
Connection establish failure on one unsupported cipher suite

### ISSUE THREAD

**Issue by Gilis95** [bcgit/bc-java#476]
Hello in `org.bouncycastle.jsse.provider.ProvSSLContextSpi#isSupportedCipherSuites` you fail in case one unsupported cipher suite is found among provided array of cipher suites, instead of ignoring it. This causes an issue to us, in case of creating `SSLSocket` with specific array of cipher suites provided by user.

Version of library we use: 1.60
Example stack trace:
```
java.lang.IllegalArgumentException: 'cipherSuites' cannot be null, or contain unsupported cipher suites
        at org.bouncycastle.jsse.provider.ProvSSLParameters.setCipherSuites(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.setEnabledCipherSuites(Unknown Source)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:386)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by peterdettman** [comment]
Thanks, we've updated the code to tolerate unrecognised cipher suites, which is compatible with latest JDK behaviour. Note that null or "" values are still not allowed and will result in an exception (same as JDK).
