### ISSUE TITLE
has unsigned entries - module-info.class for jdk15on-1.61

### ISSUE THREAD

**Issue by looly** [bcgit/bc-java#477]
```java
Provider provider = new org.bouncycastle.jce.provider.BouncyCastleProvider();
KeyGenerator.getInstance(algorithm, provider);
```

When I use this code, throw below error, 1.60 is OK.

```java
java.lang.SecurityException: JCE cannot authenticate the provider BC
	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:114)
	at javax.crypto.KeyGenerator.getInstance(KeyGenerator.java:287)
	at cn.hutool.crypto.KeyUtil.getKeyGenerator(KeyUtil.java:518)
	at cn.hutool.crypto.KeyUtil.generateKey(KeyUtil.java:98)
	at cn.hutool.crypto.KeyUtil.generateKey(KeyUtil.java:82)
	at cn.hutool.crypto.KeyUtil.generateKey(KeyUtil.java:123)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.<init>(SymmetricCrypto.java:90)
	at cn.hutool.crypto.symmetric.SymmetricCrypto.<init>(SymmetricCrypto.java:59)
	at cn.hutool.crypto.SmUtil.sm4(SmUtil.java:125)
	at cn.hutool.crypto.test.SmTest.sm4Test(SmTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: java.util.jar.JarException: file:/D:/m2_repo/org/bouncycastle/bcprov-jdk15on/1.61/bcprov-jdk15on-1.61.jar has unsigned entries - module-info.class
	at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:462)
	at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:322)
	at javax.crypto.JarVerifier.verify(JarVerifier.java:250)
	at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:161)
	at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:187)
	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:110)
	... 32 more
```

**Comment by bcgit** [comment]
What JVM is this with?

**Comment by looly** [comment]
JDK1.7.0_79

**Comment by looly** [comment]
test pass on 1.60, but fail on 1.61, maybe `module-info.class`  cause it?

**Comment by bcgit** [comment]
Is that Oracle or OpenJDK?

**Comment by looly** [comment]
Oracle

**Comment by bcgit** [comment]
Okay. Try what's in https://www.bouncycastle.org/betas now. Let me know how it goes.

**Comment by looly** [comment]
Thank you, "bcprov-jdk15on-162b07.jar" is OK.
