### ISSUE TITLE
Errors when reading PKCS7 Files

### ISSUE THREAD

**Issue by git-blame** [bcgit/bc-java#499]
I am using Apache's tika parser v1.20 on PKCS7 files. I believe it is using BC v1.60 or v1.61. However, there is always a Java exception and it seems to be from the BC code.

* A signed file: `echo "hello world" | openssl cms -sign -inkey key.pem -signer cert.pem -md sha256 -outform der -nodetach -out sign.p7`
* A digest file: ` echo "hello world" | openssl cms -digest_create -md sha256 -outform der -out digest.p7`
* A pkcs7 file from an existing issue: https://issues.apache.org/jira/projects/TIKA/issues/TIKA-1997

I don't know if it is caused by Tika using BC incorrectly or BC itself.
```
java  -jar tika-app-1.20.jar --config=tika.xml sign.p7
Exception in thread "main" org.apache.tika.exception.TikaException: TIKA-198: Illegal IOException from org.apache.tika.parser.ParserDecorator$1@ae45eb6
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:286)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
<snip>
Caused by: java.io.EOFException: DEF length 933 object truncated by 879
	at org.bouncycastle.asn1.DefiniteLengthInputStream.read(Unknown Source)
	at org.bouncycastle.asn1.DefiniteLengthInputStream.read(Unknown Source)
	at org.bouncycastle.asn1.DefiniteLengthInputStream.read(Unknown Source)
	at org.bouncycastle.asn1.DefiniteLengthInputStream.read(Unknown Source)
	at org.bouncycastle.asn1.DefiniteLengthInputStream.read(Unknown Source)
	at org.bouncycastle.asn1.DefiniteLengthInputStream.read(Unknown Source)
```

```
java  -jar tika-app-1.20.jar --config=tika.xml digest.p7
Exception in thread "main" org.apache.tika.exception.TikaException: Unexpected RuntimeException from org.apache.tika.parser.ParserDecorator$1@5dfcfece
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:282)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
	at org.apache.tika.cli.TikaCLI$OutputType.process(TikaCLI.java:209)
	at org.apache.tika.cli.TikaCLI.process(TikaCLI.java:496)
	at org.apache.tika.cli.TikaCLI.main(TikaCLI.java:149)
Caused by: java.lang.ClassCastException: org.bouncycastle.asn1.DERSequenceParser cannot be cast to org.bouncycastle.asn1.ASN1SetParser
	at org.bouncycastle.asn1.cms.SignedDataParser.getDigestAlgorithms(Unknown Source)
	at org.bouncycastle.cms.CMSSignedDataParser.<init>(Unknown Source)
	at org.bouncycastle.cms.CMSSignedDataParser.<init>(Unknown Source)
	at org.apache.tika.parser.crypto.Pkcs7Parser.parse(Pkcs7Parser.java:68)
```

```
java  -jar tika-app-1.20.jar --config=tika.xml test.xml.p7m
Exception in thread "main" org.apache.tika.exception.TikaException: TIKA-198: Illegal IOException from org.apache.tika.parser.ParserDecorator$1@47c62251
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:286)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
	at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143)
<snip>
Caused by: java.io.EOFException
	at org.bouncycastle.asn1.IndefiniteLengthInputStream.read(Unknown Source)
	at org.bouncycastle.asn1.IndefiniteLengthInputStream.read(Unknown Source)
	at org.bouncycastle.asn1.IndefiniteLengthInputStream.read(Unknown Source)
	at org.bouncycastle.asn1.IndefiniteLengthInputStream.read(Unknown Source)
	at org.bouncycastle.asn1.IndefiniteLengthInputStream.read(Unknown Source)
	at org.bouncycastle.asn1.IndefiniteLengthInputStream.read(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readObject(Unknown Source)
	at org.bouncycastle.asn1.ConstructedOctetStream.read(Unknown Source)
```

**Comment by git-blame** [comment]
Example files can be created via specified openssl commands or as attachments at https://issues.apache.org/jira/browse/TIKA-2857

**Comment by bcgit** [comment]
These all parse correctly with BC. Looking at the stack trace it looks like the streaming API is being used - it would be worth checking that it is being used correctly - as it's streaming you only get one shot at the data, and failure to read objects out of the stream that may be optional will result in the next step in the parsing failing.

**Comment by git-blame** [comment]
My guess would be that the streaming in Tika is "generic" in that it doesn't know anything about PCKS7 structures especially regarding optional objects. It probably depends on the underlying classes to correctly parse the data. In any case, I will update the Tika issue with your comment.

As an aside, which BC tool are you using to read these files? Is it built with the BC source?

**Comment by bcgit** [comment]
Yes, everything I do is built with the BC source. I just wrote a small app for these.

Closing, assuming this will be dealt with elsewhere.
