### ISSUE TITLE
InvalidCipherTextException while decrypting

### ISSUE THREAD

**Issue by keerthiis** [bcgit/bc-java#509]
Hi ,I am using Bouncy castle to decrypt the file and getting the following exception. I have the private key ,the public key and the passphrase.

Caused by: org.bouncycastle.crypto.InvalidCipherTextException: block incorrect
	at org.bouncycastle.crypto.encodings.PKCS1Encoding.decodeBlock(PKCS1Encoding.java:405)
	at org.bouncycastle.crypto.encodings.PKCS1Encoding.processBlock(PKCS1Encoding.java:201)
	at org.bouncycastle.crypto.BufferedAsymmetricBlockCipher.doFinal(BufferedAsymmetricBlockCipher.java:146)
	at org.bouncycastle.openpgp.operator.bc.BcPublicKeyDataDecryptorFactory.recoverSessionData(BcPublicKeyDataDecryptorFactory.java:97)
	... 4 more

Process finished with exit code 1

**Comment by bcgit** [comment]
The private key will be incorrect. It could be that it's not linked up with the correct PGP public key encrypted data object.
