### ISSUE TITLE
Getting compilation error after upgrading to BC version 1.61 in android application.

### ISSUE THREAD

**Issue by CyborgRahil** [bcgit/bc-java#519]
- While upgrading the version of BC to 1.61 i got compilation error in build.

- If i change the BC version to 1.60 compilation error is resolved.
Please provide your valuable feedback.

Below is the exception its :
`error processing /Users/rahil.ali/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcpkix-jdk15on/1.61/89bb3aa5b98b48e584eee2a7401b7682a46779b4/bcpkix-jdk15on-1.61.jarjava.lang.RuntimeException 
at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:148)
at org.objectweb.asm.ClassReader.readModule(ClassReader.java:731)
at org.objectweb.asm.ClassReader.accept(ClassReader.java:632)
at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)        at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:144)        at com.android.builder.desugaring.DesugaringClassAnalyzer.analyzeJar(DesugaringClassAnalyzer.java:92)        at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:63)        at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.lambda$getInitalGraphData$4(DesugarIncrementalTransformHelper.java:150)`

**Comment by bcgit** [comment]
I'm not 100% sure, but it may be due to the module_info file. Try the current beta at https://www.bouncycastle.org/betas these are "proper" multi-release jar files, I think they should resolve your issue.

**Comment by peterdettman** [comment]
This is an [issue](https://issuetracker.google.com/issues/77587908) that appears to have been fixed in the Android Gradle Plugin (AGP) as of 3.3.0. I'd recommend updating Android Studio to the latest version, or else at least updating [AGP](https://developer.android.com/studio/releases/gradle-plugin) itself. You may alsoneed to update your gradle version accordingly.

**Comment by dghgit** [comment]
Not a BC issue.
