### ISSUE TITLE
bcprov-jdk15on-1.62.jar has unsigned entries - org/bouncycastle/LICENSE.class

### ISSUE THREAD

**Issue by innocentliny** [bcgit/bc-java#557]
Hi,

I am trying to use JDK7u80 + bcprov-jdk15on-1.62.jar to write AES-GCM codes.
My build.gradle as below:
> dependencies {
>   compile group: 'org.bouncycastle', name: 'bcprov-jdk15on', version: '1.62'
>   testCompile 'org.testng:testng:6.8.21'
> }

My codes are below:
![image](https://user-images.githubusercontent.com/5312376/60961510-f2e67480-a33e-11e9-9e44-81f29c5e763f.png)

But got exception:
```
Exception in thread "main" java.lang.SecurityException: JCE cannot authenticate the provider BC
	at javax.crypto.Cipher.getInstance(Cipher.java:647)
	at javax.crypto.Cipher.getInstance(Cipher.java:585)
	at com.asuscloud.common.crypto.AESGCMUtils.main(AESGCMUtils.java:46)
Caused by: java.util.jar.JarException: file:/C:/Users/anderson/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.62/633b6739ef8f07f2e71f8eebd1c6f25b17a4ec7d/bcprov-jdk15on-1.62.jar has unsigned entries - org/bouncycastle/LICENSE.class
	at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:462)
	at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:322)
	at javax.crypto.JarVerifier.verify(JarVerifier.java:250)
	at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:161)
	at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:187)
	at javax.crypto.Cipher.getInstance(Cipher.java:643)
	... 2 more
```

bcprov-jdk15on-1.62.jar is downloaded from [https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on/1.62](https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on/1.62).

Please let me know if any I missed.
Thank you very much!

**Comment by kimmerin** [comment]
Downloaded the jar from the URL you've provided and the MANIFEST.MF contains an entry for that class:

    Name: org/bouncycastle/LICENSE.class
    SHA-256-Digest: PnhJQA4AeaEHWTRey/cRjcMPTqmCTtDuOYiGffDFebo=

Check if other libraries you're using contain that class.

**Comment by innocentliny** [comment]
@kimmerin 

Thank you for reply.

I opened all jars I used, but only bcprov-jdk15on-1.62.jar contains org/bouncycastle/LICENSE.class.
That's weird.

Please let me know if any comments.
Thank you.

**Comment by innocentliny** [comment]
Hi,

I used jarsigner to verify bcprov-jdk15on-1.62.jar as below result:
```
c:\Java\jdk1.7.0_80\bin>.\jarsigner.exe -verify C:\Users\matrix\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk15on\1.62\633b6739ef8f07f2e71f8eebd1c6f25b17a4ec7d\bcprov-jdk15on-1.62.jar
jar is unsigned. (signatures missing or not parsable)
```

**Comment by bcgit** [comment]
You should be able to use 1.62. It looks like the one in your gradle cache is somehow corrupted.

**Comment by innocentliny** [comment]
@bcgit 

Thank you for reply.
I checked the checksum of bcprov-jdk15on-1.62.jar in my local gradle cache, and it is identical to [maven repository](https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.62/bcprov-jdk15on-1.62.jar.sha1).

Please let me know if anything.
Thank you!

**Comment by mouse07410** [comment]
I was unable to use `bcprov-ext-jdk15on-1.62.jar` in my Maven project (which works fine with 1.60).

Manually pointing the run to 1.63b that I built and signed myself seems to work ok.

**Comment by bcgit** [comment]
@innocentliny you're using the Oracle JDK 7 aren't you?

**Comment by innocentliny** [comment]
@bcgit 
Yes, Oracle Java7u80 + Windows.  I can not decide to change the java version.

**Comment by bcgit** [comment]
okay, now I know what's going on - there's an issue with Oracle Java 7 and its ability to handle timestamps. Try the beta at https://www.bouncycastle.org/betas and let me know how you go.

**Comment by innocentliny** [comment]
@bcgit 
Thank you.
Below is my test result:
```
java.lang.SecurityException: JCE cannot authenticate the provider BC
	at javax.crypto.Cipher.getInstance(Cipher.java:647)
	at javax.crypto.Cipher.getInstance(Cipher.java:585)
	at com.matrix.util.AESGCMCipher.encryptBase64String(AESGCMCipher.java:70)
	at com.matrix.util.AESGCMCipherTest.testWithAdditionalAuthenticationData(AESGCMCipherTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.util.jar.JarException: file:/C:/Users/anderson/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/163b06/e0b827774df16b3fd5e8cedc3e30853a43b70505/bcprov-jdk15on-163b06.jar has unsigned entries - org/bouncycastle/LICENSE.class
	at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:462)
	at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:322)
	at javax.crypto.JarVerifier.verify(JarVerifier.java:250)
	at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:161)
	at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:187)
	at javax.crypto.Cipher.getInstance(Cipher.java:643)
```

**Comment by bcgit** [comment]
try this one: https://downloads.bouncycastle.org/betas/bcprov-jdk15on-163b07.jar

**Comment by innocentliny** [comment]
@bcgit 
bcprov-jdk15on-163b07.jar works! Magic!
And should I use bcprov-jdk15on-163b07.jar or bcprov-jdk15on-1.60.jar in production?

Thank you.

**Comment by bcgit** [comment]
I definitely wouldn't use a beta in production, and I'd really encourage you  to use the latest version of BC.
This time around I've uploaded a version of 1.62 - use  https://downloads.bouncycastle.org/misc/bcprov-jdk15on-1.62.jar 
Moving forward you've got two options, you can either get a JCE signing certificate from Oracle, then you can sign your own customised versions of the provider using Oracle JDK 1.7 or you can get a support contract and we'll be able to make sure the version of BC you are using is both fully patched and compatible, but the above jar should do for now. If the 1.62 jar works, please close off this issue.

**Comment by innocentliny** [comment]
@bcgit 

The [https://downloads.bouncycastle.org/misc/bcprov-jdk15on-1.62.jar](https://downloads.bouncycastle.org/misc/bcprov-jdk15on-1.62.jar) works now with Oracle Java7u80.
Awesome!

Thank you very much!
And would you update this jar to maven repository? It would be great if others have same problem.

**Comment by bcgit** [comment]
There's a catch, well two actually. Maven jars are immutable so I can't overwrite the one we've uploaded. The other issue is that if you check the signature you'll see everything is based on sha-1 which isn't really a good look these days, but it's the only thing the Oracle version of JDK 1.7 understands (hence the need for either you to get a signing certificate and customise, or get someone else to do it, we can't role back the signature algorithm we now use). We'll leave the jar in the misc area though so others can find it, or we can refer them to it. I'd be very surprised if you're the only person we hear from on this.

**Comment by greyp-ionic** [comment]
It seems as though this is not fixed in BC 1.63 release?

**Comment by bcgit** [comment]
Use the jdk15to18 jars.

**Comment by greyp-ionic** [comment]
Yes, the resource "jdk15to18" seems to work for this test case (JRE 1.7).  Thanks.

Reproduce:
https://github.com/greyp-ionic/bc-test-1

Test Matrix:
	group: 'org.bouncycastle', name: 'bcprov-jdk15on', version: '1.60'  PASS
	group: 'org.bouncycastle', name: 'bcprov-jdk15on', version: '1.62'  FAIL
	group: 'org.bouncycastle', name: 'bcprov-jdk15on', version: '1.63'  FAIL
	group: 'org.bouncycastle', name: 'bcprov-jdk15to18', version: '1.63'  PASS

**Comment by mouse07410** [comment]
I suspect that the problem here is with modules, or rather with how the BC modules are named compared to the JAR file names. 

I'd like to use this opportunity to remind again about my request to change the names of the BC modules to match their corresponding JAR names, to ensure compatibility across BC and JVM versions.

**Comment by bcgit** [comment]
Actually it's do to with the way the jarsigner was changed. Oracle have been making changes for a while now, some of tthem small and subtle, but they are making themselves felt. Unfortunately trying to do things with module names won't help either, this is simply going to get harder.

**Comment by mouse07410** [comment]
I wasn't aware of jarsigner changes. Would you mind listing a few (say, the most notable, or the "loudest") here? It could be useful for me and others.

**Comment by bcgit** [comment]
I'm not sure what changed in Java 8 specifically, but the issue is that somewhere in the Java 8 release cycle and beyond the jarsigner doesn't seem to be able to produce a detached CMS signature which Oracle Java 7 can verify internally, so for Oracle Java 5 to Oracle Java 7 the JCE will actually fail to verify. I'd say it's a probably a short coming of the earlier releases but it has proved to be intractable enough that we've had to start issuing the jdk15to18 jars. it looks like supporting Java 11 and later properly is also going to require a separate stream as well. I suppose we had a 10+ year run on this, but it's just not like the "good old days" anymore.
