### ISSUE TITLE
maven package jar, not working properly

### ISSUE THREAD

**Issue by victory-wu** [bcgit/bc-java#602]
Maven can't run properly after packaging JAR，But it works well with idea development tools。

> java.security.UnrecoverableKeyException: no match
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$StoreEntry.getObject(Unknown Source)
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineGetKey(Unknown Source)
        at java.security.KeyStore.getKey(KeyStore.java:1023)
        at sun.security.ssl.SunX509KeyManagerImpl.<init>(SunX509KeyManagerImpl.java:133)
        at sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(KeyManagerFactoryImpl.java:70)
        at javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:256)
        at com.wzx.modules.utils.RequestUtil.loadCert(RequestUtil.java:132)  <---- see picture

![TIM截图20191010162128](https://user-images.githubusercontent.com/6036393/66551449-13aaaa00-eb7a-11e9-9093-4b1679bd1949.jpg)

**Comment by jiaquanchao** [comment]
maybe maven-shade-plugin causes this question

**Comment by dghgit** [comment]
Closed as stale and lack of information. Suggestion about shade-plugin might be relevant though.
