### ISSUE TITLE
ProvSSLSessionHandshake getLocalSupportedSignatureAlgorithms throws UnsupportedOperationException

### ISSUE THREAD

**Issue by P4Awd** [bcgit/bc-java#607]
It appears that when trying to use the tls provider and the tls version is >= 1.2 the X509TrustManager attempts to call getLocalSupportedSignatureAlgorithms() on the ExtendedSSLSession which is expected to return an empty array (https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/ExtendedSSLSession.html#getPeerSupportedSignatureAlgorithms--)

At a glance, it appears that the issue is due to ProvSSLSessionHandshake throwing an UnsupportedOperationException

```
org.bouncycastle.jsse.provider.ProvTlsClient notifyAlertRaised
WARNING: Client raised fatal(2) internal_error(80) alert: Failed to read record
java.lang.UnsupportedOperationException
	at org.bouncycastle.jsse.provider.ProvSSLSessionHandshake.getLocalSupportedSignatureAlgorithms(Unknown Source)
	at org.bouncycastle.jsse.provider.ExportSSLSession_7.getLocalSupportedSignatureAlgorithms(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:212)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at org.bouncycastle.jsse.provider.ImportX509TrustManager_7.checkServerTrusted(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.checkServerTrusted(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvTlsClient$1.notifyServerCertificate(Unknown Source)
	at org.bouncycastle.tls.TlsUtils.processServerCertificate(Unknown Source)
	at org.bouncycastle.tls.TlsClientProtocol.handleServerCertificate(Unknown Source)
	at org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source)
	at org.bouncycastle.tls.RecordStream.readRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.blockForHandshake(Unknown Source)
	at org.bouncycastle.tls.TlsClientProtocol.connect(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
	at pps.common.framework.web.SSLContextBuilder$DelegateSSLSocket.startHandshake(SSLContextBuilder.java:444)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
```

**Comment by peterdettman** [comment]
BCJSSE provides its own TrustManagerFactory and KeyManagerFactory and doesn't currently interoperate with the SunJSSE ones (although it can work on older JDKs or earlier TLS versions).

Therefore, either explicitly specify the BCJSSE provider for your TMF (and KMF) - use the "PKIX" algorithm for both, or else install the BCJSSE provider with higher priority than the SunJSSE provider.

You will probably also want to set the default KMF/TMF algorithms to "PKIX" in java.security:
    ssl.KeyManagerFactory.algorithm=PKIX
    ssl.TrustManagerFactory.algorithm=PKIX

**Comment by brucelpt** [comment]
> BCJSSE provides its own TrustManagerFactory and KeyManagerFactory and doesn't currently interoperate with the SunJSSE ones (although it can work on older JDKs or earlier TLS versions).
> 
> Therefore, either explicitly specify the BCJSSE provider for your TMF (and KMF) - use the "PKIX" algorithm for both, or else install the BCJSSE provider with higher priority than the SunJSSE provider.
> 
> You will probably also want to set the default KMF/TMF algorithms to "PKIX" in java.security:
> ssl.KeyManagerFactory.algorithm=PKIX
> ssl.TrustManagerFactory.algorithm=PKIX
HI peter,I ran into this problem too.I have converted my keystore to BKS format.
Here's my code
`
KeyManagerFactory kmf = null;
        if (keyStorePath != null && ksPasswd != null) {
            KeyStore ks = KeyStore.getInstance("BKS","BC");
            try (InputStream is = new FileInputStream(keyStorePath)) {
                ks.load(is, ksPasswd.toCharArray());
            }
            kmf = KeyManagerFactory.getInstance(keyManagerAlg);
            kmf.init(ks, ksPasswd.toCharArray());
        }
`
But this error still appears.
`
Client raised fatal(2) internal_error(80) alert: Failed to read record
java.lang.UnsupportedOperationException
	at org.bouncycastle.jsse.provider.ProvSSLSessionHandshake.getLocalSupportedSignatureAlgorithms(Unknown Source)
	at org.bouncycastle.jsse.provider.ExportSSLSession_7.getLocalSupportedSignatureAlgorithms(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:220)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at org.bouncycastle.jsse.provider.ImportX509TrustManager_7.checkServerTrusted(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.checkServerTrusted(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvTlsClient$1.notifyServerCertificate(Unknown Source)
	at org.bouncycastle.tls.TlsUtils.processServerCertificate(Unknown Source)
	at org.bouncycastle.tls.TlsClientProtocol.handleServerCertificate(Unknown Source)
	at org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source)
	at org.bouncycastle.tls.RecordStream.readRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.blockForHandshake(Unknown Source)
	at org.bouncycastle.tls.TlsClientProtocol.connect(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
	at com.test.hello.utils.BCHttpsClient.postData(BCHttpsClient.java:95)
	at com.test.hello.utils.BCHttpsClient.main(BCHttpsClient.java:209)

java.lang.Exception: internal_error(80)
	at com.test.hello.utils.BCHttpsClient.postData(BCHttpsClient.java:113)
	at com.test.hello.utils.BCHttpsClient.main(BCHttpsClient.java:209)

`
This is my pom.xml.
`
<dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.64</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bctls-jdk15on</artifactId>
            <version>1.64</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk15on</artifactId>
            <version>1.64</version>
        </dependency>
`
I would appreciate it if you could spare some time to answer my questions.
Thank you very much.

**Comment by brucelpt** [comment]
I resend my code, the last comment was not formatted correctly.
My code:
 KeyManagerFactory kmf = null;
        if (keyStorePath != null && ksPasswd != null) {
            KeyStore ks = KeyStore.getInstance(keyType,"BC");
            try (InputStream is = new FileInputStream(keyStorePath)) {
                ks.load(is, ksPasswd.toCharArray());
            }
            kmf = KeyManagerFactory.getInstance(keyManagerAlg);
            kmf.init(ks, ksPasswd.toCharArray());
        }
pom.xml

<dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.64</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bctls-jdk15on</artifactId>
            <version>1.64</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk15on</artifactId>
            <version>1.64</version>
        </dependency>

**Comment by brucelpt** [comment]
I resend my code, the last comment was not formatted correctly

` KeyManagerFactory kmf = null;
        if (keyStorePath != null && ksPasswd != null) {
            KeyStore ks = KeyStore.getInstance(keyType,"BC");
            try (InputStream is = new FileInputStream(keyStorePath)) {
                ks.load(is, ksPasswd.toCharArray());
            }
            kmf = KeyManagerFactory.getInstance(keyManagerAlg);
            kmf.init(ks, ksPasswd.toCharArray());
        }`

pom.xml 
bcprov-jdk15on version: 1.64
bctls-jdk15on     version: 1.64
bcpkix-jdk15on  version: 1.64

**Comment by brucelpt** [comment]
> BCJSSE provides its own TrustManagerFactory and KeyManagerFactory and doesn't currently interoperate with the SunJSSE ones (although it can work on older JDKs or earlier TLS versions).
> 
> Therefore, either explicitly specify the BCJSSE provider for your TMF (and KMF) - use the "PKIX" algorithm for both, or else install the BCJSSE provider with higher priority than the SunJSSE provider.
> 
> You will probably also want to set the default KMF/TMF algorithms to "PKIX" in java.security:
> ssl.KeyManagerFactory.algorithm=PKIX
> ssl.TrustManagerFactory.algorithm=PKIX



Hi,peter.I had the same problem,too.
I have converted the keystore to BKS and used the BC provider.But it's the same error.
I don't know why.
Here is my code :
``
KeyManagerFactory kmf = null;
        if (keyStorePath != null && ksPasswd != null) {
            KeyStore ks = KeyStore.getInstance("BKS","BC");
            try (InputStream is = new FileInputStream(keyStorePath)) {
                ks.load(is, ksPasswd.toCharArray());
            }
            kmf = KeyManagerFactory.getInstance(keyManagerAlg);
            kmf.init(ks, ksPasswd.toCharArray());
        }
``


ERROR:
``
Client raised fatal(2) internal_error(80) alert: Failed to read record
java.lang.UnsupportedOperationException
	at org.bouncycastle.jsse.provider.ProvSSLSessionHandshake.getLocalSupportedSignatureAlgorithms(Unknown Source)
	at org.bouncycastle.jsse.provider.ExportSSLSession_7.getLocalSupportedSignatureAlgorithms(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:220)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at org.bouncycastle.jsse.provider.ImportX509TrustManager_7.checkServerTrusted(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.checkServerTrusted(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvTlsClient$1.notifyServerCertificate(Unknown Source)
	at org.bouncycastle.tls.TlsUtils.processServerCertificate(Unknown Source)
	at org.bouncycastle.tls.TlsClientProtocol.handleServerCertificate(Unknown Source)
	at org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source)
	at org.bouncycastle.tls.RecordStream.readRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.blockForHandshake(Unknown Source)
	at org.bouncycastle.tls.TlsClientProtocol.connect(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
	at com.test.hello.utils.BCHttpsClient.postData(BCHttpsClient.java:95)
	at com.test.hello.utils.BCHttpsClient.main(BCHttpsClient.java:209)

java.lang.Exception: internal_error(80)
	at com.test.hello.utils.BCHttpsClient.postData(BCHttpsClient.java:113)
	at com.test.hello.utils.BCHttpsClient.main(BCHttpsClient.java:209)

``
BC VERSION:
bcprov-jdk15on version 1.64
bctls-jdk15on version 1.64
bcpkix-jdk15on version 1.64

**Comment by brucelpt** [comment]
Hi peter,thank you very much.
I modified the code according to your comments and it worked
