### ISSUE TITLE
Can't identify EC private key with -keyalg X25519 using keytool

### ISSUE THREAD

**Issue by otto-dev** [bcgit/bc-java#614]
If I use `BouncyCastleProvider` to generate an `X25519` key in `keytool`, I get the error `can't identify EC private key` from [here](https://github.com/bcgit/bc-java/blob/a66e904a431d992281c8378064fed4cbc4ab1d99/prov/src/main/java/org/bouncycastle/jcajce/provider/asymmetric/util/ECUtil.java#L287). This is an example command:
```
/usr/lib/jvm/java-13-openjdk/bin/keytool \
  -genkeypair \
  -v \
  -keyalg X25519 \
  -sigalg SHA256withECDSA \
  -providerpath client/bc.jar \
  -provider org.bouncycastle.jce.provider.BouncyCastleProvider \
  -keystore exampleca.p12 \
  -storetype PKCS12 \ 
  -keypass:env PW \
  -storepass:env PW \
  -alias exampleca \
  -dname "CN=exampleCA, OU=Example Org, O=Example Company, L=San Francisco, ST=California, C=US" \
  -ext KeyUsage:critical="keyCertSign" \
  -ext BasicConstraints:critical="ca:true" \
  -validity 9999
```
And this is the stacktrace:
```
keytool error: java.security.InvalidKeyException: can't identify EC private key.
java.security.InvalidKeyException: can't identify EC private key.
	at org.bouncycastle.jcajce.provider.asymmetric.util.ECUtil.generatePrivateKeyParameter(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi.engineInitSign(Unknown Source)
	at java.base/java.security.SignatureSpi.engineInitSign(SignatureSpi.java:131)
	at java.base/java.security.SignatureSpi.engineInitSign(SignatureSpi.java:162)
	at java.base/java.security.Signature$Delegate.tryOperation(Signature.java:1313)
	at java.base/java.security.Signature$Delegate.chooseProvider(Signature.java:1256)
	at java.base/java.security.Signature$Delegate.engineInitSign(Signature.java:1381)
	at java.base/java.security.Signature.initSign(Signature.java:683)
	at java.base/java.security.Signature$1.initSign(Signature.java:146)
	at java.base/sun.security.util.SignatureUtil.initSignWithParam(SignatureUtil.java:169)
	at java.base/sun.security.x509.X509CertImpl.sign(X509CertImpl.java:597)
	at java.base/sun.security.tools.keytool.CertAndKeyGen.getSelfCertificate(CertAndKeyGen.java:305)
	at java.base/sun.security.tools.keytool.Main.doGenKeyPair(Main.java:1921)
	at java.base/sun.security.tools.keytool.Main.doCommands(Main.java:1157)
	at java.base/sun.security.tools.keytool.Main.run(Main.java:416)
	at java.base/sun.security.tools.keytool.Main.main(Main.java:409)
```

Without `BouncyCastleProvider` I get
```java.security.InvalidKeyException: No installed provider supports this key: sun.security.ec.XDHPrivateKeyImpl```

**Comment by otto-dev** [comment]
With Java 11 the error become even more bizarre. Every time you run the command, you get a different error.

In Java 11 you have to add the `  -keysize 255` parameter. 

The always start with `keytool error: java.security.InvalidKeyException: cannot identify EC private key: [...]` and followed by such as:
```
[...] java.io.IOException: corrupted stream - out of bounds length found: 56 >= 32
	at org.bouncycastle.jcajce.provider.asymmetric.util.ECUtil.generatePrivateKeyParameter(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi.engineInitSign(Unknown Source)
```

```
[...] java.io.IOException: DER length more than 4 bytes: 19
java.security.InvalidKeyException: cannot identify EC private key: java.io.IOException: DER length more than 4 bytes: 19
	at org.bouncycastle.jcajce.provider.asymmetric.util.ECUtil.generatePrivateKeyParameter(Unknown Source)
```

```
[...] java.io.EOFException: DEF length 14 object truncated by 13
java.security.InvalidKeyException: cannot identify EC private key: java.io.EOFException: DEF length 14 object truncated by 13
	at org.bouncycastle.jcajce.provider.asymmetric.util.ECUtil.generatePrivateKeyParameter(Unknown Source)
```

```
keytool error: java.security.InvalidKeyException: cannot identify EC private key: java.io.IOException: Extra data detected in stream
java.security.InvalidKeyException: cannot identify EC private key: java.io.IOException: Extra data detected in stream
	at org.bouncycastle.jcajce.provider.asymmetric.util.ECUtil.generatePrivateKeyParameter(Unknown Source)
```

**Comment by peterdettman** [comment]
The immediate issue here appears to be that you are trying to generate a self-signed certificate that uses X25519 as the key algorithm. X25519 is a key agreement algorithm, it doesn't make sense to try and sign anything with such a key.

Arguably keytool ought to spot this discrepancy and complain earlier.

**Comment by otto-dev** [comment]
Thanks, that makes sense. It was the only "algorithm name" I could find in [the docs](https://docs.oracle.com/en/java/javase/11/security/oracle-providers.html), and `curve25519` and `ed25519` didn't work at all.

**Comment by dawud-tan** [comment]
@peterdettman I got this exception too when I generate a self-signed certificate that uses Ed25519 as the key algorithm. Will the method ```ECUtil.generatePrivateKeyParameter()``` be added with ```org.bouncycastle.jcajce.interfaces.EdDSAPrivateKey```?

**Comment by peterdettman** [comment]
@dawud-tan Please show the exact command line you are using.

**Comment by dawud-tan** [comment]
I was getting the exception when I created my own [self-signed certificate generating code](https://github.com/bcgit/bc-java/blob/master/pkix/src/main/java/org/bouncycastle/operator/jcajce/JcaContentSignerBuilder.java), the ```build()``` method of class ```JcaContentSignerBuilder``` throws the following exception message: ```cannot create signer: can't identify EC private key```, here is the complete stack trace:

```java
org.bouncycastle.operator.OperatorCreationException: cannot create signer: can't identify EC private key.
	at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.build(Unknown Source)
	at PembuatSertifikatEC.cert(PembuatSertifikatEC.java:158)
	at PembuatSertifikatEC.nanti(PembuatSertifikatEC.java:78)
	at PembuatSertifikatEC.main(PembuatSertifikatEC.java:31)
Caused by: java.security.InvalidKeyException: can't identify EC private key.
	at org.bouncycastle.jcajce.provider.asymmetric.util.ECUtil.generatePrivateKeyParameter(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.ec.SignatureSpi.engineInitSign(Unknown Source)
	at java.base/java.security.Signature$Delegate.engineInitSign(Signature.java:1351)
	at java.base/java.security.Signature.initSign(Signature.java:636)
	... 4 more
```

**Comment by peterdettman** [comment]
@dawud-tan You'll have to give example code then, particularly how you are creating the private key and what algorithm you are constructing JcaContentSignerBuilder with. The most likely issue is a mismatch between the key algorithm you specified (I assume "Ed25519") and the Signature instance you created, which ought to also be Ed25519.

You can see the OP has this problem (in addition to X25519 not being a signing key) => even if it were changed to "-keyalg Ed25519", it wouldn't be a valid key for "-sigalg SHA256withECDSA".

**Comment by dawud-tan** [comment]
@peterdettman I didn't know about the commit bcgit/bc-java@328de7d39272eed0a66312358d6e7ada9af6030a my earlier question thought that ED25519 hasn't been defined in ```DefaultSignatureAlgorithmIdentifierFinder``` thanks

**Comment by dawud-tan** [comment]
@peterdettman I didn't know about the commit bcgit/bc-java@328de7d39272eed0a66312358d6e7ada9af6030a my earlier question thought that ```ED25519``` hasn't been defined in ```DefaultSignatureAlgorithmIdentifierFinder``` thanks, cause when I search the class through the github's search bar, the commit had not been shown, following is the [link to the search result](https://github.com/bcgit/bc-java/search?p=2&q=DefaultSignatureAlgorithmIdentifierFinder&unscoped_q=DefaultSignatureAlgorithmIdentifierFinder) and this link to cached version of the [DefaultSignatureAlgorithmIdentifierFinder.java](https://github.com/bcgit/bc-java/blob/738dfc0132323d66ad27e7ec366666ed3e0638ab/pkix/src/main/java/org/bouncycastle/operator/DefaultSignatureAlgorithmIdentifierFinder.java)

**Comment by dghgit** [comment]
Closing, as inactive. I've confirmed the original keytool command works with corrected parameters using the latest provider and Java 15 and later.
