### ISSUE TITLE
ChaCha20Poly1305 with CMS returns NPE when data smaller than 64 bytes

### ISSUE THREAD

**Issue by max402** [bcgit/bc-java#621]
```
public static void main(String[] args) throws Exception {
        CMSEnvelopedData encrypt1 = encrypt(new byte[64]); // works fine
        CMSEnvelopedData encrypt2 = encrypt(new byte[63]); // generates NPE
    }

    private static CMSEnvelopedData encrypt(byte[] data) throws CMSException {
        BouncyCastleProvider provider = new BouncyCastleProvider();
        Security.addProvider(provider);
        ASN1ObjectIdentifier algorithm = PKCSObjectIdentifiers.id_alg_AEADChaCha20Poly1305;
        CMSEnvelopedDataGenerator generator = new CMSEnvelopedDataGenerator();
        JcePasswordRecipientInfoGenerator recipient = new JcePasswordRecipientInfoGenerator(CMSAlgorithm.AES256_CBC, "PASSWORD".toCharArray());
        generator.addRecipientInfoGenerator(recipient);

        new Random().nextBytes(data);
        CMSProcessableByteArray content = new CMSProcessableByteArray(data);
        OutputEncryptor contentEncryptor = new JceCMSContentEncryptorBuilder(algorithm).setProvider(provider).build();
        return generator.generate(content, contentEncryptor);
    }
```
```
Exception in thread "main" java.lang.NullPointerException: 'out' cannot be null
	at org.bouncycastle.crypto.modes.ChaCha20Poly1305.processBytes(Unknown Source)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$AEADGenericBlockCipher.processBytes(Unknown Source)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineUpdate(Unknown Source)
	at java.base/javax.crypto.Cipher.update(Cipher.java:1869)
	at org.bouncycastle.jcajce.io.CipherOutputStream.write(Unknown Source)
	at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:108)
	at org.bouncycastle.cms.CMSProcessableByteArray.write(Unknown Source)
	at org.bouncycastle.cms.CMSEnvelopedDataGenerator.doGenerate(Unknown Source)
	at org.bouncycastle.cms.CMSEnvelopedDataGenerator.generate(Unknown Source)
```

```
dependencies {
    compile group: 'org.bouncycastle', name: 'bcprov-jdk15on', version: '1.64'
    compile group: 'org.bouncycastle', name: 'bcpkix-jdk15on', version: '1.64'
}
```

**Comment by peterdettman** [comment]
Fixed along with https://github.com/bcgit/bc-java/issues/674 .
