### ISSUE TITLE
NPE in PSSSignatureSpi#init due to unchecked null SecureRandom

### ISSUE THREAD

**Issue by Acinyx** [bcgit/bc-java#633]
We are observing NPE which seems to be caused by `sun.security.ssl.SignatureScheme#getSignature` providing a null `SecureRandom` instance while `org.bouncycastle.jcajce.provider.asymmetric.rsa.PSSSignatureSpi#engineInitSign(java.security.PrivateKey, java.security.SecureRandom)` assumes it won't be null and wraps it with a `ParametersWithRandom` object before calling `PSSSignatureSpi#init`.

Stacktrace:
```
Caused by: java.lang.NullPointerException
        at org.bouncycastle.crypto.signers.PSSSigner.generateSignature(PSSSigner.java:233) ~[bcprov-debug-jdk15on-1.64.jar:1.64.0]
        at org.bouncycastle.jcajce.provider.asymmetric.rsa.PSSSignatureSpi.engineSign(PSSSignatureSpi.java:176) ~[bcprov-debug-jdk15on-1.64.jar:1.64.0]
        at java.security.Signature$Delegate.engineSign(Signature.java:1404) ~[?:?]
        at java.security.Signature.sign(Signature.java:713) ~[?:?]
        at sun.security.ssl.ECDHServerKeyExchange$ECDHServerKeyExchangeMessage.<init>(ECDHServerKeyExchange.java:181) ~[?:?]
        at sun.security.ssl.ECDHServerKeyExchange$ECDHServerKeyExchangeProducer.produce(ECDHServerKeyExchange.java:499) ~[?:?]
        at sun.security.ssl.ClientHello$T12ClientHelloConsumer.consume(ClientHello.java:1102) ~[?:?]
        at sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:854) ~[?:?]
        at sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:813) ~[?:?]
        at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392) ~[?:?]
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443) ~[?:?]
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421) ~[?:?]
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:177) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402) ~[?:?]
        ... 10 more
```

Likely this can be handled like in `org.bouncycastle.jcajce.provider.asymmetric.dsa.DSASigner#engineInitSign(java.security.PrivateKey)` with a simple null check:
```
if (random != null)
{
    param = new ParametersWithRandom(param, random);
}
```

**Comment by Acinyx** [comment]
Didn't notice a PR was already created to fix this issue, but keeping this issue open for others looking for it.

**Comment by amitmun** [comment]
We ran into this issue when trying to send a client certificate over TLS1.2 with Apache HttpAsyncClient under TomEE 8, which uses BC as a security provider. Waiting for the pull request to be merged...

**Comment by amitmun** [comment]
This happened only after upgrading to OpenJDK 11.0.5+10.
With 11.0.3+7 this did not happen.
Source of the problem is probably https://bugs.openjdk.java.net/browse/JDK-8216039

**Comment by brandonweeks** [comment]
#632 was merged in 640f6cba8362f7a28a09e457af86e4fd6724c190.

**Comment by Chr3is** [comment]
@brandonweeks do you know when you're going to release the next version (v65) with this fix?

**Comment by brandonweeks** [comment]
Sorry, no. I'm not a Bouncy Castle maintainer, only the author of the patch.

**Comment by bcgit** [comment]
We're hoping to do 1.65 in early Feb. Concentrating on TLS 1.3 at the moment.

**Comment by shalvinmaharaj** [comment]
@bcgit when can we expect the release of 1.65?

**Comment by bcgit** [comment]
Soon.
