### ISSUE TITLE
Service not registered with Provider BC: BC: SecretKeyFactory.PBKDF2WITHASCII

### ISSUE THREAD

**Issue by ralfhauser** [bcgit/bc-java#642]
when trying to read a pem key, got 
java.security.NoSuchAlgorithmException: Service not registered with Provider BC: BC: SecretKeyFactory.PBKDF2WITHASCII -> org.bouncycastle.jcajce.provider.symmetric.PBEPBKDF2$PBKDF2with8BIT
  aliases: [PBKDF2WITH8BIT]

	at java.base/java.security.Provider$Service.newInstance(Provider.java:1785)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:136)
	at java.base/javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:212)
	at org.bouncycastle.jcajce.util.NamedJcaJceHelper.createSecretKeyFactory(Unknown Source)
	at org.bouncycastle.openssl.jcajce.PEMUtilities.generateSecretKeyForPKCS5Scheme2(Unknown Source)
	at org.bouncycastle.openssl.jcajce.JceOpenSSLPKCS8DecryptorProviderBuilder$1.get(Unknown Source)
	at org.bouncycastle.pkcs.PKCS8EncryptedPrivateKeyInfo.decryptPrivateKeyInfo(Unknown Source)

in debian oldstable /usr/lib/jvm/jdk-13.0.1

works nicely with java8 and BC1.54

**Comment by ralfhauser** [comment]
seems that the problem no longer exists with the BC1.64 jars
