### ISSUE TITLE
About CFB1 Mode Exception

### ISSUE THREAD

**Issue by Yifei0727** [bcgit/bc-java#644]
```java
Security.addProvider(new BouncyCastleProvider());
Cipher cipher = Cipher.getInstance("AES/CFB1/NoPadding", "BC");
cipher.init(Cipher.DECRYPT_MODE, new SecretKeySpec(new byte[16], "AES"), new IvParameterSpec(new byte[16]));
cipher.doFinal(cipher_bytes);
```
will cause
```
java.lang.ArithmeticException: / by zero
	at org.bouncycastle.crypto.BufferedBlockCipher.getUpdateOutputSize(Unknown Source)
	at org.bouncycastle.crypto.BufferedBlockCipher.processBytes(Unknown Source)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$BufferedGenericBlockCipher.processBytes(Unknown Source)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source)
	at javax.crypto.Cipher.doFinal(Cipher.java:2164)
```

and then I find the reason
`https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/crypto/modes/CFBBlockCipher.java`# 40

```java
this.blockSize = bitBlockSize / 8;
```
For bitBlockSize=1,   will return 0 of blockSize 
```java
 public int getBlockSize()
    {
        return blockSize;
    }
```

How about change it to 
```java
        this.blockSize = (bitBlockSize / 8) == 0 ? 1 : (bitBlockSize / 8);
        this.bitLength = bitBlockSize;
        //cfb1 cfb8 cfb
        if (bitLength > 8 && bitLength % 8 != 0) {
            throw new IllegalArgumentException("Not Support CFB" + bitLength);
        }
        if (bitLength < 8 && bitLength != 1) {
            throw new IllegalArgumentException("Not Support CFB" + bitLength);
        }
```

**Comment by bcgit** [comment]
Thanks for the suggestion, I have added the check.
