### ISSUE TITLE
CMSSignedData IllegalArgumentException: malformed integer with v1.64

### ISSUE THREAD

**Issue by ralfhauser** [bcgit/bc-java#645]
org.bouncycastle.cms.CMSException: IOException reading content.
	at org.bouncycastle.cms.CMSUtils.readContentInfo(Unknown Source)
	at org.bouncycastle.cms.CMSUtils.readContentInfo(Unknown Source)
	at org.bouncycastle.cms.CMSSignedData.<init>(Unknown Source)
	at com.privasphere.privalope.test.TestSuite.suite(TestSuite.java:2146)
...
Caused by: org.bouncycastle.asn1.ASN1Exception: corrupted stream detected
	at org.bouncycastle.asn1.ASN1StreamParser.readObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DERSequenceParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DERSequenceParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DERSetParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DERSequenceParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DERSequenceParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DERSequenceParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readTaggedObject(Unknown Source)
	at org.bouncycastle.asn1.BERTaggedObjectParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readTaggedObject(Unknown Source)
	at org.bouncycastle.asn1.BERTaggedObjectParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DERSequenceParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readTaggedObject(Unknown Source)
	at org.bouncycastle.asn1.BERTaggedObjectParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DERSequenceParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DERSetParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DERSequenceParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readTaggedObject(Unknown Source)
	at org.bouncycastle.asn1.BERTaggedObjectParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DERSequenceParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DERSetParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.DERSequenceParser.getLoadedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)
	at org.bouncycastle.asn1.ASN1StreamParser.readTaggedObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1InputStream.buildObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1InputStream.readObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1InputStream.readVector(Unknown Source)
	at org.bouncycastle.asn1.ASN1InputStream.buildObject(Unknown Source)
	at org.bouncycastle.asn1.ASN1InputStream.readObject(Unknown Source)
	... 22 more
Caused by: java.lang.IllegalArgumentException: malformed integer
	at org.bouncycastle.asn1.ASN1Integer.<init>(Unknown Source)
	at org.bouncycastle.asn1.ASN1InputStream.createPrimitiveDERObject(Unknown Source)
	... 68 more

Happens with both jdk1.8.0_181 and openjdk 13, but with the v1.54 of the BouncyCastle jars, it all worked fine

**Comment by ralfhauser** [comment]
How to reproduce: I want to analyze a pdf signature
FileInputStream fis = new FileInputStream("/home/you/pdfSigContent.bin");
                ByteArrayOutputStream baosPs = new ByteArrayOutputStream();
                IOUtils.copy(fis, baosPs);
                CMSSignedData sigData = new CMSSignedData(baosPs.toByteArray());
                log.debug(sigData);
[Testeingabe-sig.pdf](https://github.com/bcgit/bc-java/files/4075522/Testeingabe-sig.pdf)
or rather
[pdfSigContent.bin.zip](https://github.com/bcgit/bc-java/files/4075530/pdfSigContent.bin.zip)

**Comment by bcgit** [comment]
Try setting:

-Dorg.bouncycastle.asn1.allow_unsafe_integer=true

my guess is that will work. If it does I would recommend having a word to whoever it is that is generating these signatures as they are not encoding ASN.1 integers correctly.

**Comment by ralfhauser** [comment]
Thx, works - is there a way, to have this "per Thread" as opposed to "with a global system property" ?

**Comment by bcgit** [comment]
Sorry, no it's global at the moment. I guess you could turn it on when required and then off when it wasn't - not ideal but it would reduce the window for something unexpected getting through.

**Comment by kimmerin** [comment]
Since it's calling Properties.isOverrideSet, it might be an idea to extend Properties to hold a TheadLocal<Properties> that gets checked before the System Properties are checked for the setting. That would allow to set thread-specific settings that differ from the global ones, so as long as the signature verification process happens within the same thread this might be a solution.

I can provide an implementation of Properties with this if interested.

**Comment by kimmerin** [comment]
After writing above port, I realized that I've been looking at the source of Properties in the j2me-part of the sources. The core-Properties class already contains exactly that feature, so calling

    org.bouncycastle.util.Properties.setThreadOverride("org.bouncycastle.asn1.allow_unsafe_integer", true);

in the signature checking thread should fix the problem without the need to set a global value.

**Comment by ralfhauser** [comment]
thx, setThreadOverride seems to work!

**Comment by peterdettman** [comment]
@ralfhauser Just a final reminder to please follow up with the source of the malformed data if possible.

**Comment by ralfhauser** [comment]
[Testeingabe-sig.pdf](https://github.com/bcgit/bc-java/files/5399645/Testeingabe-sig.pdf)

**Comment by peterdettman** [comment]
@ralfhauser If that file was for me, what I actually meant was that you should follow up with whoever created it in the first place and suggest they fix their broken ASN.1 generator.
