### ISSUE TITLE
Decrypt CMS data with a private key protected by a JCE hardware security module

### ISSUE THREAD

**Issue by kinimoas** [bcgit/bc-java#670]
Hello,

we have a problem with the decryption of CMS data, when using an not extrabable PrivateKey from a hardware security module with the JCE-API.

Function names in the call stack suggest, that cms decryption with Bouncycastle depends on the ability to extract the private key, instead of relying on the JCE services to decrypt the data.

The question is, if we are mistaken and such keys are supported by the current version of Bouncycastle? Or how would we have to extend the cms classes to decode CMS data with a PrivateKey protected by a hsm.

Code:
//PrivateKey from hsm
//method to receive the PrivateKey
PrivateKey key = (PrivateKey) keyStore.getKey(theAlias, null);

//CMS data is read from a file, cont is the content from the file converted to byte[]
CMSEnvelopedDataParser parser = new CMSEnvelopedDataParser(cont);

RecipientInformationStore store = parser.getRecipientInfos();
Collection<RecipientInformation> coll = store.getRecipients();

RecipientInformation recinf = coll.iterator().next();

JceKeyAgreeEnvelopedRecipient recipient = new JceKeyAgreeEnvelopedRecipient(key);
recipient.setProvider(hsm.getProvider());

byte[] contents = recinf.getContent(recipient);

**Comment by bcgit** [comment]
You'd have to provide the stack trace. The api is designed to support HSMs, people have been doing this for years.

**Comment by kinimoas** [comment]
Stack-Trace:

```
Exception in thread "main" java.lang.NullPointerException
at org.bouncycastle.cms.jcajce.JceKeyAgreeRecipient.getPrivateKeyAlgorithmIdentifier(JceKeyAgreeRecipient.java:279)
at org.bouncycastle.cms.KeyAgreeRecipientInformation.getRecipientOperator(KeyAgreeRecipientInformation.java:126)
at org.bouncycastle.cms.RecipientInformation.getContentStream(RecipientInformation.java:169)
at org.bouncycastle.cms.RecipientInformation.getContent(RecipientInformation.java:150)

```
The null-Pointer-Excpetion is thrown because the getEncoded-method of the private key returns NULL for our HSM-JCE-interface in the call getPrivateKeyAlgorithmIdentifier:
`return PrivateKeyInfo.getInstance(recipientKey.getEncoded()).getPrivateKeyAlgorithm(); `

If this is a failure of the HSM to implement the JCE-interface correctly -  do you know the relevant specification?

**Comment by bcgit** [comment]
In this case you should be able to get it to work by overriding the method to return the correct algorithm identifier for the private key.

**Comment by kinimoas** [comment]
OK, I see. I do not know the relevant OID to construct the org.bouncycastle.asn1.x509.AlgorithmIdentifier. I assume I need to provide the OID of the curve? 

I'm able to extract the curve parameters from the private key:
key.getParams().getGenerator().getAffineX() and key.getParams().getGenerator().getAffineY()
is there a possibility in BC to convert X and Y to the OID?

**Comment by kinimoas** [comment]
If I run a modified version overriding the method to return the algorithm identifier, I see the following error:

Exception in thread "main" org.bouncycastle.cms.CMSException: originator key invalid.
at org.bouncycastle.cms.jcajce.JceKeyAgreeRecipient.extractSecretKey(JceKeyAgreeRecipient.java:273)
at org.bouncycastle.cms.jcajce.JceKeyAgreeEnvelopedRecipient.getRecipientOperator(JceKeyAgreeEnvelopedRecipient.java:28)
at org.bouncycastle.cms.KeyAgreeRecipientInformation.getRecipientOperator(KeyAgreeRecipientInformation.java:128)
at org.bouncycastle.cms.RecipientInformation.getContentStream(RecipientInformation.java:169)
at org.bouncycastle.cms.RecipientInformation.getContent(RecipientInformation.java:150)
at de.mbr_msr.pki.DecriptTest.main(DecriptTest.java:218)
Caused by: org.bouncycastle.cms.CMSException: cannot create key factory: no such algorithm: 1.3.36.3.3.2.8.1.1.7 for provider HsmXSeries
at org.bouncycastle.cms.jcajce.EnvelopedDataHelper.createKeyFactory(EnvelopedDataHelper.java:628)
at org.bouncycastle.cms.jcajce.JceKeyAgreeRecipient.extractSecretKey(JceKeyAgreeRecipient.java:219)
... 5 more
Caused by: java.security.NoSuchAlgorithmException: no such algorithm: 1.3.36.3.3.2.8.1.1.7 for provider HsmXSeries
at java.base/sun.security.jca.GetInstance.getService(GetInstance.java:101)
at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:218)
at java.base/java.security.KeyFactory.getInstance(KeyFactory.java:266)
at org.bouncycastle.jcajce.util.ProviderJcaJceHelper.createKeyFactory(ProviderJcaJceHelper.java:83)
at org.bouncycastle.cms.jcajce.EnvelopedDataHelper.createKeyFactory(EnvelopedDataHelper.java:624)
... 6 more

The manufacturer of the HSM asks why a KeyFactory is needed. This seems not to be necessary for private keys that can not be extracted.

**Comment by dghgit** [comment]
The ability to set the private key algorithm identifier should have removed the need to use the key factory. Closing as believe resolved.
