### ISSUE TITLE
ArrayIndexOutOfBoundsException in Poly1305.update(byte[], int, int) when closing a CipherOutputStream after encrypting a large (>2GB) file

### ISSUE THREAD

**Issue by acid1103** [bcgit/bc-java#673]
I'm currently using `bcprov-jdk15to18` version 1.64, retrieved using Maven. I've also tested the current beta (`bcprov-jdk15on-165b08`,) and it throws the same exception.
My code is roughly equivalent to the following:

``` java
SecretKey key = // generate a 256-bit key
byte[] iv = // 12-byte iv
Cipher cipher = new Cipher("CHACHA20-POLY1305");
cipher.init(Cipher.ENCRYPT_MODE, key, new IvParameterSpec(iv));

InputStream in = Files.newInputStream(/* large_file */);
OutputStream out =
	new CipherOutputStream(Files.newOutputStream(/* large_file.encrypted */), cipher);

// reads the contents of `in`, and writes them to `out`
copy(in, out);

in.close();
out.close();
```

At the line `out.close();` I get the following error:
```
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at org.bouncycastle.crypto.macs.Poly1305.update(Unknown Source)
	at org.bouncycastle.crypto.modes.ChaCha20Poly1305.padMAC(Unknown Source)
	at org.bouncycastle.crypto.modes.ChaCha20Poly1305.finishData(Unknown Source)
	at org.bouncycastle.crypto.modes.ChaCha20Poly1305.doFinal(Unknown Source)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$AEADGenericBlockCipher.doFinal(Unknown Source)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source)
	at javax.crypto.Cipher.doFinal(Cipher.java:2047)
	at javax.crypto.CipherOutputStream.close(CipherOutputStream.java:210)
	...
```

This only happens when writing large files. If I had to guess, it might be due to the fact that the file size (in bytes) is larger than `Integer.MAX_VALUE`.

**Comment by peterdettman** [comment]
Thanks for the report. I've pushed a fix to our git repo (which mirrors here on a delay) and we'll try to get a new beta out with the fix shortly.
