### ISSUE TITLE
Android failures due to missing SecureRandom

### ISSUE THREAD

**Issue by yschimke** [bcgit/bc-java#686]
Found while testing bouncycastle and Android with okhttp

https://github.com/square/okhttp/pull/5939

We fixed by creating a SecureRandom insead of null, but reverted because it's unclear of effects on other providers.

```
java.lang.IllegalStateException: unable to create JcaTlsCrypto: DEFAULT SecureRandom not available
at org.bouncycastle.tls.crypto.impl.jcajce.Exceptions.illegalStateException(Unknown Source:2)
at org.bouncycastle.tls.crypto.impl.jcajce.JcaTlsCryptoProvider.create(Unknown Source:65)
at org.bouncycastle.jsse.provider.ProvSSLContextSpi.engineInit(Unknown Source:6)
at javax.net.ssl.SSLContext.init(SSLContext.java:326)
at okhttp3.OkHttpClient$Companion.newSslSocketFactory(OkHttpClient.kt:1064)
at okhttp3.OkHttpClient$Companion.access$newSslSocketFactory(OkHttpClient.kt:1055)
at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:234)
at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:1052)
at okhttp.android.test.OkHttpTest.testBouncyCastleRequest(OkHttpTest.kt:545)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at okhttp3.OkHttpClientTestRule$apply$1.evaluate(OkHttpClientTestRule.kt:117)
at okhttp3.testing.PlatformRule$apply$1.evaluate(PlatformRule.kt:69)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
Caused by: java.security.NoSuchAlgorithmException: DEFAULT SecureRandom not available
at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
at java.security.SecureRandom.getInstance(SecureRandom.java:297)
at org.bouncycastle.tls.crypto.impl.jcajce.JcaTlsCryptoProvider.create(Unknown Source:10)
... 43 more
```

**Comment by dghgit** [comment]
DEFAULT is actually provider by the BC provider. It may not be in the Android version. You can swap in whatever is appropriate for the platform though, any quality SecureRandom will do.
