### ISSUE TITLE
CMSEnvelopedData - unknown object in getInstance: org.bouncycastle.asn1.BERTaggedObject

### ISSUE THREAD

**Issue by Schmidor** [bcgit/bc-java#691]
We're extracting the smime.p7m attachment from signed or encrypted mails and try to decode it by using CMSEnvelopedData.
On the attached signed content it fails with the following exception:
```
org.bouncycastle.cms.CMSException: Malformed content.
	at org.bouncycastle.cms.CMSEnvelopedData.<init>(Unknown Source) ~[bcpkix-jdk15on-1.65.jar:1.65.00.0]
	at org.bouncycastle.cms.CMSEnvelopedData.<init>(Unknown Source) ~[bcpkix-jdk15on-1.65.jar:1.65.00.0]
[...]
Caused by: java.lang.IllegalArgumentException: unknown object in getInstance: org.bouncycastle.asn1.BERTaggedObject
	at org.bouncycastle.asn1.ASN1Sequence.getInstance(ASN1Sequence.java:105) ~[bcprov-debug-jdk15on-1.65.jar:1.65.0]
	at org.bouncycastle.asn1.x509.AlgorithmIdentifier.getInstance(AlgorithmIdentifier.java:34) ~[bcprov-debug-jdk15on-1.65.jar:1.65.0]
	at org.bouncycastle.asn1.cms.EncryptedContentInfo.<init>(EncryptedContentInfo.java:51) ~[bcprov-debug-jdk15on-1.65.jar:1.65.0]
	at org.bouncycastle.asn1.cms.EncryptedContentInfo.getInstance(EncryptedContentInfo.java:82) ~[bcprov-debug-jdk15on-1.65.jar:1.65.0]
	at org.bouncycastle.asn1.cms.EnvelopedData.<init>(EnvelopedData.java:84) ~[bcprov-debug-jdk15on-1.65.jar:1.65.0]
	at org.bouncycastle.asn1.cms.EnvelopedData.getInstance(EnvelopedData.java:131) ~[bcprov-debug-jdk15on-1.65.jar:1.65.0]
	... 24 more
```

[smime.zip](https://github.com/bcgit/bc-java/files/4474721/smime.zip)

**Comment by dghgit** [comment]
I'm not sure, but I think the problem is that you need to be using CMSSignedData for signed emails, CMSEnvelopedData only supports the EnvelopedData structure.

**Comment by Schmidor** [comment]
Indeed, thanks for the hint.
