### ISSUE TITLE
RFC8419 : CMS with Ed448

### ISSUE THREAD

**Issue by pvandenbroucke** [bcgit/bc-java#692]
Hello,

I'm trying to generate CMS signatures with the algorithm Ed448 but I got this exception ; 

> Caused by: org.bouncycastle.operator.OperatorCreationException: cannot recognise digest
	at org.bouncycastle.operator.bc.BcDefaultDigestProvider.get(Unknown Source)
	at org.bouncycastle.operator.bc.BcDigestCalculatorProvider.get(Unknown Source)
	at org.bouncycastle.cms.SignerInfoGenerator.<init>(Unknown Source)
	at org.bouncycastle.cms.SignerInfoGeneratorBuilder.createGenerator(Unknown Source)
	at org.bouncycastle.cms.SignerInfoGeneratorBuilder.build(Unknown Source)

The class [DefaultDigestAlgorithmIdentifierFinder](https://github.com/bcgit/bc-java/blob/r1rv65/pkix/src/main/java/org/bouncycastle/operator/DefaultDigestAlgorithmIdentifierFinder.java#L160) defines correctly the algorithm to be used but the digest algorithm is currently not supported with the [BcDefaultDigestProvider](https://github.com/bcgit/bc-java/blob/r1rv65/pkix/src/main/java/org/bouncycastle/operator/bc/BcDefaultDigestProvider.java).

Additionally, the provider is correctly registered (org.bouncycastle.jcajce.provider.digest.SHA3$DigestShake256_512), but that's not the case for SHAKE128 or SHAKE256.

Regards,

Pierrick

**Comment by bcgit** [comment]
Which version of the API are you using? Are you using 1.65?

**Comment by pvandenbroucke** [comment]
Yes, I'm using the latest release 1.65

**Comment by bcgit** [comment]
Ah, it's currently only supported in the JCA level API. We'll need to add it to the low-level support as well.

**Comment by pvandenbroucke** [comment]
Thanks for the feedback, I will wait for the support.

**Comment by bsanchezb** [comment]
Hello, any updates on this? Seems like in 1.67 it is still not supported. I got the same exception as it was in 1.65.

**Comment by matheus-eyng** [comment]
Thanks to this issue, my team and I were able to track down the and fix the problem we were having when trying to generate CMS signatures for certificate revocation where both the CA and the revoked certificate were signed using Ed448. The error we were getting was:
```
Caused by: java.security.NoSuchAlgorithmException: no such algorithm: SHAKE256-512 for provider BC
at sun.security.jca.GetInstance.getService(GetInstance.java:87) [rt.jar:1.8.0_131]
at sun.security.jca.GetInstance.getInstance(GetInstance.java:206) [rt.jar:1.8.0_131]
at java.security.Security.getImpl(Security.java:698) [rt.jar:1.8.0_131]
at java.security.MessageDigest.getInstance(MessageDigest.java:227) [rt.jar:1.8.0_131]
at org.bouncycastle.jcajce.util.NamedJcaJceHelper.createMessageDigest(Unknown Source) [bcprov-jdk15on-1.68.jar:1.68.0]
at org.bouncycastle.operator.jcajce.OperatorHelper.createDigest(Unknown Source) [bcpkix-jdk15on-1.68.jar:1.68.00.0]
... 55 more
```
Changing to version 1.69 did not fix it. The solution is in #988.

Hope this helps someone

**Comment by dghgit** [comment]
#988 is now addressed.
