### ISSUE TITLE
NPE when used in okhttp-tls library

### ISSUE THREAD

**Issue by yschimke** [bcgit/bc-java#723]
I've raised https://github.com/bcgit/bc-java/pull/722 to keep the root cause for debugging purposes, but flagging here in case you've seen this before.

```
java.security.KeyStoreException: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at com.android.org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(BcKeyStoreSpi.java:689)
        at java.security.KeyStore.setKeyEntry(KeyStore.java:1179)
        at okhttp3.tls.internal.TlsUtil.newKeyManager(TlsUtil.kt:95)
        at okhttp3.tls.HandshakeCertificates$Builder.build(HandshakeCertificates.kt:175)
        at com.myapp.common.security.data.CommonSecurityProvider$Companion.getSslSocketFactoryConfig(CommonSecurityProvider.kt:112)
        at com.myapp.common.network.di.CommonNetworkModuleKt$commonNetworkModule$1$7.invoke(CommonNetworkModule.kt:64)
        at com.myapp.common.network.di.CommonNetworkModuleKt$commonNetworkModule$1$7.invoke(Unknown Source:4)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
```

We've had two reports of this and haven't gotten clean repro yet.

**Comment by yschimke** [comment]
Do "com.android.org.bouncycastle.jcajce" get tracked here or through AOSP?

**Comment by slovi** [comment]
I have the same issue - the problem is that KeyChain.getPrivateKey returns SSLPrivateKey instance which returns NULL on getFormat or getEncoded methods.

I have no idea how to handle these types of keys which is not possible to encode and save to keystore as an entry. The question is how to instantiate KeystoreManager in this case? (According to contract - it is correct that java.security.Key.getFormat returns NULL).

**Comment by dghgit** [comment]
AOSP. I've added support for protected keys here though. There will be an exception on storage, but passing one through a KeyStore will work now.
