### ISSUE TITLE
java.lang.IllegalArgumentException: unknown object in getInstance: org.bouncycastle.asn1.DERNull with BC 165

### ISSUE THREAD

**Issue by ccn-mm** [bcgit/bc-java#732]
I have following code for verifying RSA-PSS signatures:
```
	public static boolean verifSignedData(byte[] signedData, X509Certificate signercert) throws Exception {
		logger.entry();
		boolean result = false;
		try {
			ByteArrayInputStream inputStream = new ByteArrayInputStream(signedData);
			ASN1InputStream asnInputStream = new ASN1InputStream(inputStream);
			CMSSignedData cmsSignedData = new CMSSignedData(ContentInfo.getInstance(asnInputStream.readObject()));
			Collection<SignerInformation> signers = cmsSignedData.getSignerInfos().getSigners();
			X509CertificateHolder ch = new X509CertificateHolder(signercert.getEncoded());
			//BigInteger serialFromCert = signercert.getSerialNumber();
			for (SignerInformation si : signers) {
				BigInteger serialFromSignature =si.getSID().getSerialNumber();				
				logger.info("AlgorithmId: {} serial: {} signer DN: {}", si.getDigestAlgOID(), serialFromSignature );
				if (si.getSID().match(ch)) {
					logger.info("found match");		
					SignerInformationVerifier verifier = new JcaSimpleSignerInfoVerifierBuilder().setProvider(new BouncyCastleProvider()).build(ch);
					SignerInformationVerifier signerInformationVerifier =new JcaSimpleSignerInfoVerifierBuilder().build(signercert);
					result = si.verify(signerInformationVerifier);
					logger.info("1: "+result);
					result = si.verify(verifier);						
					logger.info("2: "+result);
							//result=true;
//					else
	//					logger.warn("Signature verification failed! serial from cert: {}. serial from signature: {}", serialFromCert, serialFromSignature);					
				}				
			}
			asnInputStream.close();
	    } catch (org.bouncycastle.cms.CMSException e) {
	    	logger.error("data seems not be signed");
	    } catch (Exception e) {
	    	logger.error("", e);
	    }
		logger.exit();
		return result;	
	}
```
I get following exception when doing a verification:
2020-06-18 10:30:06,234 INFO  de.martinm.kks.PKCSTool: verify - Got certificate from file ..\data\KKS\14091973.cert.pem. issuer: CN=Dr. Mueller, OU=BN14091973, OU=MuellerKasse, O=ITSG TrustCenter fuer Arbeitgeber, C=DE
2020-06-18 10:30:06,235 DEBUG de.martinm.kks.PKCSTool: verify - read data file: ..\data\KKS\data.signed
2020-06-18 10:30:06,241 DEBUG de.martinm.kks.PKCSTool: verify - read 5355 bytes from file ..\data\KKS\data.signed
2020-06-18 10:30:06,390 INFO  de.martinm.kks.PKCSTool: verifSignedData - AlgorithmId: 2.16.840.1.101.3.4.2.1 serial: 4103 signer DN: {}
2020-06-18 10:30:06,392 INFO  de.martinm.kks.PKCSTool: verifSignedData - found match
2020-06-18 10:30:06,520 ERROR de.martinm.kks.PKCSTool: verifSignedData -
java.lang.IllegalArgumentException: unknown object in getInstance: org.bouncycastle.asn1.DERNull
        at org.bouncycastle.asn1.ASN1Sequence.getInstance(Unknown Source)
        at org.bouncycastle.asn1.x509.AlgorithmIdentifier.getInstance(Unknown Source)
        at org.bouncycastle.operator.jcajce.OperatorHelper.notDefaultPSSParams(Unknown Source)
        at org.bouncycastle.operator.jcajce.OperatorHelper.createSignature(Unknown Source)
        at org.bouncycastle.operator.jcajce.JcaContentVerifierProviderBuilder$1.get(Unknown Source)
        at org.bouncycastle.cms.SignerInformationVerifier.getContentVerifier(Unknown Source)
        at org.bouncycastle.cms.SignerInformation.doVerify(Unknown Source)
        at org.bouncycastle.cms.SignerInformation.verify(Unknown Source)
        at de.martinm.kks.PKCSTool.verifSignedData(PKCSTool.java:108)
        at de.martinm.kks.PKCSTool.verify(PKCSTool.java:150)
        at de.martinm.kks.PKCSTool.process(PKCSTool.java:82)
        at de.martinm.kks.PKCSTool.main(PKCSTool.java:220)
2020-06-18 10:30:06,523 INFO  de.martinm.kks.PKCSTool: verify - verified: false

The exception does not occur with version 1.54 but the verification is not successful in this case

**Comment by ccn-mm** [comment]
Output with BC 1.54:
2020-06-18 11:16:56,619 INFO  de.martinm.kks.PKCSTool: verify - Got certificate from file ..\data\KKS\14091973.cert.pem. issuer: CN=Dr. Mueller, OU=BN14091973, OU=MuellerKasse, O=ITSG TrustCenter fuer Arbeitgeber, C=DE
2020-06-18 11:16:56,619 DEBUG de.martinm.kks.PKCSTool: verify - read data file: ..\data\KKS\data.signed
2020-06-18 11:16:56,625 DEBUG de.martinm.kks.PKCSTool: verify - read 5355 bytes from file ..\data\KKS\data.signed
2020-06-18 11:16:56,701 INFO  de.martinm.kks.PKCSTool: verifSignedData - AlgorithmId: 2.16.840.1.101.3.4.2.1 serial: 4103 signer DN: {}
2020-06-18 11:16:56,701 INFO  de.martinm.kks.PKCSTool: verifSignedData - found match
2020-06-18 11:16:56,835 INFO  de.martinm.kks.PKCSTool: verifSignedData - 1: false
2020-06-18 11:16:56,840 INFO  de.martinm.kks.PKCSTool: verifSignedData - 2: false
2020-06-18 11:16:56,841 INFO  de.martinm.kks.PKCSTool: verify - verified: false

**Comment by dghgit** [comment]
From the look of it the parameters structure is missing for the PSS signature. I'd have to see a dump to be sure, but I can say passing ASN.1 NULL is not valid.

**Comment by dghgit** [comment]
Appears to be resolved.
