### ISSUE TITLE
throw java.security.cert.CertificateException: Unknown authType: KE:RSA when using JDK 6 with TLS connection with RSA algorithm

### ISSUE THREAD

**Issue by tt4g** [bcgit/bc-java#748]
I get the error message "certificate_unknown(46)" and "Unknown authType: KE:RSA".

<summary>Stack trace:
<details>

```java
2020/07/14 10:55:13 org.bouncycastle.jsse.provider.PropertyUtils getStringSecurityProperty
WARN: String security property [jdk.tls.disabledAlgorithms] defaulted to: SSLv3, RC4, DES, MD5withRSA, DH keySize < 1024
, EC keySize < 224, 3DES_EDE_CBC, anon, NULL, include jdk.disabled.namedCurves
2020/07/14 10:55:13 org.bouncycastle.jsse.provider.DisabledAlgorithmConstraints create
WARN: Ignoring unsupported entry in 'jdk.tls.disabledAlgorithms': include jdk.disabled.namedCurves
2020/07/14 10:55:13 org.bouncycastle.jsse.provider.PropertyUtils getStringSecurityProperty
WARN: String security property [jdk.certpath.disabledAlgorithms] defaulted to: MD2, MD5, SHA1 jdkCA & usage TLSServer, R
SA keySize < 1024, DSA keySize < 1024, EC keySize < 224, include jdk.disabled.namedCurves
2020/07/14 10:55:13 org.bouncycastle.jsse.provider.DisabledAlgorithmConstraints create
WARN: Ignoring unsupported entry in 'jdk.certpath.disabledAlgorithms': SHA1 jdkCA & usage TLSServer
2020/07/14 10:55:13 org.bouncycastle.jsse.provider.DisabledAlgorithmConstraints create
WARN: Ignoring unsupported entry in 'jdk.certpath.disabledAlgorithms': include jdk.disabled.namedCurves
2020/07/14 10:55:14 org.bouncycastle.jsse.provider.ProvTlsClient notifyAlertRaised
INFO: Client raised fatal(2) certificate_unknown(46) alert: Failed to read record
org.bouncycastle.tls.TlsFatalAlert: certificate_unknown(46)
        at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.checkServerTrusted(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvTlsClient$1.notifyServerCertificate(Unknown Source)
        at org.bouncycastle.tls.TlsUtils.processServerCertificate(Unknown Source)
        at org.bouncycastle.tls.TlsClientProtocol.handleServerCertificate(Unknown Source)
        at org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source)
        at org.bouncycastle.tls.RecordStream.readRecord(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.blockForHandshake(Unknown Source)
        at org.bouncycastle.tls.TlsClientProtocol.connect(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:434)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:166)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:133)
        at reproduce.project.App.main(App.java:72)
Caused by: java.security.cert.CertificateException: Unknown authType: KE:RSA
        at sun.security.validator.EndEntityChecker.checkTLSServer(EndEntityChecker.java:264)
        at sun.security.validator.EndEntityChecker.check(EndEntityChecker.java:124)
        at sun.security.validator.Validator.validate(Validator.java:221)
        at com.sun.net.ssl.internal.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:126)
        at com.sun.net.ssl.internal.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:209)
        at org.bouncycastle.jsse.provider.ImportX509TrustManager_5.checkServerTrusted(Unknown Source)
        ... 17 more
org.bouncycastle.tls.TlsFatalAlert: certificate_unknown(46)
        at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.checkServerTrusted(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvTlsClient$1.notifyServerCertificate(Unknown Source)
        at org.bouncycastle.tls.TlsUtils.processServerCertificate(Unknown Source)
        at org.bouncycastle.tls.TlsClientProtocol.handleServerCertificate(Unknown Source)
        at org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source)
        at org.bouncycastle.tls.RecordStream.readRecord(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source)
        at org.bouncycastle.tls.TlsProtocol.blockForHandshake(Unknown Source)
        at org.bouncycastle.tls.TlsClientProtocol.connect(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
        at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:434)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:166)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:133)
        at reproduce.project.App.main(App.java:72)
Caused by: java.security.cert.CertificateException: Unknown authType: KE:RSA
        at sun.security.validator.EndEntityChecker.checkTLSServer(EndEntityChecker.java:264)
        at sun.security.validator.EndEntityChecker.check(EndEntityChecker.java:124)
        at sun.security.validator.Validator.validate(Validator.java:221)
        at com.sun.net.ssl.internal.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:126)
        at com.sun.net.ssl.internal.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:209)
        at org.bouncycastle.jsse.provider.ImportX509TrustManager_5.checkServerTrusted(Unknown Source)
        ... 17 more
```
</details>
</summary>

The following text is part of tcp packet capture by WireShark:

<summary>
<details>

```
Transport Layer Security
    TLSv1.2 Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.0 (0x0301)
        Length: 170
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 166
            Version: TLS 1.2 (0x0303)
            Random: a7e80741e57c8590c6125a83cb2733ab2bafbae857e4935b…
            Session ID Length: 0
            Cipher Suites Length: 26
            Cipher Suites (13 suites)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (0xc024)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (0xc023)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a)
                Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (0xc009)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)
                Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)
                Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA256 (0x003d)
                Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA256 (0x003c)
                Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
                Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
                Cipher Suite: TLS_EMPTY_RENEGOTIATION_INFO_SCSV (0x00ff)
            Compression Methods Length: 1
            Compression Methods (1 method)
            Extensions Length: 99
            Extension: extended_master_secret (len=0)
            Extension: encrypt_then_mac (len=0)
            Extension: supported_groups (len=14)
            Extension: status_request_v2 (len=16)
            Extension: status_request (len=5)
            Extension: signature_algorithms (len=34)
            Extension: ec_point_formats (len=2)


Transport Layer Security
    TLSv1.2 Record Layer: Handshake Protocol: Server Hello
        Content Type: Handshake (22)
        Version: TLS 1.2 (0x0303)
        Length: 42
        Handshake Protocol: Server Hello
            Handshake Type: Server Hello (2)
            Length: 38
            Version: TLS 1.2 (0x0303)
            Random: 5f0d1082d1ae46b46137d7e7117cef74bb685fb05cd9bd7f…
            Session ID Length: 0
            Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA256 (0x003d)
            Compression Method: null (0)


Transport Layer Security
    TLSv1.2 Record Layer: Handshake Protocol: Certificate
        Content Type: Handshake (22)
        Version: TLS 1.2 (0x0303)
        Length: 3042
        Handshake Protocol: Certificate
            Handshake Type: Certificate (11)
            Length: 3038
            Certificates Length: 3035
            Certificates (3035 bytes)


Transport Layer Security
    TLSv1.2 Record Layer: Alert (Level: Fatal, Description: Certificate Unknown)
        Content Type: Alert (21)
        Version: TLS 1.2 (0x0303)
        Length: 2
        Alert Message
            Level: Fatal (2)
            Description: Certificate Unknown (46)
```

</details>
</summary>

The Cipher suite is `TLS_RSA_WITH_AES_256_CBC_SHA256` selected by the server halo.
But `sun.security.validator.EndEntityChecker.checkTLSServer` passed `"KE:RSA"`.

I found a source that converts the server algorithm `"RSA"` to `"KE:RSA"` here:

https://github.com/bcgit/bc-java/blob/07604208a773d2334fb09276796288404804e557/tls/src/main/java/org/bouncycastle/jsse/provider/JsseUtils.java#L262-L264

Why change to an algorithm that is not supported by JDK 6?
Is there a mistake in the use of the library in my code below?
this code was written in reference to https://github.com/bcgit/bc-java/blob/r1rv66/tls/src/test/java/org/bouncycastle/jsse/provider/test/BCJSSEClientTest.java

<summary>Reproduce code :
<details>

```java
package reproduce.project;

import java.io.IOException;
import java.net.URL;
import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import javax.net.ssl.HttpsURLConnection;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSocketFactory;

import org.bouncycastle.jsse.provider.BouncyCastleJsseProvider;

public class Reproduce {

    private static SSLContext createSSLContext() throws NoSuchAlgorithmException, KeyManagementException {
        boolean fipsMode = true;
        BouncyCastleJsseProvider provider = new BouncyCastleJsseProvider(fipsMode);

        SSLContext sslContext = SSLContext.getInstance("TLS", provider);
        sslContext.init(null, null, new SecureRandom());

        return sslContext;
    }

    public static void main(String[] args) throws IOException, KeyManagementException, NoSuchAlgorithmException {
        String endpoint = "https://example.com/";

        URL url = new URL(endpoint);

        HttpsURLConnection con = (HttpsURLConnection) url.openConnection();

        SSLContext sslContext = createSSLContext();
        SSLSocketFactory sslSocketFactory = sslContext.getSocketFactory();

        con.setSSLSocketFactory(sslSocketFactory);

        con.setRequestMethod("GET");
        con.setInstanceFollowRedirects(false);
        con.setConnectTimeout(1000);
        con.setReadTimeout(1000);

        try {
            con.connect();

            System.out.println("Response status: " + con.getResponseCode());
        } finally {
            con.disconnect();
        }
    }

}
```
</details>
</summary>

### Java version

```
$ "C:\Program Files\Java\jdk1.6.0_38\bin\java" -version
java version "1.6.0_38"
Java(TM) SE Runtime Environment (build 1.6.0_38-b05)
Java HotSpot(TM) 64-Bit Server VM (build 20.13-b02, mixed mode)
```

NOTE: [Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files](https://www.oracle.com/java/technologies/javase-jce-all-downloads.html) applied.

### Dependency Librarires

* bcprov-jdk15to18-166.jar 
* bctls-jdk15to18-166.jar

**Comment by peterdettman** [comment]
A BCJSSE SSLContext can only be used with the TrustManagers from a BCJSSE TrustManagerFactory (likewise the KeyManagers from a BCJSSE KeyManagerFactory). We use an incompatible set of 'authType' strings from SunJSSE to avoid its limitations especially when selecting RSA credentials.

This can be done programmatically by explicitly passing "BCJSSE" as the provider to getInstance calls, or it can be done by configuring the provider priority so that BCJSSE is ahead of SunJSSE (and any other JSSE providers)..

So in copying the BCJSSEClientTest code, you neglected this line, which would put BCJSSE at higher priority than SunJSSE so that the test finds a BCJSSE TMF:
```
ProviderUtils.setupHighPriority(false);
```

Since you are just using the default trust store you could instead change the SSLContext initialisation this way:

```
BouncyCastleJsseProvider provider = new BouncyCastleJsseProvider(fipsMode);

TrustManagerFactory tmf = TrustManagerFactory.getInstance("PKIX", provider);
tmf.init((KeyStore)null);

SSLContext sslContext = SSLContext.getInstance("TLS", provider);
sslContext.init(null, tmf.getTrustManagers(), new SecureRandom());
```

**Comment by tt4g** [comment]
Thank you for quick response.

I didn't try the `TrustManager` provided by the BCJSSE because I wanted to use the `TrustManager` used by the JDK.

I understood that this is the design of the BCJSSE.

**Comment by peterdettman** [comment]
We tried very hard for interoperability with SunJSSE KMF and TMF and we have come quite close, but in our view SunJSSE does not handle RSA (and RSA-PSS) credentials correctly (even in latest JDK) and in order to do so we unfortunately cannot reach full interoperability.

Let us know if there are specific features of the SunJSSE TrustManager that you believe are missing from BCJSSE one.

**Comment by tt4g** [comment]
The way you taught me to use the `TrustManagerFactory` worked for me.

Thanks to the efforts of the author and contributors.
