### ISSUE TITLE
Certificate parser throws CertificateException "parsing issue: malformed PEM data: no header found" if the PEM file has additional newlines

### ISSUE THREAD

**Issue by martijnbrinkers** [bcgit/bc-java#758]
If a PEM certificate file contains additional newlines (\n), the certificate parser throws the following exception when calling CertificateFactory#generateCertificates:

```
 org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory$ExCertificateException: parsing issue: malformed PEM data: no header found
	at org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory.engineGenerateCertificate(CertificateFactory.java:240)
	at org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory.engineGenerateCertificates(CertificateFactory.java:257)
	at java.base/java.security.cert.CertificateFactory.generateCertificates(CertificateFactory.java:478)
	at Test.main(Test.java:63)
Caused by: java.io.IOException: malformed PEM data: no header found
	at org.bouncycastle.jcajce.provider.asymmetric.x509.PEMUtil.readPEMObject(PEMUtil.java:134)
	at org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory.readPEMCertificate(CertificateFactory.java:67)
	at org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory.engineGenerateCertificate(CertificateFactory.java:231)
	... 3 more
```
This was working in older version of BC.

The following test example shows that an exception is thrown when an additional newline character is added to the PEM encoded certificate.

```
import java.io.ByteArrayInputStream;
import java.security.Security;
import java.security.cert.Certificate;
import java.security.cert.CertificateException;
import java.security.cert.CertificateFactory;
import java.util.Collection;

import org.bouncycastle.jce.provider.BouncyCastleProvider;

public class Test {

    public static void main(String[] args)
    throws Exception
    {
        String PEM = "-----BEGIN CERTIFICATE-----\n" +
                "MIIFnTCCA4WgAwIBAgIQAU3ninOCS2ONavh0497qEjANBgkqhkiG9w0BAQsFADBe\n" +
                "MQswCQYDVQQGEwJOTDELMAkGA1UECAwCTkgxEjAQBgNVBAcMCUFtc3RlcmRhbTEu\n" +
                "MCwGA1UEAwwlQ2lwaGVyTWFpbCBsaWNlbnNpbmcgcm9vdCBjZXJ0aWZpY2F0ZTAe\n" +
                "Fw0xNTA2MTIxMTMxNTlaFw0zNTA2MTIxMTMxNTlaMF4xCzAJBgNVBAYTAk5MMQsw\n" +
                "CQYDVQQIDAJOSDESMBAGA1UEBwwJQW1zdGVyZGFtMS4wLAYDVQQDDCVDaXBoZXJN\n" +
                "YWlsIGxpY2Vuc2luZyByb290IGNlcnRpZmljYXRlMIICIjANBgkqhkiG9w0BAQEF\n" +
                "AAOCAg8AMIICCgKCAgEAqV/iuV6dRUyck5hUePp9v0SsmO7G/RSCT87S6BykOrsO\n" +
                "VZScamnJDy274QwUhPgh10QDeRgchNsSTjQccL8X/kVrXwcANENyl99s3PUjNTiY\n" +
                "kP92oFYK5O7C2JNmCekaErsdRymKiKo8kb3MARlfv6e2IbwMQhCaQoeBqJW3dNx+\n" +
                "lYw5dlULPp6UtoQl+JgSuphx6944CG32WOLdMYF/J9mUM1RrQKZkTP0cARXxnwwk\n" +
                "kAvH4ye9frQc6qBpTQW6r7oQ66W77tlOho/KlEHdNe3lG+g7xo3scOIsXuBNTvee\n" +
                "TiMZnNVHV7T+p4X4hZL3grAl57EXKKnOOQXwSf3FLNMJ2sKphu/Tm2xi1csZpnge\n" +
                "axtbl/UMqnEOc3WTJbN9gD1KeQiJ4cfO9jmKnr39QxGSfgWvsDRqEVh62k+7TM4B\n" +
                "GXpXtuS/gk6vzyGlcVAyanIWhibfsDsXQTPFjhjJqno1gxFvI1R/bWp0+WYw+LZg\n" +
                "hZbWLEpIxhx6QTIWpTE60x+MEnv1j22kUZ0mj7K/JSmW0zriwA8CjDwmGp8OOiC/\n" +
                "8qs+nTx6mwZWD6mrBgQPRLw57fnY3ok9gzzxSvTgmGQRIOyGQ79muoDyFTuJbU/7\n" +
                "TFH2HZDP+Xt+6xHjzz+ECGxeUvDga0u3mbFUTn9DVM45a/ADrkILwmOfSflLhkMC\n" +
                "AwEAAaNXMFUwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwEwYDVR0l\n" +
                "BAwwCgYIKwYBBQUHAwMwHQYDVR0OBBYEFHMbqoKyKrhg++J9Dc3sgcybW+wPMA0G\n" +
                "CSqGSIb3DQEBCwUAA4ICAQB6luyggsEhNYQywZAyC9BRvLSIpb3kGK1rgUcd4Jec\n" +
                "JO9L0PE8raCveRTf3NgVpvwgZqsAoWG2IAGKkdFGwgi4DJmdMDaO5YMRtK8qgDKt\n" +
                "SZfYI0TZCOrrFAPeET6Vy0tB/SelSbhW6jM0VJM1hnNo0WfLFJz8W2PjpgV8ikUj\n" +
                "hKd+sg+Qb6xOZw70vQkp/RauBbs2GSqOQXBFRvUyMD5Xjb5alK2rwXCUsk/IMDHc\n" +
                "y0OjsCgJIKpaQPME7pIyw6CVDxaeOZE/XuYw9LlFovcOUkhGBfzLBonGnCFsr9jF\n" +
                "ElKlpT2fSoOWd25tLaTXY1hoPzknoRF1d8q1tlqp6khe9vmzfRY0RRHDAE/5L+6L\n" +
                "3P/Kfr76Sn03YZYw9g/4YMdWvwScO2Ibt/nU4+din9vw5tpcUtYiCnQoS92L7EGp\n" +
                "lMgtwEDXPBmDsFl2m4zSytljTx4jrxHO8LKu0ZYsTKBGKF5/2nr074x14uNYVMrC\n" +
                "xy9+XWcC3yc9jh9n01U4XE/XE0xrAZGC4Rp/OUsTPuPnq+LfvIXcIDj/WYG8R7Yr\n" +
                "xS8PkFntbPCaQFoTzqZ4dtFk+snd6+lrWWs5uAUnSYgMf0r3axAwwswwB4/gXPur\n" +
                "BzBv00+GdMolSAOs9lgTAaDwafkp7v2nNX0FAunWwNR7j2jbHPAl+8D4HCLcjNO2\n" +
                "Dg==\n" +
                "-----END CERTIFICATE-----\n";

        Security.addProvider(new BouncyCastleProvider());

        CertificateFactory fac = CertificateFactory.getInstance("X509", "BC");

        Collection<? extends Certificate> certificates = fac.generateCertificates(new ByteArrayInputStream((PEM.getBytes("UTF-8"))));

        System.out.println(certificates.size());

        /*
         * Add additional newline
         */
        String withAdditionalNewline = PEM + "\n";

        try {
            certificates = fac.generateCertificates(new ByteArrayInputStream((withAdditionalNewline.getBytes("UTF-8"))));

            System.out.println(certificates.size());
        }
        catch (CertificateException e)
        {
            System.err.println("********* Exception thrown ********");

            e.printStackTrace();
        }
    }
}
```

**Comment by martijnbrinkers** [comment]
I think this was introduced in commit 382c162d5b9bd654dfdbb7feb64c88e21c0e2e51 for org.bouncycastle.jcajce.provider.asymmetric.x509.PEMUtil.

Before this change, PEMUtil allowed importing a text file containing PEM encoded certificates embedded within a text file containing other content. Example which I think worked previously:

```
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE----- 

Some text

```

This seems to be no longer supported because PEMUtil chockes on the text after END CERTIFICATE

**Comment by martijnbrinkers** [comment]
The issue #753, is probably related to this issue. In older BC releases (before commit 382c162), the following certificate would be imported

```
-----BEGIN CERTIFICATE-----
....
-----ENDCERTIFICATE-----
```
The latest release throws an exception "malformed PEM data: no footer found".

The change in commit 382c162 might break a lot of existing code because certificate which were initially accepted by older releases of BC are all of a sudden no longer accepted. The reporter with bug #753 probably validated the certificate prior to importing and assumed that the certificate could then be read after storing the cert in the database. The new BC release then no longer accepted the cert.

**Comment by martijnbrinkers** [comment]
The default Java (Sun) CertificateFactory, accepts PEM files with additional new lines.

**Comment by dghgit** [comment]
I've fixed this and added some test coverage in 169b05. See https://www.bouncycastle.org/betas for details.
