### ISSUE TITLE
GNUPG 2.2.X file format support

### ISSUE THREAD

**Issue by sarfudheen** [bcgit/bc-java#794]
I'm trying to load GNUPG 2.2.23 secret keys from D:\Users\xxxxx\AppData\Roaming\gnupg\private-keys-v1.d using bouncy castle bcpg-jdk15on-1.66.jar.

```
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

import org.bouncycastle.gpg.SExprParser;
import org.bouncycastle.openpgp.PGPException;
import org.bouncycastle.openpgp.PGPSecretKey;
import org.bouncycastle.openpgp.operator.PBEProtectionRemoverFactory;
import org.bouncycastle.openpgp.operator.PGPDigestCalculatorProvider;
import org.bouncycastle.openpgp.operator.jcajce.JcaKeyFingerprintCalculator;
import org.bouncycastle.openpgp.operator.jcajce.JcaPGPDigestCalculatorProviderBuilder;
import org.bouncycastle.openpgp.operator.jcajce.JcePBEProtectionRemoverFactory;
import org.bouncycastle.util.encoders.Hex;

public class LoadKey {
    public static void main(String[] args) throws IOException, PGPException {
        String filePath = "D:\\Users\\XXXX\\AppData\\Roaming\\gnupg\\private-keys-v1.d\\4B8379C14DED7818D546E3C4AF7F1D0DF5716BCD.key";
        String pass = "siv_test";
            PGPDigestCalculatorProvider calculatorProvider = new JcaPGPDigestCalculatorProviderBuilder()
                    .build();
            PBEProtectionRemoverFactory passphraseProvider = new JcePBEProtectionRemoverFactory(
                pass.toCharArray());
        InputStream in = new FileInputStream(filePath);


        PGPSecretKey key =

        new SExprParser(calculatorProvider).parseSecretKey(
                new BufferedInputStream(in), passphraseProvider,
                new JcaKeyFingerprintCalculator());

        System.out.println("Found key "
                + Hex.toHexString(key.getPublicKey().getFingerprint()));
            
        
    }
}

```
But I'm getting

**Exception in thread "main" java.io.IOException: unknown character encountered: K at org.bouncycastle.gpg.SXprUtils.skipOpenParenthesis(Unknown Source) at org.bouncycastle.gpg.SExprParser.parseSecretKey(Unknown Source)**

**gpg (GnuPG) 2.2.23

libgcrypt 1.8.6**

It seems to secret key file format has been changed between GNUPG 2.1.X et GNUPG 2.2.X

https://lists.gnupg.org/pipermail/gnupg-devel/2017-December/033295.html

**Comment by tomaswolf** [comment]
Yes, this would be useful.

1. The file format is different. See [keyformat.txt](https://github.com/gpg/gnupg/blob/master/agent/keyformat.txt) The "Extended Private Key Format" is the default since gpg-agent 2.2.20.
2. Keys are encrypted using AES/OCB/NoPadding. The `JcePBEProtectionRemoverFactory` is hard-coded to AES/CBC/NoPadding. The AAD is the full key binary s-expression (starting with the key type) minus the protected sub-list.

[Sample code](https://git.eclipse.org/r/c/jgit/jgit/+/175332) for this is in JGit. If anyone's interested in doing this properly in BC itself, feel free to take that code as inspiration.

**Comment by bodhi-one** [comment]
Bump

**Comment by dghgit** [comment]
This is now done (fully).

Two things have been done:

  1. Dedicated extended-format API (added earlier under this issue): org.bouncycastle.gpg.PGPSecretKeyParser.parse(in, maxDepth) detects and consumes the header block and returns an OpenedPGPKeyData; OpenedPGPKeyData.getKeyData(publicKey, digestProvider, protectionRemoverFactory, fingerprintCalculator, maxDepth) yields an ExtendedPGPSecretKey. The AES/OCB protection mode modern GnuPG uses (and its lack of a separate hash) is handled too, so protected keys decrypt correctly. See ExSExprTest for worked examples across RSA, DSA/ElGamal, Ed25519/Ed448/X448, NIST P-256/384/521 and Brainpool.
  2. The original entry point now just works. SExprParser.parseSecretKey(...) (the method in your original report) auto-detects an extended-format stream and  routes it through the parser above, while leaving the canonical-format path unchanged. So existing code calling parseSecretKey against a modern private-keys-v1.d/<keygrip>.key file no longer needs any change.
  
1 was actually dealt with some time ago, we just never quite made it to 2.

Now on https://www.bouncycastle.org/betas
