### ISSUE TITLE
[bctls-fips-1.0.10.1.jar] We are having an issue to validate the certificate chain with FIPS-140

### ISSUE THREAD

**Issue by minQueue** [bcgit/bc-java#812]
We are using JDK1.8.0_92, Tomcat 7.0.69, X509 Certificate w BCFKS keystore.

1. How do I disable validation? how do I disable the certificate chain validation?
  
I got the errors below

Caused by: java.security.cert.CertificateException: Unable to construct a valid chain
	at org.bouncycastle.jsse.provider.ProvX509TrustManager.validateChain(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvX509TrustManager.checkTrusted(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvX509TrustManager.checkServerTrusted(Unknown Source)
	... 82 more
Caused by: java.security.cert.CertPathBuilderException: Unable to find certificate chain.
	at org.bouncycastle.jcajce.provider.PKIXCertPathBuilderSpi.engineBuild(Unknown Source)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at org.bouncycastle.jsse.provider.ProvX509TrustManager.buildCertPath(Unknown Source)
	... 85 more

2. How do I debug validation process?

**Comment by peterdettman** [comment]
> How do I disable validation? how do I disable the certificate chain validation?

That seems like a bad idea. I gather from email elsewhere that you are using self-signed certs - have you added them to the trust store (passed to TrustManagerFactory.init)? ProvX509TrustManager will skip CertPathBuilder when a trusted cert is being used directly: https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/tls/src/main/java/org/bouncycastle/jsse/provider/ProvX509TrustManager.java#L201

**Comment by dghgit** [comment]
Closing as inactive. Assumed resolved.
