### ISSUE TITLE
NullPointerException in PSSSigner with JDK 1.8.0_261 and higher

### ISSUE THREAD

**Issue by martin-robo** [bcgit/bc-java#829]
The latest releases of the Oracle 8 JDK (JDK 1.8.0_261+) conflict with `PSSSigner` of Bouncy Castle.

`Caused by: java.lang.NullPointerException
                at org.bouncycastle.crypto.signers.PSSSigner.generateSignature(Unknown Source) ~[bcprov-jdk15on-1.60.jar:1.60.0]
                at org.bouncycastle.jcajce.provider.asymmetric.rsa.PSSSignatureSpi.engineSign(Unknown Source) ~[bcprov-jdk15on-1.60.jar:1.60.0]
                at java.security.Signature$Delegate.engineSign(Signature.java:1382) ~[?:1.8.0_261]
                at java.security.Signature.sign(Signature.java:698) ~[?:1.8.0_261]
                at sun.security.ssl.ECDHServerKeyExchange$ECDHServerKeyExchangeMessage.<init>(ECDHServerKeyExchange.java:177) ~[?:1.8.0_261]
                at sun.security.ssl.ECDHServerKeyExchange$ECDHServerKeyExchangeProducer.produce(ECDHServerKeyExchange.java:499) ~[?:1.8.0_261]
                at sun.security.ssl.ClientHello$T12ClientHelloConsumer.consume(ClientHello.java:966) ~[?:1.8.0_261]
                at sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:718) ~[?:1.8.0_261]
                at sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:683) ~[?:1.8.0_261]
                at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:376) ~[?:1.8.0_261]
                at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:451) ~[?:1.8.0_261]
                at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:987) ~[?:1.8.0_261]
                at sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:974) ~[?:1.8.0_261]
                at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_261]
                at sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:921) ~[?:1.8.0_261]
`

Right now I don't know what I can do to work around this. Has anybody some more details on this?

**Comment by coffeys** [comment]
have you tested with lastest BC releases ? I believe that issue was resolved via https://github.com/bcgit/bc-java/commit/640f6cba8362f7a28a09e457af86e4fd6724c190

**Comment by martin-robo** [comment]
Seems like your right! Sorry for bothering. This is resolved with BC 1.65, my bad. Thank you for the quick reply, though!
