### ISSUE TITLE
tls handshake failure with curve brainpoolP256r1 after new java11 update (openjdk 11.0.9 2020-10-20)

### ISSUE THREAD

**Issue by 13rian** [bcgit/bc-java#831]
after upgrading to the new java11 version the tls handshake for the brainpool curve brainpoolP256r1 throws the following exception:
Nov 11, 2020 11:49:03 AM org.bouncycastle.jsse.provider.ProvTlsServer notifyAlertRaised
INFO: Server raised fatal(2) bad_certificate(42) alert: Failed to read record
org.bouncycastle.tls.TlsFatalAlert: bad_certificate(42)
	at org.bouncycastle.jsse.provider.ProvTlsServer.notifyClientCertificate(Unknown Source)
	at org.bouncycastle.tls.TlsServerProtocol.notifyClientCertificate(Unknown Source)
	at org.bouncycastle.tls.TlsServerProtocol.receiveCertificateMessage(Unknown Source)
	at org.bouncycastle.tls.TlsServerProtocol.handleHandshakeMessage(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source)
	at org.bouncycastle.tls.RecordStream.readRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source)
	at org.bouncycastle.tls.TlsProtocol.blockForHandshake(Unknown Source)
	at org.bouncycastle.tls.TlsServerProtocol.accept(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.handshakeIfNecessary(Unknown Source)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect$AppDataInput.read(Unknown Source)
	at java.base/java.io.InputStream.read(InputStream.java:205)

prior to the update there were no issues.

**Comment by 13rian** [comment]
I figured it out. The problem was the wrong order of the Security Providers. The correct order is:
BCJSSE
BC
SUN
