### ISSUE TITLE
Support CipherSuite.TLS_PSK_WITH_AES_128_GCM_SHA256 ?

### ISSUE THREAD

**Issue by Sjworks** [bcgit/bc-java#863]
Hello,
I'm implementing Philips Hue Stream application using this library.
As I know, Hue Bridge support only TLS_PSK_WITH_AES_128_GCM_SHA256 with PSK in DTLS.

https://developers.meethue.com/develop/hue-entertainment/philips-hue-entertainment-api/
> DTLS Handshaking
> UDP port 2100 is used for DTLS handshaking and streaming. Only DTLS mode version 1.2 with Pre-Shared Key (PSK) Key exchange method with TLS_PSK_WITH_AES_128_GCM_SHA256 set as Cipher Suite is supported

When I initializing with this library. I got following error.

```
DTLS-PSK client negotiated DTLS 1.2
DTLS-PSK client raised alert: fatal(2), insufficient_security(71)
2021-01-03 21:53:05,407 ERROR [http-nio-3000-exec-2] org.apache.juli.logging.DirectJDKLog: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
org.bouncycastle.tls.TlsFatalAlert: insufficient_security(71)
	at org.bouncycastle.tls.TlsDHUtils.receiveDHConfig(TlsDHUtils.java:114)
	at org.bouncycastle.tls.TlsPSKKeyExchange.processServerKeyExchange(TlsPSKKeyExchange.java:170)
	at org.bouncycastle.tls.DTLSClientProtocol.processServerKeyExchange(Unknown Source)
	at org.bouncycastle.tls.DTLSClientProtocol.clientHandshake(Unknown Source)
	at org.bouncycastle.tls.DTLSClientProtocol.connect(Unknown Source)
```

and I captured packet using wireshark

192.168.0.10 : my app(Client)
192.168.0.200 : Hue Bridge(Server)

No. / Time / Source / Destination / Protocol / Length / Info
- 115	5.461369	192.168.0.10	192.168.0.200	DTLSv1.2	220	Client Hello
- 116	5.465340	192.168.0.200	192.168.0.10	DTLSv1.2	102	Hello Verify Request
- 117	5.465555	192.168.0.10	192.168.0.200	DTLSv1.2	252	Client Hello
- 148	6.468366	192.168.0.10	192.168.0.200	DTLSv1.2	252	Client Hello
- 149	6.470782	192.168.0.200	192.168.0.10	DTLSv1.2	154	Server Hello
- 162	7.114057	192.168.0.200	192.168.0.10	DTLSv1.2	843	Server Key Exchange
- 163	7.114057	192.168.0.200	192.168.0.10	DTLSv1.2	67	Server Hello Done
- 164	7.114498	192.168.0.10	192.168.0.200	DTLSv1.2	57	Alert (Level: Fatal, Description: Insufficient Security) - Detail below
```
Frame 164: 57 bytes on wire (456 bits), 57 bytes captured (456 bits) on interface \Device\NPF_{29874E0A-CAEB-4D52-975A-34A829E20B54}, id 0
Ethernet II, Src: Giga-Byt_08:80:2f (1c:1b:0d:08:80:2f), Dst: PhilipsL_32:bd:51 (ec:b5:fa:32:bd:51)
Internet Protocol Version 4, Src: 192.168.0.10, Dst: 192.168.0.200
User Datagram Protocol, Src Port: 63790, Dst Port: 2100
Datagram Transport Layer Security
    DTLSv1.2 Record Layer: Alert (Level: Fatal, Description: Insufficient Security)
        Content Type: Alert (21)
        Version: DTLS 1.2 (0xfefd)
        Epoch: 0
        Sequence Number: 3
        Length: 2
        Alert Message
            Level: Fatal (2)
            Description: Insufficient Security (71)
```

<b>Is it supporting TLS_PSK_WITH_AES_128_GCM_SHA256 for DTLS or not?</b>

Here is my test code.
```java
  public void test() throws IOException {

        byte[] testBytes = {
                'H', 'u', 'e', 'S', 't', 'r', 'e', 'a', 'm',
                0x01, 0x00,
                0x07,
                0x00, 0x00,
                0x00,
                0x00,
                0x00, 0x00, 0x09,
                (byte) 0xff, (byte) 0xff, 0x00, 0x00, 0x00, 0x00
        };

        InetAddress address = InetAddress.getByName(BRIDGE_IP);
        int port = BRIDGE_PORT;
        
        TlsSession session = createSession(address, port);

        MockPSKDTLSClient client = new MockPSKDTLSClient(
                session
                ,
                new BasicTlsPSKIdentity(
                        "K5w43DnvbYiFtuKs4qqOtlS9UgaDXnK1l4K6U6c1",
                        new byte[] {
                                (byte) 0xE6,
                                (byte) 0x5E,
                                (byte) 0x10,
                                (byte) 0xFA,
                                (byte) 0xBD,
                                (byte) 0x22,
                                (byte) 0x69,
                                (byte) 0xFF,
                                (byte) 0x1E,
                                (byte) 0x3E,
                                (byte) 0xC4,
                                (byte) 0x6B,
                                (byte) 0xC4,
                                (byte) 0x76,
                                (byte) 0xC3,
                                (byte) 0xD0
                        }
                )
        );

        DTLSTransport dtls = openDTLSConnection(address, port, client);

        System.out.println("Receive limit: " + dtls.getReceiveLimit());
        System.out.println("Send limit: " + dtls.getSendLimit());

        // Send and hopefully receive a packet back
        dtls.send(testBytes, 0, testBytes.length);

        dtls.close();

    }

    private static TlsSession createSession(InetAddress address, int port) throws IOException
    {
        MockPSKDTLSClient client = new MockPSKDTLSClient(
                null
                ,
                new BasicTlsPSKIdentity(
                        "K5w43DnvbYiFtuKs4qqOtlS9UgaDXnK1l4K6U6c1",
                        new byte[] {
                                (byte) 0xE6,
                                (byte) 0x5E,
                                (byte) 0x10,
                                (byte) 0xFA,
                                (byte) 0xBD,
                                (byte) 0x22,
                                (byte) 0x69,
                                (byte) 0xFF,
                                (byte) 0x1E,
                                (byte) 0x3E,
                                (byte) 0xC4,
                                (byte) 0x6B,
                                (byte) 0xC4,
                                (byte) 0x76,
                                (byte) 0xC3,
                                (byte) 0xD0
                        }
                        )
        );

        DTLSTransport dtls = openDTLSConnection(address, port, client);
        TlsSession session = client.getSessionToResume();
        dtls.close();
        return session;
    }

    private static final SecureRandom secureRandom = new SecureRandom();

    private static DTLSTransport openDTLSConnection(InetAddress address, int port, TlsClient client) throws IOException
    {
        DatagramSocket socket = new DatagramSocket();
        socket.connect(address, port);

        int mtu = 1500;
        DatagramTransport transport = new UDPTransport(socket, mtu);
//        transport = new UnreliableDatagramTransport(transport, secureRandom, 0, 0);
//        transport = new LoggingDatagramTransport(transport, System.out);

        DTLSClientProtocol protocol = new DTLSClientProtocol();

        return protocol.connect(client, transport);
    }
```

**Comment by peterdettman** [comment]
No followup.
