### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 32 out of bounds for byte[31]

### ISSUE THREAD

**Issue by laurence-t** [bcgit/bc-java#919]
Hi,
since bcprov_1.68 we see a lot of errors like this in our tests:

Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 32 out of bounds for byte[31]
at java.lang.System.arraycopy(Native Method) ~[?:?]
at org.bouncycastle.crypto.params.X25519PublicKeyParameters.<init>(Unknown Source) ~[bcprov_1.68.0.jar:1.68.0]
at org.bouncycastle.jcajce.provider.asymmetric.edec.KeyAgreementSpi.engineDoPhase(KeyAgreementSpi.java:163) ~[bcprov_1.68.0.jar:1.68.0]
at javax.crypto.KeyAgreement.doPhase(KeyAgreement.java:579) ~[?:?]

I cloned the repository and did the following change in my repo:

X25519PublicKeyParameters.java line 22:
System.arraycopy(buf, off, data, 0, buf.length);

The arraycopy should only copy as much bytes as the buffer contains.
This helped fixing our errors. I would recommend changing this line.

Thanks
Laurence

**Comment by peterdettman** [comment]
See comments for https://github.com/bcgit/bc-java/pull/920 .

**Comment by peterdettman** [comment]
I could only estimate, but 1.69 may be around the end of April.
