### ISSUE TITLE
Support for new PKCS12 encryption algorithms

### ISSUE THREAD

**Issue by zzambers** [bcgit/bc-java#958]
There has been update of default algorithms used for PKCS12 keystore encryption in openjdk [1] (and it was backported to older jdks recently). BC does not seem to support this in some configurations, which may result in following exception:
Exception in thread "main" java.io.IOException: keystore password was incorrect
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2159)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:220)
	at java.base/java.security.KeyStore.load(KeyStore.java:1473)
	at SSLSocketTester.loadKeystore(SSLSocketTester.java:148)
	at SSLSocketTester.getKeyManagers(SSLSocketTester.java:123)
	at SSLSocketTester.init(SSLSocketTester.java:94)
	at Main.main(Main.java:29)
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	... 7 more

**Steps to reproduce:**
I reproduced this by my ssl-tests testsuite [2] in configuration, where BouncyCastleProvider provider is inserted as second to the list of providers. Steps to reproduce:
export JAVA_HOME=/path/to/latest-jdk-build-from-sources
make clean && make TEST_BC_2ND=1

JDK - local build of latest jdk sources
BC - 1.68

**More details:**
Unfortunately code in PKCS12KeyStore is written in a way, that stack trace of actual exception remains hidden [3], but I was able to get it from debugger:

Exception occurred: javax.crypto.BadPaddingException (to be caught at: com.sun.crypto.provider.CipherCore.fillOutputBuffer(), line=1,075 bci=81)"thread=main", com.sun.crypto.provider.CipherCore.unpad(), line=991 bci=29

main[1] where
  [1] com.sun.crypto.provider.CipherCore.unpad (CipherCore.java:991)
  [2] com.sun.crypto.provider.CipherCore.fillOutputBuffer (CipherCore.java:1,071)
  [3] com.sun.crypto.provider.CipherCore.doFinal (CipherCore.java:864)
  [4] com.sun.crypto.provider.PBES2Core.engineDoFinal (PBES2Core.java:325)
  [5] javax.crypto.Cipher.doFinal (Cipher.java:2,205)
  [6] sun.security.pkcs12.PKCS12KeyStore.lambda$engineLoad$1 (PKCS12KeyStore.java:2,155)
  [7] sun.security.pkcs12.PKCS12KeyStore$$Lambda$26/0x0000000801031ba8.tryOnce (null)
  [8] sun.security.pkcs12.PKCS12KeyStore$RetryWithZero.run (PKCS12KeyStore.java:257)
  [9] sun.security.pkcs12.PKCS12KeyStore.engineLoad (PKCS12KeyStore.java:2,145)
  [10] sun.security.util.KeyStoreDelegator.engineLoad (KeyStoreDelegator.java:220)
  [11] java.security.KeyStore.load (KeyStore.java:1,473)
  [12] SSLSocketTester.loadKeystore (SSLSocketTester.java:148)
  [13] SSLSocketTester.getKeyManagers (SSLSocketTester.java:123)
  [14] SSLSocketTester.init (SSLSocketTester.java:94)
  [15] Main.main (Main.java:29)

After some more digging it seems that problem is that classes used for cipher and skey are not compatible with each other [4].

Breakpoint hit: "thread=main", sun.security.pkcs12.PKCS12KeyStore.lambda$engineLoad$1(), line=2,155 bci=47

main[1] print skey
 skey = "org.bouncycastle.jcajce.provider.symmetric.util.BCPBEKey@10dba097"
main[1] print cipher
 cipher = "Cipher.PBEWithHmacSHA256AndAES_256, mode: decryption, algorithm from: SunJCE"
main[1] print algParams
 algParams = "PBEWithHmacSHA256AndAES_256"
...
main[1] print algOid
 algOid = "1.2.840.113549.1.5.13"

(algOid variable for keystore using new algorithms has value of "1.2.840.113549.1.5.13", while "1.2.840.113549.1.12.1.6" was used previously)

Actual problem seems to happen in PBES2Core class, when key.getEncoded() is called [5]. PBES2Core seems to expect one byte per character, but gets 2 bytes per character resulting in error later.

**Some Final Notes:**
This change in algortighms has been backported to JDK11 and JDK8, so theese will also became affected. (I could reproduce this issue on local build of latest jdk11u-dev)

Issue can be workarounded by defining keystore.pkcs12.legacy property, when creating keystore:
keytool -J-Dkeystore.pkcs12.legacy ...

[1] https://bugs.openjdk.java.net/browse/JDK-8153005
[2] https://github.com/zzambers/ssl-tests
[3] https://github.com/openjdk/jdk/blob/f67847f52a306874d1a0d92250f8a556b3af6507/src/java.base/share/classes/sun/security/pkcs12/PKCS12KeyStore.java#L2159
[4] https://github.com/openjdk/jdk/blob/f67847f52a306874d1a0d92250f8a556b3af6507/src/java.base/share/classes/sun/security/pkcs12/PKCS12KeyStore.java#L2147
[5] https://github.com/openjdk/jdk/blob/cd1c17c0a6416a8d16cf2035f3e97dba95b6b8af/src/java.base/share/classes/com/sun/crypto/provider/PBES2Core.java#L181

**Comment by dghgit** [comment]
Nice analysis. 

It looks like the real problem (from our end) is we're not shadowing the new PBE algorithms used for key encryption. It's a bit of a tricky one though - we try and allow for 16 bits per character with PKCS12 passwords (hence the 2 bytes per char) but the Oracle implementation actually restricts passwords to the lower 7 bits of each character (so just dropping the top byte isn't enough, the PKCS12 mac actually uses the 16 bit per char password, it's why the example gets as far as reading the file). I think I can shoe horn something in there...

**Comment by dghgit** [comment]
Okay, so my original analysis was partly wrong, the real issue is that our PKCS12 implementation was (accidentally) assuming no-one else had implement AES CBC on the OID. Oracle have added it, I've fixed the PKCS12 store to just make sure it uses the BC one so the key factory is now consistent with the implementation which is consistent with the default padding used. The Oracle implementation is CBC with no padding (which strictly speaking is correct) whereas the BC one, for historical reasons, is CBC with PKCS7 (which strictly speaking is really incorrect, but very convenient). Sounds like we have to review that...
