### ISSUE TITLE
Change in Oracle JCE Code Signing CA in IBM JDK - java IBM i

### ISSUE THREAD

**Issue by JaKo8103** [bcgit/bc-java#977]
Hello,
IBM to os400 java lvl 21 add only newes certificate (https://www.ibm.com/support/pages/node/6437873) : 
New Oracle signer certificate is used to sign cryptographic provider.
        Owner: CN=JCE Code Signing CA,OU=Java Software Code Signing, O=Oracle Corporation
        Issuer: CN=JCE Code Signing CA,OU=Java Software Code Signing, O=Oracle Corporation
        Serial number: 3C:9E:B1:89:F7:33:D3
        Valid from: Jul 6 23:48:44 2016 GMT until Dec 31 00:00:00 2030

and now 	bcprov-jdk15to18-169.jar is not work - he have another cert - in jar, there are two BC 1024KE and 2048KE certificates and in 2048 we see the signature by ORACLE but the serial number is 3c9eb1fc89f733d3. IBM in java have  Serial number: 3C:9E:B1:89:F7:33:D3
Can you put a newer Oracle signature certificate in .jar?

**Comment by dghgit** [comment]
We have the latest Oracle cert. I'm not sure what is going on with the serial number, but the JCE cert actually using the subject key identifier of the issuing key not the serial number to match it up. Exactly what error are you seeing?

**Comment by JaKo8103** [comment]
Is i error log:
Caused by: java.lang.SecurityException: JCE cannot authenticate the provider BC                                           
 at javax.crypto.Cipher.getInstance(Unknown Source)                                                                       
 at javax.crypto.Cipher.getInstance(Unknown Source)    
......
Caused by: java.util.jar.JarException: file:/WOLF/WolfPgpBatch/lib/bcprov-jdk15to18-169.jar is not signed by a trusted signer.
at javax.crypto.a.a(Unknown Source)                                                                                      
 at javax.crypto.a.a(Unknown Source)                                                                                      
 at javax.crypto.a.a(Unknown Source)

**Comment by JaKo8103** [comment]
other:
Caused by: java.lang.SecurityException: JCE cannot authenticate the provider BC                                           
 at javax.crypto.Cipher.getInstance(Unknown Source)                                                                       
 at javax.crypto.Cipher.getInstance(Unknown Source)                                                                       
 ... 14 more                                                                                                              
Caused by: java.util.jar.JarException: file:/WOLF/WolfPgpBatch/lib/bcprov-jdk14-137.jar is not signed by a trusted signer.
at javax.crypto.a.a(Unknown Source)

**Comment by JaKo8103** [comment]
sorry in bcprov-jdk15to18-169.jar i have this problem:
The library interface was incompatible with the previous one

**Comment by JaKo8103** [comment]
dghgit problem is activated when IBM add to only java:
Latest news of Java on IBM 

April, 2021:  New Oracle signer certificate
New Oracle signer certificate is used to sign cryptographic provider.
        Owner: CN=JCE Code Signing CA,OU=Java Software Code Signing, O=Oracle Corporation
        Issuer: CN=JCE Code Signing CA,OU=Java Software Code Signing, O=Oracle Corporation
        Serial number: 3C:9E:B1:89:F7:33:D3
        Valid from: Jul 6 23:48:44 2016 GMT until Dec 31 00:00:00 2030
GMT For details, check https://www.ibm.com/support/pages/apar/IJ26310
Once you upgraded to following levels, the old certificate is not recognized anymore. You may encounter with similar exception listed in above page.
        Java 8    SR6 FP25
        Java 7    SR10 FP75
        Java 7.1 SR4 FP75 
Third-party JCE provider users should be careful before upgrading.
Once the issue occurred, contact your provider vendor to update the provider.

**Comment by JaKo8103** [comment]
OK. Sorry for problem and create issue. Now i have more information about cert and JDC Oracle and i think so mus rewrite program and add new bcprov-jdk15to18-169.jar Thanks for help.
