### ISSUE TITLE
JsseUtils.getAuthTypeServer(KeyExchangeAlgorithm.RSA) returned value changed to "KE:RSA"

### ISSUE THREAD

**Issue by gsaviane** [bcgit/bc-java#985]
The method JsseUtils.getAuthTypeServer() has been changed in r1v66 to return "KE:RSA" on KeyExchangeAlgorithm.RSA. As a result, a TLS handshake fails when a cipher using RSA as a key exchange algorithm is in use. This is the stack trace:

	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.checkServerTrusted(ProvSSLSocketDirect.java:135)
	at org.bouncycastle.jsse.provider.ProvTlsClient$1.notifyServerCertificate(ProvTlsClient.java:360)
	at org.bouncycastle.tls.TlsUtils.processServerCertificate(TlsUtils.java:4690)
	at org.bouncycastle.tls.TlsClientProtocol.handleServerCertificate(TlsClientProtocol.java:790)
	at org.bouncycastle.tls.TlsClientProtocol.handleHandshakeMessage(TlsClientProtocol.java:697)
	at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(TlsProtocol.java:691)
	at org.bouncycastle.tls.TlsProtocol.processRecord(TlsProtocol.java:580)
	at org.bouncycastle.tls.RecordStream.readRecord(RecordStream.java:245)
	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:839)
	at org.bouncycastle.tls.TlsProtocol.blockForHandshake(TlsProtocol.java:416)
	at org.bouncycastle.tls.TlsClientProtocol.connect(TlsClientProtocol.java:86)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(ProvSSLSocketDirect.java:445)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.startHandshake(ProvSSLSocketDirect.java:426)
...
Caused by: java.security.cert.CertificateException: Unknown authType: KE:RSA
	at sun.security.validator.EndEntityChecker.checkTLSServer(EndEntityChecker.java:289)
	at sun.security.validator.EndEntityChecker.check(EndEntityChecker.java:144)
	at sun.security.validator.Validator.validate(Validator.java:284)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:315)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:223)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at org.bouncycastle.jsse.provider.ImportX509TrustManager_7.checkServerTrusted(ImportX509TrustManager_7.java:56)
	at org.bouncycastle.jsse.provider.ProvSSLSocketDirect.checkServerTrusted(ProvSSLSocketDirect.java:131)

**Comment by peterdettman** [comment]
BCJSSE SSLContext is not interoperable with TrustManagerFactory (or KeyManagerFactory) from SunJSSE (the case shown in your stack trace). You have to use the BCJSSE TrustManagerFactory and/or KeyManagerFactory when using the BCJSSE SSLContext. Usually it's helpful to set these in java.security:

ssl.KeyManagerFactory.algorithm=PKIX
ssl.TrustManagerFactory.algorithm=PKIX

which will resolve things if BCJSSE is the higher-priority provider over SunJSSE. Otherwise the provider can be explicitly specified to TMF/KMF.getInstance methods.

**Comment by gsaviane** [comment]
That made it work.

Thank you!
