### ISSUE TITLE
Getting java.lang.ArithmeticException: divide by zero exception while closing stream

### ISSUE THREAD

**Issue by Susmit07** [bcgit/bc-java#993]
The code here is below, simple PGP sign document with compression enabled (BZIP2)

```
OutputStream compressedOut = null;
// Some logic ..
// Initialize compressed data generator
compressedDataGenerator = new PGPCompressedDataGenerator(PGPUtils.getPgpCompressionAlgorithm(), PGPUtils.getPgpCompressionLevel());
// compressedOut initialized
compressedOut = compressedDataGenerator.open(documentOutputStream, new byte[PGPUtils.getBufferSize()]);
PGPContentSignerBuilder signerBuilder = new BcPGPContentSignerBuilder(pgpSecretKey.getPublicKey().getAlgorithm(), PGPUtils.getPgpSigningAlgorithm());
// Exception thrown above PGPUtils.getPgpSigningAlgorithm() (Our business own use case for FIPS and NIST)
// finally block closing the compressed output stream
compressedOut.close() // Error comes
```

When I call compressedOut.close() 

I get the below error:

java.lang.ArithmeticException: divide by zero
        at org.bouncycastle.apache.bzip2.CBZip2OutputStream.mainSort(Unknown Source)
        at org.bouncycastle.apache.bzip2.CBZip2OutputStream.doReversibleTransformation(Unknown Source)
        at org.bouncycastle.apache.bzip2.CBZip2OutputStream.endBlock(Unknown Source)
        at org.bouncycastle.apache.bzip2.CBZip2OutputStream.finish(Unknown Source)
        at org.bouncycastle.openpgp.PGPCompressedDataGenerator$SafeCBZip2OutputStream.close(Unknown Source)
        at org.bouncycastle.openpgp.PGPCompressedDataGenerator.close(Unknown Source)
        at org.bouncycastle.openpgp.WrappedGeneratorStream.close(Unknown Source)

Please note this error only comes when we use **BZIP2** as compression algo. For ZLIB and ZIP it works fine.

@peterdettman your guidance is needed!!

**Comment by peterdettman** [comment]
Thanks for the report. bzip2 compression was broken for empty contents. A fix has been committed with test coverage.

**Comment by Susmit07** [comment]
Can you share with me the pull request details and which version we can expect?

**Comment by Susmit07** [comment]
@peterdettman Can you please share the pull request with me and in which version can we expect the fix?
